NGSFeatures: ematch_src/utils/sequence/align/run/allPairsNearestGlobalAffineScore.cc File Reference
allPairsNearestGlobalAffineScore.cc File Reference
#include <iostream>
#include <fstream>
#include "utils/argvParsing/ArgvParser.hh"
#include "utils/sequence/readers/fasta/FastaSeqSlurper.hh"
#include "utils/FLArray/FLEArrayByIndexSortingPredicate.hh"
#include "../SeqGlobalAffineAligner.hh"
#include "../AminoScorePam120.hh"
Namespaces
namespace cbrc
Macros
#define IGNORE_SELF -i|--ignore-self
Functions
void cbrc::allPairsNearestGlobalAffineScore ()
int main (int argc, const char *argv[])
Variables
std::vector< cbrc::LabeledSequence > seqs0
std::vector< cbrc::LabeledSequence > seqs1
bool ignoreSelf
Macro Definition Documentation
IGNORE_SELF
#define IGNORE_SELF -i|--ignore-self
Definition at line 113 of file allPairsNearestGlobalAffineScore.cc.
Function Documentation
main()
int main (int argc, const char * argv[])
Definition at line 115 of file allPairsNearestGlobalAffineScore.cc.
References cbrc::allPairsNearestGlobalAffineScore(), cbrc::aminoScorePam120, cbrc::ArgvParser::closeIstream(), cbrc::ArgvParser::die(), cbrc::ArgvParser::dieIfUnusedArgs(), fastaIstreamPtr, cbrc::ArgvParser::hasFlag(), IGNORE_SELF, ignoreSelf, cbrc::ArgvParser::openIstream(), cbrc::ArgvParser::printDoc(), Q, seqs0, seqs1, cbrc::ArgvParser::set(), cbrc::ArgvParser::setDoc(), cbrc::ArgvParser::setOrDie(), and cbrc::FastaSeqSlurper::slurpLabeledSequences().
Variable Documentation
ignoreSelf
bool ignoreSelf
Definition at line 34 of file allPairsNearestGlobalAffineScore.cc.
Referenced by cbrc::allPairsNearestGlobalAffineScore(), main(), main(), and cbrc::runGlobalAffineSearcher().
seqs0
std::vector< cbrc::LabeledSequence > seqs0
Definition at line 32 of file allPairsNearestGlobalAffineScore.cc.
Referenced by cbrc::allPairsGlobalAffineScore(), cbrc::allPairsNearestGlobalAffineScore(), main(), cbrc::runGlobalAffineNearestClass(), and cbrc::runGlobalAffineSearcher().
seqs1
std::vector< cbrc::LabeledSequence > seqs1
Definition at line 33 of file allPairsNearestGlobalAffineScore.cc.
Referenced by cbrc::allPairsGlobalAffineScore(), cbrc::allPairsNearestGlobalAffineScore(), main(), cbrc::runGlobalAffineNearestClass(), and cbrc::runGlobalAffineSearcher().