NGSFeatures: src/AverageTagsQuals_36.cc File Reference
AverageTagsQuals_36.cc File Reference
#include <iostream>
#include <vector>
#include <fstream>
#include <sstream>
#include <cstdlib>
Functions
template<typename T >
void prn_vec (std::vector< T > &arg, string sep="")
void processBlock (string &tag, vector< vector< double > > &grp)
int main (int arg_count, char *arg_vec[])
Function Documentation
main()
int main (int arg_count, char * arg_vec[])
Definition at line 199 of file AverageTagsQuals_36.cc.
References getline(), and processBlock().
prn_vec()
template<typename T > void prn_vec (std::vector< T > & arg, string sep = "")
Definition at line 18 of file AverageTagsQuals_36.cc.
processBlock()
void processBlock (string & tag, vector< vector< double > > & grp)
Definition at line 25 of file AverageTagsQuals_36.cc.
Referenced by main().