NGSFeatures: cbrc::FLENumArray< T > Class Template Reference
cbrc::FLENumArray< T > Class Template Reference
#include <FLEArray.hh>
Public Types
typedef T * iterator
typedef const T * const_iterator
typedef T * iterator
typedef const T * const_iterator
Public Types inherited from cbrc::FLEArray< T >
typedef T * iterator
typedef const T * const_iterator
typedef unsigned char uchar
typedef T * iterator
typedef const T * const_iterator
typedef unsigned char uchar
Public Member Functions
FLENumArray ()
FLENumArray (const size_t &sz)
FLENumArray (const std::string semanticTypeDescriptor, const std::string arrayLiteral)
FLENumArray (const size_t &sz, const T &fillVal)
FLENumArray (const size_t &sz, const T *const &b)
FLENumArray (const std::vector< T > &v)
FLENumArray (const FLEArray< T > &fla)
FLENumArray (const FLEArray< T > &fla, const size_t &startIndex, const size_t &endIndex)
FLENumArray operator= (const std::vector< T > &v)
FLENumArray operator= (const FLENumArray< T > &fla)
FLENumArray & operator*= (T el)
FLENumArray & operator/= (T el)
FLENumArray & operator+= (const FLENumArray< T > &fla)
FLENumArray & operator-= (const FLENumArray< T > &fla)
T sum () const
T min () const
T min (const size_t &begIdx, const size_t &endIdx) const
T max () const
T max (const size_t &begIdx, const size_t &endIdx) const
size_t firstMinIndex () const
size_t finalMinIndex () const
size_t firstMaxIndex () const
size_t finalMaxIndex () const
void squareElements ()
FLENumArray ()
FLENumArray (const size_t &sz)
FLENumArray (const std::string semanticTypeDescriptor, const std::string arrayLiteral)
FLENumArray (const size_t &sz, const T &fillVal)
FLENumArray (const size_t &sz, const T *const &b)
FLENumArray (const std::vector< T > &v)
FLENumArray (const FLEArray< T > &fla)
FLENumArray (const FLEArray< T > &fla, const size_t &startIndex, const size_t &endIndex)
FLENumArray operator= (const std::vector< T > &v)
FLENumArray operator= (const FLENumArray< T > &fla)
FLENumArray & operator*= (T el)
FLENumArray & operator/= (T el)
FLENumArray & operator+= (const FLENumArray< T > &fla)
FLENumArray & operator-= (const FLENumArray< T > &fla)
T sum () const
T min () const
T min (const size_t &begIdx, const size_t &endIdx) const
T max () const
T max (const size_t &begIdx, const size_t &endIdx) const
size_t firstMinIndex () const
size_t finalMinIndex () const
size_t firstMaxIndex () const
size_t finalMaxIndex () const
void squareElements ()
Public Member Functions inherited from cbrc::FLEArray< T >
FLEArray ()
FLEArray (const size_t &sz)
FLEArray (const std::string semanticTypeDescriptor, const std::string arrayLiteral)
FLEArray (const size_t &sz, const T &fillVal)
FLEArray (const size_t &sz, const T *const &c_array)
FLEArray (const std::vector< T > &v)
FLEArray (const FLEArray< T > &fla)
FLEArray (const FLEArray< T > &fla, const size_t &startIndex, const size_t &endIndex)
FLEArray (std::istream &is)
FLEArray (const size_t &size, std::istream &is)
virtual ~FLEArray ()
operator std::vector< T > () const
void setSize (const size_t &sz)
void resize (const size_t &sz)
FLEArray operator= (const FLEArray &fla)
FLEArray operator= (const std::vector< T > &v)
void assign (const typename FLEArray< T >::const_iterator &begin, const typename FLEArray< T >::const_iterator &end)
void assign (const typename std::vector< T >::const_iterator &begin, const typename std::vector< T >::const_iterator &end)
void setFromLiteral (const std::string semanticTypeDescriptor, const std::string arrayLiteral)
void replace (const size_t &begIdx, const FLEArray< T > &replacementArray)
void replace (const size_t &begIdx, const size_t &endIdx, const T *const &cArray)
bool operator== (const FLEArray &fla) const
bool operator!= (const FLEArray &fla) const
virtual T & operator[] (const size_t &index) const
virtual const T & operator() (const size_t &index) const
const size_t & size () const
size_t bsize () const
bool empty () const
bool indexInRange (const size_t &idx) const
iterator begin () const
iterator end () const
const_iterator constBegin () const
const_iterator constEnd () const
void zero ()
void fill (const T &fillVal, const size_t begIdx=0)
void fill (const T &fillVal, const size_t &begIdx, const size_t &endIdx)
void fillWithByte (const int &fillByte)
void read (std::istream &is)
void write (std::ostream &os) const
virtual void print (std::ostream &os=std::cout, const std::string &delimiter="\t") const
virtual void printNumbered (std::ostream &os=std::cout, const size_t startLabel=0) const
size_t find (const T &val, const size_t &begIdx, const size_t &endIdx)
size_t find (const T &val, const size_t begIdx=0)
size_t rfind (const T &val, const size_t &begIdx, const size_t &endIdx)
size_t rfind (const T &val, const size_t begIdx=0)
FLEArray ()
FLEArray (const size_t &sz)
FLEArray (const std::string semanticTypeDescriptor, const std::string arrayLiteral)
FLEArray (const size_t &sz, const T &fillVal)
FLEArray (const size_t &sz, const T *const &c_array)
FLEArray (const std::vector< T > &v)
FLEArray (const FLEArray< T > &fla)
FLEArray (const FLEArray< T > &fla, const size_t &startIndex, const size_t &endIndex)
FLEArray (std::istream &is)
FLEArray (const size_t &size, std::istream &is)
virtual ~FLEArray ()
operator std::vector< T > () const
void setSize (const size_t &sz)
void resize (const size_t &sz)
FLEArray operator= (const FLEArray &fla)
FLEArray operator= (const std::vector< T > &v)
void assign (const typename FLEArray< T >::const_iterator &begin, const typename FLEArray< T >::const_iterator &end)
void assign (const typename std::vector< T >::const_iterator &begin, const typename std::vector< T >::const_iterator &end)
void setFromLiteral (const std::string semanticTypeDescriptor, const std::string arrayLiteral)
void replace (const size_t &begIdx, const FLEArray< T > &replacementArray)
void replace (const size_t &begIdx, const size_t &endIdx, const T *const &cArray)
bool operator== (const FLEArray &fla) const
bool operator!= (const FLEArray &fla) const
virtual T & operator[] (const size_t &index) const
virtual const T & operator() (const size_t &index) const
const size_t & size () const
size_t bsize () const
bool empty () const
bool indexInRange (const size_t &idx) const
iterator begin () const
iterator end () const
const_iterator constBegin () const
const_iterator constEnd () const
void zero ()
void fill (const T &fillVal, const size_t begIdx=0)
void fill (const T &fillVal, const size_t &begIdx, const size_t &endIdx)
void fillWithByte (const int &fillByte)
void read (std::istream &is)
void write (std::ostream &os) const
virtual void print (std::ostream &os=std::cout, const std::string &delimiter="\t") const
virtual void printNumbered (std::ostream &os=std::cout, const size_t startLabel=0) const
size_t find (const T &val, const size_t &begIdx, const size_t &endIdx)
size_t find (const T &val, const size_t begIdx=0)
size_t rfind (const T &val, const size_t &begIdx, const size_t &endIdx)
size_t rfind (const T &val, const size_t begIdx=0)
Additional Inherited Members
Static Public Member Functions inherited from cbrc::FLEArray< T >
static void skip (std::istream &is)
static void skip (std::istream &is)
Static Public Attributes inherited from cbrc::FLEArray< T >
static const size_t npos = static_cast<size_t>(-1)
Protected Member Functions inherited from cbrc::FLEArray< T >
bool _validIndex (const size_t &idx) const
bool _validRange (const size_t &begIdx, const size_t &endIdx)
void _assertNonzeroSize () const
void _assertSizeEqual (const FLEArray< T > &fla) const
bool _validIndex (const size_t &idx) const
bool _validRange (const size_t &begIdx, const size_t &endIdx)
void _assertNonzeroSize () const
void _assertSizeEqual (const FLEArray< T > &fla) const
Static Protected Member Functions inherited from cbrc::FLEArray< T >
static size_t bsize (const size_t &numElems)
static size_t bsize (const size_t &numElems)
Protected Attributes inherited from cbrc::FLEArray< T >
size_t s
T * a
Detailed Description
template<typename T>
class cbrc::FLENumArray< T >
Definition at line 342 of file FLEArray.hh.
Member Typedef Documentation
const_iterator [1/2]
template<typename T > typedef const T* cbrc::FLENumArray< T >::const_iterator
Definition at line 346 of file FLEArray.hh.
const_iterator [2/2]
template<typename T > typedef const T* cbrc::FLENumArray< T >::const_iterator
Definition at line 346 of file FLEArray.hh.
iterator [1/2]
template<typename T > typedef T* cbrc::FLENumArray< T >::iterator
Definition at line 345 of file FLEArray.hh.
iterator [2/2]
template<typename T > typedef T* cbrc::FLENumArray< T >::iterator
Definition at line 345 of file FLEArray.hh.
Constructor & Destructor Documentation
FLENumArray() [1/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray () inline
Definition at line 348 of file FLEArray.hh.
FLENumArray() [2/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray (const size_t & sz) inline
Definition at line 351 of file FLEArray.hh.
FLENumArray() [3/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray (const std::string semanticTypeDescriptor, const std::string arrayLiteral) inline
Definition at line 354 of file FLEArray.hh.
FLENumArray() [4/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray (const size_t & sz, const T & fillVal) inline
Definition at line 358 of file FLEArray.hh.
FLENumArray() [5/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray (const size_t & sz, const T *const & b) inline
Definition at line 361 of file FLEArray.hh.
FLENumArray() [6/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray (const std::vector< T > & v) inline
Definition at line 364 of file FLEArray.hh.
FLENumArray() [7/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray (const FLEArray< T > & fla) inline
Definition at line 367 of file FLEArray.hh.
FLENumArray() [8/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray (const FLEArray< T > & fla, const size_t & startIndex, const size_t & endIndex) inline
Definition at line 370 of file FLEArray.hh.
FLENumArray() [9/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray () inline
Definition at line 348 of file FLEArray.hh.
FLENumArray() [10/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray (const size_t & sz) inline
Definition at line 351 of file FLEArray.hh.
FLENumArray() [11/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray (const std::string semanticTypeDescriptor, const std::string arrayLiteral) inline
Definition at line 354 of file FLEArray.hh.
FLENumArray() [12/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray (const size_t & sz, const T & fillVal) inline
Definition at line 358 of file FLEArray.hh.
FLENumArray() [13/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray (const size_t & sz, const T *const & b) inline
Definition at line 361 of file FLEArray.hh.
FLENumArray() [14/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray (const std::vector< T > & v) inline
Definition at line 364 of file FLEArray.hh.
FLENumArray() [15/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray (const FLEArray< T > & fla) inline
Definition at line 367 of file FLEArray.hh.
FLENumArray() [16/16]
template<typename T > cbrc::FLENumArray< T >::FLENumArray (const FLEArray< T > & fla, const size_t & startIndex, const size_t & endIndex) inline
Definition at line 370 of file FLEArray.hh.
Member Function Documentation
finalMaxIndex() [1/2]
template<typename T > size_t cbrc::FLENumArray< T >::finalMaxIndex () const
Definition at line 923 of file FLEArray.hh.
References cbrc::FLEArray< T >::_assertNonzeroSize(), cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
finalMaxIndex() [2/2]
template<typename T > size_t cbrc::FLENumArray< T >::finalMaxIndex () const
finalMinIndex() [1/2]
template<typename T > size_t cbrc::FLENumArray< T >::finalMinIndex () const
Definition at line 891 of file FLEArray.hh.
References cbrc::FLEArray< T >::_assertNonzeroSize(), cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
finalMinIndex() [2/2]
template<typename T > size_t cbrc::FLENumArray< T >::finalMinIndex () const
firstMaxIndex() [1/2]
template<typename T > size_t cbrc::FLENumArray< T >::firstMaxIndex () const
Definition at line 907 of file FLEArray.hh.
References cbrc::FLEArray< T >::_assertNonzeroSize(), cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
firstMaxIndex() [2/2]
template<typename T > size_t cbrc::FLENumArray< T >::firstMaxIndex () const
firstMinIndex() [1/2]
template<typename T > size_t cbrc::FLENumArray< T >::firstMinIndex () const
Definition at line 875 of file FLEArray.hh.
References cbrc::FLEArray< T >::_assertNonzeroSize(), cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
firstMinIndex() [2/2]
template<typename T > size_t cbrc::FLENumArray< T >::firstMinIndex () const
max() [1/4]
template<typename T > T cbrc::FLENumArray< T >::max () const
Definition at line 834 of file FLEArray.hh.
References cbrc::FLEArray< T >::_assertNonzeroSize(), cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and cbrc::FLEArray< T >::FLEArray().
max() [2/4]
template<typename T > T cbrc::FLENumArray< T >::max () const
max() [3/4]
template<typename T > T cbrc::FLENumArray< T >::max (const size_t & begIdx, const size_t & endIdx) const
Definition at line 852 of file FLEArray.hh.
References cbrc::FLEArray< T >::_assertNonzeroSize(), cbrc::FLEArray< T >::_validIndex(), cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::FLEArray().
max() [4/4]
template<typename T > T cbrc::FLENumArray< T >::max (const size_t & begIdx, const size_t & endIdx) const
min() [1/4]
template<typename T > T cbrc::FLENumArray< T >::min () const
Definition at line 793 of file FLEArray.hh.
References cbrc::FLEArray< T >::_assertNonzeroSize(), cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and cbrc::FLEArray< T >::FLEArray().
min() [2/4]
template<typename T > T cbrc::FLENumArray< T >::min () const
min() [3/4]
template<typename T > T cbrc::FLENumArray< T >::min (const size_t & begIdx, const size_t & endIdx) const
Definition at line 811 of file FLEArray.hh.
References cbrc::FLEArray< T >::_assertNonzeroSize(), cbrc::FLEArray< T >::_validIndex(), cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::FLEArray().
min() [4/4]
template<typename T > T cbrc::FLENumArray< T >::min (const size_t & begIdx, const size_t & endIdx) const
operator*=() [1/2]
template<typename T > FLENumArray & cbrc::FLENumArray< T >::operator*= (T el) inline
Definition at line 382 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
operator*=() [2/2]
template<typename T > FLENumArray & cbrc::FLENumArray< T >::operator*= (T el) inline
Definition at line 382 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
operator+=() [1/2]
template<typename T > FLENumArray & cbrc::FLENumArray< T >::operator+= (const FLENumArray< T > & fla) inline
Definition at line 394 of file FLEArray.hh.
References cbrc::FLEArray< T >::_assertSizeEqual(), cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
operator+=() [2/2]
template<typename T > FLENumArray & cbrc::FLENumArray< T >::operator+= (const FLENumArray< T > & fla) inline
Definition at line 394 of file FLEArray.hh.
References cbrc::FLEArray< T >::_assertSizeEqual(), cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
operator-=() [1/2]
template<typename T > FLENumArray & cbrc::FLENumArray< T >::operator-= (const FLENumArray< T > & fla) inline
Definition at line 401 of file FLEArray.hh.
References cbrc::FLEArray< T >::_assertSizeEqual(), cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
operator-=() [2/2]
template<typename T > FLENumArray & cbrc::FLENumArray< T >::operator-= (const FLENumArray< T > & fla) inline
Definition at line 401 of file FLEArray.hh.
References cbrc::FLEArray< T >::_assertSizeEqual(), cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
operator/=() [1/2]
template<typename T > FLENumArray & cbrc::FLENumArray< T >::operator/= (T el) inline
Definition at line 388 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
operator/=() [2/2]
template<typename T > FLENumArray & cbrc::FLENumArray< T >::operator/= (T el) inline
Definition at line 388 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
operator=() [1/4]
template<typename T > FLENumArray cbrc::FLENumArray< T >::operator= (const FLENumArray< T > & fla) inline
Definition at line 377 of file FLEArray.hh.
operator=() [2/4]
template<typename T > FLENumArray cbrc::FLENumArray< T >::operator= (const FLENumArray< T > & fla) inline
Definition at line 377 of file FLEArray.hh.
operator=() [3/4]
template<typename T > FLENumArray cbrc::FLENumArray< T >::operator= (const std::vector< T > & v) inline
Definition at line 373 of file FLEArray.hh.
operator=() [4/4]
template<typename T > FLENumArray cbrc::FLENumArray< T >::operator= (const std::vector< T > & v) inline
Definition at line 373 of file FLEArray.hh.
squareElements() [1/2]
template<typename T > void cbrc::FLENumArray< T >::squareElements () inline
Definition at line 431 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
squareElements() [2/2]
template<typename T > void cbrc::FLENumArray< T >::squareElements () inline
Definition at line 431 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
sum() [1/2]
template<typename T > T cbrc::FLENumArray< T >::sum () const inline
Definition at line 408 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
Referenced by cbrc::TrivialHistogram< T >::sum().
sum() [2/2]
template<typename T > T cbrc::FLENumArray< T >::sum () const inline
Definition at line 408 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
The documentation for this class was generated from the following files:
ematch_src/utils/FLArray/FLEArray.hh
knapsack_src/utils/FLArray/FLEArray.hh