NGSFeatures: cbrc::TrivialHistogram< T > Class Template Reference
cbrc::TrivialHistogram< T > Class Template Reference
#include <TrivialHistogram.hh>
Public Member Functions
TrivialHistogram (const FLENumArray< T > &data, const size_t startingCount=0)
TrivialHistogram (const size_t dataMax, const size_t startingCount=0)
TrivialHistogram (std::istream &is=std::cin)
TrivialHistogram (const TrivialHistogram< T > &histo)
void incrementCount (size_t index)
const size_t operator() (const size_t &index) const
size_t size () const
T sum () const
void write (std::ostream &os)
size_t firstNonzeroIndex ()
size_t nextNonzeroIndex (size_t i)
void printNonzeroEntries (std::ostream &os=std::cout, const char fieldSepartor=' ', const char entrySeparator='\n') const
Detailed Description
template<typename T>
class cbrc::TrivialHistogram< T >
Definition at line 19 of file TrivialHistogram.hh.
Constructor & Destructor Documentation
TrivialHistogram() [1/4]
template<typename T > cbrc::TrivialHistogram< T >::TrivialHistogram (const FLENumArray< T > & data, const size_t startingCount = 0) inline
Definition at line 21 of file TrivialHistogram.hh.
TrivialHistogram() [2/4]
template<typename T > cbrc::TrivialHistogram< T >::TrivialHistogram (const size_t dataMax, const size_t startingCount = 0) inline
Definition at line 27 of file TrivialHistogram.hh.
TrivialHistogram() [3/4]
template<typename T > cbrc::TrivialHistogram< T >::TrivialHistogram (std::istream & is = std::cin) inline
Definition at line 31 of file TrivialHistogram.hh.
References cbrc::FLEArray< T >::read().
TrivialHistogram() [4/4]
template<typename T > cbrc::TrivialHistogram< T >::TrivialHistogram (const TrivialHistogram< T > & histo) inline
Definition at line 34 of file TrivialHistogram.hh.
Member Function Documentation
firstNonzeroIndex()
template<typename T > size_t cbrc::TrivialHistogram< T >::firstNonzeroIndex () inline
Definition at line 43 of file TrivialHistogram.hh.
References cbrc::TrivialHistogram< T >::size().
incrementCount()
template<typename T > void cbrc::TrivialHistogram< T >::incrementCount (size_t index) inline
Definition at line 36 of file TrivialHistogram.hh.
nextNonzeroIndex()
template<typename T > size_t cbrc::TrivialHistogram< T >::nextNonzeroIndex (size_t i) inline
Definition at line 48 of file TrivialHistogram.hh.
References cbrc::TrivialHistogram< T >::size().
operator()()
template<typename T > const size_t cbrc::TrivialHistogram< T >::operator() (const size_t & index) const inline
Definition at line 37 of file TrivialHistogram.hh.
printNonzeroEntries()
template<typename T > void cbrc::TrivialHistogram< T >::printNonzeroEntries (std::ostream & os = std::cout, const char fieldSepartor = ' ', const char entrySeparator = '\n') const
Definition at line 13 of file TrivialHistogram.cc.
References cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
size()
template<typename T > size_t cbrc::TrivialHistogram< T >::size () const inline
Definition at line 38 of file TrivialHistogram.hh.
References cbrc::FLEArray< T >::size().
Referenced by cbrc::TrivialHistogram< T >::firstNonzeroIndex(), and cbrc::TrivialHistogram< T >::nextNonzeroIndex().
sum()
template<typename T > T cbrc::TrivialHistogram< T >::sum () const inline
Definition at line 39 of file TrivialHistogram.hh.
References cbrc::FLENumArray< T >::sum().
write()
template<typename T > void cbrc::TrivialHistogram< T >::write (std::ostream & os) inline
Definition at line 40 of file TrivialHistogram.hh.
References cbrc::FLEArray< T >::write().
The documentation for this class was generated from the following files:
ematch_src/utils/histogram/TrivialHistogram.hh
ematch_src/utils/histogram/TrivialHistogram.cc