NGSFeatures: cbrc::FastafmtRecord Class Reference
cbrc::FastafmtRecord Class Reference
#include <FastafmtRecord.hh>
Public Member Functions
FastafmtRecord ()
FastafmtRecord (const std::string &seq, const std::string name=defaultName())
FastafmtRecord (const std::string &seq, std::vector< std::string > labels)
const std::string & seq () const
std::string & seqRef ()
void setSeq (const std::string &seq)
const std::string & name () const
const std::string & label (const size_t &i) const
const std::vector< std::string > & labels () const
void setLabels (const std::vector< std::string > &labels)
void setLabel (const size_t &i, const std::string &label)
Static Public Member Functions
static const std::string & defaultName ()
static const std::string & nullSeq ()
Detailed Description
Definition at line 24 of file FastafmtRecord.hh.
Constructor & Destructor Documentation
FastafmtRecord() [1/3]
cbrc::FastafmtRecord::FastafmtRecord () inline
Definition at line 27 of file FastafmtRecord.hh.
FastafmtRecord() [2/3]
cbrc::FastafmtRecord::FastafmtRecord (const std::string & seq, const std::string name = defaultName()) inline
Definition at line 31 of file FastafmtRecord.hh.
References name().
FastafmtRecord() [3/3]
cbrc::FastafmtRecord::FastafmtRecord (const std::string & seq, std::vector< std::string > labels) inline
Definition at line 36 of file FastafmtRecord.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and labels().
Member Function Documentation
defaultName()
static const std::string & cbrc::FastafmtRecord::defaultName () inline static
Definition at line 68 of file FastafmtRecord.hh.
label()
const std::string & cbrc::FastafmtRecord::label (const size_t & i) const inline
Definition at line 49 of file FastafmtRecord.hh.
References labels().
Referenced by name(), and setLabel().
labels()
const std::vector< std::string > & cbrc::FastafmtRecord::labels () const inline
Definition at line 53 of file FastafmtRecord.hh.
Referenced by FastafmtRecord(), label(), setLabel(), and setLabels().
name()
const std::string & cbrc::FastafmtRecord::name () const inline
Definition at line 48 of file FastafmtRecord.hh.
References label().
Referenced by FastafmtRecord().
nullSeq()
static const std::string & cbrc::FastafmtRecord::nullSeq () inline static
Definition at line 74 of file FastafmtRecord.hh.
seq()
const std::string & cbrc::FastafmtRecord::seq () const inline
Definition at line 43 of file FastafmtRecord.hh.
Referenced by cbrc::FastafmtReader::seq(), and setSeq().
seqRef()
std::string & cbrc::FastafmtRecord::seqRef () inline
Definition at line 44 of file FastafmtRecord.hh.
Referenced by cbrc::FastafmtReader::readRecord(), and cbrc::FastafmtReader::upcaseSequence().
setLabel()
void cbrc::FastafmtRecord::setLabel (const size_t & i, const std::string & label) inline
Definition at line 61 of file FastafmtRecord.hh.
References label(), and labels().
setLabels()
void cbrc::FastafmtRecord::setLabels (const std::vector< std::string > & labels) inline
Definition at line 57 of file FastafmtRecord.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and labels().
setSeq()
void cbrc::FastafmtRecord::setSeq (const std::string & seq) inline
Definition at line 46 of file FastafmtRecord.hh.
References seq().
The documentation for this class was generated from the following file:
ematch_src/utils/sequence/fastafmt/FastafmtRecord.hh