NGSFeatures: cbrc::ConstResidueIndexSequenceBoundaries Class Reference
cbrc::ConstResidueIndexSequenceBoundaries Class Reference
#include <ConstResidueIndexSequenceBoundaries.hh>
Public Member Functions
ConstResidueIndexSequenceBoundaries (const ResidueIndexMap &rim, const ResidueIndexMap::indexT *const &_startPtr, const size_t &_size)
ConstResidueIndexSequenceBoundaries (const ConstResidueIndexSequenceBoundaries &sb)
const ResidueIndexMap & residueIndexMap () const
const ResidueIndexMap::indexT * startPtr () const
const ResidueIndexMap::indexT * endPtr () const
const size_t size () const
Detailed Description
Definition at line 21 of file ConstResidueIndexSequenceBoundaries.hh.
Constructor & Destructor Documentation
ConstResidueIndexSequenceBoundaries() [1/2]
cbrc::ConstResidueIndexSequenceBoundaries::ConstResidueIndexSequenceBoundaries (const ResidueIndexMap & rim, const ResidueIndexMap::indexT *const & _startPtr, const size_t & _size) inline
Definition at line 24 of file ConstResidueIndexSequenceBoundaries.hh.
ConstResidueIndexSequenceBoundaries() [2/2]
cbrc::ConstResidueIndexSequenceBoundaries::ConstResidueIndexSequenceBoundaries (const ConstResidueIndexSequenceBoundaries & sb) inline
Definition at line 29 of file ConstResidueIndexSequenceBoundaries.hh.
Member Function Documentation
endPtr()
const ResidueIndexMap::indexT * cbrc::ConstResidueIndexSequenceBoundaries::endPtr () const inline
Definition at line 37 of file ConstResidueIndexSequenceBoundaries.hh.
References size().
residueIndexMap()
const ResidueIndexMap & cbrc::ConstResidueIndexSequenceBoundaries::residueIndexMap () const inline
Definition at line 33 of file ConstResidueIndexSequenceBoundaries.hh.
size()
const size_t cbrc::ConstResidueIndexSequenceBoundaries::size () const inline
Definition at line 39 of file ConstResidueIndexSequenceBoundaries.hh.
Referenced by endPtr(), cbrc::ResidueIndexWindow::ResidueIndexWindow(), and cbrc::ResidueIndexWindow::seqEndIdx().
startPtr()
const ResidueIndexMap::indexT * cbrc::ConstResidueIndexSequenceBoundaries::startPtr () const inline
Definition at line 35 of file ConstResidueIndexSequenceBoundaries.hh.
Referenced by cbrc::ResidueIndexWindow::seqStartPtr(), cbrc::ResidueIndexWindow::windowLastPtr(), and cbrc::ResidueIndexWindow::windowStartIdx().
The documentation for this class was generated from the following file:
ematch_src/utils/sequence/ResidueIndexMap/ResidueIndexWindow/ConstResidueIndexSequenceBoundaries.hh