NGSFeatures: cbrc::Alignment Class Reference
cbrc::Alignment Class Reference
#include <Alignment.hh>
Public Types
typedef int alignScoreT
Public Member Functions
Alignment (const ResidueIndexMap &rim, const std::string &s0, const std::string &s1)
void outputHtml (std::ostream &os) const
void outputMarkSame (const std::string &outputFormat, std::ostream &os, const bool markDifferent=false, const char markChar=' *')
void outputHtmlMarkSame (std::ostream &os, const bool markDifferent=false, const char markChar=' *') const
void outputTextMarkSame (std::ostream &os, const bool markDifferent=false, const char markChar=' *') const
size_t size () const
double percentIdentity () const
alignScoreT score (const AminoScore &aScore) const
void assertStringsValid () const
Static Public Member Functions
static char indelChar ()
Friends
std::ostream & operator<< (std::ostream &os, const Alignment &al)
Detailed Description
Definition at line 26 of file Alignment.hh.
Member Typedef Documentation
alignScoreT
typedef int cbrc::Alignment::alignScoreT
Definition at line 29 of file Alignment.hh.
Constructor & Destructor Documentation
Alignment()
cbrc::Alignment::Alignment (const ResidueIndexMap & rim, const std::string & s0, const std::string & s1) inline
Definition at line 31 of file Alignment.hh.
Member Function Documentation
assertStringsValid()
void cbrc::Alignment::assertStringsValid () const
Definition at line 23 of file Alignment.cc.
References indelChar(), and size().
indelChar()
static char cbrc::Alignment::indelChar () inline static
Definition at line 46 of file Alignment.hh.
Referenced by cbrc::GlobalAffineDist::alignment(), cbrc::GlobalAffineIdentityAligner::alignment(), cbrc::SeqGlobalAffineAligner::alignment(), assertStringsValid(), outputHtml(), outputHtmlMarkSame(), outputTextMarkSame(), and score().
outputHtml()
void cbrc::Alignment::outputHtml (std::ostream & os) const
Definition at line 71 of file Alignment.cc.
References indelChar(), cbrc::FLEArray< T >::size(), size(), and cbrc::perlish::toString().
outputHtmlMarkSame()
void cbrc::Alignment::outputHtmlMarkSame (std::ostream & os, const bool markDifferent = false, const char markChar = '*') const
Definition at line 146 of file Alignment.cc.
References indelChar(), markDifferent, cbrc::FLEArray< T >::size(), size(), and cbrc::perlish::toString().
Referenced by outputMarkSame().
outputMarkSame()
void cbrc::Alignment::outputMarkSame (const std::string & outputFormat, std::ostream & os, const bool markDifferent = false, const char markChar = '*')
Definition at line 127 of file Alignment.cc.
References ALIGNMENT_OUTPUT_FORMATS, markDifferent, outputHtmlMarkSame(), outputTextMarkSame(), and Q.
outputTextMarkSame()
void cbrc::Alignment::outputTextMarkSame (std::ostream & os, const bool markDifferent = false, const char markChar = '*') const
Definition at line 207 of file Alignment.cc.
References indelChar(), markDifferent, size(), and cbrc::perlish::toString().
Referenced by outputMarkSame().
percentIdentity()
double cbrc::Alignment::percentIdentity () const
Definition at line 65 of file Alignment.cc.
References size().
score()
alignScoreT cbrc::Alignment::score (const AminoScore & aScore) const
Definition at line 47 of file Alignment.cc.
References cbrc::AminoScore::gapExtension(), cbrc::AminoScore::gapInitiation(), indelChar(), cbrc::AminoScore::score(), and size().
size()
size_t cbrc::Alignment::size () const inline
Definition at line 47 of file Alignment.hh.
Referenced by assertStringsValid(), outputHtml(), outputHtmlMarkSame(), outputTextMarkSame(), percentIdentity(), and score().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const Alignment & al) friend
Definition at line 266 of file Alignment.cc.
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/align/Alignment.hh
ematch_src/utils/sequence/align/Alignment.cc