NGSFeatures: cbrc::ResidueIndexMapTransformer Class Reference
cbrc::ResidueIndexMapTransformer Class Reference
#include <ResidueIndexMapTransformer.hh>
Public Member Functions
ResidueIndexMapTransformer (const ResidueIndexMap &origResidueIndexMap, const ResidueIndexMap &tranResidueIndexMap, const std::string &origAscii, const std::string &tranAscii)
void transformInPlace (ResidueIndexMap::indexT &indexToTransform)
void transformInPlace (ResidueIndexMap::arrayT &indicesToTransform)
Detailed Description
Definition at line 22 of file ResidueIndexMapTransformer.hh.
Constructor & Destructor Documentation
ResidueIndexMapTransformer()
cbrc::ResidueIndexMapTransformer::ResidueIndexMapTransformer (const ResidueIndexMap & origResidueIndexMap, const ResidueIndexMap & tranResidueIndexMap, const std::string & origAscii, const std::string & tranAscii)
Definition at line 17 of file ResidueIndexMapTransformer.cc.
References cbrc::FLEArray< T >::fill(), GDB_ASSERTF, cbrc::FLEArray< T >::setSize(), cbrc::FLEArray< T >::size(), cbrc::ResidueIndexMap::toResidueIndices(), and UNINITIALIZED.
Member Function Documentation
transformInPlace() [1/2]
void cbrc::ResidueIndexMapTransformer::transformInPlace (ResidueIndexMap::arrayT & indicesToTransform)
Definition at line 60 of file ResidueIndexMapTransformer.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and transformInPlace().
transformInPlace() [2/2]
void cbrc::ResidueIndexMapTransformer::transformInPlace (ResidueIndexMap::indexT & indexToTransform) inline
Definition at line 48 of file ResidueIndexMapTransformer.cc.
References GDB_ASSERTF, and UNINITIALIZED.
Referenced by transformInPlace().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/ResidueIndexMap/ResidueIndexMapTransformer.hh
ematch_src/utils/sequence/ResidueIndexMap/ResidueIndexMapTransformer.cc