NGSFeatures: cbrc::FastaRecord Class Reference
cbrc::FastaRecord Class Reference
#include <FastaRecord.hh>
Public Types
typedef std::vector< std::string > stringVecT
Public Member Functions
FastaRecord ()
FastaRecord (const std::string &seq, const std::string name=defaultName())
FastaRecord (const std::string &seq, std::vector< std::string > labels)
const std::string & seq () const
std::string & seqRef ()
void setSeq (const std::string &seq)
const std::string & name () const
const std::string & label (const size_t &i) const
const stringVecT & labels () const
void setLabels (const stringVecT &labels)
void setLabel (const size_t &i, const std::string &label)
const stringVecT & commentLinesBeforeHead () const
const std::string & headLine () const
const stringVecT & bodyLines () const
void clear ()
Static Public Member Functions
static const std::string & defaultName ()
static const std::string & nullString ()
Friends
class FastaRecordReader
Detailed Description
Definition at line 27 of file FastaRecord.hh.
Member Typedef Documentation
stringVecT
typedef std::vector<std::string> cbrc::FastaRecord::stringVecT
Definition at line 31 of file FastaRecord.hh.
Constructor & Destructor Documentation
FastaRecord() [1/3]
cbrc::FastaRecord::FastaRecord () inline
Definition at line 36 of file FastaRecord.hh.
FastaRecord() [2/3]
cbrc::FastaRecord::FastaRecord (const std::string & seq, const std::string name = defaultName()) inline
Definition at line 40 of file FastaRecord.hh.
References name().
FastaRecord() [3/3]
cbrc::FastaRecord::FastaRecord (const std::string & seq, std::vector< std::string > labels) inline
Definition at line 45 of file FastaRecord.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and labels().
Member Function Documentation
bodyLines()
const stringVecT & cbrc::FastaRecord::bodyLines () const inline
Definition at line 77 of file FastaRecord.hh.
clear()
void cbrc::FastaRecord::clear ()
Definition at line 18 of file FastaRecord.cc.
Referenced by cbrc::FastaRecordReader::nextRecord().
commentLinesBeforeHead()
const stringVecT & cbrc::FastaRecord::commentLinesBeforeHead () const inline
Definition at line 75 of file FastaRecord.hh.
defaultName()
static const std::string & cbrc::FastaRecord::defaultName () inline static
Definition at line 81 of file FastaRecord.hh.
headLine()
const std::string & cbrc::FastaRecord::headLine () const inline
Definition at line 76 of file FastaRecord.hh.
label()
const std::string & cbrc::FastaRecord::label (const size_t & i) const inline
Definition at line 62 of file FastaRecord.hh.
References labels().
Referenced by name(), and setLabel().
labels()
const stringVecT & cbrc::FastaRecord::labels () const inline
Definition at line 64 of file FastaRecord.hh.
Referenced by FastaRecord(), label(), setLabel(), and setLabels().
name()
const std::string & cbrc::FastaRecord::name () const inline
Definition at line 60 of file FastaRecord.hh.
References label().
Referenced by FastaRecord().
nullString()
static const std::string & cbrc::FastaRecord::nullString () inline static
Definition at line 87 of file FastaRecord.hh.
seq()
const std::string & cbrc::FastaRecord::seq () const inline
Definition at line 53 of file FastaRecord.hh.
Referenced by cbrc::FastaReader::seq(), and setSeq().
seqRef()
std::string & cbrc::FastaRecord::seqRef () inline
Definition at line 56 of file FastaRecord.hh.
Referenced by cbrc::FastaReader::readRecord(), and cbrc::FastaReader::upcaseSequence().
setLabel()
void cbrc::FastaRecord::setLabel (const size_t & i, const std::string & label) inline
Definition at line 70 of file FastaRecord.hh.
References label(), and labels().
setLabels()
void cbrc::FastaRecord::setLabels (const stringVecT & labels) inline
Definition at line 66 of file FastaRecord.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and labels().
setSeq()
void cbrc::FastaRecord::setSeq (const std::string & seq) inline
Definition at line 58 of file FastaRecord.hh.
References seq().
Friends And Related Symbol Documentation
FastaRecordReader
friend class FastaRecordReader friend
Definition at line 98 of file FastaRecord.hh.
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/readers/fasta/FastaRecord.hh
ematch_src/utils/sequence/readers/fasta/FastaRecord.cc