NGSFeatures: cbrc::KnapsackObject Class Reference
cbrc::KnapsackObject Class Reference
#include <KnapsackObject.hh>
Public Types
typedef short unsigned idT
typedef double weightT
Public Member Functions
KnapsackObject (const idT &id, const weightT &weight)
const idT & id () const
const weightT & weight () const
bool operator< (const KnapsackObject &otherObject) const
Detailed Description
Definition at line 19 of file KnapsackObject.hh.
Member Typedef Documentation
idT
typedef short unsigned cbrc::KnapsackObject::idT
Definition at line 22 of file KnapsackObject.hh.
weightT
typedef double cbrc::KnapsackObject::weightT
Definition at line 23 of file KnapsackObject.hh.
Constructor & Destructor Documentation
KnapsackObject()
cbrc::KnapsackObject::KnapsackObject (const idT & id, const weightT & weight) inline
Definition at line 26 of file KnapsackObject.hh.
Member Function Documentation
id()
const idT & cbrc::KnapsackObject::id () const inline
Definition at line 32 of file KnapsackObject.hh.
Referenced by operator<().
operator<()
bool cbrc::KnapsackObject::operator< (const KnapsackObject & otherObject) const inline
Definition at line 39 of file KnapsackObject.hh.
References id(), and weight().
weight()
const weightT & cbrc::KnapsackObject::weight () const inline
Definition at line 34 of file KnapsackObject.hh.
Referenced by operator<().
The documentation for this class was generated from the following file:
knapsack_src/KnapsackObject.hh