NGSFeatures: cbrc::TextWindow< T > Class Template Reference
cbrc::TextWindow< T > Class Template Reference
#include <TextWindow.hh>
Public Member Functions
TextWindow (const T *const textPtr, const size_t windowStartIdx, const size_t windowEndIdx, const size_t &textEndIdx)
TextWindow (const TextWindow &tw)
TextWindow (const TextWindow &tw, const int &windowStartRelativeIdx, const size_t &newWindowSize)
size_t size () const
size_t leftContextSize () const
size_t rightContextSize () const
const T *const & textRef () const
const T *const windowPtr () const
const T *const windowLastPtr () const
const size_t textSize () const
const size_t windowStartIdx () const
const size_t windowEndIdx () const
FLArray< T > getFLArray () const
FLEArray< T > getFLEArray () const
void operator++ ()
void operator-- ()
const T & operator() (int idx) const
bool validRelativeIdx (int idx)
Detailed Description
template<typename T>
class cbrc::TextWindow< T >
Definition at line 39 of file TextWindow.hh.
Constructor & Destructor Documentation
TextWindow() [1/3]
template<typename T > cbrc::TextWindow< T >::TextWindow (const T *const textPtr, const size_t windowStartIdx, const size_t windowEndIdx, const size_t & textEndIdx) inline
Definition at line 41 of file TextWindow.hh.
References GDB_ASSERT, cbrc::TextWindow< T >::windowEndIdx(), and cbrc::TextWindow< T >::windowStartIdx().
TextWindow() [2/3]
template<typename T > cbrc::TextWindow< T >::TextWindow (const TextWindow< T > & tw) inline
Definition at line 52 of file TextWindow.hh.
References GDB_ASSERT, and cbrc::TextWindow< T >::windowStartIdx().
TextWindow() [3/3]
template<typename T > cbrc::TextWindow< T >::TextWindow (const TextWindow< T > & tw, const int & windowStartRelativeIdx, const size_t & newWindowSize) inline
Definition at line 62 of file TextWindow.hh.
References GDB_ASSERT, cbrc::TextWindow< T >::size(), and cbrc::TextWindow< T >::validRelativeIdx().
Member Function Documentation
getFLArray()
template<typename T > FLArray< T > cbrc::TextWindow< T >::getFLArray () const inline
Definition at line 83 of file TextWindow.hh.
References cbrc::TextWindow< T >::size().
getFLEArray()
template<typename T > FLEArray< T > cbrc::TextWindow< T >::getFLEArray () const inline
Definition at line 87 of file TextWindow.hh.
References cbrc::TextWindow< T >::size().
leftContextSize()
template<typename T > size_t cbrc::TextWindow< T >::leftContextSize () const inline
Definition at line 75 of file TextWindow.hh.
References cbrc::TextWindow< T >::windowStartIdx().
operator()()
template<typename T > const T & cbrc::TextWindow< T >::operator() (int idx) const inline
Definition at line 100 of file TextWindow.hh.
References cbrc::TextWindow< T >::validRelativeIdx().
operator++()
template<typename T > void cbrc::TextWindow< T >::operator++ () inline
Definition at line 90 of file TextWindow.hh.
References cbrc::TextWindow< T >::textSize(), and cbrc::TextWindow< T >::windowEndIdx().
operator--()
template<typename T > void cbrc::TextWindow< T >::operator-- () inline
Definition at line 95 of file TextWindow.hh.
References cbrc::TextWindow< T >::windowStartIdx().
rightContextSize()
template<typename T > size_t cbrc::TextWindow< T >::rightContextSize () const inline
Definition at line 76 of file TextWindow.hh.
size()
template<typename T > size_t cbrc::TextWindow< T >::size () const inline
Definition at line 74 of file TextWindow.hh.
References cbrc::TextWindow< T >::windowStartIdx().
Referenced by cbrc::TextWindow< T >::getFLArray(), cbrc::TextWindow< T >::getFLEArray(), cbrc::TextWindow< T >::TextWindow(), and cbrc::TextWindow< T >::windowLastPtr().
textRef()
template<typename T > const T *const & cbrc::TextWindow< T >::textRef () const inline
Definition at line 77 of file TextWindow.hh.
textSize()
template<typename T > const size_t cbrc::TextWindow< T >::textSize () const inline
Definition at line 80 of file TextWindow.hh.
Referenced by cbrc::TextWindow< T >::operator++(), and cbrc::TextWindow< T >::validRelativeIdx().
validRelativeIdx()
template<typename T > bool cbrc::TextWindow< T >::validRelativeIdx (int idx) inline
Definition at line 106 of file TextWindow.hh.
References cbrc::TextWindow< T >::textSize(), and cbrc::TextWindow< T >::windowStartIdx().
Referenced by cbrc::TextWindow< T >::operator()(), and cbrc::TextWindow< T >::TextWindow().
windowEndIdx()
template<typename T > const size_t cbrc::TextWindow< T >::windowEndIdx () const inline
Definition at line 82 of file TextWindow.hh.
Referenced by cbrc::TextWindow< T >::operator++(), and cbrc::TextWindow< T >::TextWindow().
windowLastPtr()
template<typename T > const T *const cbrc::TextWindow< T >::windowLastPtr () const inline
Definition at line 79 of file TextWindow.hh.
References cbrc::TextWindow< T >::size().
windowPtr()
template<typename T > const T *const cbrc::TextWindow< T >::windowPtr () const inline
Definition at line 78 of file TextWindow.hh.
windowStartIdx()
template<typename T > const size_t cbrc::TextWindow< T >::windowStartIdx () const inline
Definition at line 81 of file TextWindow.hh.
Referenced by cbrc::TextWindow< T >::leftContextSize(), cbrc::TextWindow< T >::operator--(), cbrc::TextWindow< T >::size(), cbrc::TextWindow< T >::TextWindow(), cbrc::TextWindow< T >::TextWindow(), and cbrc::TextWindow< T >::validRelativeIdx().
The documentation for this class was generated from the following file:
ematch_src/utils/textWindow/TextWindow.hh