NGSFeatures: cbrc::Sigma4FLArray Class Reference
cbrc::Sigma4FLArray Class Reference
#include <Sigma4FLArray.hh>
Public Types
typedef short unsigned int size_type
typedef unsigned char byte
typedef std::pair< size_type, byte > idxT
Public Member Functions
Sigma4FLArray ()
Sigma4FLArray (const Sigma4FLArray &arrayToCopy)
Sigma4FLArray (const std::vector< byte > &elems)
Sigma4FLArray (std::istream &iStream)
~Sigma4FLArray ()
void operator= (const Sigma4FLArray &)
const size_type & size () const
size_t byteSize () const
byte operator() (const size_t &i) const
byte operator() (const idxT &internalIdx) const
std::vector< byte > toByteVector () const
bool operator== (const Sigma4FLArray &otherArray) const
bool operator!= (const Sigma4FLArray &otherArray) const
bool operator< (const Sigma4FLArray &otherArray) const
bool operator<= (const Sigma4FLArray &otherArray) const
void read (std::istream &iStream)
void write (std::ostream &oStream) const
const char *const c_str () const
void hexDump ()
Static Public Member Functions
static idxT toInternalIdx (const size_t &externalId)
static const size_t & sigma ()
static size_type max_size ()
Detailed Description
Definition at line 34 of file Sigma4FLArray.hh.
Member Typedef Documentation
byte
typedef unsigned char cbrc::Sigma4FLArray::byte
Definition at line 39 of file Sigma4FLArray.hh.
idxT
typedef std::pair<size_type, byte> cbrc::Sigma4FLArray::idxT
Definition at line 42 of file Sigma4FLArray.hh.
size_type
typedef short unsigned int cbrc::Sigma4FLArray::size_type
Definition at line 38 of file Sigma4FLArray.hh.
Constructor & Destructor Documentation
Sigma4FLArray() [1/4]
cbrc::Sigma4FLArray::Sigma4FLArray () inline
Definition at line 46 of file Sigma4FLArray.hh.
Sigma4FLArray() [2/4]
cbrc::Sigma4FLArray::Sigma4FLArray (const Sigma4FLArray & arrayToCopy) inline
Definition at line 51 of file Sigma4FLArray.hh.
References cbrc::FLEArray< T >::a.
Sigma4FLArray() [3/4]
cbrc::Sigma4FLArray::Sigma4FLArray (const std::vector< byte > & elems)
Definition at line 25 of file Sigma4FLArray.cc.
References byteSize(), GDB_ASSERTF, cbrc::stlUtils::max(), max_size(), sigma(), and cbrc::FLEArray< T >::size().
Sigma4FLArray() [4/4]
cbrc::Sigma4FLArray::Sigma4FLArray (std::istream & iStream) inline
Definition at line 63 of file Sigma4FLArray.hh.
References read().
~Sigma4FLArray()
cbrc::Sigma4FLArray::~Sigma4FLArray () inline
Definition at line 69 of file Sigma4FLArray.hh.
Member Function Documentation
byteSize()
size_t cbrc::Sigma4FLArray::byteSize () const inline
Definition at line 80 of file Sigma4FLArray.hh.
References size().
Referenced by hexDump(), operator!=(), operator<(), operator=(), operator==(), read(), Sigma4FLArray(), and write().
c_str()
const char *const cbrc::Sigma4FLArray::c_str () const
Definition at line 175 of file Sigma4FLArray.cc.
References size().
hexDump()
void cbrc::Sigma4FLArray::hexDump ()
Definition at line 189 of file Sigma4FLArray.cc.
References byteSize().
max_size()
static size_type cbrc::Sigma4FLArray::max_size () inline static
Definition at line 131 of file Sigma4FLArray.hh.
Referenced by Sigma4FLArray().
operator!=()
bool cbrc::Sigma4FLArray::operator!= (const Sigma4FLArray & otherArray) const inline
Definition at line 102 of file Sigma4FLArray.hh.
References cbrc::FLEArray< T >::a, byteSize(), cbrc::FLEArray< T >::size(), and size().
operator()() [1/2]
Sigma4FLArray::byte cbrc::Sigma4FLArray::operator() (const idxT & internalIdx) const
Definition at line 89 of file Sigma4FLArray.cc.
References cbrc::mask.
operator()() [2/2]
byte cbrc::Sigma4FLArray::operator() (const size_t & i) const inline
Definition at line 84 of file Sigma4FLArray.hh.
References operator()(), and toInternalIdx().
Referenced by operator()().
operator<()
bool cbrc::Sigma4FLArray::operator< (const Sigma4FLArray & otherArray) const
Definition at line 109 of file Sigma4FLArray.cc.
References cbrc::FLEArray< T >::a, byteSize(), cbrc::FLEArray< T >::size(), and size().
operator<=()
bool cbrc::Sigma4FLArray::operator<= (const Sigma4FLArray & otherArray) const
operator=()
void cbrc::Sigma4FLArray::operator= (const Sigma4FLArray & arrayToCopy)
Definition at line 77 of file Sigma4FLArray.cc.
References cbrc::FLEArray< T >::a, byteSize(), and cbrc::FLEArray< T >::size().
operator==()
bool cbrc::Sigma4FLArray::operator== (const Sigma4FLArray & otherArray) const inline
Definition at line 96 of file Sigma4FLArray.hh.
References cbrc::FLEArray< T >::a, byteSize(), cbrc::FLEArray< T >::size(), and size().
read()
void cbrc::Sigma4FLArray::read (std::istream & iStream)
Definition at line 135 of file Sigma4FLArray.cc.
References byteSize(), and cbrc::FLEArray< T >::read().
Referenced by Sigma4FLArray().
sigma()
static const size_t & cbrc::Sigma4FLArray::sigma () inline static
Definition at line 126 of file Sigma4FLArray.hh.
Referenced by Sigma4FLArray(), and toInternalIdx().
size()
const size_type & cbrc::Sigma4FLArray::size () const inline
Definition at line 78 of file Sigma4FLArray.hh.
Referenced by byteSize(), c_str(), operator!=(), operator<(), cbrc::operator<<(), operator==(), and toByteVector().
toByteVector()
std::vector< Sigma4FLArray::byte > cbrc::Sigma4FLArray::toByteVector () const
Definition at line 123 of file Sigma4FLArray.cc.
References size().
toInternalIdx()
Sigma4FLArray::idxT cbrc::Sigma4FLArray::toInternalIdx (const size_t & externalId) static
Definition at line 163 of file Sigma4FLArray.cc.
References sigma().
Referenced by operator()().
write()
void cbrc::Sigma4FLArray::write (std::ostream & oStream) const
Definition at line 155 of file Sigma4FLArray.cc.
References byteSize(), and cbrc::FLEArray< T >::write().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/packedDNA/Sigma4FLArray.hh
ematch_src/utils/sequence/packedDNA/Sigma4FLArray.cc