NGSFeatures: cbrc::FastaSeqSlurper Class Reference
cbrc::FastaSeqSlurper Class Reference
#include <FastaSeqSlurper.hh>
Public Member Functions
FastaSeqSlurper (std::istream &defaultIstream=std::cin, const FastaInputOptions &inputOptions=defaultFastaInputOptions)
std::vector< LabeledAsciiSeq > slurpSeqs ()
std::vector< LabeledAsciiSeq > slurpSeqs (std::istream &iStream)
void slurpLabeledAsciiSeqs (std::vector< LabeledAsciiSeq > &labSeqs, std::istream &is)
std::vector< LabeledSequence > slurpLabeledSequences ()
std::vector< LabeledSequence > slurpLabeledSequences (std::istream &is)
std::vector< LabeledSequence > slurpLabeledSequences (std::istream &is, const ResidueIndexMap &residueIndexMap)
void slurpLabeledSequences (std::vector< LabeledSequence > &labSeqs)
void slurpLabeledSequences (std::vector< LabeledSequence > &labSeqs, const ResidueIndexMap &residueIndexMap)
void slurpLabeledSequences (std::vector< LabeledSequence > &labSeqs, std::istream &is)
void slurpLabeledSequences (std::vector< LabeledSequence > &labSeqs, std::istream &is, const ResidueIndexMap &residueIndexMap)
LabeledAsciiSeq getLabeledAsciiSeq () const
LabeledSequence getLabeledSequence () const
LabeledSequence getLabeledSequence (const ResidueIndexMap &residueIndexMap) const
Public Member Functions inherited from cbrc::FastaRecordReader
FastaRecordReader (std::istream &defaultIstream=std::cin, const FastaInputOptions &inputOptions=defaultFastaInputOptions)
const FastaRecord * nextRecord ()
const FastaRecord * nextRecord (std::istream &iStream)
const FastaRecord * nextRecordOrDie (const char *const errorMessage="")
const FastaRecord * nextRecordOrDie (std::istream &iStream, const char *const errorMessage="")
const FastaInputOptions & inputOptions () const
const FastaRecord & curRecord () const
const std::string & seq () const
std::string & seqRef ()
std::istream & defaultIstream () const
const std::string & defaultName ()
void freeCurRecord ()
Detailed Description
Definition at line 21 of file FastaSeqSlurper.hh.
Constructor & Destructor Documentation
FastaSeqSlurper()
cbrc::FastaSeqSlurper::FastaSeqSlurper (std::istream & defaultIstream = std::cin, const FastaInputOptions & inputOptions = defaultFastaInputOptions) inline
Definition at line 24 of file FastaSeqSlurper.hh.
Member Function Documentation
getLabeledAsciiSeq()
LabeledAsciiSeq cbrc::FastaSeqSlurper::getLabeledAsciiSeq () const inline
Definition at line 103 of file FastaSeqSlurper.hh.
References cbrc::FastaRecordReader::curRecord(), and cbrc::FastaRecordReader::seq().
Referenced by slurpLabeledAsciiSeqs(), and slurpSeqs().
getLabeledSequence() [1/2]
LabeledSequence cbrc::FastaSeqSlurper::getLabeledSequence () const inline
Definition at line 107 of file FastaSeqSlurper.hh.
References cbrc::FastaRecordReader::curRecord(), and cbrc::FastaRecordReader::seq().
Referenced by slurpLabeledSequences(), slurpLabeledSequences(), slurpLabeledSequences(), and slurpLabeledSequences().
getLabeledSequence() [2/2]
LabeledSequence cbrc::FastaSeqSlurper::getLabeledSequence (const ResidueIndexMap & residueIndexMap) const inline
Definition at line 111 of file FastaSeqSlurper.hh.
References cbrc::FastaRecordReader::curRecord(), and cbrc::FastaRecordReader::seq().
slurpLabeledAsciiSeqs()
void cbrc::FastaSeqSlurper::slurpLabeledAsciiSeqs (std::vector< LabeledAsciiSeq > & labSeqs, std::istream & is) inline
Definition at line 41 of file FastaSeqSlurper.hh.
References getLabeledAsciiSeq(), and cbrc::FastaRecordReader::nextRecord().
slurpLabeledSequences() [1/7]
std::vector< LabeledSequence > cbrc::FastaSeqSlurper::slurpLabeledSequences () inline
Definition at line 48 of file FastaSeqSlurper.hh.
References cbrc::FastaRecordReader::defaultIstream(), and slurpLabeledSequences().
Referenced by main(), slurpLabeledSequences(), slurpLabeledSequences(), and slurpLabeledSequences().
slurpLabeledSequences() [2/7]
std::vector< LabeledSequence > cbrc::FastaSeqSlurper::slurpLabeledSequences (std::istream & is) inline
Definition at line 53 of file FastaSeqSlurper.hh.
References getLabeledSequence(), and cbrc::FastaRecordReader::nextRecord().
slurpLabeledSequences() [3/7]
std::vector< LabeledSequence > cbrc::FastaSeqSlurper::slurpLabeledSequences (std::istream & is, const ResidueIndexMap & residueIndexMap) inline
Definition at line 64 of file FastaSeqSlurper.hh.
References getLabeledSequence(), and cbrc::FastaRecordReader::nextRecord().
slurpLabeledSequences() [4/7]
void cbrc::FastaSeqSlurper::slurpLabeledSequences (std::vector< LabeledSequence > & labSeqs) inline
Definition at line 78 of file FastaSeqSlurper.hh.
References cbrc::FastaRecordReader::defaultIstream(), and slurpLabeledSequences().
slurpLabeledSequences() [5/7]
void cbrc::FastaSeqSlurper::slurpLabeledSequences (std::vector< LabeledSequence > & labSeqs, const ResidueIndexMap & residueIndexMap) inline
Definition at line 82 of file FastaSeqSlurper.hh.
References cbrc::FastaRecordReader::defaultIstream(), and slurpLabeledSequences().
slurpLabeledSequences() [6/7]
void cbrc::FastaSeqSlurper::slurpLabeledSequences (std::vector< LabeledSequence > & labSeqs, std::istream & is) inline
Definition at line 87 of file FastaSeqSlurper.hh.
References getLabeledSequence(), and cbrc::FastaRecordReader::nextRecord().
slurpLabeledSequences() [7/7]
void cbrc::FastaSeqSlurper::slurpLabeledSequences (std::vector< LabeledSequence > & labSeqs, std::istream & is, const ResidueIndexMap & residueIndexMap) inline
Definition at line 92 of file FastaSeqSlurper.hh.
References getLabeledSequence(), and cbrc::FastaRecordReader::nextRecord().
slurpSeqs() [1/2]
std::vector< LabeledAsciiSeq > cbrc::FastaSeqSlurper::slurpSeqs () inline
Definition at line 34 of file FastaSeqSlurper.hh.
References cbrc::FastaRecordReader::defaultIstream(), and slurpSeqs().
Referenced by slurpSeqs().
slurpSeqs() [2/2]
std::vector< LabeledAsciiSeq > cbrc::FastaSeqSlurper::slurpSeqs (std::istream & iStream)
Definition at line 14 of file FastaSeqSlurper.cc.
References getLabeledAsciiSeq(), and cbrc::FastaRecordReader::nextRecord().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/readers/fasta/FastaSeqSlurper.hh
ematch_src/utils/sequence/readers/fasta/FastaSeqSlurper.cc