NGSFeatures: cbrc::SerialNumbersForStrings_accessCounting< serialNumT > Class Template Reference
cbrc::SerialNumbersForStrings_accessCounting< serialNumT > Class Template Reference
#include <SerialNumbersForStrings_accessCounting.hh>
Public Member Functions
SerialNumbersForStrings_accessCounting ()
SerialNumbersForStrings_accessCounting (const SerialNumbersForStrings< serialNumT > &sns)
SerialNumbersForStrings_accessCounting (const std::vector< std::string > &strings)
bool operator== (const SerialNumbersForStrings_accessCounting &sns) const
size_t size () const
serialNumT getSerialNumber (const std::string &s)
void registerNewSerialNumber (const std::string &s)
size_t operator() (const std::string &s) const
bool contains (const std::string &s) const
std::vector< std::string > strings () const
size_t accessCount (const size_t &serialNumber) const
const std::string & operator() (const size_t &serialNumber) const
void renumberByAccessCount ()
Public Member Functions inherited from cbrc::SerialNumbersForStrings< serialNumT >
SerialNumbersForStrings ()
SerialNumbersForStrings (const SerialNumbersForStrings &sns)
SerialNumbersForStrings (const stringVecT &strings)
virtual ~SerialNumbersForStrings ()
bool operator== (const SerialNumbersForStrings &sns) const
bool operator!= (const SerialNumbersForStrings &sns) const
virtual void registerNewSerialNumbers (const stringVecT &strings)
virtual void registerNewSerialNumbers (const stringVecT::const_iterator &beg, const stringVecT::const_iterator &end)
virtual const_iterator begin () const
virtual const_iterator end () const
virtual bool has (const std::string &s) const
void read (std::istream &iStream=std::cin)
void write (std::ostream &oStream=std::cout) const
Detailed Description
template<typename serialNumT>
class cbrc::SerialNumbersForStrings_accessCounting< serialNumT >
Definition at line 23 of file SerialNumbersForStrings_accessCounting.hh.
Constructor & Destructor Documentation
SerialNumbersForStrings_accessCounting() [1/3]
template<typename serialNumT > cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::SerialNumbersForStrings_accessCounting () inline
Definition at line 62 of file SerialNumbersForStrings_accessCounting.hh.
SerialNumbersForStrings_accessCounting() [2/3]
template<typename serialNumT > cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::SerialNumbersForStrings_accessCounting (const SerialNumbersForStrings< serialNumT > & sns) inline
Definition at line 64 of file SerialNumbersForStrings_accessCounting.hh.
References cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::registerNewSerialNumber(), and cbrc::FLEArray< T >::size().
SerialNumbersForStrings_accessCounting() [3/3]
template<typename serialNumT > cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::SerialNumbersForStrings_accessCounting (const std::vector< std::string > & strings) inline
Definition at line 71 of file SerialNumbersForStrings_accessCounting.hh.
References cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::registerNewSerialNumber(), cbrc::FLEArray< T >::size(), and cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::strings().
Member Function Documentation
accessCount()
template<typename serialNumT > size_t cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::accessCount (const size_t & serialNumber) const inline
Definition at line 108 of file SerialNumbersForStrings_accessCounting.hh.
contains()
template<typename serialNumT > bool cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::contains (const std::string & s) const inline
Definition at line 99 of file SerialNumbersForStrings_accessCounting.hh.
References cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::size().
getSerialNumber()
template<typename serialNumT > serialNumT cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::getSerialNumber (const std::string & s) virtual
Reimplemented from cbrc::SerialNumbersForStrings< serialNumT >.
Definition at line 131 of file SerialNumbersForStrings_accessCounting.hh.
References cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::size().
operator()() [1/2]
template<typename serialNumT > const std::string & cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::operator() (const size_t & serialNumber) const inline virtual
Reimplemented from cbrc::SerialNumbersForStrings< serialNumT >.
Definition at line 112 of file SerialNumbersForStrings_accessCounting.hh.
operator()() [2/2]
template<typename serialNumT > size_t cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::operator() (const std::string & s) const virtual
Reimplemented from cbrc::SerialNumbersForStrings< serialNumT >.
Definition at line 156 of file SerialNumbersForStrings_accessCounting.hh.
References cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::size().
operator==()
template<typename serialNumT > bool cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::operator== (const SerialNumbersForStrings_accessCounting< serialNumT > & sns) const inline
Definition at line 78 of file SerialNumbersForStrings_accessCounting.hh.
References cbrc::FLEArray< T >::size(), and cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::size().
registerNewSerialNumber()
template<typename serialNumT > void cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::registerNewSerialNumber (const std::string & s) inline virtual
Reimplemented from cbrc::SerialNumbersForStrings< serialNumT >.
Definition at line 92 of file SerialNumbersForStrings_accessCounting.hh.
Referenced by cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::SerialNumbersForStrings_accessCounting(), and cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::SerialNumbersForStrings_accessCounting().
renumberByAccessCount()
template<typename serialNumT > void cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::renumberByAccessCount () inline
Definition at line 117 of file SerialNumbersForStrings_accessCounting.hh.
size()
template<typename serialNumT > size_t cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::size () const inline virtual
Reimplemented from cbrc::SerialNumbersForStrings< serialNumT >.
Definition at line 86 of file SerialNumbersForStrings_accessCounting.hh.
Referenced by cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::contains(), and cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::operator==().
strings()
template<typename serialNumT > std::vector< std::string > cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::strings () const virtual
Reimplemented from cbrc::SerialNumbersForStrings< serialNumT >.
Definition at line 168 of file SerialNumbersForStrings_accessCounting.hh.
References cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
Referenced by cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::SerialNumbersForStrings_accessCounting().
The documentation for this class was generated from the following file:
ematch_src/utils/serialNumbers/SerialNumbersForStrings/SerialNumbersForStrings_accessCounting.hh