NGSFeatures: cbrc::FLNumMatrix< T > Class Template Reference
cbrc::FLNumMatrix< T > Class Template Reference
#include <FLMatrix.hh>
Public Member Functions
FLNumMatrix ()
FLNumMatrix (const size_t sz0, const size_t sz1)
FLNumMatrix (const size_t sz0, const size_t sz1, const T fillVal)
FLNumMatrix (const size_t sz0, const size_t sz1, const T **const b)
FLNumMatrix (const std::vector< std::vector< T > > v)
FLNumMatrix (const FLMatrix< T > &flm)
FLNumMatrix operator= (const std::vector< std::vector< T > > v)
FLNumMatrix operator= (const FLNumMatrix &flm)
FLNumMatrix & operator*= (T el)
FLNumMatrix & operator/= (T el)
FLNumMatrix & operator+= (T el)
FLNumMatrix & operator+= (const FLNumMatrix &flm)
T sum ()
T sum (unsigned char dimension, unsigned int index)
T divide (unsigned char dimension, unsigned int index, T divisor)
void normalize (unsigned char dimension)
Public Member Functions inherited from cbrc::FLMatrix< T >
FLMatrix ()
FLMatrix (const size_t sz0, const size_t sz1)
FLMatrix (const size_t sz0, const size_t sz1, const T fillVal)
FLMatrix (const size_t sz0, const size_t sz1, const T **const b)
FLMatrix (const std::vector< std::vector< T > > v)
FLMatrix (const FLMatrix< T > &flm)
virtual ~FLMatrix ()
void setSize (size_t sz0, size_t sz1)
void resizeDestructive (size_t sz0, size_t sz1)
FLMatrix operator= (const FLMatrix &flm)
FLMatrix operator= (std::vector< std::vector< T > > v)
T getVal (size_t index0, size_t index1, T defValue)
void zero ()
void fill (T fillVal)
void fillWithByte (int fillByte)
bool validIndex (size_t index) const
bool validIndex (size_t index0, size_t index1) const
bool operator== (const FLMatrix &flm) const
virtual T & operator[] (const size_t index) const
virtual T & operator() (const size_t index0, const size_t index1) const
FLMatrix< T > submatrix (const size_t startRow, const size_t endRow, const size_t startCol, const size_t endCol) const
void printColumnMajor (std::ostream &os) const
void shiftLeft (FLArray< T > newCol)
void shiftRight (FLArray< T > newCol)
virtual const T * getColPtr (const size_t index0) const
size_t size () const
size_t size0 () const
size_t size1 () const
iterator begin () const
iterator end () const
T * getPtr () const
void friend testFLMatrix ()
Additional Inherited Members
Public Types inherited from cbrc::FLMatrix< T >
typedef T * iterator
typedef const T * const_iterator
Protected Member Functions inherited from cbrc::FLMatrix< T >
bool validAsMatrix (std::vector< std::vector< T > > v) const
Protected Attributes inherited from cbrc::FLMatrix< T >
size_t s
size_t s0
size_t s1
T * m
Detailed Description
template<typename T>
class cbrc::FLNumMatrix< T >
Definition at line 272 of file FLMatrix.hh.
Constructor & Destructor Documentation
FLNumMatrix() [1/6]
template<typename T > cbrc::FLNumMatrix< T >::FLNumMatrix () inline
Definition at line 274 of file FLMatrix.hh.
FLNumMatrix() [2/6]
template<typename T > cbrc::FLNumMatrix< T >::FLNumMatrix (const size_t sz0, const size_t sz1) inline
Definition at line 275 of file FLMatrix.hh.
FLNumMatrix() [3/6]
template<typename T > cbrc::FLNumMatrix< T >::FLNumMatrix (const size_t sz0, const size_t sz1, const T fillVal) inline
Definition at line 276 of file FLMatrix.hh.
FLNumMatrix() [4/6]
template<typename T > cbrc::FLNumMatrix< T >::FLNumMatrix (const size_t sz0, const size_t sz1, const T **const b) inline
Definition at line 277 of file FLMatrix.hh.
FLNumMatrix() [5/6]
template<typename T > cbrc::FLNumMatrix< T >::FLNumMatrix (const std::vector< std::vector< T > > v) inline
Definition at line 278 of file FLMatrix.hh.
FLNumMatrix() [6/6]
template<typename T > cbrc::FLNumMatrix< T >::FLNumMatrix (const FLMatrix< T > & flm) inline
Definition at line 279 of file FLMatrix.hh.
Member Function Documentation
divide()
template<typename T > T cbrc::FLNumMatrix< T >::divide (unsigned char dimension, unsigned int index, T divisor) inline
Definition at line 331 of file FLMatrix.hh.
Referenced by cbrc::FLNumMatrix< T >::normalize().
normalize()
template<typename T > void cbrc::FLNumMatrix< T >::normalize (unsigned char dimension) inline
Definition at line 349 of file FLMatrix.hh.
References cbrc::FLNumMatrix< T >::divide(), cbrc::FLMatrix< T >::size0(), cbrc::FLMatrix< T >::size1(), and cbrc::FLNumMatrix< T >::sum().
operator*=()
template<typename T > FLNumMatrix & cbrc::FLNumMatrix< T >::operator*= (T el) inline
Definition at line 284 of file FLMatrix.hh.
operator+=() [1/2]
template<typename T > FLNumMatrix & cbrc::FLNumMatrix< T >::operator+= (const FLNumMatrix< T > & flm) inline
Definition at line 296 of file FLMatrix.hh.
operator+=() [2/2]
template<typename T > FLNumMatrix & cbrc::FLNumMatrix< T >::operator+= (T el) inline
Definition at line 292 of file FLMatrix.hh.
operator/=()
template<typename T > FLNumMatrix & cbrc::FLNumMatrix< T >::operator/= (T el) inline
Definition at line 288 of file FLMatrix.hh.
operator=() [1/2]
template<typename T > FLNumMatrix cbrc::FLNumMatrix< T >::operator= (const FLNumMatrix< T > & flm) inline
Definition at line 283 of file FLMatrix.hh.
operator=() [2/2]
template<typename T > FLNumMatrix cbrc::FLNumMatrix< T >::operator= (const std::vector< std::vector< T > > v) inline
Definition at line 280 of file FLMatrix.hh.
sum() [1/2]
template<typename T > T cbrc::FLNumMatrix< T >::sum () inline
Definition at line 302 of file FLMatrix.hh.
Referenced by cbrc::FLNumMatrix< T >::normalize().
sum() [2/2]
template<typename T > T cbrc::FLNumMatrix< T >::sum (unsigned char dimension, unsigned int index) inline
Definition at line 310 of file FLMatrix.hh.
The documentation for this class was generated from the following file:
ematch_src/utils/FLArray/FLMatrix.hh