NGSFeatures: cbrc::GlobalAffineIdentityAligner Class Reference
cbrc::GlobalAffineIdentityAligner Class Reference
#include <GlobalAffineIdentityAligner.hh>
Public Member Functions
GlobalAffineIdentityAligner (const ResidueSimilarityAffineEdit &residueSimilarityMeasure, const ResidueIndexMap::arrayT &seq0)
const ResidueIndexMap::arrayT & residues () const
const alignScoreT & bestPossibleScore () const
alignScoreT score (const ResidueIndexMap::arrayT &s1) const
double identity (const ResidueIndexMap::arrayT &s1) const
alignScoreT scoreFreeStartGap (const ResidueIndexMap::arrayT &s1)
Alignment alignment (const ResidueIndexMap::arrayT &s1)
alignScoreT scoreBounded (const ResidueIndexMap::arrayT &s1, const FLEArrayFast< alignScoreT > &s1BestPossibleSuffixScores, const alignScoreT lowerBound)
alignScoreT lengthDifferenceBasedScoreUpperBound (const ResidueIndexMap::arrayT &s1) const
alignScoreT purelyLengthDifferenceBasedScoreUpperBound (const size_t &len1) const
alignScoreT feasibleBound (const ResidueIndexMap::arrayT &s1)
alignScoreT singleSeqBasedScoreUpperBound (const ResidueIndexMap::arrayT &s1) const
FLEArray< alignScoreT > bestPossibleSuffixScore (const ResidueIndexMap::arrayT &s0) const
void bestPossibleSuffixScore (const ResidueIndexMap::arrayT &s0, FLEArray< alignScoreT > &suffixScores) const
Detailed Description
Definition at line 27 of file GlobalAffineIdentityAligner.hh.
Constructor & Destructor Documentation
GlobalAffineIdentityAligner()
cbrc::GlobalAffineIdentityAligner::GlobalAffineIdentityAligner (const ResidueSimilarityAffineEdit & residueSimilarityMeasure, const ResidueIndexMap::arrayT & seq0) inline
Definition at line 29 of file GlobalAffineIdentityAligner.hh.
References cbrc::FLEMatrix< T >::setSize(), singleSeqBasedScoreUpperBound(), and cbrc::FLEArray< T >::size().
Member Function Documentation
alignment()
Alignment cbrc::GlobalAffineIdentityAligner::alignment (const ResidueIndexMap::arrayT & s1)
Definition at line 99 of file GlobalAffineIdentityAligner.cc.
References cbrc::alignScoreTMin, cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), cbrc::Alignment::indelChar(), score(), and cbrc::FLEArray< T >::size().
bestPossibleScore()
const alignScoreT & cbrc::GlobalAffineIdentityAligner::bestPossibleScore () const inline
Definition at line 47 of file GlobalAffineIdentityAligner.hh.
bestPossibleSuffixScore() [1/2]
FLEArray< alignScoreT > cbrc::GlobalAffineIdentityAligner::bestPossibleSuffixScore (const ResidueIndexMap::arrayT & s0) const inline
Definition at line 89 of file GlobalAffineIdentityAligner.hh.
References bestPossibleSuffixScore(), and cbrc::FLEArray< T >::size().
Referenced by bestPossibleSuffixScore().
bestPossibleSuffixScore() [2/2]
void cbrc::GlobalAffineIdentityAligner::bestPossibleSuffixScore (const ResidueIndexMap::arrayT & s0, FLEArray< alignScoreT > & suffixScores) const
Definition at line 434 of file GlobalAffineIdentityAligner.cc.
References cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
feasibleBound()
alignScoreT cbrc::GlobalAffineIdentityAligner::feasibleBound (const ResidueIndexMap::arrayT & s1)
Definition at line 271 of file GlobalAffineIdentityAligner.cc.
References cbrc::FLEArray< T >::size().
identity()
double cbrc::GlobalAffineIdentityAligner::identity (const ResidueIndexMap::arrayT & s1) const inline
Definition at line 53 of file GlobalAffineIdentityAligner.hh.
References score(), and cbrc::FLEArray< T >::size().
lengthDifferenceBasedScoreUpperBound()
alignScoreT cbrc::GlobalAffineIdentityAligner::lengthDifferenceBasedScoreUpperBound (const ResidueIndexMap::arrayT & s1) const
Definition at line 48 of file GlobalAffineIdentityAligner.cc.
References cbrc::FLEArray< T >::size().
purelyLengthDifferenceBasedScoreUpperBound()
alignScoreT cbrc::GlobalAffineIdentityAligner::purelyLengthDifferenceBasedScoreUpperBound (const size_t & len1) const
Definition at line 35 of file GlobalAffineIdentityAligner.cc.
References cbrc::FLEArray< T >::size().
residues()
const ResidueIndexMap::arrayT & cbrc::GlobalAffineIdentityAligner::residues () const inline
Definition at line 40 of file GlobalAffineIdentityAligner.hh.
score()
alignScoreT cbrc::GlobalAffineIdentityAligner::score (const ResidueIndexMap::arrayT & s1) const
Definition at line 62 of file GlobalAffineIdentityAligner.cc.
References cbrc::alignScoreTMin, score(), and cbrc::FLEArray< T >::size().
Referenced by alignment(), identity(), score(), and scoreFreeStartGap().
scoreBounded()
alignScoreT cbrc::GlobalAffineIdentityAligner::scoreBounded (const ResidueIndexMap::arrayT & s1, const FLEArrayFast< alignScoreT > & s1BestPossibleSuffixScores, const alignScoreT lowerBound)
Definition at line 330 of file GlobalAffineIdentityAligner.cc.
References cbrc::alignScoreTMin, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
scoreFreeStartGap()
alignScoreT cbrc::GlobalAffineIdentityAligner::scoreFreeStartGap (const ResidueIndexMap::arrayT & s1)
Definition at line 224 of file GlobalAffineIdentityAligner.cc.
References score(), and cbrc::FLEArray< T >::size().
singleSeqBasedScoreUpperBound()
alignScoreT cbrc::GlobalAffineIdentityAligner::singleSeqBasedScoreUpperBound (const ResidueIndexMap::arrayT & s1) const inline
Definition at line 85 of file GlobalAffineIdentityAligner.hh.
References cbrc::FLEArray< T >::size().
Referenced by GlobalAffineIdentityAligner().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/align/GlobalAffineIdentityAligner.hh
ematch_src/utils/sequence/align/GlobalAffineIdentityAligner.cc