NGSFeatures: cbrc::ResidueIndexWindow Class Reference
cbrc::ResidueIndexWindow Class Reference
#include <ResidueIndexWindow.hh>
Public Member Functions
ResidueIndexWindow (const ConstResidueIndexSequenceBoundaries *const seqBoundariesPtr, const size_t &windowStartIdx, const size_t &_windowEndIdx)
ResidueIndexWindow (const ResidueIndexWindow &tw)
ResidueIndexWindow (const ResidueIndexWindow &tw, const int &windowStartRelativeIdx, const size_t &newWindowSize)
size_t size () const
size_t leftContextSize () const
size_t rightContextSize () const
const indexT *const seqStartPtr () const
const indexT *const windowStartPtr () const
const indexT *const windowLastPtr () const
const size_t seqSize () const
const size_t windowStartIdx () const
const size_t windowEndIdx () const
const size_t seqEndIdx () const
FLEArray< indexT > getFLEArray () const
bool increment ()
bool decrement ()
const indexT & operator() (const int &relativeIdx) const
size_t relativeIdxToSeqIdx (const int &relativeIdx)
bool validRelativeIdx (const int &relativeIdx) const
bool validBoundaries () const
Friends
std::ostream & operator<< (std::ostream &os, const ResidueIndexWindow &riw)
Detailed Description
Definition at line 30 of file ResidueIndexWindow.hh.
Constructor & Destructor Documentation
ResidueIndexWindow() [1/3]
cbrc::ResidueIndexWindow::ResidueIndexWindow (const ConstResidueIndexSequenceBoundaries *const seqBoundariesPtr, const size_t & windowStartIdx, const size_t & _windowEndIdx)
Definition at line 13 of file ResidueIndexWindow.cc.
References GDB_ASSERT, cbrc::ConstResidueIndexSequenceBoundaries::size(), and windowStartIdx().
ResidueIndexWindow() [2/3]
cbrc::ResidueIndexWindow::ResidueIndexWindow (const ResidueIndexWindow & tw)
Definition at line 27 of file ResidueIndexWindow.cc.
References GDB_ASSERT, seqEndIdx(), and windowStartIdx().
ResidueIndexWindow() [3/3]
cbrc::ResidueIndexWindow::ResidueIndexWindow (const ResidueIndexWindow & tw, const int & windowStartRelativeIdx, const size_t & newWindowSize)
Definition at line 38 of file ResidueIndexWindow.cc.
References GDB_ASSERT, and seqStartPtr().
Member Function Documentation
decrement()
bool cbrc::ResidueIndexWindow::decrement () inline
Definition at line 65 of file ResidueIndexWindow.hh.
References windowEndIdx().
getFLEArray()
FLEArray< indexT > cbrc::ResidueIndexWindow::getFLEArray () const inline
Definition at line 56 of file ResidueIndexWindow.hh.
References size(), and windowStartPtr().
increment()
bool cbrc::ResidueIndexWindow::increment () inline
Definition at line 59 of file ResidueIndexWindow.hh.
References seqSize(), and windowEndIdx().
leftContextSize()
size_t cbrc::ResidueIndexWindow::leftContextSize () const inline
Definition at line 43 of file ResidueIndexWindow.hh.
References windowStartIdx().
operator()()
const indexT & cbrc::ResidueIndexWindow::operator() (const int & relativeIdx) const inline
Definition at line 71 of file ResidueIndexWindow.hh.
References validRelativeIdx().
relativeIdxToSeqIdx()
size_t cbrc::ResidueIndexWindow::relativeIdxToSeqIdx (const int & relativeIdx) inline
Definition at line 77 of file ResidueIndexWindow.hh.
References validRelativeIdx(), and windowStartIdx().
rightContextSize()
size_t cbrc::ResidueIndexWindow::rightContextSize () const inline
Definition at line 44 of file ResidueIndexWindow.hh.
References seqEndIdx().
seqEndIdx()
const size_t cbrc::ResidueIndexWindow::seqEndIdx () const inline
Definition at line 55 of file ResidueIndexWindow.hh.
References cbrc::ConstResidueIndexSequenceBoundaries::size().
Referenced by ResidueIndexWindow(), rightContextSize(), seqSize(), and validRelativeIdx().
seqSize()
const size_t cbrc::ResidueIndexWindow::seqSize () const inline
Definition at line 50 of file ResidueIndexWindow.hh.
References seqEndIdx().
Referenced by increment().
seqStartPtr()
const indexT *const cbrc::ResidueIndexWindow::seqStartPtr () const inline
Definition at line 45 of file ResidueIndexWindow.hh.
References cbrc::ConstResidueIndexSequenceBoundaries::startPtr().
Referenced by ResidueIndexWindow().
size()
size_t cbrc::ResidueIndexWindow::size () const inline
Definition at line 42 of file ResidueIndexWindow.hh.
References windowStartIdx().
Referenced by getFLEArray().
validBoundaries()
bool cbrc::ResidueIndexWindow::validBoundaries () const inline
Definition at line 84 of file ResidueIndexWindow.hh.
References validRelativeIdx(), windowEndIdx(), and windowStartIdx().
validRelativeIdx()
bool cbrc::ResidueIndexWindow::validRelativeIdx (const int & relativeIdx) const
Definition at line 51 of file ResidueIndexWindow.cc.
References seqEndIdx(), and windowStartIdx().
Referenced by operator()(), relativeIdxToSeqIdx(), and validBoundaries().
windowEndIdx()
const size_t cbrc::ResidueIndexWindow::windowEndIdx () const inline
Definition at line 54 of file ResidueIndexWindow.hh.
Referenced by decrement(), increment(), validBoundaries(), and windowLastPtr().
windowLastPtr()
const indexT *const cbrc::ResidueIndexWindow::windowLastPtr () const inline
Definition at line 47 of file ResidueIndexWindow.hh.
References cbrc::ConstResidueIndexSequenceBoundaries::startPtr(), and windowEndIdx().
windowStartIdx()
const size_t cbrc::ResidueIndexWindow::windowStartIdx () const inline
Definition at line 51 of file ResidueIndexWindow.hh.
References cbrc::ConstResidueIndexSequenceBoundaries::startPtr().
Referenced by leftContextSize(), relativeIdxToSeqIdx(), ResidueIndexWindow(), ResidueIndexWindow(), size(), validBoundaries(), and validRelativeIdx().
windowStartPtr()
const indexT *const cbrc::ResidueIndexWindow::windowStartPtr () const inline
Definition at line 46 of file ResidueIndexWindow.hh.
Referenced by getFLEArray(), and cbrc::ResiduesIndexMap::operator()().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const ResidueIndexWindow & riw) friend
Definition at line 95 of file ResidueIndexWindow.hh.
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/ResidueIndexMap/ResidueIndexWindow/ResidueIndexWindow.hh
ematch_src/utils/sequence/ResidueIndexMap/ResidueIndexWindow/ResidueIndexWindow.cc