NGSFeatures: cbrc::RecountNeighborList Class Reference
cbrc::RecountNeighborList Class Reference
#include <RecountNeighborList.hh>
Public Types
typedef std::vector< RecountTagIdProbPair > neighborVecT
typedef neighborVecT::const_iterator const_iterator
typedef neighborVecT::iterator iterator
Public Member Functions
RecountNeighborList ()
RecountNeighborList (const tagIdT &id, const tagIdVecT &neighborIds, const probVecT &neighborProbs)
void set (const tagIdT &id, const tagIdVecT &neighborIds, const probVecT &neighborProbs)
void set (const tagIdVecT &neighborIds, const probVecT &neighborProbs)
const tagIdT & id () const
const_iterator begin () const
const_iterator end () const
bool read (std::istream &iStream)
void write (std::ostream &oStream) const
void normalizeProbabilities ()
Detailed Description
Definition at line 23 of file RecountNeighborList.hh.
Member Typedef Documentation
const_iterator
typedef neighborVecT::const_iterator cbrc::RecountNeighborList::const_iterator
Definition at line 28 of file RecountNeighborList.hh.
iterator
typedef neighborVecT::iterator cbrc::RecountNeighborList::iterator
Definition at line 29 of file RecountNeighborList.hh.
neighborVecT
typedef std::vector<RecountTagIdProbPair> cbrc::RecountNeighborList::neighborVecT
Definition at line 26 of file RecountNeighborList.hh.
Constructor & Destructor Documentation
RecountNeighborList() [1/2]
cbrc::RecountNeighborList::RecountNeighborList () inline
Definition at line 32 of file RecountNeighborList.hh.
RecountNeighborList() [2/2]
cbrc::RecountNeighborList::RecountNeighborList (const tagIdT & id, const tagIdVecT & neighborIds, const probVecT & neighborProbs) inline
Definition at line 34 of file RecountNeighborList.hh.
References set().
Member Function Documentation
begin()
const_iterator cbrc::RecountNeighborList::begin () const inline
Definition at line 60 of file RecountNeighborList.hh.
end()
const_iterator cbrc::RecountNeighborList::end () const inline
Definition at line 61 of file RecountNeighborList.hh.
id()
const tagIdT & cbrc::RecountNeighborList::id () const inline
Definition at line 57 of file RecountNeighborList.hh.
Referenced by cbrc::dumpNeighborList(), cbrc::dumpNeighborList(), cbrc::RecountComputerForGraphOnDisk::meanCountsFromTrue(), cbrc::RecountComputerForGraphOnDisk::meanCountsFromTrue(), set(), cbrc::RecountComputerForGraphOnDisk::varianceCountsFromTrue(), and cbrc::RecountComputerForGraphOnDisk::varianceCountsFromTrue().
normalizeProbabilities()
void cbrc::RecountNeighborList::normalizeProbabilities ()
Definition at line 75 of file RecountNeighborList.cc.
read()
bool cbrc::RecountNeighborList::read (std::istream & iStream)
Definition at line 33 of file RecountNeighborList.cc.
References GDB_ASSERTF, and cbrc::FLEArray< T >::read().
Referenced by cbrc::RecountNeighborProbGraphOnDisk::readFirstNode(), and cbrc::RecountNeighborProbGraphOnDisk::readNextNode().
set() [1/2]
void cbrc::RecountNeighborList::set (const tagIdT & id, const tagIdVecT & neighborIds, const probVecT & neighborProbs) inline
Definition at line 44 of file RecountNeighborList.hh.
References id(), and set().
Referenced by RecountNeighborList(), set(), and cbrc::RecountNeighborProbGraphWriter::write().
set() [2/2]
void cbrc::RecountNeighborList::set (const tagIdVecT & neighborIds, const probVecT & neighborProbs)
Definition at line 16 of file RecountNeighborList.cc.
References GDB_ASSERTF, and cbrc::FLEArray< T >::size().
write()
void cbrc::RecountNeighborList::write (std::ostream & oStream) const
Definition at line 61 of file RecountNeighborList.cc.
References cbrc::FLEArray< T >::size(), and cbrc::FLEArray< T >::write().
Referenced by cbrc::RecountNeighborProbGraphWriter::write().
The documentation for this class was generated from the following files:
ematch_src/RecountNeighborList.hh
ematch_src/RecountNeighborList.cc