NGSFeatures: cbrc::BoundedLenFifoVector< T > Class Template Reference
cbrc::BoundedLenFifoVector< T > Class Template Reference
#include <BoundedLenFifoVector.hh>
Public Member Functions
BoundedLenFifoVector (const size_t &capacity)
const size_t & capacity () const
const size_t & size () const
const T & oldestElem (const size_t &oldnessRank) const
void push (const T &elem)
void popOldest ()
Detailed Description
template<typename T>
class cbrc::BoundedLenFifoVector< T >
Definition at line 18 of file BoundedLenFifoVector.hh.
Constructor & Destructor Documentation
BoundedLenFifoVector()
template<typename T > cbrc::BoundedLenFifoVector< T >::BoundedLenFifoVector (const size_t & capacity) inline
Definition at line 21 of file BoundedLenFifoVector.hh.
References cbrc::BoundedLenFifoVector< T >::capacity().
Member Function Documentation
capacity()
template<typename T > const size_t & cbrc::BoundedLenFifoVector< T >::capacity () const inline
Definition at line 30 of file BoundedLenFifoVector.hh.
Referenced by cbrc::BoundedLenFifoVector< T >::BoundedLenFifoVector(), and cbrc::BoundedLenFifoVector< T >::oldestElem().
oldestElem()
template<typename T > const T & cbrc::BoundedLenFifoVector< T >::oldestElem (const size_t & oldnessRank) const inline
Definition at line 38 of file BoundedLenFifoVector.hh.
References cbrc::BoundedLenFifoVector< T >::capacity().
popOldest()
template<typename T > void cbrc::BoundedLenFifoVector< T >::popOldest () inline
Definition at line 77 of file BoundedLenFifoVector.hh.
References cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
push()
template<typename T > void cbrc::BoundedLenFifoVector< T >::push (const T & elem) inline
Definition at line 61 of file BoundedLenFifoVector.hh.
References cbrc::FLEArray< T >::size().
size()
template<typename T > const size_t & cbrc::BoundedLenFifoVector< T >::size () const inline
Definition at line 32 of file BoundedLenFifoVector.hh.
The documentation for this class was generated from the following file:
ematch_src/utils/BoundedLenFifo/BoundedLenFifoVector.hh