NGSFeatures: cbrc::FastaReader Class Reference
cbrc::FastaReader Class Reference
#include <FastaReader.hh>
Public Member Functions
FastaReader ()
bool readRecord (std::istream &is)
std::vector< FastaRecord > slurpSeqs (std::istream &is)
void resetToReadFreshStream ()
const std::string & curHead () const
FastaRecord curRecord () const
const std::string & seq () const
const std::string & delimiterPattern () const
void setDelimiterPattern (const std::string &delimiterPattern)
const size_t & lineLengthForPrintingSequence () const
const std::string & commentMarker () const
void upcaseSequence ()
Static Public Member Functions
static bool delimiterPatternSupported (const std::string &delimiterPattern)
Detailed Description
Definition at line 31 of file FastaReader.hh.
Constructor & Destructor Documentation
FastaReader()
cbrc::FastaReader::FastaReader () inline
Definition at line 33 of file FastaReader.hh.
Member Function Documentation
commentMarker()
const std::string & cbrc::FastaReader::commentMarker () const inline
Definition at line 80 of file FastaReader.hh.
curHead()
const std::string & cbrc::FastaReader::curHead () const inline
Definition at line 56 of file FastaReader.hh.
curRecord()
FastaRecord cbrc::FastaReader::curRecord () const inline
Definition at line 60 of file FastaReader.hh.
Referenced by seq().
delimiterPattern()
const std::string & cbrc::FastaReader::delimiterPattern () const inline
Definition at line 69 of file FastaReader.hh.
Referenced by delimiterPatternSupported(), and setDelimiterPattern().
delimiterPatternSupported()
bool cbrc::FastaReader::delimiterPatternSupported (const std::string & delimiterPattern) static
Definition at line 105 of file FastaReader.cc.
References delimiterPattern().
Referenced by setDelimiterPattern().
lineLengthForPrintingSequence()
const size_t & cbrc::FastaReader::lineLengthForPrintingSequence () const inline
Definition at line 77 of file FastaReader.hh.
readRecord()
bool cbrc::FastaReader::readRecord (std::istream & is)
Definition at line 17 of file FastaReader.cc.
References seq(), and cbrc::FastaRecord::seqRef().
resetToReadFreshStream()
void cbrc::FastaReader::resetToReadFreshStream () inline
Definition at line 48 of file FastaReader.hh.
seq()
const std::string & cbrc::FastaReader::seq () const inline
Definition at line 64 of file FastaReader.hh.
References curRecord(), and cbrc::FastaRecord::seq().
Referenced by readRecord().
setDelimiterPattern()
void cbrc::FastaReader::setDelimiterPattern (const std::string & delimiterPattern) inline
Definition at line 72 of file FastaReader.hh.
References delimiterPattern(), and delimiterPatternSupported().
slurpSeqs()
std::vector< FastaRecord > cbrc::FastaReader::slurpSeqs (std::istream & is)
upcaseSequence()
void cbrc::FastaReader::upcaseSequence ()
Definition at line 124 of file FastaReader.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and cbrc::FastaRecord::seqRef().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/readers/fasta/FastaReader.hh
ematch_src/utils/sequence/readers/fasta/FastaReader.cc