NGSFeatures: cbrc::LabeledSequencePairPredicate_logicalOr Class Reference
cbrc::LabeledSequencePairPredicate_logicalOr Class Reference
#include <LabeledSequencePairPredicate_logicalOr.hh>
Public Types
typedef std::vector< LabeledSequencePairPredicate * > predicatePtrVecT
Public Member Functions
LabeledSequencePairPredicate_logicalOr (const predicatePtrVecT &predicates)
bool operator() (const LabeledSequence &seq0, const LabeledSequence &seq1) const
void print () const
const predicatePtrVecT & predicates () const
Public Member Functions inherited from cbrc::LabeledSequencePairPredicate
virtual ~LabeledSequencePairPredicate ()
Detailed Description
Definition at line 20 of file LabeledSequencePairPredicate_logicalOr.hh.
Member Typedef Documentation
predicatePtrVecT
typedef std::vector<LabeledSequencePairPredicate*> cbrc::LabeledSequencePairPredicate_logicalOr::predicatePtrVecT
Definition at line 22 of file LabeledSequencePairPredicate_logicalOr.hh.
Constructor & Destructor Documentation
LabeledSequencePairPredicate_logicalOr()
cbrc::LabeledSequencePairPredicate_logicalOr::LabeledSequencePairPredicate_logicalOr (const predicatePtrVecT & predicates) inline
Definition at line 25 of file LabeledSequencePairPredicate_logicalOr.hh.
Member Function Documentation
operator()()
bool cbrc::LabeledSequencePairPredicate_logicalOr::operator() (const LabeledSequence & seq0, const LabeledSequence & seq1) const virtual
Implements cbrc::LabeledSequencePairPredicate.
Definition at line 13 of file LabeledSequencePairPredicate_logicalOr.cc.
References cbrc::FLEArray< T >::end(), and predicates().
predicates()
const predicatePtrVecT & cbrc::LabeledSequencePairPredicate_logicalOr::predicates () const inline
Definition at line 35 of file LabeledSequencePairPredicate_logicalOr.hh.
Referenced by operator()(), and print().
print()
void cbrc::LabeledSequencePairPredicate_logicalOr::print () const virtual
Implements cbrc::LabeledSequencePairPredicate.
Definition at line 30 of file LabeledSequencePairPredicate_logicalOr.cc.
References predicates(), print(), and cbrc::FLEArray< T >::size().
Referenced by print().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/LabeledSequencePairPredicate_logicalOr.hh
ematch_src/utils/sequence/LabeledSequencePairPredicate_logicalOr.cc