NGSFeatures: cbrc::String2KeyHashtable< ValT > Class Template Reference
cbrc::String2KeyHashtable< ValT > Class Template Reference
#include <String2KeyHashtable.hh>
Public Member Functions
String2KeyHashtable (size_t size=11, size_t maxTSize=1796359771)
String2KeyHashtable (const String2KeyHashtable< ValT > &ht)
String2KeyHashtable< ValT > operator= (const String2KeyHashtable< ValT > &ht)
void copy (const String2KeyHashtable< ValT > &ht)
~String2KeyHashtable ()
void setNotFoundValue (ValT val)
void clear ()
size_t size () const
String2KeyHashIterator< ValT > begin () const
String2KeyHashIterator< ValT > end () const
std::vector< std::pair< std::string, ValT > > contentsAsVector () const
bool has (const std::string s0, const std::string s1) const
ValT operator() (const std::string s0, const std::string s1) const
ValT & ref (const std::string s0, const std::string s1)
String2KeyAndValue< ValT > * find (const String2KeyAndValue< ValT > &elem)
ValT & add2 (const std::string &s0, const std::string &s1, bool resizeAllowed=true)
String2KeyAndValue< ValT > * add (const String2KeyAndValue< ValT > &elem, bool resizeAllowed=true)
Detailed Description
template<typename ValT>
class cbrc::String2KeyHashtable< ValT >
Definition at line 188 of file String2KeyHashtable.hh.
Constructor & Destructor Documentation
String2KeyHashtable() [1/2]
template<typename ValT > cbrc::String2KeyHashtable< ValT >::String2KeyHashtable (size_t size = 11, size_t maxTSize = 1796359771) inline
Definition at line 182 of file String2KeyHashtable.hh.
String2KeyHashtable() [2/2]
template<typename ValT > cbrc::String2KeyHashtable< ValT >::String2KeyHashtable (const String2KeyHashtable< ValT > & ht) inline
Definition at line 182 of file String2KeyHashtable.hh.
~String2KeyHashtable()
template<typename ValT > cbrc::String2KeyHashtable< ValT >::~String2KeyHashtable () inline
Definition at line 226 of file String2KeyHashtable.hh.
References cbrc::String2KeyHashtable< ValT >::clear().
Member Function Documentation
add()
template<typename ValT > String2KeyAndValue< ValT > * cbrc::String2KeyHashtable< ValT >::add (const String2KeyAndValue< ValT > & elem, bool resizeAllowed = true) inline
Definition at line 337 of file String2KeyHashtable.hh.
References cbrc::String2KeyHashtable< ValT >::add().
Referenced by cbrc::String2KeyHashtable< ValT >::add().
add2()
template<typename ValT > ValT & cbrc::String2KeyHashtable< ValT >::add2 (const std::string & s0, const std::string & s1, bool resizeAllowed = true) inline
Definition at line 294 of file String2KeyHashtable.hh.
References cbrc::String2KeyHashtable< ValT >::add2(), and cbrc::string2HashVal().
Referenced by cbrc::String2KeyHashtable< ValT >::add2(), and cbrc::String2KeyHashtable< ValT >::ref().
begin()
template<typename ValT > String2KeyHashIterator< ValT > cbrc::String2KeyHashtable< ValT >::begin () const inline
Definition at line 242 of file String2KeyHashtable.hh.
References cbrc::String2KeyHashtable< ValT >::size().
Referenced by cbrc::String2KeyHashtable< ValT >::contentsAsVector().
clear()
template<typename ValT > void cbrc::String2KeyHashtable< ValT >::clear () inline
Definition at line 228 of file String2KeyHashtable.hh.
Referenced by cbrc::String2KeyHashtable< ValT >::~String2KeyHashtable().
contentsAsVector()
template<typename ValT > std::vector< std::pair< std::string, ValT > > cbrc::String2KeyHashtable< ValT >::contentsAsVector () const inline
Definition at line 249 of file String2KeyHashtable.hh.
References cbrc::String2KeyHashtable< ValT >::begin(), cbrc::String2KeyHashtable< ValT >::end(), and cbrc::String2KeyHashtable< ValT >::size().
copy()
template<typename ValT > void cbrc::String2KeyHashtable< ValT >::copy (const String2KeyHashtable< ValT > & ht) inline
Definition at line 205 of file String2KeyHashtable.hh.
Referenced by cbrc::String2KeyHashtable< ValT >::operator=().
end()
template<typename ValT > String2KeyHashIterator< ValT > cbrc::String2KeyHashtable< ValT >::end () const inline
Definition at line 248 of file String2KeyHashtable.hh.
Referenced by cbrc::String2KeyHashtable< ValT >::contentsAsVector().
find()
template<typename ValT > String2KeyAndValue< ValT > * cbrc::String2KeyHashtable< ValT >::find (const String2KeyAndValue< ValT > & elem) inline
Definition at line 283 of file String2KeyHashtable.hh.
has()
template<typename ValT > bool cbrc::String2KeyHashtable< ValT >::has (const std::string s0, const std::string s1) const inline
Definition at line 257 of file String2KeyHashtable.hh.
References cbrc::string2HashVal().
operator()()
template<typename ValT > ValT cbrc::String2KeyHashtable< ValT >::operator() (const std::string s0, const std::string s1) const inline
Definition at line 265 of file String2KeyHashtable.hh.
References cbrc::string2HashVal().
operator=()
template<typename ValT > String2KeyHashtable< ValT > cbrc::String2KeyHashtable< ValT >::operator= (const String2KeyHashtable< ValT > & ht) inline
Definition at line 201 of file String2KeyHashtable.hh.
References cbrc::String2KeyHashtable< ValT >::copy().
ref()
template<typename ValT > ValT & cbrc::String2KeyHashtable< ValT >::ref (const std::string s0, const std::string s1) inline
Definition at line 273 of file String2KeyHashtable.hh.
References cbrc::String2KeyHashtable< ValT >::add2(), and cbrc::string2HashVal().
setNotFoundValue()
template<typename ValT > void cbrc::String2KeyHashtable< ValT >::setNotFoundValue (ValT val) inline
Definition at line 227 of file String2KeyHashtable.hh.
size()
template<typename ValT > size_t cbrc::String2KeyHashtable< ValT >::size () const inline
Definition at line 241 of file String2KeyHashtable.hh.
Referenced by cbrc::String2KeyHashtable< ValT >::begin(), and cbrc::String2KeyHashtable< ValT >::contentsAsVector().
The documentation for this class was generated from the following file:
ematch_src/utils/ChainHashtable/String2KeyHashtable.hh