NGSFeatures: cbrc::ResiduesIndexMap Class Reference
cbrc::ResiduesIndexMap Class Reference
#include <ResiduesIndexMap.hh>
Public Types
typedef unsigned int indexT
Public Member Functions
ResiduesIndexMap (const ResidueIndexMap &rim)
indexT operator() (const ResidueIndexMap::arrayT &residueIndices) const
indexT operator() (const ResidueIndexMap::indexT *const &r, const size_t &stringLen) const
indexT operator() (const ResidueIndexWindow &riw) const
indexT operator() (const std::string &residues) const
ResidueIndexMap::vectorT toResidueIndicesVector (const ResiduesIndexMap::indexT &idx, const size_t &stringLen) const
std::string toResidues (const indexT &residuesIndex, const size_t &stringLen) const
const size_t & maxStringLen () const
size_t sigma () const
const ResidueIndexMap & residueIndexMap () const
Detailed Description
Definition at line 37 of file ResiduesIndexMap.hh.
Member Typedef Documentation
indexT
typedef unsigned int cbrc::ResiduesIndexMap::indexT
Definition at line 40 of file ResiduesIndexMap.hh.
Constructor & Destructor Documentation
ResiduesIndexMap()
cbrc::ResiduesIndexMap::ResiduesIndexMap (const ResidueIndexMap & rim)
Definition at line 16 of file ResiduesIndexMap.cc.
References sigma().
Member Function Documentation
maxStringLen()
const size_t & cbrc::ResiduesIndexMap::maxStringLen () const inline
Definition at line 70 of file ResiduesIndexMap.hh.
Referenced by operator()(), operator()(), toResidueIndicesVector(), and toResidues().
operator()() [1/4]
indexT cbrc::ResiduesIndexMap::operator() (const ResidueIndexMap::arrayT & residueIndices) const inline
Definition at line 46 of file ResiduesIndexMap.hh.
References operator()(), and cbrc::FLEArray< T >::size().
Referenced by operator()(), and operator()().
operator()() [2/4]
ResiduesIndexMap::indexT cbrc::ResiduesIndexMap::operator() (const ResidueIndexMap::indexT *const & r, const size_t & stringLen) const
Definition at line 24 of file ResiduesIndexMap.cc.
References maxStringLen(), and sigma().
operator()() [3/4]
indexT cbrc::ResiduesIndexMap::operator() (const ResidueIndexWindow & riw) const inline
Definition at line 52 of file ResiduesIndexMap.hh.
References cbrc::FLEArray< T >::size(), and cbrc::ResidueIndexWindow::windowStartPtr().
operator()() [4/4]
ResiduesIndexMap::indexT cbrc::ResiduesIndexMap::operator() (const std::string & residues) const
Definition at line 45 of file ResiduesIndexMap.cc.
References maxStringLen(), operator()(), and cbrc::FLEArray< T >::size().
residueIndexMap()
const ResidueIndexMap & cbrc::ResiduesIndexMap::residueIndexMap () const inline
Definition at line 72 of file ResiduesIndexMap.hh.
sigma()
size_t cbrc::ResiduesIndexMap::sigma () const inline
Definition at line 71 of file ResiduesIndexMap.hh.
Referenced by operator()(), ResiduesIndexMap(), and toResidueIndicesVector().
toResidueIndicesVector()
ResidueIndexMap::vectorT cbrc::ResiduesIndexMap::toResidueIndicesVector (const ResiduesIndexMap::indexT & idx, const size_t & stringLen) const
Definition at line 54 of file ResiduesIndexMap.cc.
References maxStringLen(), and sigma().
Referenced by toResidues().
toResidues()
std::string cbrc::ResiduesIndexMap::toResidues (const indexT & residuesIndex, const size_t & stringLen) const
Definition at line 75 of file ResiduesIndexMap.cc.
References maxStringLen(), and toResidueIndicesVector().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/ResidueIndexMap/ResiduesIndexMap.hh
ematch_src/utils/sequence/ResidueIndexMap/ResiduesIndexMap.cc