NGSFeatures: cbrc::GlobalAffineDist Class Reference
cbrc::GlobalAffineDist Class Reference
#include <GlobalAffineDist.hh>
Public Member Functions
GlobalAffineDist (const AminoDistance &ad, const FLArray< residueIndex > &seq0)
alignDistT dist (const FLArray< residueIndex > &s1)
Alignment alignment (const FLArray< residueIndex > &s1)
alignDistT distFreeStartGap (const FLArray< residueIndex > &s1)
alignDistT distBounded (const FLArray< residueIndex > &s1, const FLArray< alignDistT > &s1BestPossibleSuffixDists, const alignDistT maxDistance)
alignDistT prefixDistBounded (const FLArray< residueIndex > &s1, alignDistT maxDistance)
alignDistT oneSequenceBasedUpperBound (const FLArray< residueIndex > &s1)
alignDistT lengthBasedUpperBound (size_t l1)
alignDistT feasibleBound (const FLArray< residueIndex > &s1)
const FLArrayFast< residueIndex > getResidues () const
Static Public Member Functions
static alignDistT bestPossibleDist (const AminoDistance &ad, const FLArray< residueIndex > &s1)
static FLArray< alignDistT > bestPossibleSuffixDist (const AminoDistance &ad, const FLArray< residueIndex > &s0)
Friends
void testGlobalAffineDist ()
Detailed Description
Definition at line 25 of file GlobalAffineDist.hh.
Constructor & Destructor Documentation
GlobalAffineDist()
cbrc::GlobalAffineDist::GlobalAffineDist (const AminoDistance & ad, const FLArray< residueIndex > & seq0) inline
Definition at line 27 of file GlobalAffineDist.hh.
References bestPossibleDist(), cbrc::FLMatrix< T >::setSize(), and cbrc::FLEArray< T >::size().
Member Function Documentation
alignment()
Alignment cbrc::GlobalAffineDist::alignment (const FLArray< residueIndex > & s1)
Definition at line 65 of file GlobalAffineDist.cc.
References dist(), cbrc::Alignment::indelChar(), and cbrc::FLEArray< T >::size().
bestPossibleDist()
static alignDistT cbrc::GlobalAffineDist::bestPossibleDist (const AminoDistance & ad, const FLArray< residueIndex > & s1) inline static
Definition at line 53 of file GlobalAffineDist.hh.
References dist(), and cbrc::FLEArray< T >::size().
Referenced by distBounded(), GlobalAffineDist(), and oneSequenceBasedUpperBound().
bestPossibleSuffixDist()
static FLArray< alignDistT > cbrc::GlobalAffineDist::bestPossibleSuffixDist (const AminoDistance & ad, const FLArray< residueIndex > & s0) inline static
Definition at line 58 of file GlobalAffineDist.hh.
References cbrc::FLEArray< T >::size().
dist()
alignDistT cbrc::GlobalAffineDist::dist (const FLArray< residueIndex > & s1)
Definition at line 31 of file GlobalAffineDist.cc.
References dist(), and cbrc::FLEArray< T >::size().
Referenced by alignment(), bestPossibleDist(), dist(), distBounded(), distFreeStartGap(), and prefixDistBounded().
distBounded()
alignDistT cbrc::GlobalAffineDist::distBounded (const FLArray< residueIndex > & s1, const FLArray< alignDistT > & s1BestPossibleSuffixDists, const alignDistT maxDistance)
Definition at line 299 of file GlobalAffineDist.cc.
References bestPossibleDist(), dist(), and cbrc::FLEArray< T >::size().
distFreeStartGap()
alignDistT cbrc::GlobalAffineDist::distFreeStartGap (const FLArray< residueIndex > & s1)
Definition at line 169 of file GlobalAffineDist.cc.
References dist(), and cbrc::FLEArray< T >::size().
feasibleBound()
alignDistT cbrc::GlobalAffineDist::feasibleBound (const FLArray< residueIndex > & s1)
Definition at line 260 of file GlobalAffineDist.cc.
References cbrc::FLEArray< T >::size().
getResidues()
const FLArrayFast< residueIndex > cbrc::GlobalAffineDist::getResidues () const inline
Definition at line 52 of file GlobalAffineDist.hh.
lengthBasedUpperBound()
alignDistT cbrc::GlobalAffineDist::lengthBasedUpperBound (size_t l1) inline
Definition at line 45 of file GlobalAffineDist.hh.
References cbrc::FLEArray< T >::size().
oneSequenceBasedUpperBound()
alignDistT cbrc::GlobalAffineDist::oneSequenceBasedUpperBound (const FLArray< residueIndex > & s1) inline
Definition at line 38 of file GlobalAffineDist.hh.
References bestPossibleDist(), and cbrc::FLEArray< T >::size().
prefixDistBounded()
alignDistT cbrc::GlobalAffineDist::prefixDistBounded (const FLArray< residueIndex > & s1, alignDistT maxDistance)
Definition at line 215 of file GlobalAffineDist.cc.
References dist(), and cbrc::FLEArray< T >::size().
Friends And Related Symbol Documentation
testGlobalAffineDist
void testGlobalAffineDist () friend
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/align/GlobalAffineDist.hh
ematch_src/utils/sequence/align/GlobalAffineDist.cc