NGSFeatures: cbrc::FLMatrix< T > Class Template Reference
cbrc::FLMatrix< T > Class Template Reference
#include <FLMatrix.hh>
Public Types
typedef T * iterator
typedef const T * const_iterator
Public Member Functions
FLMatrix ()
FLMatrix (const size_t sz0, const size_t sz1)
FLMatrix (const size_t sz0, const size_t sz1, const T fillVal)
FLMatrix (const size_t sz0, const size_t sz1, const T **const b)
FLMatrix (const std::vector< std::vector< T > > v)
FLMatrix (const FLMatrix< T > &flm)
virtual ~FLMatrix ()
void setSize (size_t sz0, size_t sz1)
void resizeDestructive (size_t sz0, size_t sz1)
FLMatrix operator= (const FLMatrix &flm)
FLMatrix operator= (std::vector< std::vector< T > > v)
T getVal (size_t index0, size_t index1, T defValue)
void zero ()
void fill (T fillVal)
void fillWithByte (int fillByte)
bool validIndex (size_t index) const
bool validIndex (size_t index0, size_t index1) const
bool operator== (const FLMatrix &flm) const
virtual T & operator[] (const size_t index) const
virtual T & operator() (const size_t index0, const size_t index1) const
FLMatrix< T > submatrix (const size_t startRow, const size_t endRow, const size_t startCol, const size_t endCol) const
void printColumnMajor (std::ostream &os) const
void shiftLeft (FLArray< T > newCol)
void shiftRight (FLArray< T > newCol)
virtual const T * getColPtr (const size_t index0) const
size_t size () const
size_t size0 () const
size_t size1 () const
iterator begin () const
iterator end () const
T * getPtr () const
void friend testFLMatrix ()
Protected Member Functions
bool validAsMatrix (std::vector< std::vector< T > > v) const
Protected Attributes
size_t s
size_t s0
size_t s1
T * m
Detailed Description
template<typename T>
class cbrc::FLMatrix< T >
Definition at line 47 of file FLMatrix.hh.
Member Typedef Documentation
const_iterator
template<typename T > typedef const T* cbrc::FLMatrix< T >::const_iterator
Definition at line 50 of file FLMatrix.hh.
iterator
template<typename T > typedef T* cbrc::FLMatrix< T >::iterator
Definition at line 49 of file FLMatrix.hh.
Constructor & Destructor Documentation
FLMatrix() [1/6]
template<typename T > cbrc::FLMatrix< T >::FLMatrix () inline
Definition at line 51 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, and cbrc::FLMatrix< T >::s.
FLMatrix() [2/6]
template<typename T > cbrc::FLMatrix< T >::FLMatrix (const size_t sz0, const size_t sz1) inline
Definition at line 52 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, and cbrc::FLMatrix< T >::s.
FLMatrix() [3/6]
template<typename T > cbrc::FLMatrix< T >::FLMatrix (const size_t sz0, const size_t sz1, const T fillVal) inline
Definition at line 56 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::fill(), cbrc::FLMatrix< T >::m, and cbrc::FLMatrix< T >::s.
FLMatrix() [4/6]
template<typename T > cbrc::FLMatrix< T >::FLMatrix (const size_t sz0, const size_t sz1, const T **const b) inline
Definition at line 61 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, and cbrc::FLMatrix< T >::s.
FLMatrix() [5/6]
template<typename T > cbrc::FLMatrix< T >::FLMatrix (const std::vector< std::vector< T > > v) inline
Definition at line 66 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, cbrc::FLMatrix< T >::s, cbrc::FLMatrix< T >::s0, cbrc::FLMatrix< T >::s1, cbrc::FLEArray< T >::size(), and cbrc::FLMatrix< T >::validAsMatrix().
FLMatrix() [6/6]
template<typename T > cbrc::FLMatrix< T >::FLMatrix (const FLMatrix< T > & flm) inline
Definition at line 80 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, cbrc::FLEArray< T >::s, cbrc::FLMatrix< T >::s, cbrc::FLMatrix< T >::s0, and cbrc::FLMatrix< T >::s1.
~FLMatrix()
template<typename T > virtual cbrc::FLMatrix< T >::~FLMatrix () inline virtual
Definition at line 85 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m.
Member Function Documentation
begin()
template<typename T > iterator cbrc::FLMatrix< T >::begin () const inline
Definition at line 216 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m.
end()
template<typename T > iterator cbrc::FLMatrix< T >::end () const inline
Definition at line 217 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, and cbrc::FLMatrix< T >::s.
fill()
template<typename T > void cbrc::FLMatrix< T >::fill (T fillVal) inline
Definition at line 141 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, and cbrc::FLMatrix< T >::s.
Referenced by cbrc::FLMatrix< T >::FLMatrix().
fillWithByte()
template<typename T > void cbrc::FLMatrix< T >::fillWithByte (int fillByte) inline
Definition at line 144 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, and cbrc::FLMatrix< T >::s.
getColPtr()
template<typename T > virtual const T * cbrc::FLMatrix< T >::getColPtr (const size_t index0) const inline virtual
Reimplemented in cbrc::FLMatrixFast< T >, cbrc::FLMatrixFast< alignDistT >, and cbrc::FLNumMatrixFast< T >.
Definition at line 209 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, cbrc::FLMatrix< T >::s0, and cbrc::FLMatrix< T >::s1.
getPtr()
template<typename T > T * cbrc::FLMatrix< T >::getPtr () const inline
Definition at line 220 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m.
getVal()
template<typename T > T cbrc::FLMatrix< T >::getVal (size_t index0, size_t index1, T defValue) inline
Definition at line 135 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, cbrc::FLMatrix< T >::s1, and cbrc::FLMatrix< T >::validIndex().
operator()()
template<typename T > virtual T & cbrc::FLMatrix< T >::operator() (const size_t index0, const size_t index1) const inline virtual
Reimplemented in cbrc::FLMatrixFast< T >, cbrc::FLMatrixFast< alignDistT >, and cbrc::FLNumMatrixFast< T >.
Definition at line 166 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, cbrc::FLMatrix< T >::s1, and cbrc::FLMatrix< T >::validIndex().
Referenced by cbrc::FLMatrix< T >::printColumnMajor(), and cbrc::FLMatrix< T >::submatrix().
operator=() [1/2]
template<typename T > FLMatrix cbrc::FLMatrix< T >::operator= (const FLMatrix< T > & flm) inline
Definition at line 100 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, cbrc::FLEArray< T >::s, cbrc::FLMatrix< T >::s, cbrc::FLMatrix< T >::s0, cbrc::FLMatrix< T >::s1, cbrc::FLEArray< T >::size(), and cbrc::FLMatrix< T >::size().
operator=() [2/2]
template<typename T > FLMatrix cbrc::FLMatrix< T >::operator= (std::vector< std::vector< T > > v) inline
Definition at line 112 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, cbrc::FLMatrix< T >::s, cbrc::FLMatrix< T >::s0, cbrc::FLMatrix< T >::s1, cbrc::FLEArray< T >::size(), cbrc::FLMatrix< T >::size(), and cbrc::FLMatrix< T >::validAsMatrix().
operator==()
template<typename T > bool cbrc::FLMatrix< T >::operator== (const FLMatrix< T > & flm) const inline
Definition at line 158 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, cbrc::FLEArray< T >::s, and cbrc::FLMatrix< T >::s.
operator[]()
template<typename T > virtual T & cbrc::FLMatrix< T >::operator[] (const size_t index) const inline virtual
Reimplemented in cbrc::FLMatrixFast< T >, cbrc::FLMatrixFast< alignDistT >, and cbrc::FLNumMatrixFast< T >.
Definition at line 162 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, and cbrc::FLMatrix< T >::validIndex().
printColumnMajor()
template<typename T > void cbrc::FLMatrix< T >::printColumnMajor (std::ostream & os) const inline
Definition at line 189 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::operator()(), cbrc::FLMatrix< T >::size(), cbrc::FLMatrix< T >::size0(), and cbrc::FLMatrix< T >::size1().
resizeDestructive()
template<typename T > void cbrc::FLMatrix< T >::resizeDestructive (size_t sz0, size_t sz1) inline
Definition at line 92 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, cbrc::FLMatrix< T >::s, cbrc::FLMatrix< T >::s0, and cbrc::FLMatrix< T >::s1.
setSize()
template<typename T > void cbrc::FLMatrix< T >::setSize (size_t sz0, size_t sz1) inline
Definition at line 86 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, cbrc::FLMatrix< T >::s, cbrc::FLMatrix< T >::s0, and cbrc::FLMatrix< T >::s1.
Referenced by cbrc::GlobalAffineDist::GlobalAffineDist().
shiftLeft()
template<typename T > void cbrc::FLMatrix< T >::shiftLeft (FLArray< T > newCol) inline
Definition at line 199 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, cbrc::FLMatrix< T >::s, cbrc::FLMatrix< T >::s1, and cbrc::FLEArray< T >::size().
shiftRight()
template<typename T > void cbrc::FLMatrix< T >::shiftRight (FLArray< T > newCol) inline
Definition at line 204 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, cbrc::FLMatrix< T >::s, cbrc::FLMatrix< T >::s1, and cbrc::FLEArray< T >::size().
size()
template<typename T > size_t cbrc::FLMatrix< T >::size () const inline
Definition at line 213 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::s.
Referenced by cbrc::FLMatrix< T >::operator=(), cbrc::FLMatrix< T >::operator=(), cbrc::FLMatrix< T >::printColumnMajor(), and cbrc::FLMatrix< T >::validAsMatrix().
size0()
template<typename T > size_t cbrc::FLMatrix< T >::size0 () const inline
Definition at line 214 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::s0.
Referenced by cbrc::FLNumMatrix< T >::normalize(), and cbrc::FLMatrix< T >::printColumnMajor().
size1()
template<typename T > size_t cbrc::FLMatrix< T >::size1 () const inline
Definition at line 215 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::s1.
Referenced by cbrc::FLNumMatrix< T >::normalize(), and cbrc::FLMatrix< T >::printColumnMajor().
submatrix()
template<typename T > FLMatrix< T > cbrc::FLMatrix< T >::submatrix (const size_t startRow, const size_t endRow, const size_t startCol, const size_t endCol) const inline
Definition at line 175 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::operator()(), and cbrc::FLMatrix< T >::validIndex().
testFLMatrix()
template<typename T > void friend cbrc::FLMatrix< T >::testFLMatrix ()
validAsMatrix()
template<typename T > bool cbrc::FLMatrix< T >::validAsMatrix (std::vector< std::vector< T > > v) const inline protected
Definition at line 223 of file FLMatrix.hh.
References cbrc::FLEArray< T >::size(), and cbrc::FLMatrix< T >::size().
Referenced by cbrc::FLMatrix< T >::FLMatrix(), and cbrc::FLMatrix< T >::operator=().
validIndex() [1/2]
template<typename T > bool cbrc::FLMatrix< T >::validIndex (size_t index) const inline
Definition at line 147 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::s.
Referenced by cbrc::FLMatrix< T >::getVal(), cbrc::FLMatrix< T >::operator()(), cbrc::FLMatrix< T >::operator[](), and cbrc::FLMatrix< T >::submatrix().
validIndex() [2/2]
template<typename T > bool cbrc::FLMatrix< T >::validIndex (size_t index0, size_t index1) const inline
Definition at line 154 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::s0, and cbrc::FLMatrix< T >::s1.
zero()
template<typename T > void cbrc::FLMatrix< T >::zero () inline
Definition at line 138 of file FLMatrix.hh.
References cbrc::FLMatrix< T >::m, and cbrc::FLMatrix< T >::s.
Member Data Documentation
m
template<typename T > T* cbrc::FLMatrix< T >::m protected
Definition at line 233 of file FLMatrix.hh.
Referenced by cbrc::FLMatrix< T >::begin(), cbrc::FLMatrix< T >::end(), cbrc::FLMatrix< T >::fill(), cbrc::FLMatrix< T >::fillWithByte(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::getColPtr(), cbrc::FLMatrix< T >::getPtr(), cbrc::FLMatrix< T >::getVal(), cbrc::FLMatrix< T >::operator()(), cbrc::FLMatrix< T >::operator=(), cbrc::FLMatrix< T >::operator=(), cbrc::FLMatrix< T >::operator==(), cbrc::FLMatrix< T >::operator[](), cbrc::FLMatrix< T >::resizeDestructive(), cbrc::FLMatrix< T >::setSize(), cbrc::FLMatrix< T >::shiftLeft(), cbrc::FLMatrix< T >::shiftRight(), cbrc::FLMatrix< T >::zero(), and cbrc::FLMatrix< T >::~FLMatrix().
s
template<typename T > size_t cbrc::FLMatrix< T >::s protected
Definition at line 232 of file FLMatrix.hh.
Referenced by cbrc::FLMatrix< T >::end(), cbrc::FLMatrix< T >::fill(), cbrc::FLMatrix< T >::fillWithByte(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::operator=(), cbrc::FLMatrix< T >::operator=(), cbrc::FLMatrix< T >::operator==(), cbrc::FLMatrix< T >::resizeDestructive(), cbrc::FLMatrix< T >::setSize(), cbrc::FLMatrix< T >::shiftLeft(), cbrc::FLMatrix< T >::shiftRight(), cbrc::FLMatrix< T >::size(), cbrc::FLMatrix< T >::validIndex(), and cbrc::FLMatrix< T >::zero().
s0
template<typename T > size_t cbrc::FLMatrix< T >::s0 protected
Definition at line 232 of file FLMatrix.hh.
Referenced by cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::getColPtr(), cbrc::FLMatrix< T >::operator=(), cbrc::FLMatrix< T >::operator=(), cbrc::FLMatrix< T >::resizeDestructive(), cbrc::FLMatrix< T >::setSize(), cbrc::FLMatrix< T >::size0(), and cbrc::FLMatrix< T >::validIndex().
s1
template<typename T > size_t cbrc::FLMatrix< T >::s1 protected
Definition at line 232 of file FLMatrix.hh.
Referenced by cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLMatrix< T >::getColPtr(), cbrc::FLMatrix< T >::getVal(), cbrc::FLMatrix< T >::operator()(), cbrc::FLMatrix< T >::operator=(), cbrc::FLMatrix< T >::operator=(), cbrc::FLMatrix< T >::resizeDestructive(), cbrc::FLMatrix< T >::setSize(), cbrc::FLMatrix< T >::shiftLeft(), cbrc::FLMatrix< T >::shiftRight(), cbrc::FLMatrix< T >::size1(), and cbrc::FLMatrix< T >::validIndex().
The documentation for this class was generated from the following file:
ematch_src/utils/FLArray/FLMatrix.hh