NGSFeatures: cbrc::Blast8ResultReader Class Reference
cbrc::Blast8ResultReader Class Reference
#include <Blast8ResultReader.hh>
Public Member Functions
Blast8ResultReader (std::istream &is, const bool ignoreSelfHit=true)
size_t size () const
bool has (const std::string s) const
const std::vector< Blast8Result > & operator() (const size_t i) const
const std::vector< Blast8Result > & operator() (const std::string id) const
double maxEValue () const
void sortByEValue ()
bool sortedByEValue () const
void printNormalizedSimilarity (std::ostream &os) const
void printNegLgEValues (std::ostream &os) const
Static Public Member Functions
static bool isBlastCommentLine (const std::string &line)
Friends
void testBlast8ResultReader ()
std::ostream & operator<< (std::ostream &os, const Blast8ResultReader &brr)
Detailed Description
Definition at line 58 of file Blast8ResultReader.hh.
Constructor & Destructor Documentation
Blast8ResultReader()
cbrc::Blast8ResultReader::Blast8ResultReader (std::istream & is, const bool ignoreSelfHit = true)
Definition at line 24 of file Blast8ResultReader.cc.
References isBlastCommentLine(), cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLines(), and cbrc::perlish::split().
Member Function Documentation
has()
bool cbrc::Blast8ResultReader::has (const std::string s) const inline
Definition at line 62 of file Blast8ResultReader.hh.
References cbrc::StringKeyHashtable< ValT >::has().
Referenced by cbrc::dumpBlastNNUtility(), cbrc::filterSameClassHighBlast(), and cbrc::labeledBlastToOddsRatio().
isBlastCommentLine()
bool cbrc::Blast8ResultReader::isBlastCommentLine (const std::string & line) static
Definition at line 103 of file Blast8ResultReader.cc.
References cbrc::FLEArray< T >::find().
Referenced by Blast8ResultReader(), cbrc::filterBlast8ResultEValueThreshold(), and cbrc::Blast8Result::setFromStream().
maxEValue()
double cbrc::Blast8ResultReader::maxEValue () const
Definition at line 72 of file Blast8ResultReader.cc.
Referenced by printNormalizedSimilarity().
operator()() [1/2]
const std::vector< Blast8Result > & cbrc::Blast8ResultReader::operator() (const size_t i) const inline
Definition at line 63 of file Blast8ResultReader.hh.
operator()() [2/2]
const std::vector< Blast8Result > & cbrc::Blast8ResultReader::operator() (const std::string id) const inline
Definition at line 64 of file Blast8ResultReader.hh.
References cbrc::StringKeyHashtable< ValT >::has().
printNegLgEValues()
void cbrc::Blast8ResultReader::printNegLgEValues (std::ostream & os) const
Definition at line 92 of file Blast8ResultReader.cc.
Referenced by cbrc::printBlast8ResultNegLgEValues().
printNormalizedSimilarity()
void cbrc::Blast8ResultReader::printNormalizedSimilarity (std::ostream & os) const
Definition at line 82 of file Blast8ResultReader.cc.
References maxEValue().
Referenced by cbrc::printNormalizedBlastSimilarity().
size()
size_t cbrc::Blast8ResultReader::size () const inline
Definition at line 61 of file Blast8ResultReader.hh.
sortByEValue()
void cbrc::Blast8ResultReader::sortByEValue ()
Definition at line 56 of file Blast8ResultReader.cc.
sortedByEValue()
bool cbrc::Blast8ResultReader::sortedByEValue () const
Definition at line 62 of file Blast8ResultReader.cc.
References cbrc::Blast8Result::firstGreater().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const Blast8ResultReader & brr) friend
Definition at line 108 of file Blast8ResultReader.cc.
testBlast8ResultReader
void testBlast8ResultReader () friend
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/readers/Blast8ResultReader.hh
ematch_src/utils/sequence/readers/Blast8ResultReader.cc