NGSFeatures: cbrc::Blast8Result Class Reference
cbrc::Blast8Result Class Reference
#include <Blast8ResultReader.hh>
Public Member Functions
Blast8Result (const std::vector< std::string > fields)
Blast8Result (const Blast8Result &br)
Blast8Result ()
void setFields (const std::vector< std::string > &f)
bool setFromStream (std::istream &is)
std::string queryName () const
std::string hitName () const
size_t size () const
double eValue () const
bool operator< (const Blast8Result &br) const
Static Public Member Functions
static bool firstGreater (const Blast8Result &br1, const Blast8Result &br2)
Detailed Description
Definition at line 24 of file Blast8ResultReader.hh.
Constructor & Destructor Documentation
Blast8Result() [1/3]
cbrc::Blast8Result::Blast8Result (const std::vector< std::string > fields) inline
Definition at line 26 of file Blast8ResultReader.hh.
Blast8Result() [2/3]
cbrc::Blast8Result::Blast8Result (const Blast8Result & br) inline
Definition at line 27 of file Blast8ResultReader.hh.
Blast8Result() [3/3]
cbrc::Blast8Result::Blast8Result () inline
Definition at line 30 of file Blast8ResultReader.hh.
Member Function Documentation
eValue()
double cbrc::Blast8Result::eValue () const inline
Definition at line 42 of file Blast8ResultReader.hh.
References cbrc::perlish::toDouble().
Referenced by operator<().
firstGreater()
static bool cbrc::Blast8Result::firstGreater (const Blast8Result & br1, const Blast8Result & br2) inline static
Definition at line 44 of file Blast8ResultReader.hh.
Referenced by cbrc::Blast8ResultReader::sortedByEValue().
hitName()
std::string cbrc::Blast8Result::hitName () const inline
Definition at line 40 of file Blast8ResultReader.hh.
operator<()
bool cbrc::Blast8Result::operator< (const Blast8Result & br) const inline
Definition at line 43 of file Blast8ResultReader.hh.
References eValue().
queryName()
std::string cbrc::Blast8Result::queryName () const inline
Definition at line 39 of file Blast8ResultReader.hh.
setFields()
void cbrc::Blast8Result::setFields (const std::vector< std::string > & f) inline
Definition at line 33 of file Blast8ResultReader.hh.
References f().
setFromStream()
bool cbrc::Blast8Result::setFromStream (std::istream & is)
Definition at line 16 of file Blast8ResultReader.cc.
References cbrc::Blast8ResultReader::isBlastCommentLine(), cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLine(), and cbrc::perlish::split().
size()
size_t cbrc::Blast8Result::size () const inline
Definition at line 41 of file Blast8ResultReader.hh.
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/readers/Blast8ResultReader.hh
ematch_src/utils/sequence/readers/Blast8ResultReader.cc