NGSFeatures: cbrc::RecountNeighborProbGraphWriter Class Reference
cbrc::RecountNeighborProbGraphWriter Class Reference
#include <RecountNeighborProbGraphWriter.hh>
Public Types
typedef SortedTagSet::tagSeqT tagSeqT
Public Member Functions
RecountNeighborProbGraphWriter (std::istream &tagSeqsIstream)
size_t write (std::ofstream &ofStream, std::istream &tagNeighborlistIstream)
RecountNeighborProbGraphWriter (std::istream &tagSeqsIstream)
size_t write (std::ofstream &ofStream, std::istream &tagNeighborlistIstream)
Detailed Description
Definition at line 19 of file RecountNeighborProbGraphWriter.hh.
Member Typedef Documentation
tagSeqT
typedef SortedTagSet::tagSeqT cbrc::RecountNeighborProbGraphWriter::tagSeqT
Definition at line 23 of file RecountNeighborProbGraphWriter_SortedTagSet.hh.
Constructor & Destructor Documentation
RecountNeighborProbGraphWriter() [1/2]
cbrc::RecountNeighborProbGraphWriter::RecountNeighborProbGraphWriter (std::istream & tagSeqsIstream) inline
Definition at line 26 of file RecountNeighborProbGraphWriter.hh.
RecountNeighborProbGraphWriter() [2/2]
cbrc::RecountNeighborProbGraphWriter::RecountNeighborProbGraphWriter (std::istream & tagSeqsIstream) inline
Definition at line 27 of file RecountNeighborProbGraphWriter_SortedTagSet.hh.
Member Function Documentation
write() [1/2]
size_t cbrc::RecountNeighborProbGraphWriter::write (std::ofstream & ofStream, std::istream & tagNeighborlistIstream)
LOOP EXIT!
LOOP EXIT!
Definition at line 20 of file RecountNeighborProbGraphWriter.cc.
References GDB_ASSERTF, cbrc::FLEArray< T >::resize(), cbrc::RecountNeighborList::set(), cbrc::RecountNeighborProbGraphFormat::signature(), cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLine(), cbrc::perlish::split(), cbrc::FLEArray< T >::write(), cbrc::RecountNeighborList::write(), and cbrc::binaryIO::writeContentsOnly().
write() [2/2]
size_t cbrc::RecountNeighborProbGraphWriter::write (std::ofstream & ofStream, std::istream & tagNeighborlistIstream)
The documentation for this class was generated from the following files:
ematch_src/RecountNeighborProbGraphWriter.hh
ematch_src/RecountNeighborProbGraphWriter_SortedTagSet.hh
ematch_src/RecountNeighborProbGraphWriter.cc
ematch_src/RecountNeighborProbGraphWriter_SortedTagSet.cc