NGSFeatures: cbrc::SerialNumbersForStrings< serialNumT > Class Template Reference
cbrc::SerialNumbersForStrings< serialNumT > Class Template Reference
#include <SerialNumbersForStrings.hh>
Public Member Functions
SerialNumbersForStrings ()
SerialNumbersForStrings (const SerialNumbersForStrings &sns)
SerialNumbersForStrings (const stringVecT &strings)
virtual ~SerialNumbersForStrings ()
bool operator== (const SerialNumbersForStrings &sns) const
bool operator!= (const SerialNumbersForStrings &sns) const
virtual serialNumT getSerialNumber (const std::string &s)
virtual void registerNewSerialNumber (const std::string &s)
virtual void registerNewSerialNumbers (const stringVecT &strings)
virtual void registerNewSerialNumbers (const stringVecT::const_iterator &beg, const stringVecT::const_iterator &end)
virtual const_iterator begin () const
virtual const_iterator end () const
virtual size_t size () const
virtual stringVecT strings () const
virtual size_t operator() (const std::string &s) const
virtual bool has (const std::string &s) const
virtual const std::string & operator() (const size_t &serialNumber) const
void read (std::istream &iStream=std::cin)
void write (std::ostream &oStream=std::cout) const
Detailed Description
template<typename serialNumT>
class cbrc::SerialNumbersForStrings< serialNumT >
Definition at line 27 of file SerialNumbersForStrings.hh.
Constructor & Destructor Documentation
SerialNumbersForStrings() [1/3]
template<typename serialNumT > cbrc::SerialNumbersForStrings< serialNumT >::SerialNumbersForStrings () inline
Definition at line 35 of file SerialNumbersForStrings.hh.
SerialNumbersForStrings() [2/3]
template<typename serialNumT > cbrc::SerialNumbersForStrings< serialNumT >::SerialNumbersForStrings (const SerialNumbersForStrings< serialNumT > & sns) inline
Definition at line 37 of file SerialNumbersForStrings.hh.
References cbrc::FLEArray< T >::size().
SerialNumbersForStrings() [3/3]
template<typename serialNumT > cbrc::SerialNumbersForStrings< serialNumT >::SerialNumbersForStrings (const stringVecT & strings) inline
Definition at line 44 of file SerialNumbersForStrings.hh.
References cbrc::SerialNumbersForStrings< serialNumT >::registerNewSerialNumber(), cbrc::FLEArray< T >::size(), and cbrc::SerialNumbersForStrings< serialNumT >::strings().
~SerialNumbersForStrings()
template<typename serialNumT > virtual cbrc::SerialNumbersForStrings< serialNumT >::~SerialNumbersForStrings () inline virtual
Definition at line 51 of file SerialNumbersForStrings.hh.
Member Function Documentation
begin()
template<typename serialNumT > virtual const_iterator cbrc::SerialNumbersForStrings< serialNumT >::begin () const inline virtual
Definition at line 81 of file SerialNumbersForStrings.hh.
References cbrc::FLEArray< T >::begin(), and cbrc::SerialNumbersForStrings< serialNumT >::strings().
end()
template<typename serialNumT > virtual const_iterator cbrc::SerialNumbersForStrings< serialNumT >::end () const inline virtual
Definition at line 82 of file SerialNumbersForStrings.hh.
References cbrc::FLEArray< T >::end(), and cbrc::SerialNumbersForStrings< serialNumT >::strings().
Referenced by cbrc::SerialNumbersForStrings< serialNumT >::registerNewSerialNumbers().
getSerialNumber()
template<typename serialNumT > serialNumT cbrc::SerialNumbersForStrings< serialNumT >::getSerialNumber (const std::string & s) virtual
Reimplemented in cbrc::SerialNumbersForStrings_accessCounting< serialNumT >.
Definition at line 150 of file SerialNumbersForStrings.hh.
References cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::size().
Referenced by cbrc::MatrixGraph::readEdgesOneEdgePerLineFormat(), cbrc::NeighborListGraph::readOneEdgePerLineFormat(), and cbrc::ConstantLabeledSquareDoubleFLENumMatrix::setFromStream().
has()
template<typename serialNumT > virtual bool cbrc::SerialNumbersForStrings< serialNumT >::has (const std::string & s) const inline virtual
Definition at line 95 of file SerialNumbersForStrings.hh.
Referenced by cbrc::SerialNumbersForStrings< serialNumT >::registerNewSerialNumber().
operator!=()
template<typename serialNumT > bool cbrc::SerialNumbersForStrings< serialNumT >::operator!= (const SerialNumbersForStrings< serialNumT > & sns) const
Definition at line 142 of file SerialNumbersForStrings.hh.
operator()() [1/2]
template<typename serialNumT > virtual const std::string & cbrc::SerialNumbersForStrings< serialNumT >::operator() (const size_t & serialNumber) const inline virtual
Reimplemented in cbrc::SerialNumbersForStrings_accessCounting< serialNumT >.
Definition at line 105 of file SerialNumbersForStrings.hh.
operator()() [2/2]
template<typename serialNumT > size_t cbrc::SerialNumbersForStrings< serialNumT >::operator() (const std::string & s) const virtual
Reimplemented in cbrc::SerialNumbersForStrings_accessCounting< serialNumT >.
Definition at line 163 of file SerialNumbersForStrings.hh.
References cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::size().
operator==()
template<typename serialNumT > bool cbrc::SerialNumbersForStrings< serialNumT >::operator== (const SerialNumbersForStrings< serialNumT > & sns) const
Definition at line 128 of file SerialNumbersForStrings.hh.
References cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
read()
template<typename serialNumT > void cbrc::SerialNumbersForStrings< serialNumT >::read (std::istream & iStream = std::cin) inline
Definition at line 111 of file SerialNumbersForStrings.hh.
References cbrc::stringBinaryIO::read().
registerNewSerialNumber()
template<typename serialNumT > virtual void cbrc::SerialNumbersForStrings< serialNumT >::registerNewSerialNumber (const std::string & s) inline virtual
Reimplemented in cbrc::SerialNumbersForStrings_accessCounting< serialNumT >.
Definition at line 62 of file SerialNumbersForStrings.hh.
References cbrc::SerialNumbersForStrings< serialNumT >::has().
Referenced by cbrc::MatrixGraph::readContinuousIntegerNodesFormat(), cbrc::SerialNumbersForStrings< serialNumT >::registerNewSerialNumbers(), cbrc::SerialNumbersForStrings< serialNumT >::registerNewSerialNumbers(), and cbrc::SerialNumbersForStrings< serialNumT >::SerialNumbersForStrings().
registerNewSerialNumbers() [1/2]
template<typename serialNumT > virtual void cbrc::SerialNumbersForStrings< serialNumT >::registerNewSerialNumbers (const stringVecT & strings) inline virtual
Definition at line 68 of file SerialNumbersForStrings.hh.
References cbrc::SerialNumbersForStrings< serialNumT >::registerNewSerialNumber(), cbrc::FLEArray< T >::size(), and cbrc::SerialNumbersForStrings< serialNumT >::strings().
registerNewSerialNumbers() [2/2]
template<typename serialNumT > virtual void cbrc::SerialNumbersForStrings< serialNumT >::registerNewSerialNumbers (const stringVecT::const_iterator & beg, const stringVecT::const_iterator & end) inline virtual
Definition at line 73 of file SerialNumbersForStrings.hh.
References cbrc::SerialNumbersForStrings< serialNumT >::end(), and cbrc::SerialNumbersForStrings< serialNumT >::registerNewSerialNumber().
size()
template<typename serialNumT > virtual size_t cbrc::SerialNumbersForStrings< serialNumT >::size () const inline virtual
Reimplemented in cbrc::SerialNumbersForStrings_accessCounting< serialNumT >.
Definition at line 84 of file SerialNumbersForStrings.hh.
strings()
template<typename serialNumT > virtual stringVecT cbrc::SerialNumbersForStrings< serialNumT >::strings () const inline virtual
Reimplemented in cbrc::SerialNumbersForStrings_accessCounting< serialNumT >.
Definition at line 87 of file SerialNumbersForStrings.hh.
Referenced by cbrc::SerialNumbersForStrings< serialNumT >::begin(), cbrc::SerialNumbersForStrings< serialNumT >::end(), cbrc::SerialNumbersForStrings< serialNumT >::registerNewSerialNumbers(), and cbrc::SerialNumbersForStrings< serialNumT >::SerialNumbersForStrings().
write()
template<typename serialNumT > void cbrc::SerialNumbersForStrings< serialNumT >::write (std::ostream & oStream = std::cout) const inline
Definition at line 115 of file SerialNumbersForStrings.hh.
References cbrc::stringBinaryIO::write().
The documentation for this class was generated from the following file:
ematch_src/utils/serialNumbers/SerialNumbersForStrings/SerialNumbersForStrings.hh