NGSFeatures: cbrc::DeltaCompressedInt< intType > Class Template Reference
cbrc::DeltaCompressedInt< intType > Class Template Reference
#include <DeltaCompressedInt.hh>
Public Member Functions
DeltaCompressedInt (const std::vector< intType > &v)
intType first () const
intType nextDelta (size_t &arrayIndex) const
bool operator== (const std::vector< intType > &v)
size_t size () const
size_t arraySize () const
Detailed Description
template<typename intType>
class cbrc::DeltaCompressedInt< intType >
Definition at line 40 of file DeltaCompressedInt.hh.
Constructor & Destructor Documentation
DeltaCompressedInt()
template<typename intType > cbrc::DeltaCompressedInt< intType >::DeltaCompressedInt (const std::vector< intType > & v) inline
Definition at line 131 of file DeltaCompressedInt.hh.
Member Function Documentation
arraySize()
template<typename intType > size_t cbrc::DeltaCompressedInt< intType >::arraySize () const inline
Definition at line 107 of file DeltaCompressedInt.hh.
Referenced by cbrc::DeltaCompressedInt< intType >::operator==().
first()
template<typename intType > intType cbrc::DeltaCompressedInt< intType >::first () const inline
Definition at line 74 of file DeltaCompressedInt.hh.
Referenced by cbrc::DeltaCompressedInt< intType >::operator==().
nextDelta()
template<typename intType > intType cbrc::DeltaCompressedInt< intType >::nextDelta (size_t & arrayIndex) const inline
Definition at line 77 of file DeltaCompressedInt.hh.
Referenced by cbrc::DeltaCompressedInt< intType >::operator==().
operator==()
template<typename intType > bool cbrc::DeltaCompressedInt< intType >::operator== (const std::vector< intType > & v) inline
Definition at line 95 of file DeltaCompressedInt.hh.
References cbrc::DeltaCompressedInt< intType >::arraySize(), cbrc::DeltaCompressedInt< intType >::first(), and cbrc::DeltaCompressedInt< intType >::nextDelta().
size()
template<typename intType > size_t cbrc::DeltaCompressedInt< intType >::size () const inline
Definition at line 106 of file DeltaCompressedInt.hh.
The documentation for this class was generated from the following file:
ematch_src/utils/deltaCompressed/DeltaCompressedInt.hh