NGSFeatures: cbrc::MallocNumArray< T > Class Template Reference
cbrc::MallocNumArray< T > Class Template Reference
#include <MallocArray.hh>
Public Member Functions
MallocNumArray ()
MallocNumArray (const size_t sz)
MallocNumArray (size_t sz, T fillVal)
MallocNumArray (size_t sz, T *b)
MallocNumArray (std::vector< T > v)
MallocNumArray (T v[], unsigned int numElems)
MallocNumArray (const MallocArray< T > &fla)
MallocNumArray operator= (std::vector< T > v)
MallocNumArray operator= (const MallocNumArray &fla)
MallocNumArray & operator*= (T el)
MallocNumArray & operator/= (T el)
MallocNumArray & operator+= (const MallocNumArray< T > &fla)
T sum () const
T max () const
size_t maxIndex () const
void squareElements ()
Public Member Functions inherited from cbrc::MallocArray< T >
MallocArray ()
MallocArray (const size_t sz)
MallocArray (size_t sz, T fillVal)
MallocArray (size_t sz, T *b)
MallocArray (const std::vector< T > &v)
MallocArray (T v[], unsigned int numElems)
MallocArray (const MallocArray< T > &fla)
MallocArray (std::istream &is)
virtual ~MallocArray ()
operator std::vector< T > () const
size_t bsize ()
void write (std::ostream &os)
void read (std::istream &is)
void setSize (size_t sz)
void resize (size_t sz)
MallocArray operator= (const MallocArray &fla)
MallocArray operator= (std::vector< T > v)
void assign (const typename MallocArray< T >::const_iterator &begin, const typename MallocArray< T >::const_iterator &end)
void assign (const typename std::vector< T >::const_iterator &begin, const typename std::vector< T >::const_iterator &end)
void zero ()
void fill (T fillVal)
void fillWithByte (int fillByte)
bool validIndex (size_t index) const
bool operator== (const MallocArray &fla) const
virtual T & operator[] (const size_t index) const
virtual T & operator[] (int index) const
void copyTo (const T &elem, size_t index)
size_t size () const
bool empty () const
iterator begin () const
iterator end () const
Additional Inherited Members
Public Types inherited from cbrc::MallocArray< T >
typedef T * iterator
typedef const T * const_iterator
Protected Attributes inherited from cbrc::MallocArray< T >
size_t s
T * a
Detailed Description
template<typename T>
class cbrc::MallocNumArray< T >
Definition at line 267 of file MallocArray.hh.
Constructor & Destructor Documentation
MallocNumArray() [1/7]
template<typename T > cbrc::MallocNumArray< T >::MallocNumArray () inline
Definition at line 269 of file MallocArray.hh.
MallocNumArray() [2/7]
template<typename T > cbrc::MallocNumArray< T >::MallocNumArray (const size_t sz) inline
Definition at line 270 of file MallocArray.hh.
MallocNumArray() [3/7]
template<typename T > cbrc::MallocNumArray< T >::MallocNumArray (size_t sz, T fillVal) inline
Definition at line 271 of file MallocArray.hh.
MallocNumArray() [4/7]
template<typename T > cbrc::MallocNumArray< T >::MallocNumArray (size_t sz, T * b) inline
Definition at line 272 of file MallocArray.hh.
MallocNumArray() [5/7]
template<typename T > cbrc::MallocNumArray< T >::MallocNumArray (std::vector< T > v) inline
Definition at line 273 of file MallocArray.hh.
MallocNumArray() [6/7]
template<typename T > cbrc::MallocNumArray< T >::MallocNumArray (T v[], unsigned int numElems) inline
Definition at line 274 of file MallocArray.hh.
MallocNumArray() [7/7]
template<typename T > cbrc::MallocNumArray< T >::MallocNumArray (const MallocArray< T > & fla) inline
Definition at line 275 of file MallocArray.hh.
Member Function Documentation
max()
template<typename T > T cbrc::MallocNumArray< T >::max () const inline
Definition at line 312 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, and cbrc::MallocArray< T >::size().
maxIndex()
template<typename T > size_t cbrc::MallocNumArray< T >::maxIndex () const inline
Definition at line 318 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, and cbrc::MallocArray< T >::size().
operator*=()
template<typename T > MallocNumArray & cbrc::MallocNumArray< T >::operator*= (T el) inline
Definition at line 294 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, and cbrc::MallocArray< T >::size().
operator+=()
template<typename T > MallocNumArray & cbrc::MallocNumArray< T >::operator+= (const MallocNumArray< T > & fla) inline
Definition at line 302 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, cbrc::FLEArray< T >::size(), and cbrc::MallocArray< T >::size().
operator/=()
template<typename T > MallocNumArray & cbrc::MallocNumArray< T >::operator/= (T el) inline
Definition at line 298 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, and cbrc::MallocArray< T >::size().
operator=() [1/2]
template<typename T > MallocNumArray cbrc::MallocNumArray< T >::operator= (const MallocNumArray< T > & fla) inline
Definition at line 277 of file MallocArray.hh.
References cbrc::FLEArray< T >::a, cbrc::MallocArray< T >::a, cbrc::MallocArray< T >::s, cbrc::FLEArray< T >::size(), and cbrc::MallocArray< T >::size().
operator=() [2/2]
template<typename T > MallocNumArray cbrc::MallocNumArray< T >::operator= (std::vector< T > v) inline
Definition at line 276 of file MallocArray.hh.
squareElements()
template<typename T > void cbrc::MallocNumArray< T >::squareElements () inline
Definition at line 331 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, and cbrc::MallocArray< T >::size().
sum()
template<typename T > T cbrc::MallocNumArray< T >::sum () const inline
Definition at line 307 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, and cbrc::MallocArray< T >::size().
The documentation for this class was generated from the following file:
ematch_src/utils/FLArray/MallocArray.hh