NGSFeatures: cbrc::DNAArrayBit8< len > Class Template Reference
cbrc::DNAArrayBit8< len > Class Template Reference
#include <DNAArrayBit8.hh>
Public Member Functions
DNAArrayBit8 ()
DNAArrayBit8 (byte bases) throw (std::length_error)
DNAArrayBit8 (ResidueIndexMap::arrayT residueIndices) throw (std::length_error)
byte const getBases ()
void setBases (byte bs)
operator size_t () const
bool operator== (const char *const s) const
byte operator() (const size_t index) const throw (std::out_of_range)
void set (const size_t index, const byte base) throw (std::out_of_range,std::invalid_argument)
DNAArrayBit8< len > substitute (const size_t index, const byte base) const
std::string getIndices () const
size_t length () const
void friend testDNAArrayBit8 ()
Detailed Description
template<size_t len>
class cbrc::DNAArrayBit8< len >
Definition at line 33 of file DNAArrayBit8.hh.
Constructor & Destructor Documentation
DNAArrayBit8() [1/3]
template<size_t len> cbrc::DNAArrayBit8< len >::DNAArrayBit8 () inline
Definition at line 35 of file DNAArrayBit8.hh.
References cbrc::DNAArrayBit8< len >::DNAArrayBit8().
Referenced by cbrc::DNAArrayBit8< len >::DNAArrayBit8().
DNAArrayBit8() [2/3]
template<size_t len> cbrc::DNAArrayBit8< len >::DNAArrayBit8 (byte bases) throw (std::length_error) inline
Definition at line 36 of file DNAArrayBit8.hh.
DNAArrayBit8() [3/3]
template<size_t len> cbrc::DNAArrayBit8< len >::DNAArrayBit8 (ResidueIndexMap::arrayT residueIndices) throw (std::length_error) inline
Definition at line 39 of file DNAArrayBit8.hh.
References cbrc::DNAArrayBit8< len >::length(), and cbrc::DNAArrayBit8< len >::set().
Member Function Documentation
getBases()
template<size_t len> byte const cbrc::DNAArrayBit8< len >::getBases () inline
Definition at line 49 of file DNAArrayBit8.hh.
getIndices()
template<size_t len> std::string cbrc::DNAArrayBit8< len >::getIndices () const inline
Definition at line 94 of file DNAArrayBit8.hh.
References cbrc::FLEArray< T >::resize().
length()
template<size_t len> size_t cbrc::DNAArrayBit8< len >::length () const inline
Definition at line 100 of file DNAArrayBit8.hh.
Referenced by cbrc::DNAArrayBit8< len >::DNAArrayBit8(), cbrc::DNAArrayBit8< len >::operator()(), and cbrc::DNAArrayBit8< len >::set().
operator size_t()
template<size_t len> cbrc::DNAArrayBit8< len >::operator size_t () const inline
Definition at line 53 of file DNAArrayBit8.hh.
operator()()
template<size_t len> byte cbrc::DNAArrayBit8< len >::operator() (const size_t index) const throw (std::out_of_range) inline
Definition at line 65 of file DNAArrayBit8.hh.
References cbrc::DNAArrayBit8< len >::length(), and cbrc::setMask.
operator==()
template<size_t len> bool cbrc::DNAArrayBit8< len >::operator== (const char *const s) const inline
Definition at line 56 of file DNAArrayBit8.hh.
References cbrc::DNAProperResidueIndexMap.
set()
template<size_t len> void cbrc::DNAArrayBit8< len >::set (const size_t index, const byte base) throw (std::out_of_range, std::invalid_argument) inline
Definition at line 74 of file DNAArrayBit8.hh.
References cbrc::clearMask, cbrc::DNAArrayBit8< len >::length(), and cbrc::maxResidueIndex.
Referenced by cbrc::DNAArrayBit8< len >::DNAArrayBit8().
setBases()
template<size_t len> void cbrc::DNAArrayBit8< len >::setBases (byte bs) inline
Definition at line 50 of file DNAArrayBit8.hh.
substitute()
template<size_t len> DNAArrayBit8< len > cbrc::DNAArrayBit8< len >::substitute (const size_t index, const byte base) const inline
Definition at line 89 of file DNAArrayBit8.hh.
testDNAArrayBit8()
template<size_t len> void friend cbrc::DNAArrayBit8< len >::testDNAArrayBit8 ()
The documentation for this class was generated from the following file:
ematch_src/utils/sequence/packedDNA/DNAArrayBit8.hh