NGSFeatures: cbrc::SortedTagSet Class Reference
cbrc::SortedTagSet Class Reference
#include <SortedTagSet.hh>
Public Types
enum fileFormatT { binary , text }
typedef Sigma4FLArray tagSeqT
typedef std::vector< tagSeqT > tagSeqVecT
typedef tagSeqVecT::const_iterator const_iterator
typedef tagSeqVecT::iterator iterator
Public Member Functions
SortedTagSet (const tagSeqVecT &vec)
SortedTagSet (std::istream &iStream, fileFormatT fileFormat=text)
void initialSort ()
size_t size () const
bool has (const tagSeqT &tag) const
const tagSeqT & operator() (const size_t &i) const
size_t operator() (const tagSeqT &tag) const
size_t getSerialNumberOrDie (const tagSeqT &tag) const
const_iterator begin () const
const_iterator end () const
tagSeqT toTagSeq (const std::string &s) const
std::string toString (const tagSeqT &tag) const
void readFromBinaryStream (std::istream &iStream)
void readFromTextStream (std::istream &iStream)
void assertIsSorted () const
Static Public Member Functions
static const ResidueIndexMap & residueIndexMap ()
Detailed Description
Definition at line 22 of file SortedTagSet.hh.
Member Typedef Documentation
const_iterator
typedef tagSeqVecT::const_iterator cbrc::SortedTagSet::const_iterator
Definition at line 31 of file SortedTagSet.hh.
iterator
typedef tagSeqVecT::iterator cbrc::SortedTagSet::iterator
Definition at line 32 of file SortedTagSet.hh.
tagSeqT
typedef Sigma4FLArray cbrc::SortedTagSet::tagSeqT
Definition at line 28 of file SortedTagSet.hh.
tagSeqVecT
typedef std::vector<tagSeqT> cbrc::SortedTagSet::tagSeqVecT
Definition at line 29 of file SortedTagSet.hh.
Member Enumeration Documentation
fileFormatT
enum cbrc::SortedTagSet::fileFormatT
Enumerator
binary
text
Definition at line 30 of file SortedTagSet.hh.
Constructor & Destructor Documentation
SortedTagSet() [1/2]
cbrc::SortedTagSet::SortedTagSet (const tagSeqVecT & vec) inline
Definition at line 36 of file SortedTagSet.hh.
References initialSort().
SortedTagSet() [2/2]
cbrc::SortedTagSet::SortedTagSet (std::istream & iStream, fileFormatT fileFormat = text) inline
Definition at line 41 of file SortedTagSet.hh.
References readFromBinaryStream(), readFromTextStream(), and text.
Member Function Documentation
assertIsSorted()
void cbrc::SortedTagSet::assertIsSorted () const
Definition at line 70 of file SortedTagSet.cc.
References GDB_ASSERTF.
Referenced by readFromTextStream().
begin()
const_iterator cbrc::SortedTagSet::begin () const inline
Definition at line 78 of file SortedTagSet.hh.
end()
const_iterator cbrc::SortedTagSet::end () const inline
Definition at line 79 of file SortedTagSet.hh.
getSerialNumberOrDie()
size_t cbrc::SortedTagSet::getSerialNumberOrDie (const tagSeqT & tag) const inline
Definition at line 69 of file SortedTagSet.hh.
References GDB_ASSERTF.
has()
bool cbrc::SortedTagSet::has (const tagSeqT & tag) const inline
Definition at line 55 of file SortedTagSet.hh.
Referenced by cbrc::RecountTagCounts::RecountTagCounts().
initialSort()
void cbrc::SortedTagSet::initialSort () inline
Definition at line 46 of file SortedTagSet.hh.
Referenced by SortedTagSet().
operator()() [1/2]
const tagSeqT & cbrc::SortedTagSet::operator() (const size_t & i) const inline
Definition at line 59 of file SortedTagSet.hh.
operator()() [2/2]
size_t cbrc::SortedTagSet::operator() (const tagSeqT & tag) const inline
Definition at line 64 of file SortedTagSet.hh.
readFromBinaryStream()
void cbrc::SortedTagSet::readFromBinaryStream (std::istream & iStream) inline
Definition at line 102 of file SortedTagSet.hh.
Referenced by SortedTagSet().
readFromTextStream()
void cbrc::SortedTagSet::readFromTextStream (std::istream & iStream)
Definition at line 31 of file SortedTagSet.cc.
References assertIsSorted(), DO_OR_DIEF, cbrc::perlish::fromString(), residueIndexMap(), and cbrc::perlish::slurpLine().
Referenced by SortedTagSet().
residueIndexMap()
static const ResidueIndexMap & cbrc::SortedTagSet::residueIndexMap () inline static
Definition at line 84 of file SortedTagSet.hh.
Referenced by readFromTextStream(), toString(), and toTagSeq().
size()
size_t cbrc::SortedTagSet::size () const inline
Definition at line 53 of file SortedTagSet.hh.
toString()
std::string cbrc::SortedTagSet::toString (const tagSeqT & tag) const inline
Definition at line 94 of file SortedTagSet.hh.
References residueIndexMap().
Referenced by cbrc::dumpNeighborList().
toTagSeq()
SortedTagSet::tagSeqT cbrc::SortedTagSet::toTagSeq (const std::string & s) const
Definition at line 14 of file SortedTagSet.cc.
References GDB_DIEF, and residueIndexMap().
Referenced by cbrc::RecountTagCounts::RecountTagCounts().
The documentation for this class was generated from the following files:
ematch_src/SortedTagSet.hh
ematch_src/SortedTagSet.cc