NGSFeatures: cbrc::FLSorted< T > Class Template Reference
cbrc::FLSorted< T > Class Template Reference
#include <FLSorted.hh>
Public Member Functions
FLSorted ()
FLSorted (const std::vector< T > &v)
void operator= (const std::vector< T > &v)
void assign (const typename std::vector< T >::const_iterator &begin, const typename std::vector< T >::const_iterator &end)
size_t size () const
bool has (const T &t) const
const T & operator() (const size_t &i) const
T & operator[] (const size_t &i) const
size_t operator() (const T &t) const
FLArray< T >::iterator begin () const
FLArray< T >::iterator end () const
Friends
std::ostream & operator<< (std::ostream &os, const FLSorted< T > &sl)
Detailed Description
template<typename T>
class cbrc::FLSorted< T >
Definition at line 34 of file FLSorted.hh.
Constructor & Destructor Documentation
FLSorted() [1/2]
template<typename T > cbrc::FLSorted< T >::FLSorted () inline
Definition at line 37 of file FLSorted.hh.
FLSorted() [2/2]
template<typename T > cbrc::FLSorted< T >::FLSorted (const std::vector< T > & v) inline
Definition at line 38 of file FLSorted.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and cbrc::FLEArray< T >::resize().
Member Function Documentation
assign()
template<typename T > void cbrc::FLSorted< T >::assign (const typename std::vector< T >::const_iterator & begin, const typename std::vector< T >::const_iterator & end) inline
Definition at line 52 of file FLSorted.hh.
References cbrc::FLEArray< T >::assign(), cbrc::FLEArray< T >::begin(), cbrc::FLSorted< T >::begin(), cbrc::FLEArray< T >::empty(), cbrc::FLEArray< T >::end(), cbrc::FLSorted< T >::end(), GDB_DIEF, and cbrc::FLEArray< T >::resize().
begin()
template<typename T > FLArray< T >::iterator cbrc::FLSorted< T >::begin () const inline
Definition at line 81 of file FLSorted.hh.
References cbrc::FLEArray< T >::begin().
Referenced by cbrc::FLSorted< T >::assign().
end()
template<typename T > FLArray< T >::iterator cbrc::FLSorted< T >::end () const inline
Definition at line 82 of file FLSorted.hh.
References cbrc::FLEArray< T >::end().
Referenced by cbrc::FLSorted< T >::assign().
has()
template<typename T > bool cbrc::FLSorted< T >::has (const T & t) const inline
Definition at line 71 of file FLSorted.hh.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
Referenced by cbrc::FLSorted2TypePairSet< T0, T1 >::operator()().
operator()() [1/2]
template<typename T > const T & cbrc::FLSorted< T >::operator() (const size_t & i) const inline
Definition at line 73 of file FLSorted.hh.
operator()() [2/2]
template<typename T > size_t cbrc::FLSorted< T >::operator() (const T & t) const inline
Definition at line 77 of file FLSorted.hh.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
operator=()
template<typename T > void cbrc::FLSorted< T >::operator= (const std::vector< T > & v) inline
Definition at line 43 of file FLSorted.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::empty(), cbrc::FLEArray< T >::end(), GDB_ASSERTF, and cbrc::FLEArray< T >::resize().
operator[]()
template<typename T > T & cbrc::FLSorted< T >::operator[] (const size_t & i) const inline
Definition at line 74 of file FLSorted.hh.
size()
template<typename T > size_t cbrc::FLSorted< T >::size () const inline
Definition at line 70 of file FLSorted.hh.
References cbrc::FLEArray< T >::size().
Referenced by cbrc::FLSorted2TypePairSet< T0, T1 >::FLSorted2TypePairSet().
Friends And Related Symbol Documentation
operator<<
template<typename T > std::ostream & operator<< (std::ostream & os, const FLSorted< T > & sl) friend
Definition at line 89 of file FLSorted.hh.
The documentation for this class was generated from the following file:
ematch_src/utils/FLArray/FLSorted.hh