NGSFeatures: cbrc::LabeledSequence Class Reference
cbrc::LabeledSequence Class Reference
#include <LabeledSequence.hh>
Public Member Functions
LabeledSequence (const std::string &residues, const std::vector< std::string > &labels)
LabeledSequence (const std::string &residues, const std::vector< std::string > &labels, const ResidueIndexMap &residueIndexMap)
LabeledSequence (const LabeledSequence &ls)
const std::string & residues () const
const ResidueIndexMap::arrayT & residueIndices () const
const ResidueIndexMap::arrayT * residueIndicesPtr () const
const std::string & name () const
const std::string & className () const
const std::string & label (const size_t &i) const
const std::vector< std::string > & labels () const
size_t size () const
size_t length () const
const ResidueIndexMap & residueIndexMap () const
Static Public Member Functions
static bool notLonger (const LabeledSequence &ls0, const LabeledSequence &ls1)
Detailed Description
Definition at line 25 of file LabeledSequence.hh.
Constructor & Destructor Documentation
LabeledSequence() [1/3]
cbrc::LabeledSequence::LabeledSequence (const std::string & residues, const std::vector< std::string > & labels)
Definition at line 14 of file LabeledSequence.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), labels(), residueIndexMap(), cbrc::residueIndexMapGuessedFromResidues(), residues(), and cbrc::FLEArray< T >::size().
LabeledSequence() [2/3]
cbrc::LabeledSequence::LabeledSequence (const std::string & residues, const std::vector< std::string > & labels, const ResidueIndexMap & residueIndexMap)
Definition at line 29 of file LabeledSequence.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), labels(), residues(), and cbrc::FLEArray< T >::size().
LabeledSequence() [3/3]
cbrc::LabeledSequence::LabeledSequence (const LabeledSequence & ls)
Definition at line 55 of file LabeledSequence.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and cbrc::FLEArray< T >::size().
Member Function Documentation
className()
const std::string & cbrc::LabeledSequence::className () const inline
Definition at line 43 of file LabeledSequence.hh.
References label().
label()
const std::string & cbrc::LabeledSequence::label (const size_t & i) const inline
Definition at line 45 of file LabeledSequence.hh.
References cbrc::LabeledSequenceUndefinedLabel(), labels(), and size().
Referenced by className(), and name().
labels()
const std::vector< std::string > & cbrc::LabeledSequence::labels () const inline
Definition at line 50 of file LabeledSequence.hh.
Referenced by label(), LabeledSequence(), and LabeledSequence().
length()
size_t cbrc::LabeledSequence::length () const inline
Definition at line 53 of file LabeledSequence.hh.
References residueIndices(), and cbrc::FLEArray< T >::size().
Referenced by cbrc::SimilaritySearchableSequences::bestMatch().
name()
const std::string & cbrc::LabeledSequence::name () const inline
Definition at line 42 of file LabeledSequence.hh.
References label().
Referenced by cbrc::SimilaritySearchableSequences::bestMatch().
notLonger()
static bool cbrc::LabeledSequence::notLonger (const LabeledSequence & ls0, const LabeledSequence & ls1) inline static
Definition at line 59 of file LabeledSequence.hh.
References cbrc::FLEArray< T >::size().
residueIndexMap()
const ResidueIndexMap & cbrc::LabeledSequence::residueIndexMap () const inline
Definition at line 55 of file LabeledSequence.hh.
Referenced by LabeledSequence().
residueIndices()
const ResidueIndexMap::arrayT & cbrc::LabeledSequence::residueIndices () const inline
Definition at line 40 of file LabeledSequence.hh.
Referenced by cbrc::SimilaritySearchableSequences::bestMatch(), cbrc::SimilaritySearchableSequences::identicalMatches(), length(), and size().
residueIndicesPtr()
const ResidueIndexMap::arrayT * cbrc::LabeledSequence::residueIndicesPtr () const inline
Definition at line 41 of file LabeledSequence.hh.
residues()
const std::string & cbrc::LabeledSequence::residues () const inline
Definition at line 39 of file LabeledSequence.hh.
Referenced by LabeledSequence(), and LabeledSequence().
size()
size_t cbrc::LabeledSequence::size () const inline
Definition at line 52 of file LabeledSequence.hh.
References residueIndices(), and cbrc::FLEArray< T >::size().
Referenced by label().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/LabeledSequence.hh
ematch_src/utils/sequence/LabeledSequence.cc