NGSFeatures: cbrc::RecountNeighborProbGraphOnDisk Class Reference
cbrc::RecountNeighborProbGraphOnDisk Class Reference
#include <RecountNeighborProbGraphOnDisk.hh>
Public Member Functions
RecountNeighborProbGraphOnDisk (const TagSet &tagID_to_seq, std::ifstream &graphFile)
const size_t & size () const
const RecountNeighborList & curNeighborList () const
const TagSet & tagID_to_seq () const
void readFirstNode ()
bool readNextNode ()
RecountNeighborProbGraphOnDisk (const SortedTagSet &tagId_to_seq, std::ifstream &graphFile)
const size_t & size () const
const RecountNeighborList & curNeighborList () const
const SortedTagSet & tagId_to_seq () const
void readFirstNode ()
bool readNextNode ()
Detailed Description
Definition at line 28 of file RecountNeighborProbGraphOnDisk.hh.
Constructor & Destructor Documentation
RecountNeighborProbGraphOnDisk() [1/2]
cbrc::RecountNeighborProbGraphOnDisk::RecountNeighborProbGraphOnDisk (const TagSet & tagID_to_seq, std::ifstream & graphFile) inline
Definition at line 32 of file RecountNeighborProbGraphOnDisk.hh.
RecountNeighborProbGraphOnDisk() [2/2]
cbrc::RecountNeighborProbGraphOnDisk::RecountNeighborProbGraphOnDisk (const SortedTagSet & tagId_to_seq, std::ifstream & graphFile) inline
Definition at line 32 of file RecountNeighborProbGraphOnDisk_SortedTagSet.hh.
Member Function Documentation
curNeighborList() [1/2]
const RecountNeighborList & cbrc::RecountNeighborProbGraphOnDisk::curNeighborList () const inline
Definition at line 46 of file RecountNeighborProbGraphOnDisk.hh.
Referenced by cbrc::dumpRecountNeighborProbGraphOnDisk().
curNeighborList() [2/2]
const RecountNeighborList & cbrc::RecountNeighborProbGraphOnDisk::curNeighborList () const inline
Definition at line 46 of file RecountNeighborProbGraphOnDisk_SortedTagSet.hh.
readFirstNode() [1/2]
void cbrc::RecountNeighborProbGraphOnDisk::readFirstNode () inline
Definition at line 56 of file RecountNeighborProbGraphOnDisk.hh.
References DO_OR_DIEF, and cbrc::RecountNeighborList::read().
Referenced by cbrc::dumpRecountNeighborProbGraphOnDisk(), cbrc::RecountComputerForGraphOnDisk::meanCountsFromTrue(), cbrc::RecountComputerForGraphOnDisk::meanCountsFromTrue(), cbrc::RecountComputerForGraphOnDisk::varianceCountsFromTrue(), and cbrc::RecountComputerForGraphOnDisk::varianceCountsFromTrue().
readFirstNode() [2/2]
void cbrc::RecountNeighborProbGraphOnDisk::readFirstNode () inline
Definition at line 56 of file RecountNeighborProbGraphOnDisk_SortedTagSet.hh.
References DO_OR_DIEF, and cbrc::RecountNeighborList::read().
readNextNode() [1/2]
bool cbrc::RecountNeighborProbGraphOnDisk::readNextNode () inline
Definition at line 62 of file RecountNeighborProbGraphOnDisk.hh.
References cbrc::RecountNeighborList::read().
Referenced by cbrc::dumpRecountNeighborProbGraphOnDisk(), cbrc::RecountComputerForGraphOnDisk::meanCountsFromTrue(), cbrc::RecountComputerForGraphOnDisk::meanCountsFromTrue(), cbrc::RecountComputerForGraphOnDisk::varianceCountsFromTrue(), and cbrc::RecountComputerForGraphOnDisk::varianceCountsFromTrue().
readNextNode() [2/2]
bool cbrc::RecountNeighborProbGraphOnDisk::readNextNode () inline
Definition at line 62 of file RecountNeighborProbGraphOnDisk_SortedTagSet.hh.
References cbrc::RecountNeighborList::read().
size() [1/2]
const size_t & cbrc::RecountNeighborProbGraphOnDisk::size () const inline
Definition at line 44 of file RecountNeighborProbGraphOnDisk.hh.
size() [2/2]
const size_t & cbrc::RecountNeighborProbGraphOnDisk::size () const inline
Definition at line 44 of file RecountNeighborProbGraphOnDisk_SortedTagSet.hh.
tagID_to_seq()
const TagSet & cbrc::RecountNeighborProbGraphOnDisk::tagID_to_seq () const inline
Definition at line 50 of file RecountNeighborProbGraphOnDisk.hh.
tagId_to_seq()
const SortedTagSet & cbrc::RecountNeighborProbGraphOnDisk::tagId_to_seq () const inline
Definition at line 50 of file RecountNeighborProbGraphOnDisk_SortedTagSet.hh.
The documentation for this class was generated from the following files:
ematch_src/RecountNeighborProbGraphOnDisk.hh
ematch_src/RecountNeighborProbGraphOnDisk_SortedTagSet.hh
ematch_src/RecountNeighborProbGraphOnDisk.cc
ematch_src/RecountNeighborProbGraphOnDisk_SortedTagSet.cc