NGSFeatures: cbrc::AminoScoreIdentity Class Reference
cbrc::AminoScoreIdentity Class Reference
#include <AminoScoreIdentity.hh>
Public Member Functions
AminoScoreIdentity (const ResidueIndexMap &residueIndexMap=aminoResidueIndexMap, const alignScoreT matchScore=1, const alignScoreT mismatchScore=0, const alignScoreT gapInitiation=-2, const alignScoreT gapExtension=-1)
alignScoreT score (const ResidueIndexMap::indexT &r1, const ResidueIndexMap::indexT &r2) const
alignScoreT maxScore (const ResidueIndexMap::indexT &r1) const
const ResidueIndexMap & residueIndexMap () const
alignScoreT maxScore () const
alignScoreT minScore () const
alignScoreT gapInitiation () const
alignScoreT gapExtension () const
Public Member Functions inherited from cbrc::AminoScore
bool minScoreIsValid () const
virtual ~AminoScore ()
Detailed Description
Definition at line 18 of file AminoScoreIdentity.hh.
Constructor & Destructor Documentation
AminoScoreIdentity()
cbrc::AminoScoreIdentity::AminoScoreIdentity (const ResidueIndexMap & residueIndexMap = aminoResidueIndexMap, const alignScoreT matchScore = 1, const alignScoreT mismatchScore = 0, const alignScoreT gapInitiation = -2, const alignScoreT gapExtension = -1) inline
Definition at line 20 of file AminoScoreIdentity.hh.
References gapExtension(), and gapInitiation().
Member Function Documentation
gapExtension()
alignScoreT cbrc::AminoScoreIdentity::gapExtension () const inline virtual
Implements cbrc::AminoScore.
Definition at line 57 of file AminoScoreIdentity.hh.
Referenced by AminoScoreIdentity().
gapInitiation()
alignScoreT cbrc::AminoScoreIdentity::gapInitiation () const inline virtual
Implements cbrc::AminoScore.
Definition at line 55 of file AminoScoreIdentity.hh.
Referenced by AminoScoreIdentity().
maxScore() [1/2]
alignScoreT cbrc::AminoScoreIdentity::maxScore () const inline virtual
Implements cbrc::AminoScore.
Definition at line 51 of file AminoScoreIdentity.hh.
maxScore() [2/2]
alignScoreT cbrc::AminoScoreIdentity::maxScore (const ResidueIndexMap::indexT & r1) const inline virtual
Implements cbrc::AminoScore.
Definition at line 46 of file AminoScoreIdentity.hh.
minScore()
alignScoreT cbrc::AminoScoreIdentity::minScore () const inline virtual
Implements cbrc::AminoScore.
Definition at line 53 of file AminoScoreIdentity.hh.
residueIndexMap()
const ResidueIndexMap & cbrc::AminoScoreIdentity::residueIndexMap () const inline virtual
Implements cbrc::AminoScore.
Definition at line 49 of file AminoScoreIdentity.hh.
score()
alignScoreT cbrc::AminoScoreIdentity::score (const ResidueIndexMap::indexT & r1, const ResidueIndexMap::indexT & r2) const inline virtual
Implements cbrc::AminoScore.
Definition at line 37 of file AminoScoreIdentity.hh.
The documentation for this class was generated from the following file:
ematch_src/utils/sequence/align/AminoScoreIdentity.hh