NGSFeatures: cbrc::Matrix< T > Class Template Reference
cbrc::Matrix< T > Class Template Reference
#include <Matrix.hh>
Public Types
typedef T element_type
Public Member Functions
Matrix ()
Matrix (size_t, size_t)
Matrix (const Matrix< T > &)
~Matrix ()
Matrix< T > & operator= (const Matrix< T > &)
element_type * operator[] (size_t) const
size_t column_size ()
size_t row_size ()
void resize (size_t, size_t)
bool check_valid (size_t r, size_t c)
void set_valid (size_t r, size_t c, bool validity=1)
Detailed Description
template<class T>
class cbrc::Matrix< T >
Definition at line 28 of file Matrix.hh.
Member Typedef Documentation
element_type
template<class T > typedef T cbrc::Matrix< T >::element_type
Definition at line 32 of file Matrix.hh.
Constructor & Destructor Documentation
Matrix() [1/3]
template<class T > cbrc::Matrix< T >::Matrix ()
Definition at line 66 of file Matrix.hh.
References cbrc::FLEArray< T >::FLEArray().
Matrix() [2/3]
template<class T > cbrc::Matrix< T >::Matrix (size_t r, size_t c)
Definition at line 69 of file Matrix.hh.
References cbrc::FLEArray< T >::FLEArray().
Matrix() [3/3]
template<class T > cbrc::Matrix< T >::Matrix (const Matrix< T > & mm)
Definition at line 77 of file Matrix.hh.
References cbrc::FLEArray< T >::FLEArray().
~Matrix()
template<class T > cbrc::Matrix< T >::~Matrix ()
Definition at line 123 of file Matrix.hh.
Member Function Documentation
check_valid()
template<class T > bool cbrc::Matrix< T >::check_valid (size_t r, size_t c) inline
Definition at line 50 of file Matrix.hh.
column_size()
template<class T > size_t cbrc::Matrix< T >::column_size ()
Definition at line 104 of file Matrix.hh.
operator=()
template<class T > Matrix< T > & cbrc::Matrix< T >::operator= (const Matrix< T > & mm)
Definition at line 84 of file Matrix.hh.
References cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::resize().
operator[]()
template<class T > T * cbrc::Matrix< T >::operator[] (size_t r) const
Definition at line 98 of file Matrix.hh.
References cbrc::FLEArray< T >::FLEArray().
resize()
template<class T > void cbrc::Matrix< T >::resize (size_t r, size_t c)
Definition at line 114 of file Matrix.hh.
References cbrc::FLEArray< T >::FLEArray().
row_size()
template<class T > size_t cbrc::Matrix< T >::row_size ()
Definition at line 109 of file Matrix.hh.
set_valid()
template<class T > void cbrc::Matrix< T >::set_valid (size_t r, size_t c, bool validity = 1) inline
Definition at line 51 of file Matrix.hh.
The documentation for this class was generated from the following file:
ematch_src/utils/Matrix/Matrix.hh