NGSFeatures: cbrc::SimilaritySearchableSequences Class Reference
cbrc::SimilaritySearchableSequences Class Reference
#include <SimilaritySearchableSequences.hh>
Public Types
typedef std::pair< size_t, alignScoreT > indexScorePairT
Public Member Functions
SimilaritySearchableSequences (const AminoScore &resSubScore, const std::vector< LabeledSequence > &seqs)
indexScorePairT bestMatch (const LabeledSequence &query, const LabeledSequencePairPredicate &skipPairPredicate) const
indexScorePairT bestMatch (const LabeledSequence &query, const alignScoreT loosenessFactor=defaultLoosenessFactor(), const LabeledSequencePairPredicate &skipPairPredicate=labeledSequencePairPredicate_alwaysFalse) const
std::vector< size_t > identicalMatches (const LabeledSequence &query) const
std::vector< size_t > withinHammingDistance (const LabeledSequence &query, const double &threshold) const
bool wouldSkipAll (const LabeledSequence &query, const LabeledSequencePairPredicate &skipPairPredicate) const
const LabeledSequence & operator() (const size_t &index) const
size_t size () const
const std::string & seqName (const indexScorePairT &indexScorePair) const
const AminoScore & resSubScore () const
Static Public Member Functions
static const alignScoreT & defaultLoosenessFactor ()
Detailed Description
Definition at line 25 of file SimilaritySearchableSequences.hh.
Member Typedef Documentation
indexScorePairT
typedef std::pair<size_t, alignScoreT> cbrc::SimilaritySearchableSequences::indexScorePairT
Definition at line 27 of file SimilaritySearchableSequences.hh.
Constructor & Destructor Documentation
SimilaritySearchableSequences()
cbrc::SimilaritySearchableSequences::SimilaritySearchableSequences (const AminoScore & resSubScore, const std::vector< LabeledSequence > & seqs) inline
Definition at line 30 of file SimilaritySearchableSequences.hh.
Member Function Documentation
bestMatch() [1/2]
SimilaritySearchableSequences::indexScorePairT cbrc::SimilaritySearchableSequences::bestMatch (const LabeledSequence & query, const alignScoreT loosenessFactor = defaultLoosenessFactor(), const LabeledSequencePairPredicate & skipPairPredicate = labeledSequencePairPredicate_alwaysFalse) const
Definition at line 66 of file SimilaritySearchableSequences.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), cbrc::FLEArrayIdentityPermutation(), GDB_ASSERTF, cbrc::LabeledSequence::length(), cbrc::LabeledSequence::name(), cbrc::LabeledSequence::residueIndices(), resSubScore(), cbrc::FLEArray< T >::size(), and wouldSkipAll().
bestMatch() [2/2]
indexScorePairT cbrc::SimilaritySearchableSequences::bestMatch (const LabeledSequence & query, const LabeledSequencePairPredicate & skipPairPredicate) const inline
Definition at line 42 of file SimilaritySearchableSequences.hh.
References bestMatch(), and defaultLoosenessFactor().
Referenced by bestMatch().
defaultLoosenessFactor()
static const alignScoreT & cbrc::SimilaritySearchableSequences::defaultLoosenessFactor () inline static
Definition at line 86 of file SimilaritySearchableSequences.hh.
Referenced by bestMatch().
identicalMatches()
std::vector< size_t > cbrc::SimilaritySearchableSequences::identicalMatches (const LabeledSequence & query) const
Definition at line 20 of file SimilaritySearchableSequences.cc.
References cbrc::LabeledSequence::residueIndices(), and cbrc::FLEArray< T >::size().
operator()()
const LabeledSequence & cbrc::SimilaritySearchableSequences::operator() (const size_t & index) const inline
Definition at line 71 of file SimilaritySearchableSequences.hh.
resSubScore()
const AminoScore & cbrc::SimilaritySearchableSequences::resSubScore () const inline
Definition at line 79 of file SimilaritySearchableSequences.hh.
Referenced by bestMatch().
seqName()
const std::string & cbrc::SimilaritySearchableSequences::seqName (const indexScorePairT & indexScorePair) const inline
Definition at line 75 of file SimilaritySearchableSequences.hh.
size()
size_t cbrc::SimilaritySearchableSequences::size () const inline
Definition at line 73 of file SimilaritySearchableSequences.hh.
References cbrc::FLEArray< T >::size().
withinHammingDistance()
std::vector< size_t > cbrc::SimilaritySearchableSequences::withinHammingDistance (const LabeledSequence & query, const double & threshold) const
Definition at line 30 of file SimilaritySearchableSequences.cc.
References cbrc::HammingDistanceComputer::computeBounded(), and cbrc::FLEArray< T >::size().
wouldSkipAll()
bool cbrc::SimilaritySearchableSequences::wouldSkipAll (const LabeledSequence & query, const LabeledSequencePairPredicate & skipPairPredicate) const
Definition at line 48 of file SimilaritySearchableSequences.cc.
References cbrc::FLEArray< T >::FLEArray().
Referenced by bestMatch().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/align/SimilaritySearchableSequences.hh
ematch_src/utils/sequence/align/SimilaritySearchableSequences.cc