NGSFeatures: cbrc::TransfacTextLabelInfo Class Reference
cbrc::TransfacTextLabelInfo Class Reference
#include <TransfacTextLabelInfo.hh>
Public Member Functions
TransfacTextLabelInfo ()
bool isVersion (const TransfacTextLine &transfacLine) const
bool isAccession (const TransfacTextLine &transfacLine) const
bool isBindingFactor (const TransfacTextLine &transfacLine) const
bool isBlankLine (const TransfacTextLine &transfacLine) const
bool isDescription (const TransfacTextLine &transfacLine) const
bool isFreqMatrix (const TransfacTextLine &transfacLine) const
bool isFreqMatrixBody (const TransfacTextLine &transfacLine) const
bool isName (const TransfacTextLine &transfacLine) const
bool isRecordSeparator (const TransfacTextLine &transfacLine) const
Detailed Description
Definition at line 21 of file TransfacTextLabelInfo.hh.
Constructor & Destructor Documentation
TransfacTextLabelInfo()
cbrc::TransfacTextLabelInfo::TransfacTextLabelInfo () inline
Definition at line 23 of file TransfacTextLabelInfo.hh.
Member Function Documentation
isAccession()
bool cbrc::TransfacTextLabelInfo::isAccession (const TransfacTextLine & transfacLine) const inline
Definition at line 37 of file TransfacTextLabelInfo.hh.
References cbrc::TransfacTextLine::label().
Referenced by cbrc::TransfacReader::readRecord().
isBindingFactor()
bool cbrc::TransfacTextLabelInfo::isBindingFactor (const TransfacTextLine & transfacLine) const inline
Definition at line 40 of file TransfacTextLabelInfo.hh.
References cbrc::TransfacTextLine::label().
Referenced by cbrc::TransfacReader::readRecord().
isBlankLine()
bool cbrc::TransfacTextLabelInfo::isBlankLine (const TransfacTextLine & transfacLine) const inline
Definition at line 43 of file TransfacTextLabelInfo.hh.
References cbrc::TransfacTextLine::label().
Referenced by cbrc::TransfacReader::nextNonBlankLine().
isDescription()
bool cbrc::TransfacTextLabelInfo::isDescription (const TransfacTextLine & transfacLine) const inline
Definition at line 46 of file TransfacTextLabelInfo.hh.
References cbrc::TransfacTextLine::label().
Referenced by cbrc::TransfacReader::readRecord().
isFreqMatrix()
bool cbrc::TransfacTextLabelInfo::isFreqMatrix (const TransfacTextLine & transfacLine) const inline
Definition at line 49 of file TransfacTextLabelInfo.hh.
References cbrc::TransfacTextLine::label().
Referenced by cbrc::TransfacReader::readRecord().
isFreqMatrixBody()
bool cbrc::TransfacTextLabelInfo::isFreqMatrixBody (const TransfacTextLine & transfacLine) const inline
Definition at line 52 of file TransfacTextLabelInfo.hh.
References cbrc::TransfacTextLine::label(), and cbrc::perlish::looksLikeUnsignedInt().
isName()
bool cbrc::TransfacTextLabelInfo::isName (const TransfacTextLine & transfacLine) const inline
Definition at line 55 of file TransfacTextLabelInfo.hh.
References cbrc::TransfacTextLine::label().
Referenced by cbrc::TransfacReader::readRecord().
isRecordSeparator()
bool cbrc::TransfacTextLabelInfo::isRecordSeparator (const TransfacTextLine & transfacLine) const inline
Definition at line 58 of file TransfacTextLabelInfo.hh.
References cbrc::TransfacTextLine::label().
Referenced by cbrc::TransfacReader::readRecord(), and cbrc::TransfacReader::TransfacReader().
isVersion()
bool cbrc::TransfacTextLabelInfo::isVersion (const TransfacTextLine & transfacLine) const inline
Definition at line 34 of file TransfacTextLabelInfo.hh.
References cbrc::TransfacTextLine::label().
Referenced by cbrc::TransfacReader::TransfacReader().
The documentation for this class was generated from the following file:
ematch_src/utils/sequence/readers/transfac/TransfacTextLabelInfo.hh