NGSFeatures: cbrc::KnapsackObjectVector Class Reference
cbrc::KnapsackObjectVector Class Reference
#include <KnapsackObjectVector.hh>
Public Types
typedef KnapsackObject::idT idT
typedef KnapsackObject::weightT weightT
Public Member Functions
KnapsackObjectVector ()
KnapsackObjectVector (const KnapsackObjectVector &other)
KnapsackObjectVector (const std::vector< KnapsackObject > &v)
KnapsackObjectVector (const std::vector< double > &logProbVec)
KnapsackObjectVector (std::istream &iStream)
std::vector< KnapsackObject >::iterator begin ()
std::vector< KnapsackObject >::iterator end ()
const std::vector< KnapsackObject > & v () const
const KnapsackObject & operator() (const size_t &i) const
const size_t size () const
void readText_idsFrom0 (std::istream &iStream)
void makeFromWeightVector (const std::vector< double > &logProbVec)
Detailed Description
Definition at line 22 of file KnapsackObjectVector.hh.
Member Typedef Documentation
idT
typedef KnapsackObject::idT cbrc::KnapsackObjectVector::idT
Definition at line 27 of file KnapsackObjectVector.hh.
weightT
typedef KnapsackObject::weightT cbrc::KnapsackObjectVector::weightT
Definition at line 28 of file KnapsackObjectVector.hh.
Constructor & Destructor Documentation
KnapsackObjectVector() [1/5]
cbrc::KnapsackObjectVector::KnapsackObjectVector () inline
Definition at line 33 of file KnapsackObjectVector.hh.
KnapsackObjectVector() [2/5]
cbrc::KnapsackObjectVector::KnapsackObjectVector (const KnapsackObjectVector & other) inline
Definition at line 35 of file KnapsackObjectVector.hh.
KnapsackObjectVector() [3/5]
cbrc::KnapsackObjectVector::KnapsackObjectVector (const std::vector< KnapsackObject > & v) inline
Definition at line 39 of file KnapsackObjectVector.hh.
KnapsackObjectVector() [4/5]
cbrc::KnapsackObjectVector::KnapsackObjectVector (const std::vector< double > & logProbVec) inline
Definition at line 44 of file KnapsackObjectVector.hh.
References makeFromWeightVector().
KnapsackObjectVector() [5/5]
cbrc::KnapsackObjectVector::KnapsackObjectVector (std::istream & iStream) inline
Definition at line 50 of file KnapsackObjectVector.hh.
References readText_idsFrom0().
Member Function Documentation
begin()
std::vector< KnapsackObject >::iterator cbrc::KnapsackObjectVector::begin () inline
Definition at line 58 of file KnapsackObjectVector.hh.
Referenced by cbrc::KnapsackEnumerator::computeCombinations().
end()
std::vector< KnapsackObject >::iterator cbrc::KnapsackObjectVector::end () inline
Definition at line 59 of file KnapsackObjectVector.hh.
References end().
Referenced by cbrc::KnapsackEnumerator::computeCombinations(), and end().
makeFromWeightVector()
void cbrc::KnapsackObjectVector::makeFromWeightVector (const std::vector< double > & logProbVec)
Definition at line 30 of file KnapsackObjectVector.cc.
References cbrc::FLEArray< T >::size().
Referenced by KnapsackObjectVector().
operator()()
const KnapsackObject & cbrc::KnapsackObjectVector::operator() (const size_t & i) const inline
Definition at line 63 of file KnapsackObjectVector.hh.
References size(), and v().
readText_idsFrom0()
void cbrc::KnapsackObjectVector::readText_idsFrom0 (std::istream & iStream)
Definition at line 15 of file KnapsackObjectVector.cc.
References cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLine(), and cbrc::perlish::split().
Referenced by KnapsackObjectVector().
size()
const size_t cbrc::KnapsackObjectVector::size () const inline
Definition at line 68 of file KnapsackObjectVector.hh.
References cbrc::FLEArray< T >::size(), and v().
Referenced by operator()().
v()
const std::vector< KnapsackObject > & cbrc::KnapsackObjectVector::v () const inline
Definition at line 61 of file KnapsackObjectVector.hh.
Referenced by operator()(), and size().
The documentation for this class was generated from the following files:
knapsack_src/KnapsackObjectVector.hh
knapsack_src/KnapsackObjectVector.cc