NGSFeatures: cbrc::TagSet Class Reference
cbrc::TagSet Class Reference
#include <TagSet.hh>
Public Types
enum fileFormatT { binary , text }
typedef sigma4bitPackingUtils::unpackedVecT unpackedSeqT
Public Member Functions
TagSet (std::istream &iStream, fileFormatT fileFormat=text)
~TagSet ()
const size_t & size () const
const size_t & totalSize () const
size_t size (const size_t &i) const
size_t sizeInBytes (const size_t &i) const
bool has (const std::string &asciiSeq)
bool has (const unpackedSeqT &unpackedSeq) const
size_t operator() (const std::string &asciiSeq) const
size_t operator() (const unpackedSeqT &unpackedSeq) const
byte operator() (const size_t &seqIdx, const size_t &charIdx) const
size_t getSerialNumberOrDie (const std::string &asciiSeq) const
std::string toString (const size_t &i) const
std::string toString (const unpackedSeqT &unpackedSeq) const
unpackedSeqT toUnpackedSeq (const std::string &tagSeq) const
void readFromBinaryStream (std::istream &iStream)
void readFromTextStream (std::istream &iStream)
Static Public Member Functions
static const ResidueIndexMap & residueIndexMap ()
Detailed Description
Definition at line 25 of file TagSet.hh.
Member Typedef Documentation
unpackedSeqT
typedef sigma4bitPackingUtils::unpackedVecT cbrc::TagSet::unpackedSeqT
Definition at line 31 of file TagSet.hh.
Member Enumeration Documentation
fileFormatT
enum cbrc::TagSet::fileFormatT
Enumerator
binary
text
Definition at line 30 of file TagSet.hh.
Constructor & Destructor Documentation
TagSet()
cbrc::TagSet::TagSet (std::istream & iStream, fileFormatT fileFormat = text) inline
Definition at line 35 of file TagSet.hh.
References readFromBinaryStream(), readFromTextStream(), and text.
~TagSet()
cbrc::TagSet::~TagSet () inline
Definition at line 40 of file TagSet.hh.
Member Function Documentation
getSerialNumberOrDie()
size_t cbrc::TagSet::getSerialNumberOrDie (const std::string & asciiSeq) const inline
Definition at line 94 of file TagSet.hh.
References GDB_ASSERTF, has(), and toUnpackedSeq().
Referenced by cbrc::RecountTagCounts::RecountTagCounts().
has() [1/2]
bool cbrc::TagSet::has (const std::string & asciiSeq) inline
Definition at line 62 of file TagSet.hh.
References has(), and toUnpackedSeq().
Referenced by getSerialNumberOrDie(), and has().
has() [2/2]
bool cbrc::TagSet::has (const unpackedSeqT & unpackedSeq) const inline
Definition at line 66 of file TagSet.hh.
operator()() [1/3]
byte cbrc::TagSet::operator() (const size_t & seqIdx, const size_t & charIdx) const inline
Definition at line 86 of file TagSet.hh.
References cbrc::sigma4bitPackingUtils::assignNthUnpacked().
operator()() [2/3]
size_t cbrc::TagSet::operator() (const std::string & asciiSeq) const inline
Definition at line 74 of file TagSet.hh.
References toUnpackedSeq().
operator()() [3/3]
size_t cbrc::TagSet::operator() (const unpackedSeqT & unpackedSeq) const inline
Definition at line 81 of file TagSet.hh.
readFromBinaryStream()
void cbrc::TagSet::readFromBinaryStream (std::istream & iStream) inline
Definition at line 127 of file TagSet.hh.
Referenced by TagSet().
readFromTextStream()
void cbrc::TagSet::readFromTextStream (std::istream & iStream)
Definition at line 64 of file TagSet.cc.
References ASSERTF, DO_OR_DIEF, cbrc::perlish::fromString(), cbrc::sigma4bitPackingUtils::pack(), residueIndexMap(), size(), cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLine(), cbrc::perlish::split(), and totalSize().
Referenced by TagSet().
residueIndexMap()
static const ResidueIndexMap & cbrc::TagSet::residueIndexMap () inline static
Definition at line 104 of file TagSet.hh.
Referenced by readFromTextStream(), toString(), and toUnpackedSeq().
size() [1/2]
const size_t & cbrc::TagSet::size () const inline
Definition at line 48 of file TagSet.hh.
Referenced by readFromTextStream(), sizeInBytes(), and toString().
size() [2/2]
size_t cbrc::TagSet::size (const size_t & i) const inline
Definition at line 53 of file TagSet.hh.
sizeInBytes()
size_t cbrc::TagSet::sizeInBytes (const size_t & i) const inline
Definition at line 57 of file TagSet.hh.
References cbrc::sigma4bitPackingUtils::numBytesNeededToStore(), and size().
toString() [1/2]
std::string cbrc::TagSet::toString (const size_t & i) const inline
Definition at line 112 of file TagSet.hh.
References size(), toString(), and cbrc::sigma4bitPackingUtils::toUnpacked().
Referenced by cbrc::dumpNeighborList(), cbrc::observedMeanStdev_fromTrueCounts(), cbrc::RecountTagCounts::print(), and toString().
toString() [2/2]
std::string cbrc::TagSet::toString (const unpackedSeqT & unpackedSeq) const inline
Definition at line 116 of file TagSet.hh.
References residueIndexMap().
totalSize()
const size_t & cbrc::TagSet::totalSize () const inline
Definition at line 50 of file TagSet.hh.
Referenced by readFromTextStream().
toUnpackedSeq()
unpackedSeqT cbrc::TagSet::toUnpackedSeq (const std::string & tagSeq) const inline
Definition at line 120 of file TagSet.hh.
References residueIndexMap().
Referenced by getSerialNumberOrDie(), has(), and operator()().
The documentation for this class was generated from the following files:
ematch_src/TagSet.hh
ematch_src/TagSet.cc