NGSFeatures: cbrc::RecountComputerForGraphOnDisk Class Reference
cbrc::RecountComputerForGraphOnDisk Class Reference
#include <RecountComputerForGraphOnDisk.hh>
Public Member Functions
RecountComputerForGraphOnDisk (RecountNeighborProbGraphOnDisk &neighborProbGraph)
const RecountNeighborProbGraphOnDisk & neighborProbGraph () const
void meanCountsFromTrue (RecountTagCounts &observedCounts, const RecountTagCounts &trueCounts) const
void varianceCountsFromTrue (RecountTagCounts &variances, const RecountTagCounts &trueCounts) const
RecountComputerForGraphOnDisk (RecountNeighborProbGraphOnDisk &neighborProbGraph)
const RecountNeighborProbGraphOnDisk & neighborProbGraph () const
void meanCountsFromTrue (RecountTagCounts &observedCounts, const RecountTagCounts &trueCounts)
void varianceCountsFromTrue (RecountTagCounts &variances, const RecountTagCounts &trueCounts)
Detailed Description
Definition at line 23 of file RecountComputerForGraphOnDisk.hh.
Constructor & Destructor Documentation
RecountComputerForGraphOnDisk() [1/2]
cbrc::RecountComputerForGraphOnDisk::RecountComputerForGraphOnDisk (RecountNeighborProbGraphOnDisk & neighborProbGraph) inline
Definition at line 26 of file RecountComputerForGraphOnDisk.hh.
RecountComputerForGraphOnDisk() [2/2]
cbrc::RecountComputerForGraphOnDisk::RecountComputerForGraphOnDisk (RecountNeighborProbGraphOnDisk & neighborProbGraph) inline
Definition at line 29 of file RecountComputerForGraphOnDisk_SortedTagSet.hh.
Member Function Documentation
meanCountsFromTrue() [1/2]
void cbrc::RecountComputerForGraphOnDisk::meanCountsFromTrue (RecountTagCounts & observedCounts, const RecountTagCounts & trueCounts)
Definition at line 17 of file RecountComputerForGraphOnDisk_SortedTagSet.cc.
References GDB_ASSERTF, cbrc::RecountNeighborList::id(), neighborProbGraph(), cbrc::RecountNeighborProbGraphOnDisk::readFirstNode(), cbrc::RecountNeighborProbGraphOnDisk::readNextNode(), cbrc::RecountTagCounts::size(), cbrc::FLEArray< T >::size(), and cbrc::RecountTagCounts::zero().
meanCountsFromTrue() [2/2]
void cbrc::RecountComputerForGraphOnDisk::meanCountsFromTrue (RecountTagCounts & observedCounts, const RecountTagCounts & trueCounts) const
Definition at line 17 of file RecountComputerForGraphOnDisk.cc.
References GDB_ASSERTF, cbrc::RecountNeighborList::id(), neighborProbGraph(), cbrc::RecountNeighborProbGraphOnDisk::readFirstNode(), cbrc::RecountNeighborProbGraphOnDisk::readNextNode(), cbrc::RecountTagCounts::size(), cbrc::FLEArray< T >::size(), and cbrc::RecountTagCounts::zero().
neighborProbGraph() [1/2]
const RecountNeighborProbGraphOnDisk & cbrc::RecountComputerForGraphOnDisk::neighborProbGraph () const inline
Definition at line 31 of file RecountComputerForGraphOnDisk.hh.
Referenced by meanCountsFromTrue(), meanCountsFromTrue(), varianceCountsFromTrue(), and varianceCountsFromTrue().
neighborProbGraph() [2/2]
const RecountNeighborProbGraphOnDisk & cbrc::RecountComputerForGraphOnDisk::neighborProbGraph () const inline
Definition at line 35 of file RecountComputerForGraphOnDisk_SortedTagSet.hh.
varianceCountsFromTrue() [1/2]
void cbrc::RecountComputerForGraphOnDisk::varianceCountsFromTrue (RecountTagCounts & variances, const RecountTagCounts & trueCounts)
Definition at line 49 of file RecountComputerForGraphOnDisk_SortedTagSet.cc.
References GDB_ASSERTF, cbrc::RecountNeighborList::id(), neighborProbGraph(), cbrc::RecountNeighborProbGraphOnDisk::readFirstNode(), cbrc::RecountNeighborProbGraphOnDisk::readNextNode(), cbrc::FLEArray< T >::size(), and cbrc::FLEArray< T >::zero().
varianceCountsFromTrue() [2/2]
void cbrc::RecountComputerForGraphOnDisk::varianceCountsFromTrue (RecountTagCounts & variances, const RecountTagCounts & trueCounts) const
Definition at line 49 of file RecountComputerForGraphOnDisk.cc.
References GDB_ASSERTF, cbrc::RecountNeighborList::id(), neighborProbGraph(), cbrc::RecountNeighborProbGraphOnDisk::readFirstNode(), cbrc::RecountNeighborProbGraphOnDisk::readNextNode(), cbrc::FLEArray< T >::size(), and cbrc::FLEArray< T >::zero().
The documentation for this class was generated from the following files:
ematch_src/RecountComputerForGraphOnDisk.hh
ematch_src/RecountComputerForGraphOnDisk_SortedTagSet.hh
ematch_src/RecountComputerForGraphOnDisk.cc
ematch_src/RecountComputerForGraphOnDisk_SortedTagSet.cc