NGSFeatures: cbrc::MallocArray< T > Class Template Reference
cbrc::MallocArray< T > Class Template Reference
#include <MallocArray.hh>
Public Types
typedef T * iterator
typedef const T * const_iterator
Public Member Functions
MallocArray ()
MallocArray (const size_t sz)
MallocArray (size_t sz, T fillVal)
MallocArray (size_t sz, T *b)
MallocArray (const std::vector< T > &v)
MallocArray (T v[], unsigned int numElems)
MallocArray (const MallocArray< T > &fla)
MallocArray (std::istream &is)
virtual ~MallocArray ()
operator std::vector< T > () const
size_t bsize ()
void write (std::ostream &os)
void read (std::istream &is)
void setSize (size_t sz)
void resize (size_t sz)
MallocArray operator= (const MallocArray &fla)
MallocArray operator= (std::vector< T > v)
void assign (const typename MallocArray< T >::const_iterator &begin, const typename MallocArray< T >::const_iterator &end)
void assign (const typename std::vector< T >::const_iterator &begin, const typename std::vector< T >::const_iterator &end)
void zero ()
void fill (T fillVal)
void fillWithByte (int fillByte)
bool validIndex (size_t index) const
bool operator== (const MallocArray &fla) const
virtual T & operator[] (const size_t index) const
virtual T & operator[] (int index) const
void copyTo (const T &elem, size_t index)
size_t size () const
bool empty () const
iterator begin () const
iterator end () const
Protected Attributes
size_t s
T * a
Detailed Description
template<typename T>
class cbrc::MallocArray< T >
Definition at line 77 of file MallocArray.hh.
Member Typedef Documentation
const_iterator
template<typename T > typedef const T* cbrc::MallocArray< T >::const_iterator
Definition at line 80 of file MallocArray.hh.
iterator
template<typename T > typedef T* cbrc::MallocArray< T >::iterator
Definition at line 79 of file MallocArray.hh.
Constructor & Destructor Documentation
MallocArray() [1/8]
template<typename T > cbrc::MallocArray< T >::MallocArray () inline
Definition at line 82 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, and cbrc::MallocArray< T >::s.
MallocArray() [2/8]
template<typename T > cbrc::MallocArray< T >::MallocArray (const size_t sz) inline explicit
Definition at line 83 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, and cbrc::MallocArray< T >::size().
MallocArray() [3/8]
template<typename T > cbrc::MallocArray< T >::MallocArray (size_t sz, T fillVal) inline
Definition at line 86 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, cbrc::MallocArray< T >::fill(), and cbrc::MallocArray< T >::size().
MallocArray() [4/8]
template<typename T > cbrc::MallocArray< T >::MallocArray (size_t sz, T * b) inline
Definition at line 90 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, and cbrc::MallocArray< T >::size().
MallocArray() [5/8]
template<typename T > cbrc::MallocArray< T >::MallocArray (const std::vector< T > & v) inline
Definition at line 94 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, cbrc::MallocArray< T >::s, cbrc::FLEArray< T >::size(), and cbrc::MallocArray< T >::size().
MallocArray() [6/8]
template<typename T > cbrc::MallocArray< T >::MallocArray (T v[], unsigned int numElems) inline
Definition at line 99 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, cbrc::MallocArray< T >::bsize(), and cbrc::MallocArray< T >::size().
MallocArray() [7/8]
template<typename T > cbrc::MallocArray< T >::MallocArray (const MallocArray< T > & fla) inline
Definition at line 103 of file MallocArray.hh.
References cbrc::MallocArray< T >::assign(), cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
MallocArray() [8/8]
template<typename T > cbrc::MallocArray< T >::MallocArray (std::istream & is) inline
Definition at line 106 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, cbrc::MallocArray< T >::bsize(), cbrc::MallocArray< T >::s, and cbrc::MallocArray< T >::size().
~MallocArray()
template<typename T > virtual cbrc::MallocArray< T >::~MallocArray () inline virtual
Definition at line 111 of file MallocArray.hh.
References cbrc::MallocArray< T >::a.
Member Function Documentation
assign() [1/2]
template<typename T > void cbrc::MallocArray< T >::assign (const typename MallocArray< T >::const_iterator & begin, const typename MallocArray< T >::const_iterator & end) inline
Definition at line 181 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, cbrc::MallocArray< T >::begin(), cbrc::MallocArray< T >::end(), and cbrc::MallocArray< T >::resize().
Referenced by cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::operator=(), and cbrc::MallocArray< T >::operator=().
assign() [2/2]
template<typename T > void cbrc::MallocArray< T >::assign (const typename std::vector< T >::const_iterator & begin, const typename std::vector< T >::const_iterator & end) inline
Definition at line 188 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, cbrc::MallocArray< T >::begin(), cbrc::MallocArray< T >::end(), and cbrc::MallocArray< T >::resize().
begin()
template<typename T > iterator cbrc::MallocArray< T >::begin () const inline
Definition at line 233 of file MallocArray.hh.
References cbrc::MallocArray< T >::a.
Referenced by cbrc::MallocArray< T >::assign(), cbrc::MallocArray< T >::assign(), and cbrc::MallocArray< T >::operator std::vector< T >().
bsize()
template<typename T > size_t cbrc::MallocArray< T >::bsize () inline
Definition at line 117 of file MallocArray.hh.
References cbrc::MallocArray< T >::size().
Referenced by cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::read(), and cbrc::MallocArray< T >::write().
copyTo()
template<typename T > void cbrc::MallocArray< T >::copyTo (const T & elem, size_t index) inline
Definition at line 227 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, and cbrc::MallocArray< T >::validIndex().
empty()
template<typename T > bool cbrc::MallocArray< T >::empty () const inline
Definition at line 232 of file MallocArray.hh.
References cbrc::MallocArray< T >::s.
end()
template<typename T > iterator cbrc::MallocArray< T >::end () const inline
Definition at line 234 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, and cbrc::MallocArray< T >::s.
Referenced by cbrc::MallocArray< T >::assign(), cbrc::MallocArray< T >::assign(), and cbrc::MallocArray< T >::operator std::vector< T >().
fill()
template<typename T > void cbrc::MallocArray< T >::fill (T fillVal) inline
Definition at line 198 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, and cbrc::MallocArray< T >::s.
Referenced by cbrc::MallocArray< T >::MallocArray(), and cbrc::MallocArray< T >::zero().
fillWithByte()
template<typename T > void cbrc::MallocArray< T >::fillWithByte (int fillByte) inline
Definition at line 201 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, and cbrc::MallocArray< T >::s.
operator std::vector< T >()
template<typename T > cbrc::MallocArray< T >::operator std::vector< T > () const inline
Definition at line 112 of file MallocArray.hh.
References cbrc::MallocArray< T >::begin(), cbrc::MallocArray< T >::end(), and cbrc::MallocArray< T >::size().
operator=() [1/2]
template<typename T > MallocArray cbrc::MallocArray< T >::operator= (const MallocArray< T > & fla) inline
Definition at line 146 of file MallocArray.hh.
References cbrc::FLEArray< T >::a, cbrc::MallocArray< T >::a, cbrc::MallocArray< T >::assign(), cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), cbrc::MallocArray< T >::s, cbrc::FLEArray< T >::size(), and cbrc::MallocArray< T >::size().
operator=() [2/2]
template<typename T > MallocArray cbrc::MallocArray< T >::operator= (std::vector< T > v) inline
Definition at line 177 of file MallocArray.hh.
References cbrc::MallocArray< T >::assign().
operator==()
template<typename T > bool cbrc::MallocArray< T >::operator== (const MallocArray< T > & fla) const inline
Definition at line 214 of file MallocArray.hh.
References cbrc::FLEArray< T >::a, cbrc::MallocArray< T >::a, cbrc::FLEArray< T >::size(), and cbrc::MallocArray< T >::size().
operator[]() [1/2]
template<typename T > virtual T & cbrc::MallocArray< T >::operator[] (const size_t index) const inline virtual
Reimplemented in cbrc::MallocArrayFast< T >, and cbrc::MallocNumArrayFast< T >.
Definition at line 218 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, and cbrc::MallocArray< T >::validIndex().
operator[]() [2/2]
template<typename T > virtual T & cbrc::MallocArray< T >::operator[] (int index) const inline virtual
Definition at line 222 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, cbrc::MallocArray< T >::size(), and cbrc::MallocArray< T >::validIndex().
read()
template<typename T > void cbrc::MallocArray< T >::read (std::istream & is) inline
Definition at line 122 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, cbrc::MallocArray< T >::bsize(), cbrc::FLEArray< T >::read(), cbrc::MallocArray< T >::s, and cbrc::MallocArray< T >::size().
resize()
template<typename T > void cbrc::MallocArray< T >::resize (size_t sz) inline
Definition at line 137 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, cbrc::MallocArray< T >::s, and cbrc::MallocArray< T >::setSize().
Referenced by cbrc::MallocArray< T >::assign(), and cbrc::MallocArray< T >::assign().
setSize()
template<typename T > void cbrc::MallocArray< T >::setSize (size_t sz) inline
Definition at line 132 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, cbrc::MallocArray< T >::s, and cbrc::MallocArray< T >::size().
Referenced by cbrc::MallocArray< T >::resize().
size()
template<typename T > size_t cbrc::MallocArray< T >::size () const inline
Definition at line 231 of file MallocArray.hh.
References cbrc::MallocArray< T >::s.
Referenced by cbrc::MallocArray< T >::bsize(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocNumArray< T >::max(), cbrc::MallocNumArray< T >::maxIndex(), cbrc::MallocArray< T >::operator std::vector< T >(), cbrc::MallocNumArray< T >::operator*=(), cbrc::MallocNumArray< T >::operator+=(), cbrc::MallocNumArray< T >::operator/=(), cbrc::MallocArray< T >::operator=(), cbrc::MallocNumArray< T >::operator=(), cbrc::MallocArray< T >::operator==(), cbrc::MallocArray< T >::operator[](), cbrc::MallocArray< T >::read(), cbrc::MallocArray< T >::setSize(), cbrc::MallocNumArray< T >::squareElements(), and cbrc::MallocNumArray< T >::sum().
validIndex()
template<typename T > bool cbrc::MallocArray< T >::validIndex (size_t index) const inline
Definition at line 204 of file MallocArray.hh.
References cbrc::MallocArray< T >::s.
Referenced by cbrc::MallocArray< T >::copyTo(), cbrc::MallocArray< T >::operator[](), cbrc::MallocArrayFast< T >::operator[](), cbrc::MallocNumArrayFast< T >::operator[](), and cbrc::MallocArray< T >::operator[]().
write()
template<typename T > void cbrc::MallocArray< T >::write (std::ostream & os) inline
Definition at line 118 of file MallocArray.hh.
References cbrc::MallocArray< T >::a, cbrc::MallocArray< T >::bsize(), cbrc::MallocArray< T >::s, and cbrc::FLEArray< T >::write().
zero()
template<typename T > void cbrc::MallocArray< T >::zero () inline
Definition at line 197 of file MallocArray.hh.
References cbrc::MallocArray< T >::fill().
Member Data Documentation
a
template<typename T > T* cbrc::MallocArray< T >::a protected
Definition at line 239 of file MallocArray.hh.
Referenced by cbrc::MallocArray< T >::assign(), cbrc::MallocArray< T >::assign(), cbrc::MallocArray< T >::begin(), cbrc::MallocArray< T >::copyTo(), cbrc::MallocArray< T >::end(), cbrc::MallocArray< T >::fill(), cbrc::MallocArray< T >::fillWithByte(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocNumArray< T >::max(), cbrc::MallocNumArray< T >::maxIndex(), cbrc::MallocNumArray< T >::operator*=(), cbrc::MallocNumArray< T >::operator+=(), cbrc::MallocNumArray< T >::operator/=(), cbrc::MallocArray< T >::operator=(), cbrc::MallocNumArray< T >::operator=(), cbrc::MallocArray< T >::operator==(), cbrc::MallocArray< T >::operator[](), cbrc::MallocArrayFast< T >::operator[](), cbrc::MallocNumArrayFast< T >::operator[](), cbrc::MallocArray< T >::operator[](), cbrc::MallocArray< T >::read(), cbrc::MallocArray< T >::resize(), cbrc::MallocArray< T >::setSize(), cbrc::MallocNumArray< T >::squareElements(), cbrc::MallocNumArray< T >::sum(), cbrc::MallocArray< T >::write(), and cbrc::MallocArray< T >::~MallocArray().
s
template<typename T > size_t cbrc::MallocArray< T >::s protected
Definition at line 238 of file MallocArray.hh.
Referenced by cbrc::MallocArray< T >::empty(), cbrc::MallocArray< T >::end(), cbrc::MallocArray< T >::fill(), cbrc::MallocArray< T >::fillWithByte(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::MallocArray(), cbrc::MallocArray< T >::operator=(), cbrc::MallocNumArray< T >::operator=(), cbrc::MallocArray< T >::read(), cbrc::MallocArray< T >::resize(), cbrc::MallocArray< T >::setSize(), cbrc::MallocArray< T >::size(), cbrc::MallocArray< T >::validIndex(), and cbrc::MallocArray< T >::write().
The documentation for this class was generated from the following file:
ematch_src/utils/FLArray/MallocArray.hh