NGSFeatures: cbrc::StringKeyAndValue< ValT > Class Template Reference
cbrc::StringKeyAndValue< ValT > Class Template Reference
#include <StringKeyHashtable.hh>
Public Member Functions
StringKeyAndValue (const std::string &key, const ValT value)
StringKeyAndValue (const StringKeyAndValue< ValT > &snh)
void operator= (const ValT &val)
operator ValT & ()
size_t hashVal () const
bool keyEquals (const StringKeyAndValue< ValT > &snh) const
std::string key () const
ValT value () const
void setValue (const ValT &newVal)
Friends
class StringKeyHashtable< ValT >
void testStringKeyAndValue ()
Detailed Description
template<typename ValT>
class cbrc::StringKeyAndValue< ValT >
Definition at line 33 of file StringKeyHashtable.hh.
Constructor & Destructor Documentation
StringKeyAndValue() [1/2]
template<typename ValT > cbrc::StringKeyAndValue< ValT >::StringKeyAndValue (const std::string & key, const ValT value) inline
Definition at line 36 of file StringKeyHashtable.hh.
References cbrc::StringKeyAndValue< ValT >::key(), and cbrc::StringKeyAndValue< ValT >::value().
StringKeyAndValue() [2/2]
template<typename ValT > cbrc::StringKeyAndValue< ValT >::StringKeyAndValue (const StringKeyAndValue< ValT > & snh) inline
Definition at line 37 of file StringKeyHashtable.hh.
Member Function Documentation
hashVal()
template<typename ValT > size_t cbrc::StringKeyAndValue< ValT >::hashVal () const inline
Definition at line 40 of file StringKeyHashtable.hh.
References stringHashValue().
key()
template<typename ValT > std::string cbrc::StringKeyAndValue< ValT >::key () const inline
Definition at line 42 of file StringKeyHashtable.hh.
Referenced by cbrc::StringKeyAndValue< ValT >::StringKeyAndValue().
keyEquals()
template<typename ValT > bool cbrc::StringKeyAndValue< ValT >::keyEquals (const StringKeyAndValue< ValT > & snh) const inline
Definition at line 41 of file StringKeyHashtable.hh.
operator ValT &()
template<typename ValT > cbrc::StringKeyAndValue< ValT >::operator ValT & () inline
Definition at line 39 of file StringKeyHashtable.hh.
operator=()
template<typename ValT > void cbrc::StringKeyAndValue< ValT >::operator= (const ValT & val) inline
Definition at line 38 of file StringKeyHashtable.hh.
setValue()
template<typename ValT > void cbrc::StringKeyAndValue< ValT >::setValue (const ValT & newVal) inline
Definition at line 44 of file StringKeyHashtable.hh.
value()
template<typename ValT > ValT cbrc::StringKeyAndValue< ValT >::value () const inline
Definition at line 43 of file StringKeyHashtable.hh.
Referenced by cbrc::StringKeyAndValue< ValT >::StringKeyAndValue().
Friends And Related Symbol Documentation
StringKeyHashtable< ValT >
template<typename ValT > friend class StringKeyHashtable< ValT > friend
Definition at line 44 of file StringKeyHashtable.hh.
testStringKeyAndValue
template<typename ValT > void testStringKeyAndValue () friend
The documentation for this class was generated from the following file:
ematch_src/utils/ChainHashtable/StringKeyHashtable.hh