NGSFeatures: cbrc::FastaWriter Class Reference
cbrc::FastaWriter Class Reference
#include <FastaWriter.hh>
Public Member Functions
FastaWriter ()
void print (const LabeledAsciiSeq &labeledAsciiSeq, std::ostream &os=std::cout)
const size_t & lineLengthForPrintingSeq () const
const bool & addAsteriskAtEndOfSeq () const
const std::string & stringBeforeName () const
const std::string delimiter () const
Static Public Member Functions
static const size_t & defaultLineLengthForPrintingSeq ()
static const bool & defaultAddAsteriskAtEndOfSeq ()
static const std::string & defaultStringBeforeName ()
static const std::string & defaultDelimiter ()
Detailed Description
Definition at line 19 of file FastaWriter.hh.
Constructor & Destructor Documentation
FastaWriter()
cbrc::FastaWriter::FastaWriter () inline
Definition at line 21 of file FastaWriter.hh.
Member Function Documentation
addAsteriskAtEndOfSeq()
const bool & cbrc::FastaWriter::addAsteriskAtEndOfSeq () const inline
Definition at line 61 of file FastaWriter.hh.
defaultAddAsteriskAtEndOfSeq()
static const bool & cbrc::FastaWriter::defaultAddAsteriskAtEndOfSeq () inline static
Definition at line 40 of file FastaWriter.hh.
defaultDelimiter()
static const std::string & cbrc::FastaWriter::defaultDelimiter () inline static
Definition at line 50 of file FastaWriter.hh.
defaultLineLengthForPrintingSeq()
static const size_t & cbrc::FastaWriter::defaultLineLengthForPrintingSeq () inline static
Definition at line 35 of file FastaWriter.hh.
defaultStringBeforeName()
static const std::string & cbrc::FastaWriter::defaultStringBeforeName () inline static
Definition at line 45 of file FastaWriter.hh.
delimiter()
const std::string cbrc::FastaWriter::delimiter () const inline
Definition at line 69 of file FastaWriter.hh.
Referenced by print().
lineLengthForPrintingSeq()
const size_t & cbrc::FastaWriter::lineLengthForPrintingSeq () const inline
Definition at line 57 of file FastaWriter.hh.
Referenced by print().
print()
void cbrc::FastaWriter::print (const LabeledAsciiSeq & labeledAsciiSeq, std::ostream & os = std::cout)
Definition at line 13 of file FastaWriter.cc.
References delimiter(), lineLengthForPrintingSeq(), cbrc::fastafmt::recordStartMarker(), cbrc::FLEArray< T >::size(), and stringBeforeName().
stringBeforeName()
const std::string & cbrc::FastaWriter::stringBeforeName () const inline
Definition at line 65 of file FastaWriter.hh.
Referenced by print().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/readers/fasta/FastaWriter.hh
ematch_src/utils/sequence/readers/fasta/FastaWriter.cc