NGSFeatures: cbrc::AminoScore Class Reference
cbrc::AminoScore Class Reference abstract
#include <AminoScore.hh>
Public Member Functions
virtual alignScoreT gapInitiation () const =0
virtual alignScoreT gapExtension () const =0
virtual alignScoreT score (const ResidueIndexMap::indexT &r1, const ResidueIndexMap::indexT &r2) const =0
virtual alignScoreT maxScore () const =0
virtual alignScoreT maxScore (const ResidueIndexMap::indexT &r1) const =0
virtual alignScoreT minScore () const =0
bool minScoreIsValid () const
virtual const ResidueIndexMap & residueIndexMap () const =0
virtual ~AminoScore ()
Detailed Description
Definition at line 25 of file AminoScore.hh.
Constructor & Destructor Documentation
~AminoScore()
virtual cbrc::AminoScore::~AminoScore () inline virtual
Definition at line 43 of file AminoScore.hh.
Member Function Documentation
gapExtension()
virtual alignScoreT cbrc::AminoScore::gapExtension () const pure virtual
Implemented in cbrc::AminoScoreIdentity, and cbrc::AminoScorePam120.
Referenced by minScoreIsValid(), and cbrc::Alignment::score().
gapInitiation()
virtual alignScoreT cbrc::AminoScore::gapInitiation () const pure virtual
Implemented in cbrc::AminoScoreIdentity, and cbrc::AminoScorePam120.
Referenced by minScoreIsValid(), and cbrc::Alignment::score().
maxScore() [1/2]
virtual alignScoreT cbrc::AminoScore::maxScore () const pure virtual
Implemented in cbrc::AminoScoreIdentity, and cbrc::AminoScorePam120.
Referenced by cbrc::SeqGlobalAffineAligner::bestPossibleSuffixScore().
maxScore() [2/2]
virtual alignScoreT cbrc::AminoScore::maxScore (const ResidueIndexMap::indexT & r1) const pure virtual
Implemented in cbrc::AminoScoreIdentity, and cbrc::AminoScorePam120.
minScore()
virtual alignScoreT cbrc::AminoScore::minScore () const pure virtual
Implemented in cbrc::AminoScoreIdentity, and cbrc::AminoScorePam120.
Referenced by minScoreIsValid().
minScoreIsValid()
bool cbrc::AminoScore::minScoreIsValid () const
Definition at line 17 of file AminoScore.cc.
References gapExtension(), gapInitiation(), minScore(), residueIndexMap(), and score().
residueIndexMap()
virtual const ResidueIndexMap & cbrc::AminoScore::residueIndexMap () const pure virtual
Implemented in cbrc::AminoScoreIdentity, and cbrc::AminoScorePam120.
Referenced by minScoreIsValid().
score()
virtual alignScoreT cbrc::AminoScore::score (const ResidueIndexMap::indexT & r1, const ResidueIndexMap::indexT & r2) const pure virtual
Implemented in cbrc::AminoScoreIdentity, and cbrc::AminoScorePam120.
Referenced by minScoreIsValid(), and cbrc::Alignment::score().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/align/AminoScore.hh
ematch_src/utils/sequence/align/AminoScore.cc