NGSFeatures: cbrc::ConstantLabeledSquareDoubleFLENumMatrix Class Reference
cbrc::ConstantLabeledSquareDoubleFLENumMatrix Class Reference
#include <ConstantLabeledSquareDoubleFLENumMatrix.hh>
Public Member Functions
ConstantLabeledSquareDoubleFLENumMatrix (std::istream &is)
ConstantLabeledSquareDoubleFLENumMatrix (std::istream &is, const std::string inputDelimiter)
ConstantLabeledSquareDoubleFLENumMatrix (const ConstantLabeledSquareDoubleFLENumMatrix &matrixToCopy)
void setFromStream (std::istream &is, const std::string inputDelimiter="[ \t]+")
double operator() (const size_t &index0, const size_t &index1) const
double operator() (const std::string &label0, const std::string &label1) const
const SerialNumbersForStrings< size_t > & labels () const
const std::string & indexToLabel (const size_t &i) const
size_t size0 () const
void renumLabels (const SerialNumbersForStrings< size_t > &labelsNewOrder)
bool symmetric () const
Public Member Functions inherited from cbrc::ConstantLabeledSquareDoubleInterface
virtual ~ConstantLabeledSquareDoubleInterface ()
Static Public Member Functions
static const std::string outputDelimiter ()
Friends
std::ostream & operator<< (std::ostream &os, const ConstantLabeledSquareDoubleFLENumMatrix &mat)
Detailed Description
Definition at line 34 of file ConstantLabeledSquareDoubleFLENumMatrix.hh.
Constructor & Destructor Documentation
ConstantLabeledSquareDoubleFLENumMatrix() [1/3]
cbrc::ConstantLabeledSquareDoubleFLENumMatrix::ConstantLabeledSquareDoubleFLENumMatrix (std::istream & is) inline
Definition at line 36 of file ConstantLabeledSquareDoubleFLENumMatrix.hh.
References setFromStream().
ConstantLabeledSquareDoubleFLENumMatrix() [2/3]
cbrc::ConstantLabeledSquareDoubleFLENumMatrix::ConstantLabeledSquareDoubleFLENumMatrix (std::istream & is, const std::string inputDelimiter) inline
Definition at line 39 of file ConstantLabeledSquareDoubleFLENumMatrix.hh.
References setFromStream().
ConstantLabeledSquareDoubleFLENumMatrix() [3/3]
cbrc::ConstantLabeledSquareDoubleFLENumMatrix::ConstantLabeledSquareDoubleFLENumMatrix (const ConstantLabeledSquareDoubleFLENumMatrix & matrixToCopy) inline
Definition at line 42 of file ConstantLabeledSquareDoubleFLENumMatrix.hh.
Member Function Documentation
indexToLabel()
const std::string & cbrc::ConstantLabeledSquareDoubleFLENumMatrix::indexToLabel (const size_t & i) const inline
Definition at line 65 of file ConstantLabeledSquareDoubleFLENumMatrix.hh.
References labels().
labels()
const SerialNumbersForStrings< size_t > & cbrc::ConstantLabeledSquareDoubleFLENumMatrix::labels () const inline
Definition at line 61 of file ConstantLabeledSquareDoubleFLENumMatrix.hh.
Referenced by indexToLabel(), operator()(), and setFromStream().
operator()() [1/2]
double cbrc::ConstantLabeledSquareDoubleFLENumMatrix::operator() (const size_t & index0, const size_t & index1) const inline virtual
Implements cbrc::ConstantLabeledSquareDoubleInterface.
Definition at line 52 of file ConstantLabeledSquareDoubleFLENumMatrix.hh.
operator()() [2/2]
double cbrc::ConstantLabeledSquareDoubleFLENumMatrix::operator() (const std::string & label0, const std::string & label1) const inline virtual
Implements cbrc::ConstantLabeledSquareDoubleInterface.
Definition at line 56 of file ConstantLabeledSquareDoubleFLENumMatrix.hh.
References labels().
outputDelimiter()
static const std::string cbrc::ConstantLabeledSquareDoubleFLENumMatrix::outputDelimiter () inline static
Definition at line 50 of file ConstantLabeledSquareDoubleFLENumMatrix.hh.
renumLabels()
void cbrc::ConstantLabeledSquareDoubleFLENumMatrix::renumLabels (const SerialNumbersForStrings< size_t > & labelsNewOrder) virtual
Implements cbrc::ConstantLabeledSquareDoubleInterface.
Definition at line 55 of file ConstantLabeledSquareDoubleFLENumMatrix.cc.
References cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
setFromStream()
void cbrc::ConstantLabeledSquareDoubleFLENumMatrix::setFromStream (std::istream & is, const std::string inputDelimiter = "[ \t]+")
Definition at line 14 of file ConstantLabeledSquareDoubleFLENumMatrix.cc.
References GDB_ASSERTF, cbrc::SerialNumbersForStrings< serialNumT >::getSerialNumber(), cbrc::perlish::isSharpCommentOrEmpty(), labels(), cbrc::FLEMatrix< T >::setSize(), cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLine(), and cbrc::perlish::split().
Referenced by ConstantLabeledSquareDoubleFLENumMatrix(), and ConstantLabeledSquareDoubleFLENumMatrix().
size0()
size_t cbrc::ConstantLabeledSquareDoubleFLENumMatrix::size0 () const inline
Definition at line 72 of file ConstantLabeledSquareDoubleFLENumMatrix.hh.
References cbrc::FLEMatrix< T >::size0().
Referenced by symmetric().
symmetric()
bool cbrc::ConstantLabeledSquareDoubleFLENumMatrix::symmetric () const
Definition at line 122 of file ConstantLabeledSquareDoubleFLENumMatrix.cc.
References size0().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const ConstantLabeledSquareDoubleFLENumMatrix & mat) friend
Definition at line 147 of file ConstantLabeledSquareDoubleFLENumMatrix.cc.
The documentation for this class was generated from the following files:
ematch_src/utils/FLArray/ConstantLabeledSquareDoubleFLENumMatrix.hh
ematch_src/utils/FLArray/ConstantLabeledSquareDoubleFLENumMatrix.cc