NGSFeatures: cbrc::TrivialUnsignedHistogram< T > Class Template Reference
cbrc::TrivialUnsignedHistogram< T > Class Template Reference
#include <TrivialUnsignedHistogram.hh>
Public Member Functions
TrivialUnsignedHistogram (const FLENumArray< T > &data, const size_t startingCount=0)
TrivialUnsignedHistogram (const size_t dataMax, const size_t startingCount=0)
TrivialUnsignedHistogram (std::istream &is=std::cin)
void incrementCount (size_t index)
const size_t operator() (const size_t &index) const
size_t size () const
void write (std::ostream &os)
void printNonzeroEntries (std::ostream &os=std::cout, const char fieldSepartor=' ', const char entrySeparator='\n') const
Detailed Description
template<typename T>
class cbrc::TrivialUnsignedHistogram< T >
Definition at line 19 of file TrivialUnsignedHistogram.hh.
Constructor & Destructor Documentation
TrivialUnsignedHistogram() [1/3]
template<typename T > cbrc::TrivialUnsignedHistogram< T >::TrivialUnsignedHistogram (const FLENumArray< T > & data, const size_t startingCount = 0) inline
Definition at line 21 of file TrivialUnsignedHistogram.hh.
TrivialUnsignedHistogram() [2/3]
template<typename T > cbrc::TrivialUnsignedHistogram< T >::TrivialUnsignedHistogram (const size_t dataMax, const size_t startingCount = 0) inline
Definition at line 27 of file TrivialUnsignedHistogram.hh.
TrivialUnsignedHistogram() [3/3]
template<typename T > cbrc::TrivialUnsignedHistogram< T >::TrivialUnsignedHistogram (std::istream & is = std::cin) inline
Definition at line 31 of file TrivialUnsignedHistogram.hh.
References cbrc::FLEArray< T >::read().
Member Function Documentation
incrementCount()
template<typename T > void cbrc::TrivialUnsignedHistogram< T >::incrementCount (size_t index) inline
Definition at line 34 of file TrivialUnsignedHistogram.hh.
operator()()
template<typename T > const size_t cbrc::TrivialUnsignedHistogram< T >::operator() (const size_t & index) const inline
Definition at line 35 of file TrivialUnsignedHistogram.hh.
printNonzeroEntries()
template<typename T > void cbrc::TrivialUnsignedHistogram< T >::printNonzeroEntries (std::ostream & os = std::cout, const char fieldSepartor = ' ', const char entrySeparator = '\n') const inline
Definition at line 40 of file TrivialUnsignedHistogram.hh.
References cbrc::FLEArray< T >::size().
size()
template<typename T > size_t cbrc::TrivialUnsignedHistogram< T >::size () const inline
Definition at line 36 of file TrivialUnsignedHistogram.hh.
References cbrc::FLEArray< T >::size().
write()
template<typename T > void cbrc::TrivialUnsignedHistogram< T >::write (std::ostream & os) inline
Definition at line 37 of file TrivialUnsignedHistogram.hh.
References cbrc::FLEArray< T >::write().
The documentation for this class was generated from the following file:
ematch_src/utils/histogram/TrivialUnsignedHistogram.hh