NGSFeatures: cbrc::LabeledAsciiSeq Class Reference
cbrc::LabeledAsciiSeq Class Reference
#include <LabeledAsciiSeq.hh>
Public Member Functions
LabeledAsciiSeq ()
LabeledAsciiSeq (const std::string &seq, const std::vector< std::string > &labels)
LabeledAsciiSeq (const LabeledAsciiSeq &labeledAsciiSeq)
LabeledAsciiSeq (const std::string &seq, const std::string name=defaultSeqName())
const LabeledAsciiSeq & operator= (const LabeledAsciiSeq &labSeq)
const std::string & seq () const
void setSeq (const std::string &seq)
const std::string & name () const
void setName (const std::string &name)
size_t size () const
const char & operator() (const size_t &idx)
const std::string & label (const size_t &i) const
const std::vector< std::string > & labels () const
const size_t numLabels () const
void setLabels (const std::vector< std::string > &labels)
Detailed Description
Definition at line 24 of file LabeledAsciiSeq.hh.
Constructor & Destructor Documentation
LabeledAsciiSeq() [1/4]
cbrc::LabeledAsciiSeq::LabeledAsciiSeq () inline
Definition at line 27 of file LabeledAsciiSeq.hh.
LabeledAsciiSeq() [2/4]
cbrc::LabeledAsciiSeq::LabeledAsciiSeq (const std::string & seq, const std::vector< std::string > & labels) inline
Definition at line 32 of file LabeledAsciiSeq.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and labels().
LabeledAsciiSeq() [3/4]
cbrc::LabeledAsciiSeq::LabeledAsciiSeq (const LabeledAsciiSeq & labeledAsciiSeq) inline
Definition at line 39 of file LabeledAsciiSeq.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and cbrc::FLEArray< T >::size().
LabeledAsciiSeq() [4/4]
cbrc::LabeledAsciiSeq::LabeledAsciiSeq (const std::string & seq, const std::string name = defaultSeqName()) inline explicit
Definition at line 48 of file LabeledAsciiSeq.hh.
References name().
Member Function Documentation
label()
const std::string & cbrc::LabeledAsciiSeq::label (const size_t & i) const inline
Definition at line 77 of file LabeledAsciiSeq.hh.
Referenced by name().
labels()
const std::vector< std::string > & cbrc::LabeledAsciiSeq::labels () const inline
Definition at line 78 of file LabeledAsciiSeq.hh.
Referenced by LabeledAsciiSeq(), and setLabels().
name()
const std::string & cbrc::LabeledAsciiSeq::name () const inline
Definition at line 69 of file LabeledAsciiSeq.hh.
References label().
Referenced by LabeledAsciiSeq(), and setName().
numLabels()
const size_t cbrc::LabeledAsciiSeq::numLabels () const inline
Definition at line 79 of file LabeledAsciiSeq.hh.
operator()()
const char & cbrc::LabeledAsciiSeq::operator() (const size_t & idx) inline
Definition at line 74 of file LabeledAsciiSeq.hh.
operator=()
const LabeledAsciiSeq & cbrc::LabeledAsciiSeq::operator= (const LabeledAsciiSeq & labSeq) inline
Definition at line 55 of file LabeledAsciiSeq.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and cbrc::FLEArray< T >::size().
seq()
const std::string & cbrc::LabeledAsciiSeq::seq () const inline
Definition at line 66 of file LabeledAsciiSeq.hh.
Referenced by setSeq(), and size().
setLabels()
void cbrc::LabeledAsciiSeq::setLabels (const std::vector< std::string > & labels) inline
Definition at line 81 of file LabeledAsciiSeq.hh.
References labels().
setName()
void cbrc::LabeledAsciiSeq::setName (const std::string & name) inline
Definition at line 70 of file LabeledAsciiSeq.hh.
References name().
setSeq()
void cbrc::LabeledAsciiSeq::setSeq (const std::string & seq) inline
Definition at line 67 of file LabeledAsciiSeq.hh.
References seq().
size()
size_t cbrc::LabeledAsciiSeq::size () const inline
Definition at line 72 of file LabeledAsciiSeq.hh.
References seq(), and cbrc::FLEArray< T >::size().
The documentation for this class was generated from the following file:
ematch_src/utils/sequence/LabeledAsciiSeq.hh