NGSFeatures: cbrc::FLEMatrix< T > Class Template Reference
cbrc::FLEMatrix< T > Class Template Reference
#include <FLEMatrix.hh>
Public Types
typedef T * iterator
typedef const T * const_iterator
Public Member Functions
FLEMatrix ()
FLEMatrix (const size_t sz0, const size_t sz1)
FLEMatrix (const size_t sz0, const size_t sz1, const T fillVal)
FLEMatrix (const size_t sz0, const size_t sz1, const T **const b)
FLEMatrix (const std::vector< std::vector< T > > &v)
FLEMatrix (const FLEMatrix< T > &flm)
virtual ~FLEMatrix ()
void setSize (size_t sz0, size_t sz1)
void resizeDestructive (size_t sz0, size_t sz1)
FLEMatrix operator= (const FLEMatrix &flm)
FLEMatrix operator= (std::vector< std::vector< T > > v)
T getVal (size_t index0, size_t index1, T defValue)
void zero ()
void fill (T fillVal)
void fillWithByte (int fillByte)
bool validIndex (size_t index) const
bool validIndex (size_t index0, size_t index1) const
bool operator== (const FLEMatrix &flm) const
virtual T & operator[] (const size_t index) const
virtual T & operator() (const size_t index0, const size_t index1) const
FLEMatrix< T > submatrix (const size_t startRow, const size_t endRow, const size_t startCol, const size_t endCol) const
void printColumnMajor (std::ostream &os) const
void shiftLeft (FLEArray< T > newCol)
void shiftRight (FLEArray< T > newCol)
virtual const T * getColPtr (const size_t index0) const
const size_t & size () const
const size_t & size0 () const
const size_t & size1 () const
iterator begin () const
iterator end () const
T * getPtr () const
void friend testFLEMatrix ()
Protected Member Functions
bool validAsMatrix (const std::vector< std::vector< T > > &v) const
Protected Attributes
size_t s
size_t s0
size_t s1
T * m
Detailed Description
template<typename T>
class cbrc::FLEMatrix< T >
Definition at line 59 of file FLEMatrix.hh.
Member Typedef Documentation
const_iterator
template<typename T > typedef const T* cbrc::FLEMatrix< T >::const_iterator
Definition at line 62 of file FLEMatrix.hh.
iterator
template<typename T > typedef T* cbrc::FLEMatrix< T >::iterator
Definition at line 61 of file FLEMatrix.hh.
Constructor & Destructor Documentation
FLEMatrix() [1/6]
template<typename T > cbrc::FLEMatrix< T >::FLEMatrix () inline
Definition at line 63 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, and cbrc::FLEMatrix< T >::s.
FLEMatrix() [2/6]
template<typename T > cbrc::FLEMatrix< T >::FLEMatrix (const size_t sz0, const size_t sz1) inline
Definition at line 64 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, and cbrc::FLEMatrix< T >::s.
FLEMatrix() [3/6]
template<typename T > cbrc::FLEMatrix< T >::FLEMatrix (const size_t sz0, const size_t sz1, const T fillVal) inline
Definition at line 68 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::fill(), cbrc::FLEMatrix< T >::m, and cbrc::FLEMatrix< T >::s.
FLEMatrix() [4/6]
template<typename T > cbrc::FLEMatrix< T >::FLEMatrix (const size_t sz0, const size_t sz1, const T **const b) inline
Definition at line 73 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, and cbrc::FLEMatrix< T >::s.
FLEMatrix() [5/6]
template<typename T > cbrc::FLEMatrix< T >::FLEMatrix (const std::vector< std::vector< T > > & v) inline
Definition at line 78 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, cbrc::FLEMatrix< T >::s, cbrc::FLEMatrix< T >::s0, cbrc::FLEMatrix< T >::s1, cbrc::FLEArray< T >::size(), and cbrc::FLEMatrix< T >::validAsMatrix().
FLEMatrix() [6/6]
template<typename T > cbrc::FLEMatrix< T >::FLEMatrix (const FLEMatrix< T > & flm) inline
Definition at line 92 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, cbrc::FLEArray< T >::s, cbrc::FLEMatrix< T >::s, cbrc::FLEMatrix< T >::s0, and cbrc::FLEMatrix< T >::s1.
~FLEMatrix()
template<typename T > virtual cbrc::FLEMatrix< T >::~FLEMatrix () inline virtual
Definition at line 97 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m.
Member Function Documentation
begin()
template<typename T > iterator cbrc::FLEMatrix< T >::begin () const inline
Definition at line 230 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m.
end()
template<typename T > iterator cbrc::FLEMatrix< T >::end () const inline
Definition at line 231 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, and cbrc::FLEMatrix< T >::s.
fill()
template<typename T > void cbrc::FLEMatrix< T >::fill (T fillVal) inline
Definition at line 153 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, and cbrc::FLEMatrix< T >::s.
Referenced by cbrc::FLEMatrix< T >::FLEMatrix().
fillWithByte()
template<typename T > void cbrc::FLEMatrix< T >::fillWithByte (int fillByte) inline
Definition at line 156 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, and cbrc::FLEMatrix< T >::s.
getColPtr()
template<typename T > virtual const T * cbrc::FLEMatrix< T >::getColPtr (const size_t index0) const inline virtual
Reimplemented in cbrc::FLEMatrixFast< T >, cbrc::FLEMatrixFast< alignScoreT >, cbrc::FLENumMatrixFast< T >, and cbrc::FLENumMatrixFast< double >.
Definition at line 221 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, cbrc::FLEMatrix< T >::s0, and cbrc::FLEMatrix< T >::s1.
getPtr()
template<typename T > T * cbrc::FLEMatrix< T >::getPtr () const inline
Definition at line 234 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m.
getVal()
template<typename T > T cbrc::FLEMatrix< T >::getVal (size_t index0, size_t index1, T defValue) inline
Definition at line 147 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, cbrc::FLEMatrix< T >::s1, and cbrc::FLEMatrix< T >::validIndex().
operator()()
template<typename T > virtual T & cbrc::FLEMatrix< T >::operator() (const size_t index0, const size_t index1) const inline virtual
Reimplemented in cbrc::FLEMatrixFast< T >, cbrc::FLEMatrixFast< alignScoreT >, cbrc::FLENumMatrixFast< T >, and cbrc::FLENumMatrixFast< double >.
Definition at line 178 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, cbrc::FLEMatrix< T >::s1, and cbrc::FLEMatrix< T >::validIndex().
Referenced by cbrc::FLEMatrix< T >::printColumnMajor(), and cbrc::FLEMatrix< T >::submatrix().
operator=() [1/2]
template<typename T > FLEMatrix cbrc::FLEMatrix< T >::operator= (const FLEMatrix< T > & flm) inline
Definition at line 112 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, cbrc::FLEArray< T >::s, cbrc::FLEMatrix< T >::s, cbrc::FLEMatrix< T >::s0, cbrc::FLEMatrix< T >::s1, cbrc::FLEArray< T >::size(), and cbrc::FLEMatrix< T >::size().
operator=() [2/2]
template<typename T > FLEMatrix cbrc::FLEMatrix< T >::operator= (std::vector< std::vector< T > > v) inline
Definition at line 124 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, cbrc::FLEMatrix< T >::s, cbrc::FLEMatrix< T >::s0, cbrc::FLEMatrix< T >::s1, cbrc::FLEArray< T >::size(), cbrc::FLEMatrix< T >::size(), and cbrc::FLEMatrix< T >::validAsMatrix().
operator==()
template<typename T > bool cbrc::FLEMatrix< T >::operator== (const FLEMatrix< T > & flm) const inline
Definition at line 170 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, cbrc::FLEArray< T >::s, and cbrc::FLEMatrix< T >::s.
operator[]()
template<typename T > virtual T & cbrc::FLEMatrix< T >::operator[] (const size_t index) const inline virtual
Reimplemented in cbrc::FLEMatrixFast< T >, cbrc::FLEMatrixFast< alignScoreT >, cbrc::FLENumMatrixFast< T >, and cbrc::FLENumMatrixFast< double >.
Definition at line 174 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, and cbrc::FLEMatrix< T >::validIndex().
printColumnMajor()
template<typename T > void cbrc::FLEMatrix< T >::printColumnMajor (std::ostream & os) const inline
Definition at line 201 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::operator()(), cbrc::FLEMatrix< T >::size(), cbrc::FLEMatrix< T >::size0(), and cbrc::FLEMatrix< T >::size1().
resizeDestructive()
template<typename T > void cbrc::FLEMatrix< T >::resizeDestructive (size_t sz0, size_t sz1) inline
Definition at line 104 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, cbrc::FLEMatrix< T >::s, cbrc::FLEMatrix< T >::s0, and cbrc::FLEMatrix< T >::s1.
setSize()
template<typename T > void cbrc::FLEMatrix< T >::setSize (size_t sz0, size_t sz1) inline
Definition at line 98 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, cbrc::FLEMatrix< T >::s, cbrc::FLEMatrix< T >::s0, and cbrc::FLEMatrix< T >::s1.
Referenced by cbrc::GlobalAffineIdentityAligner::GlobalAffineIdentityAligner(), cbrc::LabeledSquareFLENumMatrix< elemT >::LabeledSquareFLENumMatrix(), cbrc::SeqGlobalAffineAligner::SeqGlobalAffineAligner(), and cbrc::ConstantLabeledSquareDoubleFLENumMatrix::setFromStream().
shiftLeft()
template<typename T > void cbrc::FLEMatrix< T >::shiftLeft (FLEArray< T > newCol) inline
Definition at line 211 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, cbrc::FLEMatrix< T >::s, cbrc::FLEMatrix< T >::s1, and cbrc::FLEArray< T >::size().
shiftRight()
template<typename T > void cbrc::FLEMatrix< T >::shiftRight (FLEArray< T > newCol) inline
Definition at line 216 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, cbrc::FLEMatrix< T >::s, cbrc::FLEMatrix< T >::s1, and cbrc::FLEArray< T >::size().
size()
template<typename T > const size_t & cbrc::FLEMatrix< T >::size () const inline
Definition at line 226 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::s.
Referenced by cbrc::FLEMatrix< T >::operator=(), cbrc::FLEMatrix< T >::operator=(), cbrc::FLEMatrix< T >::printColumnMajor(), and cbrc::FLEMatrix< T >::validAsMatrix().
size0()
template<typename T > const size_t & cbrc::FLEMatrix< T >::size0 () const inline
Definition at line 227 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::s0.
Referenced by cbrc::FLENumMatrix< T >::normalize(), cbrc::FLEMatrix< T >::printColumnMajor(), cbrc::LabeledSquareFLENumMatrix< elemT >::size(), and cbrc::ConstantLabeledSquareDoubleFLENumMatrix::size0().
size1()
template<typename T > const size_t & cbrc::FLEMatrix< T >::size1 () const inline
Definition at line 228 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::s1.
Referenced by cbrc::FLENumMatrix< T >::normalize(), and cbrc::FLEMatrix< T >::printColumnMajor().
submatrix()
template<typename T > FLEMatrix< T > cbrc::FLEMatrix< T >::submatrix (const size_t startRow, const size_t endRow, const size_t startCol, const size_t endCol) const inline
Definition at line 187 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::operator()(), and cbrc::FLEMatrix< T >::validIndex().
testFLEMatrix()
template<typename T > void friend cbrc::FLEMatrix< T >::testFLEMatrix ()
validAsMatrix()
template<typename T > bool cbrc::FLEMatrix< T >::validAsMatrix (const std::vector< std::vector< T > > & v) const inline protected
Definition at line 237 of file FLEMatrix.hh.
References cbrc::FLEArray< T >::size(), and cbrc::FLEMatrix< T >::size().
Referenced by cbrc::FLEMatrix< T >::FLEMatrix(), and cbrc::FLEMatrix< T >::operator=().
validIndex() [1/2]
template<typename T > bool cbrc::FLEMatrix< T >::validIndex (size_t index) const inline
Definition at line 159 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::s.
Referenced by cbrc::FLEMatrix< T >::getVal(), cbrc::FLEMatrix< T >::operator()(), cbrc::FLEMatrix< T >::operator[](), and cbrc::FLEMatrix< T >::submatrix().
validIndex() [2/2]
template<typename T > bool cbrc::FLEMatrix< T >::validIndex (size_t index0, size_t index1) const inline
Definition at line 166 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::s0, and cbrc::FLEMatrix< T >::s1.
zero()
template<typename T > void cbrc::FLEMatrix< T >::zero () inline
Definition at line 150 of file FLEMatrix.hh.
References cbrc::FLEMatrix< T >::m, and cbrc::FLEMatrix< T >::s.
Referenced by cbrc::LabeledSquareFLENumMatrix< elemT >::zero().
Member Data Documentation
m
template<typename T > T* cbrc::FLEMatrix< T >::m protected
Definition at line 253 of file FLEMatrix.hh.
Referenced by cbrc::FLEMatrix< T >::begin(), cbrc::FLEMatrix< T >::end(), cbrc::FLEMatrix< T >::fill(), cbrc::FLEMatrix< T >::fillWithByte(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::getColPtr(), cbrc::FLEMatrix< T >::getPtr(), cbrc::FLEMatrix< T >::getVal(), cbrc::FLEMatrix< T >::operator()(), cbrc::FLEMatrix< T >::operator=(), cbrc::FLEMatrix< T >::operator=(), cbrc::FLEMatrix< T >::operator==(), cbrc::FLEMatrix< T >::operator[](), cbrc::FLEMatrix< T >::resizeDestructive(), cbrc::FLEMatrix< T >::setSize(), cbrc::FLEMatrix< T >::shiftLeft(), cbrc::FLEMatrix< T >::shiftRight(), cbrc::FLEMatrix< T >::zero(), and cbrc::FLEMatrix< T >::~FLEMatrix().
s
template<typename T > size_t cbrc::FLEMatrix< T >::s protected
Definition at line 252 of file FLEMatrix.hh.
Referenced by cbrc::FLEMatrix< T >::end(), cbrc::FLEMatrix< T >::fill(), cbrc::FLEMatrix< T >::fillWithByte(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::operator=(), cbrc::FLEMatrix< T >::operator=(), cbrc::FLEMatrix< T >::operator==(), cbrc::FLEMatrix< T >::resizeDestructive(), cbrc::FLEMatrix< T >::setSize(), cbrc::FLEMatrix< T >::shiftLeft(), cbrc::FLEMatrix< T >::shiftRight(), cbrc::FLEMatrix< T >::size(), cbrc::FLEMatrix< T >::validIndex(), and cbrc::FLEMatrix< T >::zero().
s0
template<typename T > size_t cbrc::FLEMatrix< T >::s0 protected
Definition at line 252 of file FLEMatrix.hh.
Referenced by cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::getColPtr(), cbrc::FLEMatrix< T >::operator=(), cbrc::FLEMatrix< T >::operator=(), cbrc::FLEMatrix< T >::resizeDestructive(), cbrc::FLEMatrix< T >::setSize(), cbrc::FLEMatrix< T >::size0(), and cbrc::FLEMatrix< T >::validIndex().
s1
template<typename T > size_t cbrc::FLEMatrix< T >::s1 protected
Definition at line 252 of file FLEMatrix.hh.
Referenced by cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLEMatrix< T >::getColPtr(), cbrc::FLEMatrix< T >::getVal(), cbrc::FLEMatrix< T >::operator()(), cbrc::FLEMatrix< T >::operator=(), cbrc::FLEMatrix< T >::operator=(), cbrc::FLEMatrix< T >::resizeDestructive(), cbrc::FLEMatrix< T >::setSize(), cbrc::FLEMatrix< T >::shiftLeft(), cbrc::FLEMatrix< T >::shiftRight(), cbrc::FLEMatrix< T >::size1(), and cbrc::FLEMatrix< T >::validIndex().
The documentation for this class was generated from the following file:
ematch_src/utils/FLArray/FLEMatrix.hh