NGSFeatures: cbrc::ResidueIndexMap Class Reference
cbrc::ResidueIndexMap Class Reference
#include <ResidueIndexMap.hh>
Public Types
typedef char residueT
typedef unsigned char indexT
typedef FLENumArray< indexT > arrayT
typedef std::vector< indexT > vectorT
Public Member Functions
ResidueIndexMap (const std::string &alphabet, const bool &caseSensitive=false) throw (std::invalid_argument)
ResidueIndexMap (const std::string &alphabetProper, const std::string &alphabet, const bool &caseSensitive=false) throw (std::invalid_argument)
ResidueIndexMap (const char *const &alphabetProper, const char *const &alphabet, const bool &caseSensitive=false) throw (std::invalid_argument)
ResidueIndexMap (std::istream &is) throw (std::invalid_argument)
ResidueIndexMap ()
ResidueIndexMap (const ResidueIndexMap &rim)
virtual ~ResidueIndexMap ()
void extendAlphabet (const char &residue) throw (std::invalid_argument)
bool validResidue (const char &residue) const
bool validResidues (const std::string &residues) const
bool validResidueIndex (const indexT &residueIndex) const
bool properResidue (const char &residue) const
bool properResidues (const std::string &residues) const
bool properResidueIndex (const indexT &residueIndex) const
indexT toResidueIndex (const char &residue) const throw (std::invalid_argument)
char toResidue (const indexT &residueIndex) const throw (std::invalid_argument)
vectorT toResidueIndicesVector (const std::string &residues) const throw (std::invalid_argument)
arrayT toResidueIndices (const std::string &residues) const throw (std::invalid_argument)
void assignResidueIndices (arrayT &residueIndices, const std::string &residues) const throw (std::invalid_argument)
void assignResidueIndices (vectorT &residueIndicesVec, const std::string &residues) const throw (std::invalid_argument)
void assignResidueIndices (const arrayT::iterator &residueIndicesBegin, const std::string::const_iterator &residuesBegin, const std::string::const_iterator &residuesEnd) const throw (std::invalid_argument)
std::string toResidues (const std::string &residueIndices) const throw (std::invalid_argument)
std::string toResidues (const arrayT &residueIndices) const throw (std::invalid_argument)
std::string toResidues (const arrayT::const_iterator &residueIndicesBegin, const arrayT::const_iterator &residueIndicesEnd) const throw (std::invalid_argument)
std::string vectorToResidues (const vectorT &residueIndicesVector) const throw (std::invalid_argument)
const std::string & alphabet () const
const std::string & alphabetProper () const
size_t sigma () const
indexT maxIndex () const
bool caseSensitive () const
bool residuesAreEquivalent (const char &residue0, const char &residue1) const
void canonicalizeCase (std::string &sequence) const
char canonicalizeCase (const char &residue) const
void read (std::istream &is) throw (std::invalid_argument)
void write (std::ostream &os) const
std::vector< vectorT > splitIntoProperOnlySubstrings (const vectorT &residueIndicesVector) const
Static Public Member Functions
static const std::string & binaryStreamSignature ()
Detailed Description
Definition at line 30 of file ResidueIndexMap.hh.
Member Typedef Documentation
arrayT
typedef FLENumArray<indexT> cbrc::ResidueIndexMap::arrayT
Definition at line 36 of file ResidueIndexMap.hh.
indexT
typedef unsigned char cbrc::ResidueIndexMap::indexT
Definition at line 35 of file ResidueIndexMap.hh.
residueT
typedef char cbrc::ResidueIndexMap::residueT
Definition at line 34 of file ResidueIndexMap.hh.
vectorT
typedef std::vector<indexT> cbrc::ResidueIndexMap::vectorT
Definition at line 37 of file ResidueIndexMap.hh.
Constructor & Destructor Documentation
ResidueIndexMap() [1/6]
cbrc::ResidueIndexMap::ResidueIndexMap (const std::string & alphabet, const bool & caseSensitive = false) throw (std::invalid_argument)
Definition at line 21 of file ResidueIndexMap.cc.
ResidueIndexMap() [2/6]
cbrc::ResidueIndexMap::ResidueIndexMap (const std::string & alphabetProper, const std::string & alphabet, const bool & caseSensitive = false) throw (std::invalid_argument)
Definition at line 45 of file ResidueIndexMap.cc.
ResidueIndexMap() [3/6]
cbrc::ResidueIndexMap::ResidueIndexMap (const char *const & alphabetProper, const char *const & alphabet, const bool & caseSensitive = false) throw (std::invalid_argument)
Definition at line 32 of file ResidueIndexMap.cc.
ResidueIndexMap() [4/6]
cbrc::ResidueIndexMap::ResidueIndexMap (std::istream & is) throw (std::invalid_argument) inline
Definition at line 56 of file ResidueIndexMap.hh.
References read().
ResidueIndexMap() [5/6]
cbrc::ResidueIndexMap::ResidueIndexMap () inline
Definition at line 63 of file ResidueIndexMap.hh.
ResidueIndexMap() [6/6]
cbrc::ResidueIndexMap::ResidueIndexMap (const ResidueIndexMap & rim) inline
Definition at line 65 of file ResidueIndexMap.hh.
~ResidueIndexMap()
virtual cbrc::ResidueIndexMap::~ResidueIndexMap () inline virtual
Definition at line 70 of file ResidueIndexMap.hh.
Member Function Documentation
alphabet()
const std::string & cbrc::ResidueIndexMap::alphabet () const inline
Definition at line 136 of file ResidueIndexMap.hh.
Referenced by canonicalizeCase(), maxIndex(), cbrc::operator<<(), sigma(), validResidue(), and write().
alphabetProper()
const std::string & cbrc::ResidueIndexMap::alphabetProper () const inline
Definition at line 138 of file ResidueIndexMap.hh.
Referenced by cbrc::dumpAminoAcidContentWPformat(), cbrc::operator<<(), properResidue(), properResidueIndex(), and write().
assignResidueIndices() [1/3]
void cbrc::ResidueIndexMap::assignResidueIndices (arrayT & residueIndices, const std::string & residues) const throw (std::invalid_argument)
Definition at line 182 of file ResidueIndexMap.cc.
References cbrc::FLEArray< T >::setSize().
Referenced by cbrc::ResidueIndexedSequence::ResidueIndexedSequence().
assignResidueIndices() [2/3]
void cbrc::ResidueIndexMap::assignResidueIndices (const arrayT::iterator & residueIndicesBegin, const std::string::const_iterator & residuesBegin, const std::string::const_iterator & residuesEnd) const throw (std::invalid_argument)
Definition at line 209 of file ResidueIndexMap.cc.
assignResidueIndices() [3/3]
void cbrc::ResidueIndexMap::assignResidueIndices (vectorT & residueIndicesVec, const std::string & residues) const throw (std::invalid_argument)
Definition at line 193 of file ResidueIndexMap.cc.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
binaryStreamSignature()
static const std::string & cbrc::ResidueIndexMap::binaryStreamSignature () inline static
Definition at line 165 of file ResidueIndexMap.hh.
Referenced by write().
canonicalizeCase() [1/2]
char cbrc::ResidueIndexMap::canonicalizeCase (const char & residue) const inline
Definition at line 159 of file ResidueIndexMap.hh.
References alphabet().
canonicalizeCase() [2/2]
void cbrc::ResidueIndexMap::canonicalizeCase (std::string & sequence) const inline
Definition at line 154 of file ResidueIndexMap.hh.
References canonicalizeCase(), and cbrc::FLEArray< T >::size().
Referenced by canonicalizeCase(), and cbrc::dumpAminoAcidContentWPformat().
caseSensitive()
bool cbrc::ResidueIndexMap::caseSensitive () const inline
Definition at line 145 of file ResidueIndexMap.hh.
Referenced by cbrc::operator<<(), and residuesAreEquivalent().
extendAlphabet()
void cbrc::ResidueIndexMap::extendAlphabet (const char & residue) throw (std::invalid_argument)
Definition at line 62 of file ResidueIndexMap.cc.
maxIndex()
indexT cbrc::ResidueIndexMap::maxIndex () const inline
Definition at line 143 of file ResidueIndexMap.hh.
References alphabet(), and cbrc::FLEArray< T >::size().
properResidue()
bool cbrc::ResidueIndexMap::properResidue (const char & residue) const
Definition at line 102 of file ResidueIndexMap.cc.
References alphabetProper(), residuesAreEquivalent(), and cbrc::FLEArray< T >::size().
Referenced by properResidues().
properResidueIndex()
bool cbrc::ResidueIndexMap::properResidueIndex (const indexT & residueIndex) const inline
Definition at line 91 of file ResidueIndexMap.hh.
References alphabetProper().
Referenced by splitIntoProperOnlySubstrings().
properResidues()
bool cbrc::ResidueIndexMap::properResidues (const std::string & residues) const
Definition at line 113 of file ResidueIndexMap.cc.
References properResidue(), and cbrc::FLEArray< T >::size().
read()
void cbrc::ResidueIndexMap::read (std::istream & is) throw (std::invalid_argument)
Definition at line 290 of file ResidueIndexMap.cc.
References cbrc::perlish::die(), and cbrc::stringBinaryIO::read().
Referenced by cbrc::ResidueIndexedSequence::read(), and ResidueIndexMap().
residuesAreEquivalent()
bool cbrc::ResidueIndexMap::residuesAreEquivalent (const char & residue0, const char & residue1) const
Definition at line 275 of file ResidueIndexMap.cc.
References caseSensitive().
Referenced by properResidue(), and validResidue().
sigma()
size_t cbrc::ResidueIndexMap::sigma () const inline
Definition at line 141 of file ResidueIndexMap.hh.
References alphabet(), and cbrc::FLEArray< T >::size().
Referenced by validResidueIndex().
splitIntoProperOnlySubstrings()
std::vector< ResidueIndexMap::vectorT > cbrc::ResidueIndexMap::splitIntoProperOnlySubstrings (const vectorT & residueIndicesVector) const
Definition at line 348 of file ResidueIndexMap.cc.
References cbrc::FLEArray< T >::begin(), properResidueIndex(), and cbrc::FLEArray< T >::size().
toResidue()
char cbrc::ResidueIndexMap::toResidue (const indexT & residueIndex) const throw (std::invalid_argument)
Definition at line 140 of file ResidueIndexMap.cc.
Referenced by testDNAArrayBit16(), and testDNAArrayBit8().
toResidueIndex()
ResidueIndexMap::indexT cbrc::ResidueIndexMap::toResidueIndex (const char & residue) const throw (std::invalid_argument)
Definition at line 125 of file ResidueIndexMap.cc.
References cbrc::FLEArray< T >::size().
Referenced by testDNAArrayBit16(), and testDNAArrayBit8().
toResidueIndices()
ResidueIndexMap::arrayT cbrc::ResidueIndexMap::toResidueIndices (const std::string & residues) const throw (std::invalid_argument)
Definition at line 171 of file ResidueIndexMap.cc.
Referenced by cbrc::ResidueIndexMapTransformer::ResidueIndexMapTransformer(), cbrc::ResidueIndexMapTranslator::ResidueIndexMapTranslator(), testDNAArrayBit16(), and testDNAArrayBit8().
toResidueIndicesVector()
ResidueIndexMap::vectorT cbrc::ResidueIndexMap::toResidueIndicesVector (const std::string & residues) const throw (std::invalid_argument)
Definition at line 159 of file ResidueIndexMap.cc.
toResidues() [1/3]
std::string cbrc::ResidueIndexMap::toResidues (const arrayT & residueIndices) const throw (std::invalid_argument)
Definition at line 247 of file ResidueIndexMap.cc.
References cbrc::FLEArray< T >::resize(), and cbrc::FLEArray< T >::size().
toResidues() [2/3]
std::string cbrc::ResidueIndexMap::toResidues (const arrayT::const_iterator & residueIndicesBegin, const arrayT::const_iterator & residueIndicesEnd) const throw (std::invalid_argument)
Definition at line 257 of file ResidueIndexMap.cc.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::resize().
toResidues() [3/3]
std::string cbrc::ResidueIndexMap::toResidues (const std::string & residueIndices) const throw (std::invalid_argument)
Definition at line 225 of file ResidueIndexMap.cc.
References cbrc::FLEArray< T >::resize().
Referenced by testDNAArrayBit16(), and testDNAArrayBit8().
validResidue()
bool cbrc::ResidueIndexMap::validResidue (const char & residue) const
Definition at line 81 of file ResidueIndexMap.cc.
References alphabet(), residuesAreEquivalent(), and cbrc::FLEArray< T >::size().
Referenced by validResidues().
validResidueIndex()
bool cbrc::ResidueIndexMap::validResidueIndex (const indexT & residueIndex) const inline
Definition at line 84 of file ResidueIndexMap.hh.
References sigma().
Referenced by cbrc::KmerIndexer::toIndex().
validResidues()
bool cbrc::ResidueIndexMap::validResidues (const std::string & residues) const
Definition at line 92 of file ResidueIndexMap.cc.
References cbrc::FLEArray< T >::size(), and validResidue().
vectorToResidues()
std::string cbrc::ResidueIndexMap::vectorToResidues (const vectorT & residueIndicesVector) const throw (std::invalid_argument)
Definition at line 236 of file ResidueIndexMap.cc.
References cbrc::FLEArray< T >::resize(), and cbrc::FLEArray< T >::size().
write()
void cbrc::ResidueIndexMap::write (std::ostream & os) const
Definition at line 326 of file ResidueIndexMap.cc.
References alphabet(), alphabetProper(), binaryStreamSignature(), cbrc::perlish::die(), cbrc::stringBinaryIO::write(), cbrc::FLEArray< T >::write(), and cbrc::stringBinaryIO::writeContentsOnly().
Referenced by cbrc::writeResidueIndexMap().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/ResidueIndexMap/ResidueIndexMap.hh
ematch_src/utils/sequence/ResidueIndexMap/ResidueIndexMap.cc