NGSFeatures: cbrc::SeqGlobalAffineAligner Class Reference
cbrc::SeqGlobalAffineAligner Class Reference
#include <SeqGlobalAffineAligner.hh>
Public Member Functions
SeqGlobalAffineAligner (const AminoScore &resSubScore, const ResidueIndexMap::arrayT &seq0)
const ResidueIndexMap::arrayT & residues () const
const AminoScore & resSubScore () const
const alignScoreT & bestPossibleScore () const
alignScoreT score (const ResidueIndexMap::arrayT &s1) const
alignScoreT scoreFreeStartGap (const ResidueIndexMap::arrayT &s1) const
Alignment alignment (const ResidueIndexMap::arrayT &s1) const
alignScoreT scoreBounded (const ResidueIndexMap::arrayT &s1, const FLEArray< alignScoreT > &s1BestPossibleSuffixScores, const alignScoreT &lowerBound) const
alignScoreT scoreSuffixBounded (const ResidueIndexMap::arrayT &s1, const alignScoreT lowerBound) const
alignScoreT prefixScoreBounded (const ResidueIndexMap::arrayT &s1, const alignScoreT &prefixScoreLowerBound) const
alignScoreT lengthDifferenceBasedScoreUpperBound (const ResidueIndexMap::arrayT &s1) const
alignScoreT purelyLengthDifferenceBasedScoreUpperBound (const size_t &len1) const
alignScoreT feasibleBound (const ResidueIndexMap::arrayT &s1) const
Static Public Member Functions
static alignScoreT singleSeqBasedScoreUpperBound (const AminoScore &resSubScore, const ResidueIndexMap::arrayT &s1)
static FLEArray< alignScoreT > bestPossibleSuffixScore (const AminoScore &resSubScore, const ResidueIndexMap::arrayT &seq)
static void bestPossibleSuffixScore (FLEArray< alignScoreT > &suffixScores, const AminoScore &resSubScore, const ResidueIndexMap::arrayT &seq)
Detailed Description
Definition at line 26 of file SeqGlobalAffineAligner.hh.
Constructor & Destructor Documentation
SeqGlobalAffineAligner()
cbrc::SeqGlobalAffineAligner::SeqGlobalAffineAligner (const AminoScore & resSubScore, const ResidueIndexMap::arrayT & seq0) inline
Definition at line 28 of file SeqGlobalAffineAligner.hh.
References GDB_ASSERT, resSubScore(), cbrc::FLEMatrix< T >::setSize(), singleSeqBasedScoreUpperBound(), and cbrc::FLEArray< T >::size().
Member Function Documentation
alignment()
Alignment cbrc::SeqGlobalAffineAligner::alignment (const ResidueIndexMap::arrayT & s1) const
Definition at line 99 of file SeqGlobalAffineAligner.cc.
References cbrc::alignScoreTMin, cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), cbrc::Alignment::indelChar(), resSubScore(), score(), and cbrc::FLEArray< T >::size().
bestPossibleScore()
const alignScoreT & cbrc::SeqGlobalAffineAligner::bestPossibleScore () const inline
Definition at line 46 of file SeqGlobalAffineAligner.hh.
bestPossibleSuffixScore() [1/2]
static FLEArray< alignScoreT > cbrc::SeqGlobalAffineAligner::bestPossibleSuffixScore (const AminoScore & resSubScore, const ResidueIndexMap::arrayT & seq) inline static
Definition at line 112 of file SeqGlobalAffineAligner.hh.
References bestPossibleSuffixScore(), resSubScore(), and cbrc::FLEArray< T >::size().
Referenced by cbrc::allPairsNearestGlobalAffineScore(), bestPossibleSuffixScore(), cbrc::clusterByIdentity(), cbrc::hasHighIdentityToDataset(), scoreSuffixBounded(), and cbrc::testSeqGlobalAffineAligner().
bestPossibleSuffixScore() [2/2]
void cbrc::SeqGlobalAffineAligner::bestPossibleSuffixScore (FLEArray< alignScoreT > & suffixScores, const AminoScore & resSubScore, const ResidueIndexMap::arrayT & seq) static
Definition at line 504 of file SeqGlobalAffineAligner.cc.
References cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::indexInRange(), cbrc::AminoScore::maxScore(), and cbrc::FLEArray< T >::size().
feasibleBound()
alignScoreT cbrc::SeqGlobalAffineAligner::feasibleBound (const ResidueIndexMap::arrayT & s1) const
Definition at line 315 of file SeqGlobalAffineAligner.cc.
References resSubScore(), and cbrc::FLEArray< T >::size().
lengthDifferenceBasedScoreUpperBound()
alignScoreT cbrc::SeqGlobalAffineAligner::lengthDifferenceBasedScoreUpperBound (const ResidueIndexMap::arrayT & s1) const
Definition at line 48 of file SeqGlobalAffineAligner.cc.
References cbrc::FLEArray< T >::size().
prefixScoreBounded()
alignScoreT cbrc::SeqGlobalAffineAligner::prefixScoreBounded (const ResidueIndexMap::arrayT & s1, const alignScoreT & prefixScoreLowerBound) const
Definition at line 271 of file SeqGlobalAffineAligner.cc.
References cbrc::alignScoreTMin, resSubScore(), score(), and cbrc::FLEArray< T >::size().
purelyLengthDifferenceBasedScoreUpperBound()
alignScoreT cbrc::SeqGlobalAffineAligner::purelyLengthDifferenceBasedScoreUpperBound (const size_t & len1) const
Definition at line 36 of file SeqGlobalAffineAligner.cc.
References resSubScore(), and cbrc::FLEArray< T >::size().
residues()
const ResidueIndexMap::arrayT & cbrc::SeqGlobalAffineAligner::residues () const inline
Definition at line 38 of file SeqGlobalAffineAligner.hh.
resSubScore()
const AminoScore & cbrc::SeqGlobalAffineAligner::resSubScore () const inline
Definition at line 40 of file SeqGlobalAffineAligner.hh.
Referenced by alignment(), bestPossibleSuffixScore(), feasibleBound(), prefixScoreBounded(), purelyLengthDifferenceBasedScoreUpperBound(), score(), scoreFreeStartGap(), scoreSuffixBounded(), SeqGlobalAffineAligner(), and singleSeqBasedScoreUpperBound().
score()
alignScoreT cbrc::SeqGlobalAffineAligner::score (const ResidueIndexMap::arrayT & s1) const
Definition at line 62 of file SeqGlobalAffineAligner.cc.
References cbrc::alignScoreTMin, resSubScore(), score(), and cbrc::FLEArray< T >::size().
Referenced by alignment(), prefixScoreBounded(), score(), scoreFreeStartGap(), and singleSeqBasedScoreUpperBound().
scoreBounded()
alignScoreT cbrc::SeqGlobalAffineAligner::scoreBounded (const ResidueIndexMap::arrayT & s1, const FLEArray< alignScoreT > & s1BestPossibleSuffixScores, const alignScoreT & lowerBound) const
Definition at line 390 of file SeqGlobalAffineAligner.cc.
References cbrc::alignScoreTMin, cbrc::FLEArray< T >::FLEArray(), GDB_ASSERTF, and cbrc::FLEArray< T >::size().
Referenced by scoreSuffixBounded().
scoreFreeStartGap()
alignScoreT cbrc::SeqGlobalAffineAligner::scoreFreeStartGap (const ResidueIndexMap::arrayT & s1) const
Definition at line 224 of file SeqGlobalAffineAligner.cc.
References resSubScore(), score(), and cbrc::FLEArray< T >::size().
scoreSuffixBounded()
alignScoreT cbrc::SeqGlobalAffineAligner::scoreSuffixBounded (const ResidueIndexMap::arrayT & s1, const alignScoreT lowerBound) const
Definition at line 375 of file SeqGlobalAffineAligner.cc.
References bestPossibleSuffixScore(), resSubScore(), scoreBounded(), and cbrc::FLEArray< T >::size().
singleSeqBasedScoreUpperBound()
static alignScoreT cbrc::SeqGlobalAffineAligner::singleSeqBasedScoreUpperBound (const AminoScore & resSubScore, const ResidueIndexMap::arrayT & s1) inline static
Definition at line 104 of file SeqGlobalAffineAligner.hh.
References resSubScore(), score(), and cbrc::FLEArray< T >::size().
Referenced by SeqGlobalAffineAligner().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/align/SeqGlobalAffineAligner.hh
ematch_src/utils/sequence/align/SeqGlobalAffineAligner.cc