NGSFeatures: cbrc::StringSpecEnum Class Reference
cbrc::StringSpecEnum Class Reference
#include <StringSpecEnum.hh>
Public Member Functions
StringSpecEnum (const std::string &specString, const std::string delimiter=defaultDelimiter())
const std::string & specString () const
const std::string & delimiter () const
const std::string & value () const
const stringVecT & possibleValues () const
size_t size () const
size_t index (const std::string &s) const
bool operator== (const std::string &s)
bool isInitialized () const
Static Public Member Functions
static const std::string & defaultDelimiter ()
Detailed Description
Definition at line 21 of file StringSpecEnum.hh.
Constructor & Destructor Documentation
StringSpecEnum()
cbrc::StringSpecEnum::StringSpecEnum (const std::string & specString, const std::string delimiter = defaultDelimiter())
Definition at line 15 of file StringSpecEnum.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), possibleValues(), and cbrc::FLEArray< T >::size().
Member Function Documentation
defaultDelimiter()
static const std::string & cbrc::StringSpecEnum::defaultDelimiter () inline static
Definition at line 66 of file StringSpecEnum.hh.
delimiter()
const std::string & cbrc::StringSpecEnum::delimiter () const inline
Definition at line 39 of file StringSpecEnum.hh.
index()
size_t cbrc::StringSpecEnum::index (const std::string & s) const
Definition at line 38 of file StringSpecEnum.cc.
References possibleValues().
Referenced by operator==().
isInitialized()
bool cbrc::StringSpecEnum::isInitialized () const inline
Definition at line 61 of file StringSpecEnum.hh.
References size(), and value().
operator==()
bool cbrc::StringSpecEnum::operator== (const std::string & s) inline
Definition at line 55 of file StringSpecEnum.hh.
References index(), size(), and value().
possibleValues()
const stringVecT & cbrc::StringSpecEnum::possibleValues () const inline
Definition at line 43 of file StringSpecEnum.hh.
Referenced by index(), size(), and StringSpecEnum().
size()
size_t cbrc::StringSpecEnum::size () const inline
Definition at line 45 of file StringSpecEnum.hh.
References possibleValues(), and cbrc::FLEArray< T >::size().
Referenced by isInitialized(), and operator==().
specString()
const std::string & cbrc::StringSpecEnum::specString () const inline
Definition at line 37 of file StringSpecEnum.hh.
value()
const std::string & cbrc::StringSpecEnum::value () const inline
Definition at line 41 of file StringSpecEnum.hh.
Referenced by isInitialized(), and operator==().
The documentation for this class was generated from the following files:
ematch_src/utils/stringSpecified/StringSpecEnum.hh
ematch_src/utils/stringSpecified/StringSpecEnum.cc