NGSFeatures: cbrc::UInt332 Class Reference
cbrc::UInt332 Class Reference
#include <UInt332.hh>
Public Member Functions
UInt332 ()
UInt332 (unsigned short int val0, unsigned int val1, unsigned int val2)
UInt332 (const UInt332 &ui332)
void setVal0 (unsigned short int val0)
void setVal1 (unsigned int val1)
void setVal2 (unsigned int val2)
unsigned short int getVal0 () const
unsigned int getVal1 () const
unsigned int getVal2 () const
UInt332 operator= (const UInt332 &ui332)
bool operator== (const UInt332 &ui332) const
bool operator!= (const UInt332 &ui332) const
Static Public Member Functions
static int cmpAscendVal0 (const void *a, const void *b)
Friends
std::ostream & operator<< (std::ostream &os, const UInt332 &ui332)
void testUInt332 ()
Detailed Description
Definition at line 29 of file UInt332.hh.
Constructor & Destructor Documentation
UInt332() [1/3]
cbrc::UInt332::UInt332 () inline
Definition at line 31 of file UInt332.hh.
UInt332() [2/3]
cbrc::UInt332::UInt332 (unsigned short int val0, unsigned int val1, unsigned int val2) inline
Definition at line 32 of file UInt332.hh.
References setVal0(), setVal1(), and setVal2().
UInt332() [3/3]
cbrc::UInt332::UInt332 (const UInt332 & ui332) inline
Definition at line 35 of file UInt332.hh.
Member Function Documentation
cmpAscendVal0()
static int cbrc::UInt332::cmpAscendVal0 (const void * a, const void * b) inline static
Definition at line 69 of file UInt332.hh.
getVal0()
unsigned short int cbrc::UInt332::getVal0 () const inline
Definition at line 53 of file UInt332.hh.
getVal1()
unsigned int cbrc::UInt332::getVal1 () const inline
Definition at line 56 of file UInt332.hh.
getVal2()
unsigned int cbrc::UInt332::getVal2 () const inline
Definition at line 60 of file UInt332.hh.
operator!=()
bool cbrc::UInt332::operator!= (const UInt332 & ui332) const inline
Definition at line 66 of file UInt332.hh.
operator=()
UInt332 cbrc::UInt332::operator= (const UInt332 & ui332) inline
Definition at line 64 of file UInt332.hh.
operator==()
bool cbrc::UInt332::operator== (const UInt332 & ui332) const inline
Definition at line 65 of file UInt332.hh.
setVal0()
void cbrc::UInt332::setVal0 (unsigned short int val0) inline
Definition at line 36 of file UInt332.hh.
Referenced by UInt332().
setVal1()
void cbrc::UInt332::setVal1 (unsigned int val1) inline
Definition at line 41 of file UInt332.hh.
Referenced by UInt332().
setVal2()
void cbrc::UInt332::setVal2 (unsigned int val2) inline
Definition at line 47 of file UInt332.hh.
Referenced by UInt332().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const UInt332 & ui332) friend
Definition at line 90 of file UInt332.hh.
testUInt332
void testUInt332 () friend
The documentation for this class was generated from the following file:
ematch_src/utils/packedInts/UInt332.hh