NGSFeatures: cbrc::WeightedPoint2D< XT, YT, WT > Class Template Reference
cbrc::WeightedPoint2D< XT, YT, WT > Class Template Reference
#include <WeightedPoint2D.hh>
Public Member Functions
WeightedPoint2D ()
WeightedPoint2D (const Point2D< XT, YT > &p)
WeightedPoint2D (const WeightedPoint2D< XT, YT, WT > &wp)
WeightedPoint2D (const XT x, const YT y, const WT w=1)
operator Point2D< XT, YT > () const
bool operator!= (const WeightedPoint2D< XT, YT, WT > &p)
XT x () const
YT y () const
WT weight () const
void set (XT x, YT y)
void swapXY ()
void setX (XT x)
void setY (YT y)
void averageYCoordinateAndSumWeightsWith (const WeightedPoint2D< XT, YT, WT > &p)
void averageCoordinatesAndSumWeightsWith (const WeightedPoint2D< XT, YT, WT > &p)
Static Public Member Functions
static bool xLess (const WeightedPoint2D< XT, YT, WT > &p0, const WeightedPoint2D< XT, YT, WT > &p1)
static bool xAscending (const WeightedPoint2D< XT, YT, WT > &p0, const WeightedPoint2D< XT, YT, WT > &p1)
static bool xDescending (const WeightedPoint2D< XT, YT, WT > &p0, const WeightedPoint2D< XT, YT, WT > &p1)
static bool yAscending (const WeightedPoint2D< XT, YT, WT > &p0, const WeightedPoint2D< XT, YT, WT > &p1)
static bool yDescending (const WeightedPoint2D< XT, YT, WT > &p0, const WeightedPoint2D< XT, YT, WT > &p1)
static bool nonFinite (const WeightedPoint2D< XT, YT, WT > &p)
Friends
void testWeightedPoint2D ()
Detailed Description
template<typename XT, typename YT, typename WT = double>
class cbrc::WeightedPoint2D< XT, YT, WT >
Definition at line 19 of file WeightedPoint2D.hh.
Constructor & Destructor Documentation
WeightedPoint2D() [1/4]
template<typename XT , typename YT , typename WT = double> cbrc::WeightedPoint2D< XT, YT, WT >::WeightedPoint2D () inline
Definition at line 21 of file WeightedPoint2D.hh.
WeightedPoint2D() [2/4]
template<typename XT , typename YT , typename WT = double> cbrc::WeightedPoint2D< XT, YT, WT >::WeightedPoint2D (const Point2D< XT, YT > & p) inline
Definition at line 22 of file WeightedPoint2D.hh.
WeightedPoint2D() [3/4]
template<typename XT , typename YT , typename WT = double> cbrc::WeightedPoint2D< XT, YT, WT >::WeightedPoint2D (const WeightedPoint2D< XT, YT, WT > & wp) inline
Definition at line 23 of file WeightedPoint2D.hh.
WeightedPoint2D() [4/4]
template<typename XT , typename YT , typename WT = double> cbrc::WeightedPoint2D< XT, YT, WT >::WeightedPoint2D (const XT x, const YT y, const WT w = 1) inline
Definition at line 24 of file WeightedPoint2D.hh.
Member Function Documentation
averageCoordinatesAndSumWeightsWith()
template<typename XT , typename YT , typename WT = double> void cbrc::WeightedPoint2D< XT, YT, WT >::averageCoordinatesAndSumWeightsWith (const WeightedPoint2D< XT, YT, WT > & p) inline
Definition at line 84 of file WeightedPoint2D.hh.
averageYCoordinateAndSumWeightsWith()
template<typename XT , typename YT , typename WT = double> void cbrc::WeightedPoint2D< XT, YT, WT >::averageYCoordinateAndSumWeightsWith (const WeightedPoint2D< XT, YT, WT > & p) inline
Definition at line 75 of file WeightedPoint2D.hh.
nonFinite()
template<typename XT , typename YT , typename WT = double> static bool cbrc::WeightedPoint2D< XT, YT, WT >::nonFinite (const WeightedPoint2D< XT, YT, WT > & p) inline static
Definition at line 42 of file WeightedPoint2D.hh.
Referenced by cbrc::smoothing::monotonicSmoothY().
operator Point2D< XT, YT >()
template<typename XT , typename YT , typename WT = double> cbrc::WeightedPoint2D< XT, YT, WT >::operator Point2D< XT, YT > () const inline
Definition at line 25 of file WeightedPoint2D.hh.
operator!=()
template<typename XT , typename YT , typename WT = double> bool cbrc::WeightedPoint2D< XT, YT, WT >::operator!= (const WeightedPoint2D< XT, YT, WT > & p) inline
Definition at line 26 of file WeightedPoint2D.hh.
References cbrc::WeightedPoint2D< XT, YT, WT >::x(), and cbrc::WeightedPoint2D< XT, YT, WT >::y().
set()
template<typename XT , typename YT , typename WT = double> void cbrc::WeightedPoint2D< XT, YT, WT >::set (XT x, YT y) inline
Definition at line 33 of file WeightedPoint2D.hh.
References cbrc::WeightedPoint2D< XT, YT, WT >::x(), and cbrc::WeightedPoint2D< XT, YT, WT >::y().
setX()
template<typename XT , typename YT , typename WT = double> void cbrc::WeightedPoint2D< XT, YT, WT >::setX (XT x) inline
Definition at line 69 of file WeightedPoint2D.hh.
References cbrc::WeightedPoint2D< XT, YT, WT >::x().
setY()
template<typename XT , typename YT , typename WT = double> void cbrc::WeightedPoint2D< XT, YT, WT >::setY (YT y) inline
Definition at line 70 of file WeightedPoint2D.hh.
References cbrc::WeightedPoint2D< XT, YT, WT >::y().
swapXY()
template<typename XT , typename YT , typename WT = double> void cbrc::WeightedPoint2D< XT, YT, WT >::swapXY () inline
Definition at line 34 of file WeightedPoint2D.hh.
weight()
template<typename XT , typename YT , typename WT = double> WT cbrc::WeightedPoint2D< XT, YT, WT >::weight () const inline
Definition at line 32 of file WeightedPoint2D.hh.
x()
template<typename XT , typename YT , typename WT = double> XT cbrc::WeightedPoint2D< XT, YT, WT >::x () const inline
Definition at line 30 of file WeightedPoint2D.hh.
Referenced by cbrc::WeightedPoint2D< XT, YT, WT >::operator!=(), cbrc::WeightedPoint2D< XT, YT, WT >::set(), and cbrc::WeightedPoint2D< XT, YT, WT >::setX().
xAscending()
template<typename XT , typename YT , typename WT = double> static bool cbrc::WeightedPoint2D< XT, YT, WT >::xAscending (const WeightedPoint2D< XT, YT, WT > & p0, const WeightedPoint2D< XT, YT, WT > & p1) inline static
Definition at line 38 of file WeightedPoint2D.hh.
xDescending()
template<typename XT , typename YT , typename WT = double> static bool cbrc::WeightedPoint2D< XT, YT, WT >::xDescending (const WeightedPoint2D< XT, YT, WT > & p0, const WeightedPoint2D< XT, YT, WT > & p1) inline static
Definition at line 39 of file WeightedPoint2D.hh.
xLess()
template<typename XT , typename YT , typename WT = double> static bool cbrc::WeightedPoint2D< XT, YT, WT >::xLess (const WeightedPoint2D< XT, YT, WT > & p0, const WeightedPoint2D< XT, YT, WT > & p1) inline static
Definition at line 35 of file WeightedPoint2D.hh.
Referenced by cbrc::smoothing::monotonicSmoothY().
y()
template<typename XT , typename YT , typename WT = double> YT cbrc::WeightedPoint2D< XT, YT, WT >::y () const inline
Definition at line 31 of file WeightedPoint2D.hh.
Referenced by cbrc::WeightedPoint2D< XT, YT, WT >::operator!=(), cbrc::WeightedPoint2D< XT, YT, WT >::set(), and cbrc::WeightedPoint2D< XT, YT, WT >::setY().
yAscending()
template<typename XT , typename YT , typename WT = double> static bool cbrc::WeightedPoint2D< XT, YT, WT >::yAscending (const WeightedPoint2D< XT, YT, WT > & p0, const WeightedPoint2D< XT, YT, WT > & p1) inline static
Definition at line 40 of file WeightedPoint2D.hh.
yDescending()
template<typename XT , typename YT , typename WT = double> static bool cbrc::WeightedPoint2D< XT, YT, WT >::yDescending (const WeightedPoint2D< XT, YT, WT > & p0, const WeightedPoint2D< XT, YT, WT > & p1) inline static
Definition at line 41 of file WeightedPoint2D.hh.
Friends And Related Symbol Documentation
testWeightedPoint2D
template<typename XT , typename YT , typename WT = double> void testWeightedPoint2D () friend
The documentation for this class was generated from the following file:
ematch_src/utils/geometry/WeightedPoint2D.hh