NGSFeatures: cbrc::ArgvParser Class Reference
cbrc::ArgvParser Class Reference
#include <ArgvParser.hh>
Public Member Functions
ArgvParser (const int &argc, const char *argv[], const std::string &usage, std::ostream &errorOut=std::cout)
std::string commandLine () const
void logCommandLine (const std::string &pathname) const
std::string pathname () const
std::vector< std::string > argsAsStrings () const
std::vector< std::string > unusedArgs () const
std::string operator[] (const int &index)
int argc () const
int argcOrig () const
size_t size () const
int numArgs () const
int numOpts () const
bool hasFlag (const std::vector< std::string > &flags)
bool hasFlag (const std::string &flagSpec)
bool hasFlag (const std::string &flag, const std::string &flagAlias)
bool hasFlagDelete (const std::vector< std::string > &flags)
bool hasFlagDelete (const std::string &flagSpec)
bool hasFlagDelete (const std::string &flag, const std::string &flagAlias)
bool hasOpt (const std::vector< std::string > &flags)
bool hasOpt (const std::string &flagSpec)
bool hasOpt (const std::string &flag, const std::string &flagAlias)
bool yesNoFlag (const std::string opt)
std::string getFlag (const std::vector< std::string > &flags)
std::string getFlag (const std::string &flag, const std::string &flagAlias=_argvParserNullString)
std::string getOpt (const std::string &flagSpec, const std::string defaultValue=_argvParserNullString)
std::string getOpt (const std::vector< std::string > &flags, const std::string defaultValue=_argvParserNullString)
std::string getOptOrDie (const std::string &flagSpec)
std::string getOptOrDie (const std::vector< std::string > &flags)
std::string getEnumOrDie (const int &posArgIndex, const std::string &possibleValuesSpec)
std::string getEnumOpt (const std::string &flagSpec, const std::string &possibleValuesSpec, const std::string defaultValue=_argvParserNullString)
std::string getEnumOpt (const std::string &flagSpec, const std::vector< std::string > &possibleValues, const std::string defaultValue=_argvParserNullString)
std::string getEnumOpt (const std::vector< std::string > &flags, const std::string &possibleValuesSpec, const std::string defaultValue=_argvParserNullString)
std::string getEnumOpt (const std::vector< std::string > &flags, const std::vector< std::string > &possibleValues, const std::string defaultValue=_argvParserNullString)
bool hasArg (const int &posArgIndex)
std::string getArg (const int &posArgIndex)
std::string getArgOrDie (const int &posArgIndex)
template<typename T >
std::string set (T &lhs, const int &posArgIndex)
template<typename T >
std::string set (T &lhs, const std::vector< std::string > &flags)
template<typename T >
std::string set (T &lhs, const std::string &flagSpec)
std::string set (bool &lhs, const std::vector< std::string > &flags)
std::string set (bool &lhs, const std::string &flagSpec)
template<typename T >
std::string set (T &lhs, const std::string &flag, const std::string &flagAlias)
template<typename T >
std::string setOrDie (T &lhs, const int &posArgIndex)
template<typename T >
std::string setOrDie (T &lhs, const std::vector< std::string > &flags)
template<typename T >
std::string setOrDie (T &lhs, const std::string &flagSpec)
template<typename T >
std::string setOrDie (T &lhs, const std::string &flag, const std::string &flagAlias)
std::string setCautiously (std::ofstream &ofs, const int &posArgIndex)
std::string setCautiously (std::ofstream &ofs, const std::string &flagSpec)
std::string setCautiously (std::ofstream &ofs, const std::string &flag, const std::string &flagAlias)
std::string setCautiously (std::ofstream &ofs, const std::vector< std::string > &flags)
std::string setCautiouslyOrDie (std::ofstream &ofs, const int &posArgIndex)
std::string setCautiouslyOrDie (std::ofstream &ofs, const std::string &flagSpec)
std::string setCautiouslyOrDie (std::ofstream &ofs, const std::string &flag, const std::string &flagAlias)
std::string setCautiouslyOrDie (std::ofstream &ofs, const std::vector< std::string > &flags)
std::istream & getIstream (const int &posArgIndex)
std::istream * getIstreamPtr (const int &posArgIndex)
std::istream & getIstream (const std::string &flagSpec)
std::istream & getIstream (const std::vector< std::string > &flags)
std::istream & getIstreamOrDie (const int &posArgIndex)
std::istream & getIstreamOrDie (const std::string &flagSpec)
std::istream & getIstreamOrDie (const std::vector< std::string > &flags)
std::istream * getIstreamPtrOrDie (const int &posArgIndex)
template<typename T >
const char *const setFromNextUnused (T &lhs)
void open (std::ifstream &ifs, const std::string &pathname)
std::istream * openIstream (const std::string &pathname)
void openCautiously (std::ofstream &ofs, const std::string &pathname) const
void closeIstream (std::istream *ifsPtr)
std::string shift ()
std::string shiftOrDie ()
std::string shiftUsedOk ()
std::string shiftMandatoryUsedOk ()
std::string usage () const
void dieIfUnusedArgs () const
void printDoc (const std::string &locale="") const
void printOptionDoc (const std::string &optionName, const std::string &locale="") const
void setDoc (const std::string &optionNamesVBarList, const std::string &optionValue, const std::string &locale="C")
std::string getDoc (const std::string &optionName, std::string locale="") const
bool die (const std::string message="") const
bool has (const std::string &flag, const std::string &flagAlias=_argvParserNullString)
bool hasNextArg (const std::string &flag)
bool hasUnused (const std::string &flag)
bool eat (const std::string &opt, const std::string &alias=_argvParserNullString)
void dumpArgvInfo () const
ArgvParser (const int &argc, const char *argv[], const std::string &usage, std::ostream &errorOut=std::cout)
std::string commandLine () const
void logCommandLine (const std::string &pathname) const
std::string pathname () const
std::vector< std::string > argsAsStrings () const
std::vector< std::string > unusedArgs () const
std::string operator[] (const int &index)
int argc () const
int argcOrig () const
size_t size () const
int numArgs () const
int numOpts () const
bool hasFlag (const std::vector< std::string > &flags)
bool hasFlag (const std::string &flagSpec)
bool hasFlag (const std::string &flag, const std::string &flagAlias)
bool hasFlagDelete (const std::vector< std::string > &flags)
bool hasFlagDelete (const std::string &flagSpec)
bool hasFlagDelete (const std::string &flag, const std::string &flagAlias)
bool hasOpt (const std::vector< std::string > &flags)
bool hasOpt (const std::string &flagSpec)
bool hasOpt (const std::string &flag, const std::string &flagAlias)
bool yesNoFlag (const std::string opt)
std::string getFlag (const std::vector< std::string > &flags)
std::string getFlag (const std::string &flag, const std::string &flagAlias=_argvParserNullString)
std::string getOpt (const std::string &flagSpec, const std::string defaultValue=_argvParserNullString)
std::string getOpt (const std::vector< std::string > &flags, const std::string defaultValue=_argvParserNullString)
std::string getOptOrDie (const std::string &flagSpec)
std::string getOptOrDie (const std::vector< std::string > &flags)
std::string getEnumOrDie (const int &posArgIndex, const std::string &possibleValuesSpec)
std::string getEnumOpt (const std::string &flagSpec, const std::string &possibleValuesSpec, const std::string defaultValue=_argvParserNullString)
std::string getEnumOpt (const std::string &flagSpec, const std::vector< std::string > &possibleValues, const std::string defaultValue=_argvParserNullString)
std::string getEnumOpt (const std::vector< std::string > &flags, const std::string &possibleValuesSpec, const std::string defaultValue=_argvParserNullString)
std::string getEnumOpt (const std::vector< std::string > &flags, const std::vector< std::string > &possibleValues, const std::string defaultValue=_argvParserNullString)
bool hasArg (const int &posArgIndex)
std::string getArg (const int &posArgIndex)
std::string getArgOrDie (const int &posArgIndex)
template<typename T >
std::string set (T &lhs, const int &posArgIndex)
template<typename T >
std::string set (T &lhs, const std::vector< std::string > &flags)
template<typename T >
std::string set (T &lhs, const std::string &flagSpec)
std::string set (bool &lhs, const std::vector< std::string > &flags)
std::string set (bool &lhs, const std::string &flagSpec)
template<typename T >
std::string set (T &lhs, const std::string &flag, const std::string &flagAlias)
template<typename T >
std::string setOrDie (T &lhs, const int &posArgIndex)
template<typename T >
std::string setOrDie (T &lhs, const std::vector< std::string > &flags)
template<typename T >
std::string setOrDie (T &lhs, const std::string &flagSpec)
template<typename T >
std::string setOrDie (T &lhs, const std::string &flag, const std::string &flagAlias)
std::string setCautiously (std::ofstream &ofs, const int &posArgIndex)
std::string setCautiously (std::ofstream &ofs, const std::string &flagSpec)
std::string setCautiously (std::ofstream &ofs, const std::string &flag, const std::string &flagAlias)
std::string setCautiously (std::ofstream &ofs, const std::vector< std::string > &flags)
std::string setCautiouslyOrDie (std::ofstream &ofs, const int &posArgIndex)
std::string setCautiouslyOrDie (std::ofstream &ofs, const std::string &flagSpec)
std::string setCautiouslyOrDie (std::ofstream &ofs, const std::string &flag, const std::string &flagAlias)
std::string setCautiouslyOrDie (std::ofstream &ofs, const std::vector< std::string > &flags)
std::istream & getIstream (const int &posArgIndex)
std::istream * getIstreamPtr (const int &posArgIndex)
std::istream & getIstream (const std::string &flagSpec)
std::istream & getIstream (const std::vector< std::string > &flags)
std::istream & getIstreamOrDie (const int &posArgIndex)
std::istream & getIstreamOrDie (const std::string &flagSpec)
std::istream & getIstreamOrDie (const std::vector< std::string > &flags)
std::istream * getIstreamPtrOrDie (const int &posArgIndex)
template<typename T >
const char *const setFromNextUnused (T &lhs)
void open (std::ifstream &ifs, const std::string &pathname)
std::istream * openIstream (const std::string &pathname)
void openCautiously (std::ofstream &ofs, const std::string &pathname) const
void closeIstream (std::istream *ifsPtr)
std::string shift ()
std::string shiftOrDie ()
std::string shiftUsedOk ()
std::string shiftMandatoryUsedOk ()
std::string usage () const
void dieIfUnusedArgs () const
void printDoc (const std::string &locale="") const
void printOptionDoc (const std::string &optionName, const std::string &locale="") const
void setDoc (const std::string &optionNamesVBarList, const std::string &optionValue, const std::string &locale="C")
std::string getDoc (const std::string &optionName, std::string locale="") const
bool die (const std::string message="") const
bool has (const std::string &flag, const std::string &flagAlias=_argvParserNullString)
bool hasNextArg (const std::string &flag)
bool hasUnused (const std::string &flag)
bool eat (const std::string &opt, const std::string &alias=_argvParserNullString)
void dumpArgvInfo () const
Static Public Member Functions
static const std::string & useStdinIndicator ()
static bool fileExists (std::string pathname)
static bool isNullString (const std::string &s)
static bool looksLikeInt (const std::string &s)
static bool looksLikeUnsignedInt (const std::string &s)
static bool looksLikeDouble (const std::string &s)
static bool looksLikeInt (const char *const &s)
static bool looksLikeUnsignedInt (const char *const &s)
static bool looksLikeDouble (const char *const &s)
static bool isMember (const std::string &pipeSeparatedList, const std::string &element)
static const std::string & useStdinIndicator ()
static bool fileExists (std::string pathname)
static bool isNullString (const std::string &s)
static bool looksLikeInt (const std::string &s)
static bool looksLikeUnsignedInt (const std::string &s)
static bool looksLikeDouble (const std::string &s)
static bool looksLikeInt (const char *const &s)
static bool looksLikeUnsignedInt (const char *const &s)
static bool looksLikeDouble (const char *const &s)
static bool isMember (const std::string &pipeSeparatedList, const std::string &element)
Detailed Description
Definition at line 59 of file ArgvParser.hh.
Constructor & Destructor Documentation
ArgvParser() [1/2]
cbrc::ArgvParser::ArgvParser (const int & argc, const char * argv[], const std::string & usage, std::ostream & errorOut = std::cout) inline
Definition at line 77 of file ArgvParser.hh.
References pathname(), setDoc(), and usage().
ArgvParser() [2/2]
cbrc::ArgvParser::ArgvParser (const int & argc, const char * argv[], const std::string & usage, std::ostream & errorOut = std::cout) inline
Definition at line 77 of file ArgvParser.hh.
References pathname(), setDoc(), and usage().
Member Function Documentation
argc() [1/2]
int cbrc::ArgvParser::argc () const inline
Definition at line 118 of file ArgvParser.hh.
Referenced by argsAsStrings(), commandLine(), getArgOrDie(), logCommandLine(), operator[](), shift(), shiftMandatoryUsedOk(), shiftOrDie(), and shiftUsedOk().
argc() [2/2]
int cbrc::ArgvParser::argc () const inline
Definition at line 118 of file ArgvParser.hh.
argcOrig() [1/2]
int cbrc::ArgvParser::argcOrig () const inline
Definition at line 119 of file ArgvParser.hh.
argcOrig() [2/2]
int cbrc::ArgvParser::argcOrig () const inline
Definition at line 119 of file ArgvParser.hh.
argsAsStrings() [1/2]
std::vector< std::string > cbrc::ArgvParser::argsAsStrings () const inline
Definition at line 720 of file ArgvParser.hh.
References argc().
argsAsStrings() [2/2]
std::vector< std::string > cbrc::ArgvParser::argsAsStrings () const
closeIstream() [1/2]
void cbrc::ArgvParser::closeIstream (std::istream * ifsPtr) inline
Definition at line 1559 of file ArgvParser.hh.
Referenced by main().
closeIstream() [2/2]
void cbrc::ArgvParser::closeIstream (std::istream * ifsPtr)
commandLine() [1/2]
std::string cbrc::ArgvParser::commandLine () const inline
Definition at line 702 of file ArgvParser.hh.
References argc().
commandLine() [2/2]
std::string cbrc::ArgvParser::commandLine () const
die() [1/2]
bool cbrc::ArgvParser::die (const std::string message = "") const inline
Definition at line 1568 of file ArgvParser.hh.
References cbrc::FLEArray< T >::size(), and usage().
Referenced by dieIfUnusedArgs(), eat(), getArgOrDie(), getEnumOrDie(), hasUnused(), main(), openCautiously(), operator[](), set(), set(), set(), setCautiously(), setCautiouslyOrDie(), setCautiouslyOrDie(), setOrDie(), setOrDie(), shiftMandatoryUsedOk(), shiftOrDie(), and yesNoFlag().
die() [2/2]
bool cbrc::ArgvParser::die (const std::string message = "") const
dieIfUnusedArgs() [1/2]
void cbrc::ArgvParser::dieIfUnusedArgs () const inline
Definition at line 1584 of file ArgvParser.hh.
References die(), cbrc::FLEArray< T >::empty(), printDoc(), cbrc::FLEArray< T >::size(), and unusedArgs().
Referenced by main(), and main().
dieIfUnusedArgs() [2/2]
void cbrc::ArgvParser::dieIfUnusedArgs () const
dumpArgvInfo() [1/2]
void cbrc::ArgvParser::dumpArgvInfo () const inline
Definition at line 1717 of file ArgvParser.hh.
References size().
dumpArgvInfo() [2/2]
void cbrc::ArgvParser::dumpArgvInfo () const
eat() [1/2]
bool cbrc::ArgvParser::eat (const std::string & opt, const std::string & alias = _argvParserNullString) inline
Definition at line 480 of file ArgvParser.hh.
References die().
eat() [2/2]
bool cbrc::ArgvParser::eat (const std::string & opt, const std::string & alias = _argvParserNullString) inline
Definition at line 480 of file ArgvParser.hh.
References die().
fileExists() [1/2]
static bool cbrc::ArgvParser::fileExists (std::string pathname) inline static
Definition at line 489 of file ArgvParser.hh.
References pathname().
fileExists() [2/2]
static bool cbrc::ArgvParser::fileExists (std::string pathname) inline static
Definition at line 489 of file ArgvParser.hh.
References pathname().
getArg() [1/2]
std::string cbrc::ArgvParser::getArg (const int & posArgIndex) inline
Definition at line 743 of file ArgvParser.hh.
References cbrc::_argvParserNullString().
Referenced by getArgOrDie(), getEnumOrDie(), set(), setCautiously(), setCautiouslyOrDie(), and setOrDie().
getArg() [2/2]
std::string cbrc::ArgvParser::getArg (const int & posArgIndex)
getArgOrDie() [1/2]
std::string cbrc::ArgvParser::getArgOrDie (const int & posArgIndex) inline
Definition at line 755 of file ArgvParser.hh.
References cbrc::_argvParserNullString(), argc(), die(), getArg(), and cbrc::FLEArray< T >::size().
getArgOrDie() [2/2]
std::string cbrc::ArgvParser::getArgOrDie (const int & posArgIndex)
getDoc() [1/2]
std::string cbrc::ArgvParser::getDoc (const std::string & optionName, std::string locale = "") const inline
Definition at line 1631 of file ArgvParser.hh.
References getDoc(), and cbrc::FLEArray< T >::size().
Referenced by getDoc(), and printOptionDoc().
getDoc() [2/2]
std::string cbrc::ArgvParser::getDoc (const std::string & optionName, std::string locale = "") const
getEnumOpt() [1/8]
std::string cbrc::ArgvParser::getEnumOpt (const std::string & flagSpec, const std::string & possibleValuesSpec, const std::string defaultValue = _argvParserNullString) inline
Definition at line 220 of file ArgvParser.hh.
References getEnumOpt().
Referenced by getEnumOpt(), getEnumOpt(), and getEnumOpt().
getEnumOpt() [2/8]
std::string cbrc::ArgvParser::getEnumOpt (const std::string & flagSpec, const std::string & possibleValuesSpec, const std::string defaultValue = _argvParserNullString) inline
Definition at line 220 of file ArgvParser.hh.
References getEnumOpt().
getEnumOpt() [3/8]
std::string cbrc::ArgvParser::getEnumOpt (const std::string & flagSpec, const std::vector< std::string > & possibleValues, const std::string defaultValue = _argvParserNullString) inline
Definition at line 227 of file ArgvParser.hh.
References getEnumOpt().
getEnumOpt() [4/8]
std::string cbrc::ArgvParser::getEnumOpt (const std::string & flagSpec, const std::vector< std::string > & possibleValues, const std::string defaultValue = _argvParserNullString) inline
Definition at line 227 of file ArgvParser.hh.
References getEnumOpt().
getEnumOpt() [5/8]
std::string cbrc::ArgvParser::getEnumOpt (const std::vector< std::string > & flags, const std::string & possibleValuesSpec, const std::string defaultValue = _argvParserNullString) inline
Definition at line 234 of file ArgvParser.hh.
References getEnumOpt().
getEnumOpt() [6/8]
std::string cbrc::ArgvParser::getEnumOpt (const std::vector< std::string > & flags, const std::string & possibleValuesSpec, const std::string defaultValue = _argvParserNullString) inline
Definition at line 234 of file ArgvParser.hh.
References getEnumOpt().
getEnumOpt() [7/8]
std::string cbrc::ArgvParser::getEnumOpt (const std::vector< std::string > & flags, const std::vector< std::string > & possibleValues, const std::string defaultValue = _argvParserNullString) inline
Definition at line 843 of file ArgvParser.hh.
getEnumOpt() [8/8]
std::string cbrc::ArgvParser::getEnumOpt (const std::vector< std::string > & flags, const std::vector< std::string > & possibleValues, const std::string defaultValue = _argvParserNullString)
getEnumOrDie() [1/2]
std::string cbrc::ArgvParser::getEnumOrDie (const int & posArgIndex, const std::string & possibleValuesSpec) inline
Definition at line 816 of file ArgvParser.hh.
References cbrc::_argvParserNullString(), die(), getArg(), and hasArg().
getEnumOrDie() [2/2]
std::string cbrc::ArgvParser::getEnumOrDie (const int & posArgIndex, const std::string & possibleValuesSpec)
getFlag() [1/4]
std::string cbrc::ArgvParser::getFlag (const std::string & flag, const std::string & flagAlias = _argvParserNullString) inline
Definition at line 188 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and getFlag().
getFlag() [2/4]
std::string cbrc::ArgvParser::getFlag (const std::string & flag, const std::string & flagAlias = _argvParserNullString) inline
Definition at line 188 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and getFlag().
getFlag() [3/4]
std::string cbrc::ArgvParser::getFlag (const std::vector< std::string > & flags) inline
Definition at line 793 of file ArgvParser.hh.
References cbrc::_argvParserNullString().
Referenced by getFlag(), set(), set(), and setOrDie().
getFlag() [4/4]
std::string cbrc::ArgvParser::getFlag (const std::vector< std::string > & flags)
getIstream() [1/6]
std::istream & cbrc::ArgvParser::getIstream (const int & posArgIndex) inline
Definition at line 355 of file ArgvParser.hh.
getIstream() [2/6]
std::istream & cbrc::ArgvParser::getIstream (const int & posArgIndex) inline
Definition at line 355 of file ArgvParser.hh.
getIstream() [3/6]
std::istream & cbrc::ArgvParser::getIstream (const std::string & flagSpec) inline
Definition at line 361 of file ArgvParser.hh.
getIstream() [4/6]
std::istream & cbrc::ArgvParser::getIstream (const std::string & flagSpec) inline
Definition at line 361 of file ArgvParser.hh.
getIstream() [5/6]
std::istream & cbrc::ArgvParser::getIstream (const std::vector< std::string > & flags) inline
Definition at line 364 of file ArgvParser.hh.
getIstream() [6/6]
std::istream & cbrc::ArgvParser::getIstream (const std::vector< std::string > & flags) inline
Definition at line 364 of file ArgvParser.hh.
getIstreamOrDie() [1/6]
std::istream & cbrc::ArgvParser::getIstreamOrDie (const int & posArgIndex) inline
Definition at line 371 of file ArgvParser.hh.
getIstreamOrDie() [2/6]
std::istream & cbrc::ArgvParser::getIstreamOrDie (const int & posArgIndex) inline
Definition at line 371 of file ArgvParser.hh.
getIstreamOrDie() [3/6]
std::istream & cbrc::ArgvParser::getIstreamOrDie (const std::string & flagSpec) inline
Definition at line 374 of file ArgvParser.hh.
getIstreamOrDie() [4/6]
std::istream & cbrc::ArgvParser::getIstreamOrDie (const std::string & flagSpec) inline
Definition at line 374 of file ArgvParser.hh.
getIstreamOrDie() [5/6]
std::istream & cbrc::ArgvParser::getIstreamOrDie (const std::vector< std::string > & flags) inline
Definition at line 377 of file ArgvParser.hh.
getIstreamOrDie() [6/6]
std::istream & cbrc::ArgvParser::getIstreamOrDie (const std::vector< std::string > & flags) inline
Definition at line 377 of file ArgvParser.hh.
getIstreamPtr() [1/2]
std::istream * cbrc::ArgvParser::getIstreamPtr (const int & posArgIndex) inline
Definition at line 358 of file ArgvParser.hh.
Referenced by main().
getIstreamPtr() [2/2]
std::istream * cbrc::ArgvParser::getIstreamPtr (const int & posArgIndex) inline
Definition at line 358 of file ArgvParser.hh.
getIstreamPtrOrDie() [1/2]
std::istream * cbrc::ArgvParser::getIstreamPtrOrDie (const int & posArgIndex) inline
Definition at line 380 of file ArgvParser.hh.
Referenced by main().
getIstreamPtrOrDie() [2/2]
std::istream * cbrc::ArgvParser::getIstreamPtrOrDie (const int & posArgIndex) inline
Definition at line 380 of file ArgvParser.hh.
getOpt() [1/4]
std::string cbrc::ArgvParser::getOpt (const std::string & flagSpec, const std::string defaultValue = _argvParserNullString) inline
Definition at line 197 of file ArgvParser.hh.
References getOpt().
Referenced by getOpt(), set(), setCautiously(), setCautiouslyOrDie(), and setOrDie().
getOpt() [2/4]
std::string cbrc::ArgvParser::getOpt (const std::string & flagSpec, const std::string defaultValue = _argvParserNullString) inline
Definition at line 197 of file ArgvParser.hh.
References getOpt().
getOpt() [3/4]
std::string cbrc::ArgvParser::getOpt (const std::vector< std::string > & flags, const std::string defaultValue = _argvParserNullString) inline
Definition at line 804 of file ArgvParser.hh.
getOpt() [4/4]
std::string cbrc::ArgvParser::getOpt (const std::vector< std::string > & flags, const std::string defaultValue = _argvParserNullString)
getOptOrDie() [1/4]
std::string cbrc::ArgvParser::getOptOrDie (const std::string & flagSpec) inline
Definition at line 209 of file ArgvParser.hh.
References getOptOrDie().
Referenced by getOptOrDie().
getOptOrDie() [2/4]
std::string cbrc::ArgvParser::getOptOrDie (const std::string & flagSpec) inline
Definition at line 209 of file ArgvParser.hh.
References getOptOrDie().
getOptOrDie() [3/4]
std::string cbrc::ArgvParser::getOptOrDie (const std::vector< std::string > & flags) inline
Definition at line 862 of file ArgvParser.hh.
References cbrc::_argvParserNullString().
getOptOrDie() [4/4]
std::string cbrc::ArgvParser::getOptOrDie (const std::vector< std::string > & flags)
has() [1/2]
bool cbrc::ArgvParser::has (const std::string & flag, const std::string & flagAlias = _argvParserNullString) inline
Definition at line 461 of file ArgvParser.hh.
References hasFlag().
has() [2/2]
bool cbrc::ArgvParser::has (const std::string & flag, const std::string & flagAlias = _argvParserNullString) inline
Definition at line 461 of file ArgvParser.hh.
References hasFlag().
hasArg() [1/2]
bool cbrc::ArgvParser::hasArg (const int & posArgIndex) inline
Definition at line 1229 of file ArgvParser.hh.
Referenced by getEnumOrDie(), set(), setCautiously(), setCautiouslyOrDie(), and setOrDie().
hasArg() [2/2]
bool cbrc::ArgvParser::hasArg (const int & posArgIndex)
hasFlag() [1/6]
bool cbrc::ArgvParser::hasFlag (const std::string & flag, const std::string & flagAlias) inline
Definition at line 138 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and hasFlag().
hasFlag() [2/6]
bool cbrc::ArgvParser::hasFlag (const std::string & flag, const std::string & flagAlias) inline
Definition at line 138 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and hasFlag().
hasFlag() [3/6]
bool cbrc::ArgvParser::hasFlag (const std::string & flagSpec) inline
Definition at line 134 of file ArgvParser.hh.
References hasFlag().
hasFlag() [4/6]
bool cbrc::ArgvParser::hasFlag (const std::string & flagSpec) inline
Definition at line 134 of file ArgvParser.hh.
References hasFlag().
hasFlag() [5/6]
bool cbrc::ArgvParser::hasFlag (const std::vector< std::string > & flags) inline
Definition at line 1195 of file ArgvParser.hh.
Referenced by has(), hasFlag(), hasFlag(), and main().
hasFlag() [6/6]
bool cbrc::ArgvParser::hasFlag (const std::vector< std::string > & flags)
hasFlagDelete() [1/6]
bool cbrc::ArgvParser::hasFlagDelete (const std::string & flag, const std::string & flagAlias) inline
Definition at line 150 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and hasFlagDelete().
hasFlagDelete() [2/6]
bool cbrc::ArgvParser::hasFlagDelete (const std::string & flag, const std::string & flagAlias) inline
Definition at line 150 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and hasFlagDelete().
hasFlagDelete() [3/6]
bool cbrc::ArgvParser::hasFlagDelete (const std::string & flagSpec) inline
Definition at line 147 of file ArgvParser.hh.
References hasFlagDelete().
hasFlagDelete() [4/6]
bool cbrc::ArgvParser::hasFlagDelete (const std::string & flagSpec) inline
Definition at line 147 of file ArgvParser.hh.
References hasFlagDelete().
hasFlagDelete() [5/6]
bool cbrc::ArgvParser::hasFlagDelete (const std::vector< std::string > & flags) inline
Definition at line 1205 of file ArgvParser.hh.
Referenced by hasFlagDelete(), and hasFlagDelete().
hasFlagDelete() [6/6]
bool cbrc::ArgvParser::hasFlagDelete (const std::vector< std::string > & flags)
hasNextArg() [1/2]
bool cbrc::ArgvParser::hasNextArg (const std::string & flag) inline
Definition at line 468 of file ArgvParser.hh.
References hasOpt().
hasNextArg() [2/2]
bool cbrc::ArgvParser::hasNextArg (const std::string & flag) inline
Definition at line 468 of file ArgvParser.hh.
References hasOpt().
hasOpt() [1/6]
bool cbrc::ArgvParser::hasOpt (const std::string & flag, const std::string & flagAlias) inline
Definition at line 169 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and hasOpt().
hasOpt() [2/6]
bool cbrc::ArgvParser::hasOpt (const std::string & flag, const std::string & flagAlias) inline
Definition at line 169 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and hasOpt().
hasOpt() [3/6]
bool cbrc::ArgvParser::hasOpt (const std::string & flagSpec) inline
Definition at line 166 of file ArgvParser.hh.
References hasOpt().
hasOpt() [4/6]
bool cbrc::ArgvParser::hasOpt (const std::string & flagSpec) inline
Definition at line 166 of file ArgvParser.hh.
References hasOpt().
hasOpt() [5/6]
bool cbrc::ArgvParser::hasOpt (const std::vector< std::string > & flags) inline
Definition at line 781 of file ArgvParser.hh.
Referenced by hasNextArg(), hasOpt(), hasOpt(), main(), set(), setCautiously(), setCautiouslyOrDie(), and setOrDie().
hasOpt() [6/6]
bool cbrc::ArgvParser::hasOpt (const std::vector< std::string > & flags)
hasUnused() [1/2]
bool cbrc::ArgvParser::hasUnused (const std::string & flag) inline
Definition at line 473 of file ArgvParser.hh.
References die().
hasUnused() [2/2]
bool cbrc::ArgvParser::hasUnused (const std::string & flag) inline
Definition at line 473 of file ArgvParser.hh.
References die().
isMember() [1/2]
bool cbrc::ArgvParser::isMember (const std::string & pipeSeparatedList, const std::string & element) inline static
Definition at line 1759 of file ArgvParser.hh.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
Referenced by main().
isMember() [2/2]
static bool cbrc::ArgvParser::isMember (const std::string & pipeSeparatedList, const std::string & element) static
isNullString() [1/2]
static bool cbrc::ArgvParser::isNullString (const std::string & s) inline static
Definition at line 490 of file ArgvParser.hh.
References cbrc::_argvParserNullString().
isNullString() [2/2]
static bool cbrc::ArgvParser::isNullString (const std::string & s) inline static
Definition at line 490 of file ArgvParser.hh.
References cbrc::_argvParserNullString().
logCommandLine() [1/2]
void cbrc::ArgvParser::logCommandLine (const std::string & pathname) const inline
Definition at line 711 of file ArgvParser.hh.
References argc().
logCommandLine() [2/2]
void cbrc::ArgvParser::logCommandLine (const std::string & pathname) const
looksLikeDouble() [1/4]
bool cbrc::ArgvParser::looksLikeDouble (const char *const & s) inline static
Definition at line 1308 of file ArgvParser.hh.
looksLikeDouble() [2/4]
static bool cbrc::ArgvParser::looksLikeDouble (const char *const & s) static
looksLikeDouble() [3/4]
static bool cbrc::ArgvParser::looksLikeDouble (const std::string & s) inline static
Definition at line 497 of file ArgvParser.hh.
References looksLikeDouble().
Referenced by looksLikeDouble().
looksLikeDouble() [4/4]
static bool cbrc::ArgvParser::looksLikeDouble (const std::string & s) inline static
Definition at line 497 of file ArgvParser.hh.
References looksLikeDouble().
Referenced by looksLikeDouble().
looksLikeInt() [1/4]
bool cbrc::ArgvParser::looksLikeInt (const char *const & s) inline static
Definition at line 1280 of file ArgvParser.hh.
looksLikeInt() [2/4]
static bool cbrc::ArgvParser::looksLikeInt (const char *const & s) static
looksLikeInt() [3/4]
static bool cbrc::ArgvParser::looksLikeInt (const std::string & s) inline static
Definition at line 495 of file ArgvParser.hh.
References looksLikeInt().
Referenced by looksLikeInt().
looksLikeInt() [4/4]
static bool cbrc::ArgvParser::looksLikeInt (const std::string & s) inline static
Definition at line 495 of file ArgvParser.hh.
References looksLikeInt().
Referenced by looksLikeInt().
looksLikeUnsignedInt() [1/4]
bool cbrc::ArgvParser::looksLikeUnsignedInt (const char *const & s) inline static
Definition at line 1295 of file ArgvParser.hh.
looksLikeUnsignedInt() [2/4]
static bool cbrc::ArgvParser::looksLikeUnsignedInt (const char *const & s) static
looksLikeUnsignedInt() [3/4]
static bool cbrc::ArgvParser::looksLikeUnsignedInt (const std::string & s) inline static
Definition at line 496 of file ArgvParser.hh.
References looksLikeUnsignedInt().
Referenced by looksLikeUnsignedInt().
looksLikeUnsignedInt() [4/4]
static bool cbrc::ArgvParser::looksLikeUnsignedInt (const std::string & s) inline static
Definition at line 496 of file ArgvParser.hh.
References looksLikeUnsignedInt().
Referenced by looksLikeUnsignedInt().
numArgs() [1/2]
int cbrc::ArgvParser::numArgs () const inline
Definition at line 121 of file ArgvParser.hh.
Referenced by printDoc().
numArgs() [2/2]
int cbrc::ArgvParser::numArgs () const inline
Definition at line 121 of file ArgvParser.hh.
numOpts() [1/2]
int cbrc::ArgvParser::numOpts () const inline
Definition at line 122 of file ArgvParser.hh.
numOpts() [2/2]
int cbrc::ArgvParser::numOpts () const inline
Definition at line 122 of file ArgvParser.hh.
open() [1/2]
void cbrc::ArgvParser::open (std::ifstream & ifs, const std::string & pathname) inline
Definition at line 1526 of file ArgvParser.hh.
References GDB_ASSERTF, and pathname().
open() [2/2]
void cbrc::ArgvParser::open (std::ifstream & ifs, const std::string & pathname)
openCautiously() [1/2]
void cbrc::ArgvParser::openCautiously (std::ofstream & ofs, const std::string & pathname) const inline
Definition at line 1546 of file ArgvParser.hh.
References die(), and pathname().
Referenced by setCautiously(), setCautiously(), setCautiouslyOrDie(), and setCautiouslyOrDie().
openCautiously() [2/2]
void cbrc::ArgvParser::openCautiously (std::ofstream & ofs, const std::string & pathname) const
openIstream() [1/2]
std::istream * cbrc::ArgvParser::openIstream (const std::string & pathname) inline
Definition at line 1533 of file ArgvParser.hh.
References GDB_ASSERTF, and pathname().
Referenced by main().
openIstream() [2/2]
std::istream * cbrc::ArgvParser::openIstream (const std::string & pathname)
operator[]() [1/2]
std::string cbrc::ArgvParser::operator[] (const int & index) inline
Definition at line 731 of file ArgvParser.hh.
References argc(), and die().
operator[]() [2/2]
std::string cbrc::ArgvParser::operator[] (const int & index)
pathname() [1/2]
std::string cbrc::ArgvParser::pathname () const inline
Definition at line 106 of file ArgvParser.hh.
Referenced by ArgvParser(), fileExists(), open(), openCautiously(), openIstream(), setCautiously(), setCautiously(), setCautiouslyOrDie(), and setCautiouslyOrDie().
pathname() [2/2]
std::string cbrc::ArgvParser::pathname () const inline
Definition at line 106 of file ArgvParser.hh.
printDoc() [1/2]
void cbrc::ArgvParser::printDoc (const std::string & locale = "") const inline
Definition at line 433 of file ArgvParser.hh.
References numArgs(), and printOptionDoc().
Referenced by dieIfUnusedArgs(), and main().
printDoc() [2/2]
void cbrc::ArgvParser::printDoc (const std::string & locale = "") const inline
Definition at line 433 of file ArgvParser.hh.
References numArgs(), and printOptionDoc().
printOptionDoc() [1/2]
void cbrc::ArgvParser::printOptionDoc (const std::string & optionName, const std::string & locale = "") const inline
Definition at line 1621 of file ArgvParser.hh.
References getDoc(), and cbrc::FLEArray< T >::size().
Referenced by printDoc().
printOptionDoc() [2/2]
void cbrc::ArgvParser::printOptionDoc (const std::string & optionName, const std::string & locale = "") const
set() [1/12]
std::string cbrc::ArgvParser::set (bool & lhs, const std::string & flagSpec) inline
Definition at line 284 of file ArgvParser.hh.
References set().
set() [2/12]
std::string cbrc::ArgvParser::set (bool & lhs, const std::string & flagSpec) inline
Definition at line 284 of file ArgvParser.hh.
References set().
set() [3/12]
std::string cbrc::ArgvParser::set (bool & lhs, const std::vector< std::string > & flags) inline
Definition at line 945 of file ArgvParser.hh.
References die(), getFlag(), and cbrc::FLEArray< T >::size().
set() [4/12]
std::string cbrc::ArgvParser::set (bool & lhs, const std::vector< std::string > & flags)
set() [5/12]
template<typename T > std::string cbrc::ArgvParser::set (T & lhs, const int & posArgIndex) inline
Definition at line 905 of file ArgvParser.hh.
References cbrc::_argvParserNullString(), die(), getArg(), and hasArg().
Referenced by main(), main(), set(), set(), and set().
set() [6/12]
template<typename T > std::string cbrc::ArgvParser::set (T & lhs, const int & posArgIndex)
set() [7/12]
template<typename T > std::string cbrc::ArgvParser::set (T & lhs, const std::string & flag, const std::string & flagAlias) inline
Definition at line 291 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and set().
set() [8/12]
template<typename T > std::string cbrc::ArgvParser::set (T & lhs, const std::string & flag, const std::string & flagAlias) inline
Definition at line 291 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and set().
set() [9/12]
template<typename T > std::string cbrc::ArgvParser::set (T & lhs, const std::string & flagSpec) inline
Definition at line 277 of file ArgvParser.hh.
References set().
set() [10/12]
template<typename T > std::string cbrc::ArgvParser::set (T & lhs, const std::string & flagSpec) inline
Definition at line 277 of file ArgvParser.hh.
References set().
set() [11/12]
template<typename T > std::string cbrc::ArgvParser::set (T & lhs, const std::vector< std::string > & flags) inline
Definition at line 924 of file ArgvParser.hh.
References cbrc::_argvParserNullString(), die(), GDB_ASSERTF, getFlag(), getOpt(), hasOpt(), and cbrc::FLEArray< T >::size().
set() [12/12]
template<typename T > std::string cbrc::ArgvParser::set (T & lhs, const std::vector< std::string > & flags)
setCautiously() [1/8]
std::string cbrc::ArgvParser::setCautiously (std::ofstream & ofs, const int & posArgIndex) inline
Definition at line 1401 of file ArgvParser.hh.
References cbrc::_argvParserNullString(), getArg(), hasArg(), openCautiously(), and pathname().
Referenced by setCautiously(), and setCautiously().
setCautiously() [2/8]
std::string cbrc::ArgvParser::setCautiously (std::ofstream & ofs, const int & posArgIndex)
setCautiously() [3/8]
std::string cbrc::ArgvParser::setCautiously (std::ofstream & ofs, const std::string & flag, const std::string & flagAlias) inline
Definition at line 329 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and setCautiously().
setCautiously() [4/8]
std::string cbrc::ArgvParser::setCautiously (std::ofstream & ofs, const std::string & flag, const std::string & flagAlias) inline
Definition at line 329 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and setCautiously().
setCautiously() [5/8]
std::string cbrc::ArgvParser::setCautiously (std::ofstream & ofs, const std::string & flagSpec) inline
Definition at line 326 of file ArgvParser.hh.
References setCautiously().
setCautiously() [6/8]
std::string cbrc::ArgvParser::setCautiously (std::ofstream & ofs, const std::string & flagSpec) inline
Definition at line 326 of file ArgvParser.hh.
References setCautiously().
setCautiously() [7/8]
std::string cbrc::ArgvParser::setCautiously (std::ofstream & ofs, const std::vector< std::string > & flags) inline
Definition at line 1413 of file ArgvParser.hh.
References cbrc::_argvParserNullString(), die(), getOpt(), hasOpt(), openCautiously(), pathname(), and cbrc::FLEArray< T >::size().
setCautiously() [8/8]
std::string cbrc::ArgvParser::setCautiously (std::ofstream & ofs, const std::vector< std::string > & flags)
setCautiouslyOrDie() [1/8]
std::string cbrc::ArgvParser::setCautiouslyOrDie (std::ofstream & ofs, const int & posArgIndex) inline
Definition at line 1428 of file ArgvParser.hh.
References cbrc::_argvParserNullString(), die(), getArg(), hasArg(), openCautiously(), and pathname().
Referenced by main(), setCautiouslyOrDie(), and setCautiouslyOrDie().
setCautiouslyOrDie() [2/8]
std::string cbrc::ArgvParser::setCautiouslyOrDie (std::ofstream & ofs, const int & posArgIndex)
setCautiouslyOrDie() [3/8]
std::string cbrc::ArgvParser::setCautiouslyOrDie (std::ofstream & ofs, const std::string & flag, const std::string & flagAlias) inline
Definition at line 340 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and setCautiouslyOrDie().
setCautiouslyOrDie() [4/8]
std::string cbrc::ArgvParser::setCautiouslyOrDie (std::ofstream & ofs, const std::string & flag, const std::string & flagAlias) inline
Definition at line 340 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and setCautiouslyOrDie().
setCautiouslyOrDie() [5/8]
std::string cbrc::ArgvParser::setCautiouslyOrDie (std::ofstream & ofs, const std::string & flagSpec) inline
Definition at line 337 of file ArgvParser.hh.
References setCautiouslyOrDie().
setCautiouslyOrDie() [6/8]
std::string cbrc::ArgvParser::setCautiouslyOrDie (std::ofstream & ofs, const std::string & flagSpec) inline
Definition at line 337 of file ArgvParser.hh.
References setCautiouslyOrDie().
setCautiouslyOrDie() [7/8]
std::string cbrc::ArgvParser::setCautiouslyOrDie (std::ofstream & ofs, const std::vector< std::string > & flags) inline
Definition at line 1448 of file ArgvParser.hh.
References cbrc::_argvParserNullString(), die(), getOpt(), hasOpt(), openCautiously(), pathname(), and cbrc::FLEArray< T >::size().
setCautiouslyOrDie() [8/8]
std::string cbrc::ArgvParser::setCautiouslyOrDie (std::ofstream & ofs, const std::vector< std::string > & flags)
setDoc() [1/2]
void cbrc::ArgvParser::setDoc (const std::string & optionNamesVBarList, const std::string & optionValue, const std::string & locale = "C") inline
Definition at line 1663 of file ArgvParser.hh.
Referenced by ArgvParser(), and main().
setDoc() [2/2]
void cbrc::ArgvParser::setDoc (const std::string & optionNamesVBarList, const std::string & optionValue, const std::string & locale = "C")
setFromNextUnused() [1/2]
template<typename T > const char *const cbrc::ArgvParser::setFromNextUnused (T & lhs) inline
Definition at line 386 of file ArgvParser.hh.
References shift(), and cbrc::FLEArray< T >::size().
setFromNextUnused() [2/2]
template<typename T > const char *const cbrc::ArgvParser::setFromNextUnused (T & lhs) inline
Definition at line 386 of file ArgvParser.hh.
References shift(), and cbrc::FLEArray< T >::size().
setOrDie() [1/8]
template<typename T > std::string cbrc::ArgvParser::setOrDie (T & lhs, const int & posArgIndex) inline
Definition at line 957 of file ArgvParser.hh.
References cbrc::_argvParserNullString(), die(), getArg(), and hasArg().
Referenced by main(), setOrDie(), and setOrDie().
setOrDie() [2/8]
template<typename T > std::string cbrc::ArgvParser::setOrDie (T & lhs, const int & posArgIndex)
setOrDie() [3/8]
template<typename T > std::string cbrc::ArgvParser::setOrDie (T & lhs, const std::string & flag, const std::string & flagAlias) inline
Definition at line 317 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and setOrDie().
setOrDie() [4/8]
template<typename T > std::string cbrc::ArgvParser::setOrDie (T & lhs, const std::string & flag, const std::string & flagAlias) inline
Definition at line 317 of file ArgvParser.hh.
References _ARGVPARSER_MAKE_2_FLAGS_VECTOR, and setOrDie().
setOrDie() [5/8]
template<typename T > std::string cbrc::ArgvParser::setOrDie (T & lhs, const std::string & flagSpec) inline
Definition at line 311 of file ArgvParser.hh.
References setOrDie().
setOrDie() [6/8]
template<typename T > std::string cbrc::ArgvParser::setOrDie (T & lhs, const std::string & flagSpec) inline
Definition at line 311 of file ArgvParser.hh.
References setOrDie().
setOrDie() [7/8]
template<typename T > std::string cbrc::ArgvParser::setOrDie (T & lhs, const std::vector< std::string > & flags) inline
Definition at line 986 of file ArgvParser.hh.
References cbrc::_argvParserNullString(), die(), getFlag(), getOpt(), hasOpt(), and cbrc::FLEArray< T >::size().
setOrDie() [8/8]
template<typename T > std::string cbrc::ArgvParser::setOrDie (T & lhs, const std::vector< std::string > & flags)
shift() [1/2]
std::string cbrc::ArgvParser::shift () inline
Definition at line 877 of file ArgvParser.hh.
References cbrc::_argvParserNullString(), argc(), and size().
Referenced by setFromNextUnused(), and shiftOrDie().
shift() [2/2]
std::string cbrc::ArgvParser::shift ()
shiftMandatoryUsedOk() [1/2]
std::string cbrc::ArgvParser::shiftMandatoryUsedOk ()
Definition at line 46 of file ArgvParser.cc.
References argc(), and die().
shiftMandatoryUsedOk() [2/2]
std::string cbrc::ArgvParser::shiftMandatoryUsedOk ()
shiftOrDie() [1/2]
std::string cbrc::ArgvParser::shiftOrDie () inline
Definition at line 895 of file ArgvParser.hh.
References argc(), die(), and shift().
shiftOrDie() [2/2]
std::string cbrc::ArgvParser::shiftOrDie ()
shiftUsedOk() [1/2]
std::string cbrc::ArgvParser::shiftUsedOk ()
Definition at line 35 of file ArgvParser.cc.
References argc().
shiftUsedOk() [2/2]
std::string cbrc::ArgvParser::shiftUsedOk ()
size() [1/2]
size_t cbrc::ArgvParser::size () const inline
Definition at line 120 of file ArgvParser.hh.
Referenced by dumpArgvInfo(), and shift().
size() [2/2]
size_t cbrc::ArgvParser::size () const inline
Definition at line 120 of file ArgvParser.hh.
unusedArgs() [1/2]
std::vector< std::string > cbrc::ArgvParser::unusedArgs () const inline
Definition at line 1728 of file ArgvParser.hh.
Referenced by dieIfUnusedArgs().
unusedArgs() [2/2]
std::vector< std::string > cbrc::ArgvParser::unusedArgs () const
usage() [1/2]
std::string cbrc::ArgvParser::usage () const inline
Definition at line 425 of file ArgvParser.hh.
Referenced by ArgvParser(), and die().
usage() [2/2]
std::string cbrc::ArgvParser::usage () const inline
Definition at line 425 of file ArgvParser.hh.
useStdinIndicator() [1/2]
static const std::string & cbrc::ArgvParser::useStdinIndicator () inline static
Definition at line 66 of file ArgvParser.hh.
useStdinIndicator() [2/2]
static const std::string & cbrc::ArgvParser::useStdinIndicator () inline static
Definition at line 66 of file ArgvParser.hh.
yesNoFlag() [1/2]
bool cbrc::ArgvParser::yesNoFlag (const std::string opt)
Definition at line 18 of file ArgvParser.cc.
References die().
yesNoFlag() [2/2]
bool cbrc::ArgvParser::yesNoFlag (const std::string opt)
The documentation for this class was generated from the following files:
ematch_src/utils/argvParsing/ArgvParser.hh
knapsack_src/utils/argvParsing/ArgvParser.hh
ematch_src/utils/argvParsing/ArgvParser.cc
knapsack_src/utils/argvParsing/ArgvParser.cc