NGSFeatures: cbrc::FastafmtInputOptions Class Reference
cbrc::FastafmtInputOptions Class Reference
#include <FastafmtInputOptions.hh>
Public Member Functions
FastafmtInputOptions (const boost::regex &betweenLabelsDelimiterRegex=defaultBetweenLabelsDelimiterRegex(), const boost::regex &beforeNameDelimiterRegex=defaultBeforeNameDelimiterRegex())
const boost::regex & betweenLabelsDelimiterRegex () const
const boost::regex & beforeNameDelimiterRegex () const
void setBetweenLabelsDelimiterRegex (const boost::regex &betweenLabelsDelimiterRegex)
void setBeforeNameDelimiterRegex (const boost::regex &beforeNameDelimiterRegex)
Static Public Member Functions
static const boost::regex & defaultBetweenLabelsDelimiterRegex ()
static const boost::regex & defaultBeforeNameDelimiterRegex ()
Detailed Description
Definition at line 18 of file FastafmtInputOptions.hh.
Constructor & Destructor Documentation
FastafmtInputOptions()
cbrc::FastafmtInputOptions::FastafmtInputOptions (const boost::regex & betweenLabelsDelimiterRegex = defaultBetweenLabelsDelimiterRegex(), const boost::regex & beforeNameDelimiterRegex = defaultBeforeNameDelimiterRegex()) inline
Definition at line 21 of file FastafmtInputOptions.hh.
Member Function Documentation
beforeNameDelimiterRegex()
const boost::regex & cbrc::FastafmtInputOptions::beforeNameDelimiterRegex () const inline
Definition at line 34 of file FastafmtInputOptions.hh.
Referenced by setBeforeNameDelimiterRegex().
betweenLabelsDelimiterRegex()
const boost::regex & cbrc::FastafmtInputOptions::betweenLabelsDelimiterRegex () const inline
Definition at line 30 of file FastafmtInputOptions.hh.
Referenced by setBetweenLabelsDelimiterRegex().
defaultBeforeNameDelimiterRegex()
static const boost::regex & cbrc::FastafmtInputOptions::defaultBeforeNameDelimiterRegex () inline static
Definition at line 53 of file FastafmtInputOptions.hh.
defaultBetweenLabelsDelimiterRegex()
static const boost::regex & cbrc::FastafmtInputOptions::defaultBetweenLabelsDelimiterRegex () inline static
Definition at line 48 of file FastafmtInputOptions.hh.
setBeforeNameDelimiterRegex()
void cbrc::FastafmtInputOptions::setBeforeNameDelimiterRegex (const boost::regex & beforeNameDelimiterRegex) inline
Definition at line 42 of file FastafmtInputOptions.hh.
References beforeNameDelimiterRegex().
setBetweenLabelsDelimiterRegex()
void cbrc::FastafmtInputOptions::setBetweenLabelsDelimiterRegex (const boost::regex & betweenLabelsDelimiterRegex) inline
Definition at line 38 of file FastafmtInputOptions.hh.
References betweenLabelsDelimiterRegex().
The documentation for this class was generated from the following file:
ematch_src/utils/sequence/fastafmt/FastafmtInputOptions.hh