NGSFeatures: cbrc::StringHashtable Class Reference
cbrc::StringHashtable Class Reference
#include <StringHashtable.hh>
Public Types
enum fileFormatT { binary , text }
Public Member Functions
StringHashtable (const size_t size=11)
StringHashtable (const StringHashtable &ht)
StringHashtable operator= (const StringHashtable &ht)
void copy (const StringHashtable &ht)
~StringHashtable ()
void clear ()
size_t size () const
StringHashtableIterator begin () const
const StringHashtableIterator & end () const
std::vector< std::pair< std::string, std::string > > contentsAsVector () const
bool has (const std::string &key) const
const std::string & operator() (const std::string &key) const
std::string & operator[] (const std::string &key)
std::string & insertKeyIfNew_returnValue (const std::string &key, const bool resizeAllowed=true)
KeyValuePair * add (const KeyValuePair &elem, const bool resizeAllowed=true)
void printTableState (std::ostream &os)
Static Public Member Functions
static const std::string & notFoundValue ()
static const std::string & defaultInsertionValue ()
static size_t maxAllowedLinkListLength ()
Detailed Description
Definition at line 175 of file StringHashtable.hh.
Member Enumeration Documentation
fileFormatT
enum cbrc::StringHashtable::fileFormatT
Enumerator
binary
text
Definition at line 178 of file StringHashtable.hh.
Constructor & Destructor Documentation
StringHashtable() [1/2]
cbrc::StringHashtable::StringHashtable (const size_t size = 11) inline
Definition at line 182 of file StringHashtable.hh.
References cbrc::nextPrime(), and size().
StringHashtable() [2/2]
cbrc::StringHashtable::StringHashtable (const StringHashtable & ht) inline
Definition at line 190 of file StringHashtable.hh.
References copy().
~StringHashtable()
cbrc::StringHashtable::~StringHashtable () inline
Definition at line 221 of file StringHashtable.hh.
References clear().
Member Function Documentation
add()
KeyValuePair * cbrc::StringHashtable::add (const KeyValuePair & elem, const bool resizeAllowed = true) inline
add to head of list at position index.
Definition at line 342 of file StringHashtable.hh.
References add(), cbrc::StringHashtableLink::elem(), cbrc::StringHashtableLink::elemPtr(), cbrc::KeyValuePair::hashValue(), cbrc::KeyValuePair::keyEquals(), maxAllowedLinkListLength(), cbrc::StringHashtableLink::next(), and cbrc::StringHashtableLink::setNext().
Referenced by add().
begin()
StringHashtableIterator cbrc::StringHashtable::begin () const inline
Definition at line 253 of file StringHashtable.hh.
References GDB_ASSERTF, cbrc::StringHashtableIterator::makeInvalidIterator(), and size().
Referenced by contentsAsVector().
clear()
void cbrc::StringHashtable::clear () inline
Definition at line 238 of file StringHashtable.hh.
Referenced by ~StringHashtable().
contentsAsVector()
std::vector< std::pair< std::string, std::string > > cbrc::StringHashtable::contentsAsVector () const inline
Definition at line 267 of file StringHashtable.hh.
References begin(), end(), and size().
copy()
void cbrc::StringHashtable::copy (const StringHashtable & ht) inline
Definition at line 198 of file StringHashtable.hh.
References RUNTIME_WARN.
Referenced by operator=(), and StringHashtable().
defaultInsertionValue()
static const std::string & cbrc::StringHashtable::defaultInsertionValue () inline static
Definition at line 229 of file StringHashtable.hh.
Referenced by insertKeyIfNew_returnValue().
end()
const StringHashtableIterator & cbrc::StringHashtable::end () const inline
Definition at line 264 of file StringHashtable.hh.
Referenced by contentsAsVector().
has()
bool cbrc::StringHashtable::has (const std::string & key) const inline
Definition at line 276 of file StringHashtable.hh.
References cbrc::StringHashtableLink::elem(), cbrc::StringHashtableLink::next(), and stringHashValue().
insertKeyIfNew_returnValue()
std::string & cbrc::StringHashtable::insertKeyIfNew_returnValue (const std::string & key, const bool resizeAllowed = true) inline
add to head of list at position index
Definition at line 307 of file StringHashtable.hh.
References defaultInsertionValue(), cbrc::StringHashtableLink::elem(), insertKeyIfNew_returnValue(), maxAllowedLinkListLength(), cbrc::StringHashtableLink::next(), cbrc::StringHashtableLink::setNext(), stringHashValue(), and cbrc::StringHashtableLink::valueRef().
Referenced by insertKeyIfNew_returnValue(), and operator[]().
maxAllowedLinkListLength()
static size_t cbrc::StringHashtable::maxAllowedLinkListLength () inline static
Definition at line 236 of file StringHashtable.hh.
Referenced by add(), and insertKeyIfNew_returnValue().
notFoundValue()
static const std::string & cbrc::StringHashtable::notFoundValue () inline static
Definition at line 224 of file StringHashtable.hh.
Referenced by operator()().
operator()()
const std::string & cbrc::StringHashtable::operator() (const std::string & key) const inline
Definition at line 288 of file StringHashtable.hh.
References cbrc::StringHashtableLink::elem(), cbrc::StringHashtableLink::next(), notFoundValue(), and stringHashValue().
operator=()
StringHashtable cbrc::StringHashtable::operator= (const StringHashtable & ht) inline
Definition at line 193 of file StringHashtable.hh.
References copy().
operator[]()
std::string & cbrc::StringHashtable::operator[] (const std::string & key) inline
Definition at line 304 of file StringHashtable.hh.
References insertKeyIfNew_returnValue().
printTableState()
void cbrc::StringHashtable::printTableState (std::ostream & os) inline
Definition at line 431 of file StringHashtable.hh.
References cbrc::StringHashtableLink::key(), cbrc::StringHashtableLink::next(), and cbrc::StringHashtableLink::value().
size()
size_t cbrc::StringHashtable::size () const inline
Definition at line 251 of file StringHashtable.hh.
Referenced by begin(), contentsAsVector(), and StringHashtable().
The documentation for this class was generated from the following file:
ematch_src/utils/ChainHashtable/StringHashtable.hh