NGSFeatures: cbrc::KnapsackEnumerator Class Reference
cbrc::KnapsackEnumerator Class Reference
#include <KnapsackEnumerator.hh>
Public Types
typedef KnapsackObject::weightT weightT
typedef KnapsackObject::idT idT
typedef std::vector< idT > idVecT
typedef std::vector< idVecT > objectCombinationsVecT
Public Member Functions
KnapsackEnumerator (const weightT &capacity)
const double & capacity ()
const std::vector< idVecT > & combinations ()
const KnapsackObjectVector & objectUniverse () const
void computeCombinations (const KnapsackObjectVector &objects)
Friends
void tryKnapsackEnumerator ()
Detailed Description
Definition at line 26 of file KnapsackEnumerator.hh.
Member Typedef Documentation
idT
typedef KnapsackObject::idT cbrc::KnapsackEnumerator::idT
Definition at line 31 of file KnapsackEnumerator.hh.
idVecT
typedef std::vector<idT> cbrc::KnapsackEnumerator::idVecT
Definition at line 33 of file KnapsackEnumerator.hh.
objectCombinationsVecT
typedef std::vector<idVecT> cbrc::KnapsackEnumerator::objectCombinationsVecT
Definition at line 35 of file KnapsackEnumerator.hh.
weightT
typedef KnapsackObject::weightT cbrc::KnapsackEnumerator::weightT
Definition at line 30 of file KnapsackEnumerator.hh.
Constructor & Destructor Documentation
KnapsackEnumerator()
cbrc::KnapsackEnumerator::KnapsackEnumerator (const weightT & capacity) inline
Definition at line 41 of file KnapsackEnumerator.hh.
Member Function Documentation
capacity()
const double & cbrc::KnapsackEnumerator::capacity () inline
Definition at line 51 of file KnapsackEnumerator.hh.
Referenced by computeCombinations().
combinations()
const std::vector< idVecT > & cbrc::KnapsackEnumerator::combinations () inline
Definition at line 54 of file KnapsackEnumerator.hh.
computeCombinations()
void cbrc::KnapsackEnumerator::computeCombinations (const KnapsackObjectVector & objects)
Definition at line 14 of file KnapsackEnumerator.cc.
References cbrc::KnapsackObjectVector::begin(), capacity(), cbrc::KnapsackObjectVector::end(), objectUniverse(), and cbrc::FLEArray< T >::size().
objectUniverse()
const KnapsackObjectVector & cbrc::KnapsackEnumerator::objectUniverse () const inline
Definition at line 56 of file KnapsackEnumerator.hh.
Referenced by computeCombinations().
Friends And Related Symbol Documentation
tryKnapsackEnumerator
void tryKnapsackEnumerator () friend
The documentation for this class was generated from the following files:
knapsack_src/KnapsackEnumerator.hh
knapsack_src/KnapsackEnumerator.cc