NGSFeatures: cbrc::ResidueIndexMapTranslator Class Reference
cbrc::ResidueIndexMapTranslator Class Reference
#include <ResidueIndexMapTranslator.hh>
Public Types
typedef ResidueIndexMap::indexT residueIndexT
typedef std::vector< std::string > stringVecT
Public Member Functions
ResidueIndexMapTranslator (const ResidueIndexMap &nucleicResidueIndexMap, const ResidueIndexMap &aminoResidueIndexMap, const std::string &codonTableDescriptor)
void translateInPlace (const residueIndexT *const &nucleicBeg, const residueIndexT *const &nucleicEnd, residueIndexT *const &aminoBeg, const residueIndexT *&aminoEnd) const
Detailed Description
Definition at line 25 of file ResidueIndexMapTranslator.hh.
Member Typedef Documentation
residueIndexT
typedef ResidueIndexMap::indexT cbrc::ResidueIndexMapTranslator::residueIndexT
Definition at line 28 of file ResidueIndexMapTranslator.hh.
stringVecT
typedef std::vector<std::string> cbrc::ResidueIndexMapTranslator::stringVecT
Definition at line 30 of file ResidueIndexMapTranslator.hh.
Constructor & Destructor Documentation
ResidueIndexMapTranslator()
cbrc::ResidueIndexMapTranslator::ResidueIndexMapTranslator (const ResidueIndexMap & nucleicResidueIndexMap, const ResidueIndexMap & aminoResidueIndexMap, const std::string & codonTableDescriptor)
Definition at line 19 of file ResidueIndexMapTranslator.cc.
References cbrc::aminoResidueIndexMap, cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), cbrc::FLEArray< T >::fill(), GDB_ASSERTF, cbrc::FLEArray< T >::setSize(), cbrc::FLEArray< T >::size(), cbrc::perlish::split(), STOP_CODON_INDEX, cbrc::ResidueIndexMap::toResidueIndices(), and UNDERTERMINED_CODON_INDEX.
Member Function Documentation
translateInPlace()
void cbrc::ResidueIndexMapTranslator::translateInPlace (const residueIndexT *const & nucleicBeg, const residueIndexT *const & nucleicEnd, residueIndexT *const & aminoBeg, const residueIndexT *& aminoEnd) const
Definition at line 98 of file ResidueIndexMapTranslator.cc.
References cbrc::FLEArray< T >::FLEArray(), GDB_ASSERTF, STOP_CODON_INDEX, and UNDERTERMINED_CODON_INDEX.
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/ResidueIndexMap/ResidueIndexMapTranslator.hh
ematch_src/utils/sequence/ResidueIndexMap/ResidueIndexMapTranslator.cc