NGSFeatures: cbrc::Point2D< XT, YT > Class Template Reference
cbrc::Point2D< XT, YT > Class Template Reference
#include <Point2D.hh>
Classes
class TolerantYCompare
Public Member Functions
Point2D ()
Point2D (XT x, YT y)
XT x () const
YT y () const
void set (XT x, YT y)
void swapXY ()
void setX (XT x)
void setY (YT y)
void averageWith (const Point2D< XT, YT > &p)
Point2D< XT, YT > & operator+= (const Point2D< XT, YT > &p)
Point2D< XT, YT > operator+ (const Point2D &p) const
Point2D< XT, YT > operator* (const YT scalar) const
Point2D< XT, YT > operator/ (const YT scalar) const
Static Public Member Functions
static bool xLess (const Point2D< XT, YT > &p0, const Point2D< XT, YT > &p1)
static bool yLess (const Point2D< XT, YT > &p0, const Point2D< XT, YT > &p1)
static bool xGreater (const Point2D< XT, YT > &p0, const Point2D< XT, YT > &p1)
static bool yGreater (const Point2D< XT, YT > &p0, const Point2D< XT, YT > &p1)
static bool xAscending (const Point2D< XT, YT > &p0, const Point2D< XT, YT > &p1)
static bool xDescending (const Point2D< XT, YT > &p0, const Point2D< XT, YT > &p1)
static bool yDescending (const Point2D< XT, YT > &p0, const Point2D< XT, YT > &p1)
static bool nonFinite (const Point2D< XT, YT > &p)
Friends
void testPoint2D ()
Detailed Description
template<typename XT, typename YT>
class cbrc::Point2D< XT, YT >
Definition at line 19 of file Point2D.hh.
Constructor & Destructor Documentation
Point2D() [1/2]
template<typename XT , typename YT > cbrc::Point2D< XT, YT >::Point2D () inline
Definition at line 21 of file Point2D.hh.
Point2D() [2/2]
template<typename XT , typename YT > cbrc::Point2D< XT, YT >::Point2D (XT x, YT y) inline
Definition at line 22 of file Point2D.hh.
Member Function Documentation
averageWith()
template<typename XT , typename YT > void cbrc::Point2D< XT, YT >::averageWith (const Point2D< XT, YT > & p) inline
Definition at line 65 of file Point2D.hh.
nonFinite()
template<typename XT , typename YT > static bool cbrc::Point2D< XT, YT >::nonFinite (const Point2D< XT, YT > & p) inline static
Definition at line 54 of file Point2D.hh.
operator*()
template<typename XT , typename YT > Point2D< XT, YT > cbrc::Point2D< XT, YT >::operator* (const YT scalar) const inline
Definition at line 82 of file Point2D.hh.
References cbrc::Point2D< XT, YT >::x(), and cbrc::Point2D< XT, YT >::y().
operator+()
template<typename XT , typename YT > Point2D< XT, YT > cbrc::Point2D< XT, YT >::operator+ (const Point2D< XT, YT > & p) const inline
Definition at line 78 of file Point2D.hh.
References cbrc::Point2D< XT, YT >::x(), and cbrc::Point2D< XT, YT >::y().
operator+=()
template<typename XT , typename YT > Point2D< XT, YT > & cbrc::Point2D< XT, YT >::operator+= (const Point2D< XT, YT > & p) inline
Definition at line 73 of file Point2D.hh.
operator/()
template<typename XT , typename YT > Point2D< XT, YT > cbrc::Point2D< XT, YT >::operator/ (const YT scalar) const inline
Definition at line 85 of file Point2D.hh.
References cbrc::Point2D< XT, YT >::x(), and cbrc::Point2D< XT, YT >::y().
set()
template<typename XT , typename YT > void cbrc::Point2D< XT, YT >::set (XT x, YT y) inline
Definition at line 25 of file Point2D.hh.
References cbrc::Point2D< XT, YT >::x(), and cbrc::Point2D< XT, YT >::y().
setX()
template<typename XT , typename YT > void cbrc::Point2D< XT, YT >::setX (XT x) inline
Definition at line 63 of file Point2D.hh.
References cbrc::Point2D< XT, YT >::x().
setY()
template<typename XT , typename YT > void cbrc::Point2D< XT, YT >::setY (YT y) inline
Definition at line 64 of file Point2D.hh.
References cbrc::Point2D< XT, YT >::y().
swapXY()
template<typename XT , typename YT > void cbrc::Point2D< XT, YT >::swapXY () inline
Definition at line 27 of file Point2D.hh.
x()
template<typename XT , typename YT > XT cbrc::Point2D< XT, YT >::x () const inline
Definition at line 23 of file Point2D.hh.
Referenced by cbrc::Point2D< XT, YT >::operator*(), cbrc::Point2D< XT, YT >::operator+(), cbrc::Point2D< XT, YT >::operator/(), cbrc::Point2D< XT, YT >::set(), and cbrc::Point2D< XT, YT >::setX().
xAscending()
template<typename XT , typename YT > static bool cbrc::Point2D< XT, YT >::xAscending (const Point2D< XT, YT > & p0, const Point2D< XT, YT > & p1) inline static
Definition at line 51 of file Point2D.hh.
xDescending()
template<typename XT , typename YT > static bool cbrc::Point2D< XT, YT >::xDescending (const Point2D< XT, YT > & p0, const Point2D< XT, YT > & p1) inline static
Definition at line 52 of file Point2D.hh.
xGreater()
template<typename XT , typename YT > static bool cbrc::Point2D< XT, YT >::xGreater (const Point2D< XT, YT > & p0, const Point2D< XT, YT > & p1) inline static
Definition at line 49 of file Point2D.hh.
xLess()
template<typename XT , typename YT > static bool cbrc::Point2D< XT, YT >::xLess (const Point2D< XT, YT > & p0, const Point2D< XT, YT > & p1) inline static
Definition at line 31 of file Point2D.hh.
y()
template<typename XT , typename YT > YT cbrc::Point2D< XT, YT >::y () const inline
Definition at line 24 of file Point2D.hh.
Referenced by cbrc::Point2D< XT, YT >::operator*(), cbrc::Point2D< XT, YT >::operator+(), cbrc::Point2D< XT, YT >::operator/(), cbrc::Point2D< XT, YT >::set(), and cbrc::Point2D< XT, YT >::setY().
yDescending()
template<typename XT , typename YT > static bool cbrc::Point2D< XT, YT >::yDescending (const Point2D< XT, YT > & p0, const Point2D< XT, YT > & p1) inline static
Definition at line 53 of file Point2D.hh.
yGreater()
template<typename XT , typename YT > static bool cbrc::Point2D< XT, YT >::yGreater (const Point2D< XT, YT > & p0, const Point2D< XT, YT > & p1) inline static
Definition at line 50 of file Point2D.hh.
yLess()
template<typename XT , typename YT > static bool cbrc::Point2D< XT, YT >::yLess (const Point2D< XT, YT > & p0, const Point2D< XT, YT > & p1) inline static
Definition at line 48 of file Point2D.hh.
Friends And Related Symbol Documentation
testPoint2D
template<typename XT , typename YT > void testPoint2D () friend
The documentation for this class was generated from the following file:
ematch_src/utils/geometry/Point2D.hh