NGSFeatures: cbrc::StringKeyHashtable< ValT > Class Template Reference
cbrc::StringKeyHashtable< ValT > Class Template Reference
#include <StringKeyHashtable.hh>
Public Member Functions
StringKeyHashtable (const ValT defaultValue=1, const size_t size=11, const size_t maxTSize=1796359771)
StringKeyHashtable (const StringKeyHashtable< ValT > &ht)
StringKeyHashtable< ValT > operator= (const StringKeyHashtable< ValT > &ht)
void copy (const StringKeyHashtable< ValT > &ht)
~StringKeyHashtable ()
void setNotFoundValue (const ValT val)
void clear ()
size_t size () const
StringKeyHashIterator< ValT > begin () const
const StringKeyHashIterator< ValT > & end () const
std::vector< std::pair< std::string, ValT > > contentsAsVector () const
bool has (const std::string s) const
ValT operator() (const std::string s) const
ValT & operator[] (const std::string s)
StringKeyAndValue< ValT > * find (const StringKeyAndValue< ValT > &elem)
ValT & add2 (const std::string &s, bool resizeAllowed=true)
StringKeyAndValue< ValT > * add (const StringKeyAndValue< ValT > &elem, bool resizeAllowed=true)
Detailed Description
template<typename ValT>
class cbrc::StringKeyHashtable< ValT >
Definition at line 151 of file StringKeyHashtable.hh.
Constructor & Destructor Documentation
StringKeyHashtable() [1/2]
template<typename ValT > cbrc::StringKeyHashtable< ValT >::StringKeyHashtable (const ValT defaultValue = 1, const size_t size = 11, const size_t maxTSize = 1796359771) inline
Definition at line 145 of file StringKeyHashtable.hh.
StringKeyHashtable() [2/2]
template<typename ValT > cbrc::StringKeyHashtable< ValT >::StringKeyHashtable (const StringKeyHashtable< ValT > & ht) inline
Definition at line 145 of file StringKeyHashtable.hh.
~StringKeyHashtable()
template<typename ValT > cbrc::StringKeyHashtable< ValT >::~StringKeyHashtable () inline
Definition at line 192 of file StringKeyHashtable.hh.
References cbrc::StringKeyHashtable< ValT >::clear().
Member Function Documentation
add()
template<typename ValT > StringKeyAndValue< ValT > * cbrc::StringKeyHashtable< ValT >::add (const StringKeyAndValue< ValT > & elem, bool resizeAllowed = true) inline
Definition at line 294 of file StringKeyHashtable.hh.
References cbrc::StringKeyHashtable< ValT >::add(), and GDB_ASSERTF.
Referenced by cbrc::StringKeyHashtable< ValT >::add().
add2()
template<typename ValT > ValT & cbrc::StringKeyHashtable< ValT >::add2 (const std::string & s, bool resizeAllowed = true) inline
Definition at line 261 of file StringKeyHashtable.hh.
References cbrc::StringKeyHashtable< ValT >::add2(), GDB_ASSERTF, and stringHashValue().
Referenced by cbrc::StringKeyHashtable< ValT >::add2(), and cbrc::StringKeyHashtable< ValT >::operator[]().
begin()
template<typename ValT > StringKeyHashIterator< ValT > cbrc::StringKeyHashtable< ValT >::begin () const inline
Definition at line 208 of file StringKeyHashtable.hh.
References GDB_ASSERTF, cbrc::StringKeyHashIterator< ValT >::makeInvalidIterator(), and cbrc::StringKeyHashtable< ValT >::size().
Referenced by cbrc::StringKeyHashtable< ValT >::contentsAsVector().
clear()
template<typename ValT > void cbrc::StringKeyHashtable< ValT >::clear () inline
Definition at line 194 of file StringKeyHashtable.hh.
Referenced by cbrc::StringKeyHashtable< ValT >::~StringKeyHashtable().
contentsAsVector()
template<typename ValT > std::vector< std::pair< std::string, ValT > > cbrc::StringKeyHashtable< ValT >::contentsAsVector () const inline
Definition at line 217 of file StringKeyHashtable.hh.
References cbrc::StringKeyHashtable< ValT >::begin(), cbrc::StringKeyHashtable< ValT >::end(), and cbrc::StringKeyHashtable< ValT >::size().
copy()
template<typename ValT > void cbrc::StringKeyHashtable< ValT >::copy (const StringKeyHashtable< ValT > & ht) inline
Definition at line 173 of file StringKeyHashtable.hh.
References RUNTIME_WARN.
Referenced by cbrc::StringKeyHashtable< ValT >::operator=().
end()
template<typename ValT > const StringKeyHashIterator< ValT > & cbrc::StringKeyHashtable< ValT >::end () const inline
Definition at line 216 of file StringKeyHashtable.hh.
Referenced by cbrc::StringKeyHashtable< ValT >::contentsAsVector().
find()
template<typename ValT > StringKeyAndValue< ValT > * cbrc::StringKeyHashtable< ValT >::find (const StringKeyAndValue< ValT > & elem) inline
Definition at line 250 of file StringKeyHashtable.hh.
has()
template<typename ValT > bool cbrc::StringKeyHashtable< ValT >::has (const std::string s) const inline
Definition at line 225 of file StringKeyHashtable.hh.
References stringHashValue().
Referenced by cbrc::LabeledSequences::has(), cbrc::Blast8ResultReader::has(), and cbrc::Blast8ResultReader::operator()().
operator()()
template<typename ValT > ValT cbrc::StringKeyHashtable< ValT >::operator() (const std::string s) const inline
Definition at line 233 of file StringKeyHashtable.hh.
References stringHashValue().
operator=()
template<typename ValT > StringKeyHashtable< ValT > cbrc::StringKeyHashtable< ValT >::operator= (const StringKeyHashtable< ValT > & ht) inline
Definition at line 169 of file StringKeyHashtable.hh.
References cbrc::StringKeyHashtable< ValT >::copy().
operator[]()
template<typename ValT > ValT & cbrc::StringKeyHashtable< ValT >::operator[] (const std::string s) inline
Definition at line 241 of file StringKeyHashtable.hh.
References cbrc::StringKeyHashtable< ValT >::add2(), and stringHashValue().
setNotFoundValue()
template<typename ValT > void cbrc::StringKeyHashtable< ValT >::setNotFoundValue (const ValT val) inline
Definition at line 193 of file StringKeyHashtable.hh.
size()
template<typename ValT > size_t cbrc::StringKeyHashtable< ValT >::size () const inline
Definition at line 207 of file StringKeyHashtable.hh.
Referenced by cbrc::StringKeyHashtable< ValT >::begin(), and cbrc::StringKeyHashtable< ValT >::contentsAsVector().
The documentation for this class was generated from the following file:
ematch_src/utils/ChainHashtable/StringKeyHashtable.hh