NGSFeatures: cbrc::StringHashtableLink Class Reference
cbrc::StringHashtableLink Class Reference
#include <StringHashtable.hh>
Public Member Functions
StringHashtableLink (const StringHashtableLink &link)
StringHashtableLink (const KeyValuePair &elem)
StringHashtableLink (const std::string &key, const std::string &value)
~StringHashtableLink ()
StringHashtableLink *const next () const
void setNext (StringHashtableLink *const &next)
const std::string & key () const
const std::string & value () const
std::string & valueRef ()
const KeyValuePair & elem () const
KeyValuePair * elemPtr ()
Public Attributes
KeyValuePair _elem
StringHashtableLink * _next
Friends
class StringHashtable
class KeyValuePair
class StringKeyHashIterator
Detailed Description
Definition at line 72 of file StringHashtable.hh.
Constructor & Destructor Documentation
StringHashtableLink() [1/3]
cbrc::StringHashtableLink::StringHashtableLink (const StringHashtableLink & link) inline
Definition at line 77 of file StringHashtable.hh.
StringHashtableLink() [2/3]
cbrc::StringHashtableLink::StringHashtableLink (const KeyValuePair & elem) inline
Definition at line 81 of file StringHashtable.hh.
StringHashtableLink() [3/3]
cbrc::StringHashtableLink::StringHashtableLink (const std::string & key, const std::string & value) inline
Definition at line 85 of file StringHashtable.hh.
~StringHashtableLink()
cbrc::StringHashtableLink::~StringHashtableLink () inline
Definition at line 90 of file StringHashtable.hh.
Member Function Documentation
elem()
const KeyValuePair & cbrc::StringHashtableLink::elem () const inline
Definition at line 101 of file StringHashtable.hh.
References _elem.
Referenced by cbrc::StringHashtable::add(), cbrc::StringHashtable::has(), cbrc::StringHashtable::insertKeyIfNew_returnValue(), key(), cbrc::StringHashtable::operator()(), and value().
elemPtr()
KeyValuePair * cbrc::StringHashtableLink::elemPtr () inline
Definition at line 102 of file StringHashtable.hh.
References _elem.
Referenced by cbrc::StringHashtable::add(), and cbrc::StringHashtableIterator::elemPtr().
key()
const std::string & cbrc::StringHashtableLink::key () const inline
Definition at line 96 of file StringHashtable.hh.
References elem().
Referenced by cbrc::StringHashtable::printTableState().
next()
StringHashtableLink *const cbrc::StringHashtableLink::next () const inline
Definition at line 92 of file StringHashtable.hh.
References _next.
Referenced by cbrc::StringHashtable::add(), cbrc::StringHashtable::has(), cbrc::StringHashtable::insertKeyIfNew_returnValue(), cbrc::StringHashtable::operator()(), cbrc::StringHashtableIterator::operator++(), cbrc::StringHashtable::printTableState(), and setNext().
setNext()
void cbrc::StringHashtableLink::setNext (StringHashtableLink *const & next) inline
Definition at line 93 of file StringHashtable.hh.
References _next, and next().
Referenced by cbrc::StringHashtable::add(), and cbrc::StringHashtable::insertKeyIfNew_returnValue().
value()
const std::string & cbrc::StringHashtableLink::value () const inline
Definition at line 97 of file StringHashtable.hh.
References elem().
Referenced by cbrc::StringHashtable::printTableState().
valueRef()
std::string & cbrc::StringHashtableLink::valueRef () inline
Definition at line 99 of file StringHashtable.hh.
References _elem, and cbrc::KeyValuePair::valueRef().
Referenced by cbrc::StringHashtable::insertKeyIfNew_returnValue().
Friends And Related Symbol Documentation
KeyValuePair
friend class KeyValuePair friend
Definition at line 75 of file StringHashtable.hh.
StringHashtable
friend class StringHashtable friend
Definition at line 74 of file StringHashtable.hh.
StringKeyHashIterator
friend class StringKeyHashIterator friend
Definition at line 76 of file StringHashtable.hh.
Member Data Documentation
_elem
KeyValuePair cbrc::StringHashtableLink::_elem
Definition at line 105 of file StringHashtable.hh.
Referenced by elem(), elemPtr(), and valueRef().
_next
StringHashtableLink* cbrc::StringHashtableLink::_next
Definition at line 106 of file StringHashtable.hh.
Referenced by next(), and setNext().
The documentation for this class was generated from the following file:
ematch_src/utils/ChainHashtable/StringHashtable.hh