NGSFeatures: cbrc::FastaRecordReader Class Reference
cbrc::FastaRecordReader Class Reference
#include <FastaRecordReader.hh>
Public Member Functions
FastaRecordReader (std::istream &defaultIstream=std::cin, const FastaInputOptions &inputOptions=defaultFastaInputOptions)
const FastaRecord * nextRecord ()
const FastaRecord * nextRecord (std::istream &iStream)
const FastaRecord * nextRecordOrDie (const char *const errorMessage="")
const FastaRecord * nextRecordOrDie (std::istream &iStream, const char *const errorMessage="")
const FastaInputOptions & inputOptions () const
const FastaRecord & curRecord () const
const std::string & seq () const
std::string & seqRef ()
std::istream & defaultIstream () const
const std::string & defaultName ()
void freeCurRecord ()
Detailed Description
Definition at line 35 of file FastaRecordReader.hh.
Constructor & Destructor Documentation
FastaRecordReader()
cbrc::FastaRecordReader::FastaRecordReader (std::istream & defaultIstream = std::cin, const FastaInputOptions & inputOptions = defaultFastaInputOptions) inline
Definition at line 39 of file FastaRecordReader.hh.
Member Function Documentation
curRecord()
const FastaRecord & cbrc::FastaRecordReader::curRecord () const inline
Definition at line 67 of file FastaRecordReader.hh.
Referenced by cbrc::FastaSeqSlurper::getLabeledAsciiSeq(), cbrc::FastaSeqSlurper::getLabeledSequence(), cbrc::FastaSeqSlurper::getLabeledSequence(), nextRecord(), and seq().
defaultIstream()
std::istream & cbrc::FastaRecordReader::defaultIstream () const inline
Definition at line 76 of file FastaRecordReader.hh.
Referenced by nextRecord(), nextRecordOrDie(), cbrc::FastaSeqSlurper::slurpLabeledSequences(), cbrc::FastaSeqSlurper::slurpLabeledSequences(), cbrc::FastaSeqSlurper::slurpLabeledSequences(), and cbrc::FastaSeqSlurper::slurpSeqs().
defaultName()
const std::string & cbrc::FastaRecordReader::defaultName () inline
Definition at line 79 of file FastaRecordReader.hh.
freeCurRecord()
void cbrc::FastaRecordReader::freeCurRecord ()
inputOptions()
const FastaInputOptions & cbrc::FastaRecordReader::inputOptions () const inline
Definition at line 65 of file FastaRecordReader.hh.
Referenced by nextRecord().
nextRecord() [1/2]
const FastaRecord * cbrc::FastaRecordReader::nextRecord ()
Definition at line 24 of file FastaRecordReader.cc.
References defaultIstream(), and nextRecord().
Referenced by nextRecord(), nextRecordOrDie(), cbrc::FastaSeqSlurper::slurpLabeledAsciiSeqs(), cbrc::FastaSeqSlurper::slurpLabeledSequences(), cbrc::FastaSeqSlurper::slurpLabeledSequences(), cbrc::FastaSeqSlurper::slurpLabeledSequences(), cbrc::FastaSeqSlurper::slurpLabeledSequences(), and cbrc::FastaSeqSlurper::slurpSeqs().
nextRecord() [2/2]
const FastaRecord * cbrc::FastaRecordReader::nextRecord (std::istream & iStream)
Definition at line 81 of file FastaRecordReader.cc.
References cbrc::FastaRecord::clear(), curRecord(), GDB_ASSERTF, inputOptions(), seq(), and cbrc::fastafmt::seqTerminationMarker().
nextRecordOrDie() [1/2]
const FastaRecord * cbrc::FastaRecordReader::nextRecordOrDie (const char *const errorMessage = "")
Definition at line 32 of file FastaRecordReader.cc.
References defaultIstream(), and nextRecordOrDie().
Referenced by nextRecordOrDie().
nextRecordOrDie() [2/2]
const FastaRecord * cbrc::FastaRecordReader::nextRecordOrDie (std::istream & iStream, const char *const errorMessage = "")
Definition at line 44 of file FastaRecordReader.cc.
References GDB_DIE, nextRecord(), and cbrc::FLEArray< T >::size().
seq()
const std::string & cbrc::FastaRecordReader::seq () const inline
Definition at line 70 of file FastaRecordReader.hh.
References curRecord().
Referenced by cbrc::FastaSeqSlurper::getLabeledAsciiSeq(), cbrc::FastaSeqSlurper::getLabeledSequence(), cbrc::FastaSeqSlurper::getLabeledSequence(), and nextRecord().
seqRef()
std::string & cbrc::FastaRecordReader::seqRef () inline
Definition at line 72 of file FastaRecordReader.hh.
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/readers/fasta/FastaRecordReader.hh
ematch_src/utils/sequence/readers/fasta/FastaRecordReader.cc