NGSFeatures: cbrc::ChainHashtable< hashableType > Class Template Reference
cbrc::ChainHashtable< hashableType > Class Template Reference
#include <ChainHashtable.hh>
Public Member Functions
ChainHashtable (size_t size=11, size_t maxTSize=1796359771)
~ChainHashtable ()
void clear ()
size_t size () const
ChainHashIterator< hashableType > begin () const
hashableType * find (const hashableType &elem)
hashableType * add (const hashableType &elem, bool resizeAllowed=true)
Detailed Description
template<typename hashableType>
class cbrc::ChainHashtable< hashableType >
Definition at line 200 of file ChainHashtable.hh.
Constructor & Destructor Documentation
ChainHashtable()
template<typename hashableType > cbrc::ChainHashtable< hashableType >::ChainHashtable (size_t size = 11, size_t maxTSize = 1796359771) inline
Definition at line 194 of file ChainHashtable.hh.
~ChainHashtable()
template<typename hashableType > cbrc::ChainHashtable< hashableType >::~ChainHashtable () inline
Definition at line 209 of file ChainHashtable.hh.
References cbrc::ChainHashtable< hashableType >::clear().
Member Function Documentation
add()
template<typename hashableType > hashableType * cbrc::ChainHashtable< hashableType >::add (const hashableType & elem, bool resizeAllowed = true) inline
Definition at line 242 of file ChainHashtable.hh.
References cbrc::ChainHashtable< hashableType >::add().
Referenced by cbrc::ChainHashtable< hashableType >::add().
begin()
template<typename hashableType > ChainHashIterator< hashableType > cbrc::ChainHashtable< hashableType >::begin () const inline
Definition at line 225 of file ChainHashtable.hh.
References cbrc::ChainHashtable< hashableType >::size().
clear()
template<typename hashableType > void cbrc::ChainHashtable< hashableType >::clear () inline
Definition at line 211 of file ChainHashtable.hh.
Referenced by cbrc::ChainHashtable< hashableType >::~ChainHashtable().
find()
template<typename hashableType > hashableType * cbrc::ChainHashtable< hashableType >::find (const hashableType & elem) inline
Definition at line 231 of file ChainHashtable.hh.
size()
template<typename hashableType > size_t cbrc::ChainHashtable< hashableType >::size () const inline
Definition at line 224 of file ChainHashtable.hh.
Referenced by cbrc::ChainHashtable< hashableType >::begin().
The documentation for this class was generated from the following file:
ematch_src/utils/ChainHashtable/ChainHashtable.hh