NGSFeatures: cbrc::FLNumArray< T > Class Template Reference
cbrc::FLNumArray< T > Class Template Reference
#include <FLArray.hh>
Public Member Functions
FLNumArray ()
FLNumArray (const size_t sz)
FLNumArray (size_t sz, T fillVal)
FLNumArray (size_t sz, T *b)
FLNumArray (std::vector< T > v)
FLNumArray (T v[], unsigned int numElems)
FLNumArray (const FLArray< T > &fla)
FLNumArray operator= (std::vector< T > v)
FLNumArray operator= (const FLNumArray &fla)
FLNumArray & operator*= (T el)
FLNumArray & operator/= (T el)
T sum () const
T max () const
size_t maxIndex () const
void squareElements ()
Public Member Functions inherited from cbrc::FLArray< T >
FLArray ()
FLArray (const size_t &sz)
FLArray (const size_t &sz, const T &fillVal)
FLArray (const size_t &sz, const T *&b)
FLArray (const std::vector< T > &v)
FLArray (const std::string &v)
FLArray (const FLArray< T > &fla)
virtual ~FLArray ()
operator std::vector< T > () const
void setSize (size_t sz)
void resize (size_t sz)
FLArray operator= (const FLArray &fla)
FLArray operator= (std::vector< T > v)
void assign (const typename FLArray< T >::const_iterator &begin, const typename FLArray< T >::const_iterator &end)
void assign (const typename std::vector< T >::const_iterator &begin, const typename std::vector< T >::const_iterator &end)
void zero ()
void fill (const T &fillVal)
void fillWithByte (const int &fillByte)
bool validIndex (const size_t &index) const
bool operator== (const FLArray &fla) const
virtual const T & operator() (const size_t &index) const
virtual T & operator[] (const size_t &index) const
void copyTo (const T &elem, size_t index)
virtual void printNumbered (std::ostream &os=std::cout, unsigned startLabel=0) const
const size_t & size () const
bool empty () const
iterator begin () const
iterator end () const
Additional Inherited Members
Public Types inherited from cbrc::FLArray< T >
typedef T * iterator
typedef const T * const_iterator
Protected Attributes inherited from cbrc::FLArray< T >
size_t s
T * a
Detailed Description
template<typename T>
class cbrc::FLNumArray< T >
Definition at line 211 of file FLArray.hh.
Constructor & Destructor Documentation
FLNumArray() [1/7]
template<typename T > cbrc::FLNumArray< T >::FLNumArray () inline
Definition at line 213 of file FLArray.hh.
FLNumArray() [2/7]
template<typename T > cbrc::FLNumArray< T >::FLNumArray (const size_t sz) inline
Definition at line 214 of file FLArray.hh.
FLNumArray() [3/7]
template<typename T > cbrc::FLNumArray< T >::FLNumArray (size_t sz, T fillVal) inline
Definition at line 215 of file FLArray.hh.
FLNumArray() [4/7]
template<typename T > cbrc::FLNumArray< T >::FLNumArray (size_t sz, T * b) inline
Definition at line 216 of file FLArray.hh.
FLNumArray() [5/7]
template<typename T > cbrc::FLNumArray< T >::FLNumArray (std::vector< T > v) inline
Definition at line 217 of file FLArray.hh.
FLNumArray() [6/7]
template<typename T > cbrc::FLNumArray< T >::FLNumArray (T v[], unsigned int numElems) inline
Definition at line 218 of file FLArray.hh.
FLNumArray() [7/7]
template<typename T > cbrc::FLNumArray< T >::FLNumArray (const FLArray< T > & fla) inline
Definition at line 219 of file FLArray.hh.
Member Function Documentation
max()
template<typename T > T cbrc::FLNumArray< T >::max () const inline
Definition at line 240 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::size().
maxIndex()
template<typename T > size_t cbrc::FLNumArray< T >::maxIndex () const inline
Definition at line 246 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::size().
operator*=()
template<typename T > FLNumArray & cbrc::FLNumArray< T >::operator*= (T el) inline
Definition at line 227 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::size().
operator/=()
template<typename T > FLNumArray & cbrc::FLNumArray< T >::operator/= (T el) inline
Definition at line 231 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::size().
operator=() [1/2]
template<typename T > FLNumArray cbrc::FLNumArray< T >::operator= (const FLNumArray< T > & fla) inline
Definition at line 223 of file FLArray.hh.
References cbrc::FLArray< T >::assign(), cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
operator=() [2/2]
template<typename T > FLNumArray cbrc::FLNumArray< T >::operator= (std::vector< T > v) inline
Definition at line 220 of file FLArray.hh.
squareElements()
template<typename T > void cbrc::FLNumArray< T >::squareElements () inline
Definition at line 261 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::size().
sum()
template<typename T > T cbrc::FLNumArray< T >::sum () const inline
Definition at line 235 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::size().
The documentation for this class was generated from the following file:
ematch_src/utils/FLArray/FLArray.hh