NGSFeatures: cbrc::RecountTagCounts Class Reference
cbrc::RecountTagCounts Class Reference
#include <RecountTagCounts.hh>
Public Types
typedef FLENumArray< tagCountT > arrayT
typedef arrayT::iterator iterator
typedef arrayT::const_iterator const_iterator
typedef FLENumArray< tagCountT > arrayT
typedef arrayT::const_iterator const_iterator
Public Member Functions
RecountTagCounts ()
RecountTagCounts (const size_t &maxTagID)
RecountTagCounts (const TagSet &tagID_to_seq, std::istream &tagCountsTextStream)
void zero ()
void setSize (const size_t &maxTagID)
void assign (const RecountTagCounts &countsToCopy)
const arrayT & counts () const
const size_t & size () const
const tagCountT & operator() (const size_t &i) const
tagCountT & operator[] (const size_t &i) const
iterator begin () const
iterator end () const
const_iterator constBegin () const
const_iterator constEnd () const
void print (const TagSet &tagID_to_seq, std::ostream &oStream=std::cout) const
tagCountT sum ()
void operator*= (const tagCountT &multiplier)
tagCountT min () const
RecountTagCounts (const size_t &maxTagId)
RecountTagCounts (const SortedTagSet &tagId_to_seq, std::istream &tagCountsTextStream)
void zero ()
const arrayT & counts () const
const size_t & size () const
const tagCountT & operator() (const size_t &i) const
tagCountT & operator[] (const size_t &i) const
const_iterator constBegin () const
const_iterator constEnd () const
Static Public Member Functions
static void assignDifference (RecountTagCounts &difference, const RecountTagCounts &minuend, const RecountTagCounts &subtrahend)
static tagCountT maxAbsDiff (const RecountTagCounts &counts1, const RecountTagCounts &counts2)
static void assignSum (RecountTagCounts &sum, const RecountTagCounts &addend1, const RecountTagCounts &addend2, const RecountTagCounts &addend3)
Detailed Description
Definition at line 23 of file RecountTagCounts.hh.
Member Typedef Documentation
arrayT [1/2]
typedef FLENumArray<tagCountT> cbrc::RecountTagCounts::arrayT
Definition at line 28 of file RecountTagCounts.hh.
arrayT [2/2]
typedef FLENumArray<tagCountT> cbrc::RecountTagCounts::arrayT
Definition at line 26 of file RecountTagCounts_SortedTagSet.hh.
const_iterator [1/2]
typedef arrayT::const_iterator cbrc::RecountTagCounts::const_iterator
Definition at line 31 of file RecountTagCounts.hh.
const_iterator [2/2]
typedef arrayT::const_iterator cbrc::RecountTagCounts::const_iterator
Definition at line 27 of file RecountTagCounts_SortedTagSet.hh.
iterator
typedef arrayT::iterator cbrc::RecountTagCounts::iterator
Definition at line 30 of file RecountTagCounts.hh.
Constructor & Destructor Documentation
RecountTagCounts() [1/5]
cbrc::RecountTagCounts::RecountTagCounts () inline
Definition at line 36 of file RecountTagCounts.hh.
RecountTagCounts() [2/5]
cbrc::RecountTagCounts::RecountTagCounts (const size_t & maxTagID) inline
Definition at line 40 of file RecountTagCounts.hh.
References zero().
RecountTagCounts() [3/5]
cbrc::RecountTagCounts::RecountTagCounts (const TagSet & tagID_to_seq, std::istream & tagCountsTextStream)
Definition at line 18 of file RecountTagCounts.cc.
References GDB_ASSERTF, cbrc::TagSet::getSerialNumberOrDie(), cbrc::perlish::slurpLine(), cbrc::perlish::split(), and cbrc::FLEArray< T >::zero().
RecountTagCounts() [4/5]
cbrc::RecountTagCounts::RecountTagCounts (const size_t & maxTagId) inline
Definition at line 30 of file RecountTagCounts_SortedTagSet.hh.
References zero().
RecountTagCounts() [5/5]
cbrc::RecountTagCounts::RecountTagCounts (const SortedTagSet & tagId_to_seq, std::istream & tagCountsTextStream)
Definition at line 16 of file RecountTagCounts_SortedTagSet.cc.
References GDB_ASSERTF, cbrc::SortedTagSet::has(), cbrc::perlish::slurpLine(), cbrc::perlish::split(), cbrc::SortedTagSet::toTagSeq(), and cbrc::FLEArray< T >::zero().
Member Function Documentation
assign()
void cbrc::RecountTagCounts::assign (const RecountTagCounts & countsToCopy) inline
Definition at line 64 of file RecountTagCounts.hh.
References cbrc::FLEArray< T >::assign(), cbrc::FLEArray< T >::constBegin(), and cbrc::FLEArray< T >::constEnd().
Referenced by cbrc::RecountExpectationMatchingTagCorrector::inferTrueTagCounts(), cbrc::RecountExpectationMatchingTagCorrector::RecountExpectationMatchingTagCorrector(), and cbrc::RecountExpectationMatchingTagCorrector::RecountExpectationMatchingTagCorrector().
assignDifference()
void cbrc::RecountTagCounts::assignDifference (RecountTagCounts & difference, const RecountTagCounts & minuend, const RecountTagCounts & subtrahend) static
Definition at line 64 of file RecountTagCounts.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), min(), and cbrc::FLEArray< T >::size().
assignSum()
void cbrc::RecountTagCounts::assignSum (RecountTagCounts & sum, const RecountTagCounts & addend1, const RecountTagCounts & addend2, const RecountTagCounts & addend3) static
Definition at line 85 of file RecountTagCounts.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::constBegin(), cbrc::FLEArray< T >::end(), cbrc::FLEArray< T >::size(), and sum().
begin()
iterator cbrc::RecountTagCounts::begin () const inline
Definition at line 79 of file RecountTagCounts.hh.
References begin(), and counts().
Referenced by begin().
constBegin() [1/2]
const_iterator cbrc::RecountTagCounts::constBegin () const inline
Definition at line 81 of file RecountTagCounts.hh.
References cbrc::FLEArray< T >::constBegin(), and counts().
Referenced by cbrc::RecountExpectationMatchingTagCorrector::computeCountCorrections(), cbrc::RecountExpectationMatchingTagCorrector::computeCountCorrections_by1stDerivative(), and cbrc::RecountExpectationMatchingTagCorrector::totalFoldChangeError().
constBegin() [2/2]
const_iterator cbrc::RecountTagCounts::constBegin () const inline
Definition at line 56 of file RecountTagCounts_SortedTagSet.hh.
References cbrc::FLEArray< T >::constBegin(), and counts().
constEnd() [1/2]
const_iterator cbrc::RecountTagCounts::constEnd () const inline
Definition at line 82 of file RecountTagCounts.hh.
References cbrc::FLEArray< T >::constEnd(), and counts().
constEnd() [2/2]
const_iterator cbrc::RecountTagCounts::constEnd () const inline
Definition at line 57 of file RecountTagCounts_SortedTagSet.hh.
References cbrc::FLEArray< T >::constEnd(), and counts().
counts() [1/2]
const arrayT & cbrc::RecountTagCounts::counts () const inline
Definition at line 71 of file RecountTagCounts.hh.
Referenced by begin(), constBegin(), constEnd(), end(), min(), operator()(), size(), and sum().
counts() [2/2]
const arrayT & cbrc::RecountTagCounts::counts () const inline
Definition at line 48 of file RecountTagCounts_SortedTagSet.hh.
end()
iterator cbrc::RecountTagCounts::end () const inline
Definition at line 80 of file RecountTagCounts.hh.
References counts(), and end().
Referenced by cbrc::RecountExpectationMatchingTagCorrector::computeCountCorrections(), cbrc::RecountExpectationMatchingTagCorrector::computeCountCorrections_by1stDerivative(), and end().
maxAbsDiff()
tagCountT cbrc::RecountTagCounts::maxAbsDiff (const RecountTagCounts & counts1, const RecountTagCounts & counts2) static
Definition at line 111 of file RecountTagCounts.cc.
References cbrc::FLEArray< T >::constBegin(), cbrc::FLEArray< T >::constEnd(), and cbrc::FLEArray< T >::size().
Referenced by cbrc::RecountExpectationMatchingTagCorrector::inferTrueTagCounts().
min()
tagCountT cbrc::RecountTagCounts::min () const inline
Definition at line 126 of file RecountTagCounts.hh.
References counts().
Referenced by assignDifference(), and cbrc::runRecountExpectationMatchingTagCorrector().
operator()() [1/2]
const tagCountT & cbrc::RecountTagCounts::operator() (const size_t & i) const inline
Definition at line 75 of file RecountTagCounts.hh.
References counts().
operator()() [2/2]
const tagCountT & cbrc::RecountTagCounts::operator() (const size_t & i) const inline
Definition at line 52 of file RecountTagCounts_SortedTagSet.hh.
References counts().
operator*=()
void cbrc::RecountTagCounts::operator*= (const tagCountT & multiplier) inline
Definition at line 97 of file RecountTagCounts.hh.
operator[]() [1/2]
tagCountT & cbrc::RecountTagCounts::operator[] (const size_t & i) const inline
Definition at line 77 of file RecountTagCounts.hh.
operator[]() [2/2]
tagCountT & cbrc::RecountTagCounts::operator[] (const size_t & i) const inline
Definition at line 54 of file RecountTagCounts_SortedTagSet.hh.
print()
void cbrc::RecountTagCounts::print (const TagSet & tagID_to_seq, std::ostream & oStream = std::cout) const
Definition at line 52 of file RecountTagCounts.cc.
References size(), and cbrc::TagSet::toString().
setSize()
void cbrc::RecountTagCounts::setSize (const size_t & maxTagID) inline
Definition at line 58 of file RecountTagCounts.hh.
References cbrc::FLEArray< T >::setSize().
Referenced by cbrc::RecountExpectationMatchingTagCorrector::RecountExpectationMatchingTagCorrector(), and cbrc::RecountExpectationMatchingTagCorrector::RecountExpectationMatchingTagCorrector().
size() [1/2]
const size_t & cbrc::RecountTagCounts::size () const inline
Definition at line 73 of file RecountTagCounts.hh.
References counts(), and cbrc::FLEArray< T >::size().
Referenced by cbrc::RecountComputerForGraphOnDisk::meanCountsFromTrue(), cbrc::RecountComputerForGraphOnDisk::meanCountsFromTrue(), print(), cbrc::RecountExpectationMatchingTagCorrector::RecountExpectationMatchingTagCorrector(), and cbrc::RecountExpectationMatchingTagCorrector::RecountExpectationMatchingTagCorrector().
size() [2/2]
const size_t & cbrc::RecountTagCounts::size () const inline
Definition at line 50 of file RecountTagCounts_SortedTagSet.hh.
References counts(), and cbrc::FLEArray< T >::size().
sum()
tagCountT cbrc::RecountTagCounts::sum () inline
Definition at line 93 of file RecountTagCounts.hh.
References counts().
Referenced by assignSum(), and cbrc::observedMeanStdev_fromTrueCounts().
zero() [1/2]
void cbrc::RecountTagCounts::zero () inline
Definition at line 55 of file RecountTagCounts.hh.
References cbrc::FLEArray< T >::zero().
Referenced by cbrc::RecountComputerForGraphOnDisk::meanCountsFromTrue(), cbrc::RecountComputerForGraphOnDisk::meanCountsFromTrue(), cbrc::RecountExpectationMatchingTagCorrector::RecountExpectationMatchingTagCorrector(), cbrc::RecountExpectationMatchingTagCorrector::RecountExpectationMatchingTagCorrector(), RecountTagCounts(), and RecountTagCounts().
zero() [2/2]
void cbrc::RecountTagCounts::zero () inline
Definition at line 43 of file RecountTagCounts_SortedTagSet.hh.
References cbrc::FLEArray< T >::zero().
The documentation for this class was generated from the following files:
ematch_src/RecountTagCounts.hh
ematch_src/RecountTagCounts_SortedTagSet.hh
ematch_src/RecountTagCounts.cc
ematch_src/RecountTagCounts_SortedTagSet.cc