NGSFeatures: cbrc::SymmetricBitMatrix Class Reference
cbrc::SymmetricBitMatrix Class Reference
#include <SymmetricBitMatrix.hh>
Public Member Functions
SymmetricBitMatrix ()
SymmetricBitMatrix (const size_t &width)
SymmetricBitMatrix (const SymmetricBitMatrix &sbm)
virtual ~SymmetricBitMatrix ()
void setSize (const size_t &_width)
SymmetricBitMatrix operator= (const SymmetricBitMatrix &sbm)
void fill (const bool fillVal)
void zero ()
void fillWithByte (const int fillByte)
virtual bool validIndex (const size_t &index0, const size_t &index1) const
bool operator== (const SymmetricBitMatrix &sbm) const
bool operator() (size_t index0, size_t index1) const
virtual void set (size_t index0, size_t index1, bool val) const
virtual void set (size_t index0, size_t index1) const
void setFast (const size_t index0, const size_t index1) const
virtual void clear (size_t index0, size_t index1) const
void clearFast (const size_t index0, const size_t index1) const
const size_t & sizeInBytes () const
size_t width () const
Protected Member Functions
virtual size_t rowStart (const size_t row) const
void swapIfNecessary (size_t &index0, size_t &index1) const
Protected Attributes
size_t _width
size_t _sizeInBytes
byte * m
Detailed Description
Definition at line 41 of file SymmetricBitMatrix.hh.
Constructor & Destructor Documentation
SymmetricBitMatrix() [1/3]
cbrc::SymmetricBitMatrix::SymmetricBitMatrix () inline
Definition at line 43 of file SymmetricBitMatrix.hh.
References _sizeInBytes, _width, and m.
SymmetricBitMatrix() [2/3]
cbrc::SymmetricBitMatrix::SymmetricBitMatrix (const size_t & width)
Definition at line 13 of file SymmetricBitMatrix.cc.
References _sizeInBytes, m, rowStart(), sizeInBytes(), SYMMETRICBITMATRIX_BITS_PER_BYTE, and width().
SymmetricBitMatrix() [3/3]
cbrc::SymmetricBitMatrix::SymmetricBitMatrix (const SymmetricBitMatrix & sbm) inline
Definition at line 47 of file SymmetricBitMatrix.hh.
References _sizeInBytes, _width, m, and sizeInBytes().
~SymmetricBitMatrix()
virtual cbrc::SymmetricBitMatrix::~SymmetricBitMatrix () inline virtual
Definition at line 54 of file SymmetricBitMatrix.hh.
References m.
Member Function Documentation
clear()
virtual void cbrc::SymmetricBitMatrix::clear (size_t index0, size_t index1) const inline virtual
Definition at line 113 of file SymmetricBitMatrix.hh.
References m, rowStart(), swapIfNecessary(), cbrc::SymmetricBitMatrixInverseMask, and validIndex().
clearFast()
void cbrc::SymmetricBitMatrix::clearFast (const size_t index0, const size_t index1) const inline
Definition at line 121 of file SymmetricBitMatrix.hh.
References m, rowStart(), and cbrc::SymmetricBitMatrixInverseMask.
Referenced by set().
fill()
void cbrc::SymmetricBitMatrix::fill (const bool fillVal) inline
Definition at line 70 of file SymmetricBitMatrix.hh.
References m, and sizeInBytes().
fillWithByte()
void cbrc::SymmetricBitMatrix::fillWithByte (const int fillByte) inline
Definition at line 75 of file SymmetricBitMatrix.hh.
References m, and sizeInBytes().
operator()()
bool cbrc::SymmetricBitMatrix::operator() (size_t index0, size_t index1) const inline
Definition at line 88 of file SymmetricBitMatrix.hh.
References m, rowStart(), swapIfNecessary(), cbrc::SymmetricBitMatrixMask, and validIndex().
operator=()
SymmetricBitMatrix cbrc::SymmetricBitMatrix::operator= (const SymmetricBitMatrix & sbm) inline
Definition at line 58 of file SymmetricBitMatrix.hh.
References _sizeInBytes, _width, m, sizeInBytes(), and width().
operator==()
bool cbrc::SymmetricBitMatrix::operator== (const SymmetricBitMatrix & sbm) const inline
Definition at line 82 of file SymmetricBitMatrix.hh.
References m, sizeInBytes(), and width().
rowStart()
virtual size_t cbrc::SymmetricBitMatrix::rowStart (const size_t row) const inline protected virtual
Definition at line 130 of file SymmetricBitMatrix.hh.
Referenced by clear(), clearFast(), operator()(), setFast(), setSize(), and SymmetricBitMatrix().
set() [1/2]
virtual void cbrc::SymmetricBitMatrix::set (size_t index0, size_t index1) const inline virtual
Definition at line 102 of file SymmetricBitMatrix.hh.
References setFast(), swapIfNecessary(), and validIndex().
set() [2/2]
virtual void cbrc::SymmetricBitMatrix::set (size_t index0, size_t index1, bool val) const inline virtual
Definition at line 96 of file SymmetricBitMatrix.hh.
References clearFast(), setFast(), swapIfNecessary(), and validIndex().
Referenced by cbrc::MatrixGraph::setEdge().
setFast()
void cbrc::SymmetricBitMatrix::setFast (const size_t index0, const size_t index1) const inline
Definition at line 107 of file SymmetricBitMatrix.hh.
References m, rowStart(), and cbrc::SymmetricBitMatrixMask.
Referenced by set(), and set().
setSize()
void cbrc::SymmetricBitMatrix::setSize (const size_t & _width)
Definition at line 29 of file SymmetricBitMatrix.cc.
References _sizeInBytes, _width, m, rowStart(), sizeInBytes(), SYMMETRICBITMATRIX_BITS_PER_BYTE, and width().
Referenced by cbrc::MatrixGraph::MatrixGraph(), and cbrc::MatrixGraph::readContinuousIntegerNodesFormat().
sizeInBytes()
const size_t & cbrc::SymmetricBitMatrix::sizeInBytes () const inline
Definition at line 127 of file SymmetricBitMatrix.hh.
References _sizeInBytes.
Referenced by fill(), fillWithByte(), operator=(), operator==(), setSize(), SymmetricBitMatrix(), SymmetricBitMatrix(), and zero().
swapIfNecessary()
void cbrc::SymmetricBitMatrix::swapIfNecessary (size_t & index0, size_t & index1) const inline protected
Definition at line 131 of file SymmetricBitMatrix.hh.
Referenced by clear(), operator()(), set(), and set().
validIndex()
bool cbrc::SymmetricBitMatrix::validIndex (const size_t & index0, const size_t & index1) const virtual
Definition at line 40 of file SymmetricBitMatrix.cc.
References width().
Referenced by clear(), operator()(), set(), and set().
width()
size_t cbrc::SymmetricBitMatrix::width () const inline
Definition at line 128 of file SymmetricBitMatrix.hh.
References _width.
Referenced by operator=(), operator==(), setSize(), SymmetricBitMatrix(), and validIndex().
zero()
void cbrc::SymmetricBitMatrix::zero () inline
Definition at line 74 of file SymmetricBitMatrix.hh.
References m, and sizeInBytes().
Referenced by cbrc::MatrixGraph::MatrixGraph(), and cbrc::MatrixGraph::readContinuousIntegerNodesFormat().
Member Data Documentation
_sizeInBytes
size_t cbrc::SymmetricBitMatrix::_sizeInBytes protected
Definition at line 140 of file SymmetricBitMatrix.hh.
Referenced by operator=(), setSize(), sizeInBytes(), SymmetricBitMatrix(), SymmetricBitMatrix(), and SymmetricBitMatrix().
_width
size_t cbrc::SymmetricBitMatrix::_width protected
Definition at line 139 of file SymmetricBitMatrix.hh.
Referenced by operator=(), setSize(), SymmetricBitMatrix(), SymmetricBitMatrix(), and width().
m
byte* cbrc::SymmetricBitMatrix::m protected
Definition at line 141 of file SymmetricBitMatrix.hh.
Referenced by clear(), clearFast(), fill(), fillWithByte(), operator()(), operator=(), operator==(), setFast(), setSize(), SymmetricBitMatrix(), SymmetricBitMatrix(), SymmetricBitMatrix(), zero(), and ~SymmetricBitMatrix().
The documentation for this class was generated from the following files:
ematch_src/utils/BitMatrix/SymmetricBitMatrix.hh
ematch_src/utils/BitMatrix/SymmetricBitMatrix.cc