NGSFeatures: cbrc::StringHashtableIterator Class Reference
cbrc::StringHashtableIterator Class Reference
#include <StringHashtable.hh>
Public Member Functions
StringHashtableIterator ()
StringHashtableIterator (StringHashtableLink **head, StringHashtableLink **last)
void invalidate ()
bool valid () const
bool operator== (const StringHashtableIterator &ch) const
bool operator!= (const StringHashtableIterator &ch) const
KeyValuePair * elemPtr () const
KeyValuePair & operator* () const
StringHashtableIterator & operator++ ()
StringHashtableLink * getLinkPtr () const
Static Public Member Functions
static StringHashtableIterator makeInvalidIterator ()
Public Attributes
StringHashtableLink ** head
StringHashtableLink * linkPtr
StringHashtableLink ** last
Detailed Description
Definition at line 114 of file StringHashtable.hh.
Constructor & Destructor Documentation
StringHashtableIterator() [1/2]
cbrc::StringHashtableIterator::StringHashtableIterator () inline
Definition at line 116 of file StringHashtable.hh.
References invalidate().
Referenced by makeInvalidIterator().
StringHashtableIterator() [2/2]
cbrc::StringHashtableIterator::StringHashtableIterator (StringHashtableLink ** head, StringHashtableLink ** last) inline
Definition at line 119 of file StringHashtable.hh.
References head, last, and linkPtr.
Member Function Documentation
elemPtr()
KeyValuePair * cbrc::StringHashtableIterator::elemPtr () const inline
Definition at line 140 of file StringHashtable.hh.
References cbrc::StringHashtableLink::elemPtr(), and getLinkPtr().
Referenced by operator*().
getLinkPtr()
StringHashtableLink * cbrc::StringHashtableIterator::getLinkPtr () const inline
Definition at line 167 of file StringHashtable.hh.
References linkPtr.
Referenced by elemPtr().
invalidate()
void cbrc::StringHashtableIterator::invalidate () inline
Definition at line 123 of file StringHashtable.hh.
References head.
Referenced by operator++(), and StringHashtableIterator().
makeInvalidIterator()
static StringHashtableIterator cbrc::StringHashtableIterator::makeInvalidIterator () inline static
Definition at line 126 of file StringHashtable.hh.
References StringHashtableIterator().
Referenced by cbrc::StringHashtable::begin().
operator!=()
bool cbrc::StringHashtableIterator::operator!= (const StringHashtableIterator & ch) const inline
Definition at line 136 of file StringHashtable.hh.
operator*()
KeyValuePair & cbrc::StringHashtableIterator::operator* () const inline
Definition at line 141 of file StringHashtable.hh.
References elemPtr().
operator++()
StringHashtableIterator & cbrc::StringHashtableIterator::operator++ () inline
Definition at line 143 of file StringHashtable.hh.
References head, invalidate(), last, linkPtr, cbrc::StringHashtableLink::next(), and valid().
operator==()
bool cbrc::StringHashtableIterator::operator== (const StringHashtableIterator & ch) const inline
Definition at line 130 of file StringHashtable.hh.
References head, linkPtr, and valid().
valid()
bool cbrc::StringHashtableIterator::valid () const inline
Definition at line 124 of file StringHashtable.hh.
References head.
Referenced by operator++(), and operator==().
Member Data Documentation
head
StringHashtableLink** cbrc::StringHashtableIterator::head
Definition at line 168 of file StringHashtable.hh.
Referenced by invalidate(), operator++(), operator==(), StringHashtableIterator(), and valid().
last
StringHashtableLink** cbrc::StringHashtableIterator::last
Definition at line 170 of file StringHashtable.hh.
Referenced by operator++(), and StringHashtableIterator().
linkPtr
StringHashtableLink* cbrc::StringHashtableIterator::linkPtr
Definition at line 169 of file StringHashtable.hh.
Referenced by getLinkPtr(), operator++(), operator==(), and StringHashtableIterator().
The documentation for this class was generated from the following file:
ematch_src/utils/ChainHashtable/StringHashtable.hh