NGSFeatures: cbrc::MatrixGraph Class Reference
cbrc::MatrixGraph Class Reference
#include <MatrixGraph.hh>
Public Member Functions
MatrixGraph (nodeIndexT numNodes)
MatrixGraph (std::istream &is)
virtual ~MatrixGraph ()
nodeIndexT numNodes () const
std::string nodeName (const nodeIndexT &nodeIndex) const
bool hasEdge (const nodeIndexT &n0, const nodeIndexT &n1) const
void setEdge (nodeIndexT n0, nodeIndexT n1)
void setEdgesFromAdjacencyListStream (std::istream &is)
void readContinuousIntegerNodesFormat (std::istream &is)
void readEdgesOneEdgePerLineFormat (std::istream &is)
void printAdjacencyLists (std::ostream &os)
MatrixGraph (nodeIndexT numNodes)
MatrixGraph (std::istream &is)
virtual ~MatrixGraph ()
nodeIndexT numNodes () const
std::string nodeName (const nodeIndexT &nodeIndex) const
bool hasEdge (const nodeIndexT &n0, const nodeIndexT &n1) const
void setEdge (nodeIndexT n0, nodeIndexT n1)
void setEdgesFromAdjacencyListStream (std::istream &is)
void readContinuousIntegerNodesFormat (std::istream &is)
void readEdgesOneEdgePerLineFormat (std::istream &is)
void printAdjacencyLists (std::ostream &os)
Public Member Functions inherited from cbrc::Graph
virtual ~Graph ()
virtual ~Graph ()
Detailed Description
Definition at line 21 of file MatrixGraph.hh.
Constructor & Destructor Documentation
MatrixGraph() [1/4]
cbrc::MatrixGraph::MatrixGraph (nodeIndexT numNodes) inline
Definition at line 24 of file MatrixGraph.hh.
References cbrc::SymmetricBitMatrix::setSize(), and cbrc::SymmetricBitMatrix::zero().
MatrixGraph() [2/4]
cbrc::MatrixGraph::MatrixGraph (std::istream & is) inline
Definition at line 29 of file MatrixGraph.hh.
References readContinuousIntegerNodesFormat().
~MatrixGraph() [1/2]
virtual cbrc::MatrixGraph::~MatrixGraph () inline virtual
Definition at line 33 of file MatrixGraph.hh.
MatrixGraph() [3/4]
cbrc::MatrixGraph::MatrixGraph (nodeIndexT numNodes) inline
Definition at line 24 of file MatrixGraph.hh.
References cbrc::SymmetricBitMatrix::setSize(), and cbrc::SymmetricBitMatrix::zero().
MatrixGraph() [4/4]
cbrc::MatrixGraph::MatrixGraph (std::istream & is) inline
Definition at line 29 of file MatrixGraph.hh.
References readContinuousIntegerNodesFormat().
~MatrixGraph() [2/2]
virtual cbrc::MatrixGraph::~MatrixGraph () inline virtual
Definition at line 33 of file MatrixGraph.hh.
Member Function Documentation
hasEdge() [1/2]
bool cbrc::MatrixGraph::hasEdge (const nodeIndexT & n0, const nodeIndexT & n1) const inline virtual
Implements cbrc::Graph.
Definition at line 44 of file MatrixGraph.hh.
Referenced by printAdjacencyLists().
hasEdge() [2/2]
bool cbrc::MatrixGraph::hasEdge (const nodeIndexT & n0, const nodeIndexT & n1) const inline virtual
Implements cbrc::Graph.
Definition at line 44 of file MatrixGraph.hh.
nodeName() [1/2]
std::string cbrc::MatrixGraph::nodeName (const nodeIndexT & nodeIndex) const inline
Definition at line 40 of file MatrixGraph.hh.
Referenced by readContinuousIntegerNodesFormat().
nodeName() [2/2]
std::string cbrc::MatrixGraph::nodeName (const nodeIndexT & nodeIndex) const inline
Definition at line 40 of file MatrixGraph.hh.
numNodes() [1/2]
nodeIndexT cbrc::MatrixGraph::numNodes () const inline virtual
Implements cbrc::Graph.
Definition at line 37 of file MatrixGraph.hh.
Referenced by printAdjacencyLists().
numNodes() [2/2]
nodeIndexT cbrc::MatrixGraph::numNodes () const inline virtual
Implements cbrc::Graph.
Definition at line 37 of file MatrixGraph.hh.
printAdjacencyLists() [1/2]
void cbrc::MatrixGraph::printAdjacencyLists (std::ostream & os)
Definition at line 88 of file MatrixGraph.cc.
References hasEdge(), neighbors(), numNodes(), and cbrc::FLEArray< T >::size().
printAdjacencyLists() [2/2]
void cbrc::MatrixGraph::printAdjacencyLists (std::ostream & os)
readContinuousIntegerNodesFormat() [1/2]
void cbrc::MatrixGraph::readContinuousIntegerNodesFormat (std::istream & is)
Definition at line 18 of file MatrixGraph.cc.
References nodeName(), cbrc::SerialNumbersForStrings< serialNumT >::registerNewSerialNumber(), setEdge(), cbrc::SymmetricBitMatrix::setSize(), cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLine(), cbrc::perlish::split(), and cbrc::SymmetricBitMatrix::zero().
Referenced by MatrixGraph().
readContinuousIntegerNodesFormat() [2/2]
void cbrc::MatrixGraph::readContinuousIntegerNodesFormat (std::istream & is)
readEdgesOneEdgePerLineFormat() [1/2]
void cbrc::MatrixGraph::readEdgesOneEdgePerLineFormat (std::istream & is)
Definition at line 66 of file MatrixGraph.cc.
References cbrc::SerialNumbersForStrings< serialNumT >::getSerialNumber(), setEdge(), cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLine(), and cbrc::perlish::split().
readEdgesOneEdgePerLineFormat() [2/2]
void cbrc::MatrixGraph::readEdgesOneEdgePerLineFormat (std::istream & is)
setEdge() [1/2]
void cbrc::MatrixGraph::setEdge (nodeIndexT n0, nodeIndexT n1) inline
Definition at line 46 of file MatrixGraph.hh.
References cbrc::SymmetricBitMatrix::set().
Referenced by readContinuousIntegerNodesFormat(), and readEdgesOneEdgePerLineFormat().
setEdge() [2/2]
void cbrc::MatrixGraph::setEdge (nodeIndexT n0, nodeIndexT n1) inline
Definition at line 46 of file MatrixGraph.hh.
References cbrc::SymmetricBitMatrix::set().
setEdgesFromAdjacencyListStream() [1/2]
void cbrc::MatrixGraph::setEdgesFromAdjacencyListStream (std::istream & is)
setEdgesFromAdjacencyListStream() [2/2]
void cbrc::MatrixGraph::setEdgesFromAdjacencyListStream (std::istream & is)
The documentation for this class was generated from the following files:
ematch_src/graph/MatrixGraph.hh
ematch_src/utils/graph/MatrixGraph.hh
ematch_src/graph/MatrixGraph.cc
ematch_src/utils/graph/MatrixGraph.cc