NGSFeatures: cbrc::StringKeyHashIterator< ValT > Class Template Reference
cbrc::StringKeyHashIterator< ValT > Class Template Reference
#include <StringKeyHashtable.hh>
Public Member Functions
StringKeyHashIterator ()
StringKeyHashIterator (StringKeyHashtableLink< ValT > **head, StringKeyHashtableLink< ValT > **last)
void invalidate ()
bool valid () const
bool operator== (const StringKeyHashIterator< ValT > &ch) const
bool operator!= (const StringKeyHashIterator< ValT > &ch) const
StringKeyAndValue< ValT > * getElemPtr () const
StringKeyAndValue< ValT > & operator* () const
StringKeyHashIterator< ValT > & operator++ ()
Static Public Member Functions
static StringKeyHashIterator< ValT > makeInvalidIterator ()
Friends
class StringKeyHashtable< ValT >
Detailed Description
template<typename ValT>
class cbrc::StringKeyHashIterator< ValT >
Definition at line 97 of file StringKeyHashtable.hh.
Constructor & Destructor Documentation
StringKeyHashIterator() [1/2]
template<typename ValT > cbrc::StringKeyHashIterator< ValT >::StringKeyHashIterator () inline
Definition at line 88 of file StringKeyHashtable.hh.
StringKeyHashIterator() [2/2]
template<typename ValT > cbrc::StringKeyHashIterator< ValT >::StringKeyHashIterator (StringKeyHashtableLink< ValT > ** head, StringKeyHashtableLink< ValT > ** last) inline
Definition at line 88 of file StringKeyHashtable.hh.
Member Function Documentation
getElemPtr()
template<typename ValT > StringKeyAndValue< ValT > * cbrc::StringKeyHashIterator< ValT >::getElemPtr () const inline
Definition at line 116 of file StringKeyHashtable.hh.
Referenced by cbrc::StringKeyHashIterator< ValT >::operator*().
invalidate()
template<typename ValT > void cbrc::StringKeyHashIterator< ValT >::invalidate () inline
Definition at line 105 of file StringKeyHashtable.hh.
Referenced by cbrc::StringKeyHashIterator< ValT >::operator++().
makeInvalidIterator()
template<typename ValT > static StringKeyHashIterator< ValT > cbrc::StringKeyHashIterator< ValT >::makeInvalidIterator () inline static
Definition at line 107 of file StringKeyHashtable.hh.
Referenced by cbrc::StringKeyHashtable< ValT >::begin().
operator!=()
template<typename ValT > bool cbrc::StringKeyHashIterator< ValT >::operator!= (const StringKeyHashIterator< ValT > & ch) const inline
Definition at line 115 of file StringKeyHashtable.hh.
operator*()
template<typename ValT > StringKeyAndValue< ValT > & cbrc::StringKeyHashIterator< ValT >::operator* () const inline
Definition at line 117 of file StringKeyHashtable.hh.
References cbrc::StringKeyHashIterator< ValT >::getElemPtr().
operator++()
template<typename ValT > StringKeyHashIterator< ValT > & cbrc::StringKeyHashIterator< ValT >::operator++ () inline
Definition at line 118 of file StringKeyHashtable.hh.
References cbrc::StringKeyHashIterator< ValT >::invalidate(), and cbrc::StringKeyHashIterator< ValT >::valid().
operator==()
template<typename ValT > bool cbrc::StringKeyHashIterator< ValT >::operator== (const StringKeyHashIterator< ValT > & ch) const inline
Definition at line 110 of file StringKeyHashtable.hh.
References cbrc::StringKeyHashIterator< ValT >::valid().
valid()
template<typename ValT > bool cbrc::StringKeyHashIterator< ValT >::valid () const inline
Definition at line 106 of file StringKeyHashtable.hh.
Referenced by cbrc::StringKeyHashIterator< ValT >::operator++(), and cbrc::StringKeyHashIterator< ValT >::operator==().
Friends And Related Symbol Documentation
StringKeyHashtable< ValT >
template<typename ValT > friend class StringKeyHashtable< ValT > friend
Definition at line 88 of file StringKeyHashtable.hh.
The documentation for this class was generated from the following file:
ematch_src/utils/ChainHashtable/StringKeyHashtable.hh