NGSFeatures: cbrc::String2KeyAndValue< ValT > Class Template Reference
cbrc::String2KeyAndValue< ValT > Class Template Reference
#include <String2KeyHashtable.hh>
Public Member Functions
String2KeyAndValue (const std::string &key0, const std::string &key1, const ValT value)
String2KeyAndValue (const String2KeyAndValue< ValT > &snh)
void operator= (const ValT &val)
operator ValT & ()
size_t hashVal () const
bool keysEqual (const String2KeyAndValue< ValT > &snh) const
bool keysEqual (const std::string &s0, const std::string &s1) const
std::string key0 () const
std::string key1 () const
ValT value () const
void setValue (const ValT &newVal)
Friends
class String2KeyHashtable< ValT >
class String2KeyHashtableLink< ValT >
Detailed Description
template<typename ValT>
class cbrc::String2KeyAndValue< ValT >
Definition at line 75 of file String2KeyHashtable.hh.
Constructor & Destructor Documentation
String2KeyAndValue() [1/2]
template<typename ValT > cbrc::String2KeyAndValue< ValT >::String2KeyAndValue (const std::string & key0, const std::string & key1, const ValT value) inline
Definition at line 77 of file String2KeyHashtable.hh.
References cbrc::String2KeyAndValue< ValT >::key0(), cbrc::String2KeyAndValue< ValT >::key1(), and cbrc::String2KeyAndValue< ValT >::value().
String2KeyAndValue() [2/2]
template<typename ValT > cbrc::String2KeyAndValue< ValT >::String2KeyAndValue (const String2KeyAndValue< ValT > & snh) inline
Definition at line 79 of file String2KeyHashtable.hh.
Member Function Documentation
hashVal()
template<typename ValT > size_t cbrc::String2KeyAndValue< ValT >::hashVal () const inline
Definition at line 83 of file String2KeyHashtable.hh.
References cbrc::string2HashVal().
key0()
template<typename ValT > std::string cbrc::String2KeyAndValue< ValT >::key0 () const inline
Definition at line 89 of file String2KeyHashtable.hh.
Referenced by cbrc::String2KeyAndValue< ValT >::String2KeyAndValue().
key1()
template<typename ValT > std::string cbrc::String2KeyAndValue< ValT >::key1 () const inline
Definition at line 90 of file String2KeyHashtable.hh.
Referenced by cbrc::String2KeyAndValue< ValT >::String2KeyAndValue().
keysEqual() [1/2]
template<typename ValT > bool cbrc::String2KeyAndValue< ValT >::keysEqual (const std::string & s0, const std::string & s1) const inline
Definition at line 86 of file String2KeyHashtable.hh.
keysEqual() [2/2]
template<typename ValT > bool cbrc::String2KeyAndValue< ValT >::keysEqual (const String2KeyAndValue< ValT > & snh) const inline
Definition at line 84 of file String2KeyHashtable.hh.
operator ValT &()
template<typename ValT > cbrc::String2KeyAndValue< ValT >::operator ValT & () inline
Definition at line 82 of file String2KeyHashtable.hh.
operator=()
template<typename ValT > void cbrc::String2KeyAndValue< ValT >::operator= (const ValT & val) inline
Definition at line 81 of file String2KeyHashtable.hh.
setValue()
template<typename ValT > void cbrc::String2KeyAndValue< ValT >::setValue (const ValT & newVal) inline
Definition at line 92 of file String2KeyHashtable.hh.
value()
template<typename ValT > ValT cbrc::String2KeyAndValue< ValT >::value () const inline
Definition at line 91 of file String2KeyHashtable.hh.
Referenced by cbrc::String2KeyAndValue< ValT >::String2KeyAndValue().
Friends And Related Symbol Documentation
String2KeyHashtable< ValT >
template<typename ValT > friend class String2KeyHashtable< ValT > friend
Definition at line 92 of file String2KeyHashtable.hh.
String2KeyHashtableLink< ValT >
template<typename ValT > friend class String2KeyHashtableLink< ValT > friend
Definition at line 92 of file String2KeyHashtable.hh.
The documentation for this class was generated from the following file:
ematch_src/utils/ChainHashtable/String2KeyHashtable.hh