NGSFeatures: cbrc::SortedStringSet Class Reference
cbrc::SortedStringSet Class Reference
#include <SortedStringSet.hh>
Public Types
enum fileFormatT { binary , text }
typedef std::vector< std::string > stringVecT
typedef stringVecT::const_iterator const_iterator
typedef stringVecT::iterator iterator
Public Member Functions
SortedStringSet ()
SortedStringSet (const stringVecT &vec)
SortedStringSet (std::istream &iStream, fileFormatT fileFormat=text)
void initialSort ()
void operator= (const stringVecT &vec)
void assign (const stringVecT::const_iterator &begin, const stringVecT::const_iterator &end)
bool has (const std::string &s) const
const std::string & operator() (const size_t &i) const
size_t operator() (const std::string &s) const
size_t getSerialNumberOrDie (const std::string &s) const
size_t size () const
const_iterator begin () const
const_iterator end () const
const stringVecT & asStringVec () const
void readFromBinaryStream (std::istream &iStream)
void readFromTextStream (std::istream &iStream)
Detailed Description
Definition at line 22 of file SortedStringSet.hh.
Member Typedef Documentation
const_iterator
typedef stringVecT::const_iterator cbrc::SortedStringSet::const_iterator
Definition at line 25 of file SortedStringSet.hh.
iterator
typedef stringVecT::iterator cbrc::SortedStringSet::iterator
Definition at line 26 of file SortedStringSet.hh.
stringVecT
typedef std::vector<std::string> cbrc::SortedStringSet::stringVecT
Definition at line 24 of file SortedStringSet.hh.
Member Enumeration Documentation
fileFormatT
enum cbrc::SortedStringSet::fileFormatT
Enumerator
binary
text
Definition at line 27 of file SortedStringSet.hh.
Constructor & Destructor Documentation
SortedStringSet() [1/3]
cbrc::SortedStringSet::SortedStringSet () inline
Definition at line 32 of file SortedStringSet.hh.
SortedStringSet() [2/3]
cbrc::SortedStringSet::SortedStringSet (const stringVecT & vec) inline
Definition at line 34 of file SortedStringSet.hh.
References initialSort().
SortedStringSet() [3/3]
cbrc::SortedStringSet::SortedStringSet (std::istream & iStream, fileFormatT fileFormat = text) inline
Definition at line 38 of file SortedStringSet.hh.
References readFromBinaryStream(), readFromTextStream(), and text.
Member Function Documentation
assign()
void cbrc::SortedStringSet::assign (const stringVecT::const_iterator & begin, const stringVecT::const_iterator & end) inline
Definition at line 56 of file SortedStringSet.hh.
References begin(), and end().
asStringVec()
const stringVecT & cbrc::SortedStringSet::asStringVec () const inline
Definition at line 94 of file SortedStringSet.hh.
begin()
const_iterator cbrc::SortedStringSet::begin () const inline
Definition at line 89 of file SortedStringSet.hh.
Referenced by assign().
end()
const_iterator cbrc::SortedStringSet::end () const inline
Definition at line 90 of file SortedStringSet.hh.
Referenced by assign().
getSerialNumberOrDie()
size_t cbrc::SortedStringSet::getSerialNumberOrDie (const std::string & s) const inline
Definition at line 79 of file SortedStringSet.hh.
References GDB_ASSERTF.
has()
bool cbrc::SortedStringSet::has (const std::string & s) const inline
Definition at line 66 of file SortedStringSet.hh.
initialSort()
void cbrc::SortedStringSet::initialSort () inline
Definition at line 44 of file SortedStringSet.hh.
Referenced by operator=(), and SortedStringSet().
operator()() [1/2]
const std::string & cbrc::SortedStringSet::operator() (const size_t & i) const inline
Definition at line 70 of file SortedStringSet.hh.
operator()() [2/2]
size_t cbrc::SortedStringSet::operator() (const std::string & s) const inline
Definition at line 74 of file SortedStringSet.hh.
operator=()
void cbrc::SortedStringSet::operator= (const stringVecT & vec) inline
Definition at line 51 of file SortedStringSet.hh.
References initialSort().
readFromBinaryStream()
void cbrc::SortedStringSet::readFromBinaryStream (std::istream & iStream) inline
Definition at line 98 of file SortedStringSet.hh.
Referenced by SortedStringSet().
readFromTextStream()
void cbrc::SortedStringSet::readFromTextStream (std::istream & iStream) inline
Definition at line 103 of file SortedStringSet.hh.
References cbrc::perlish::slurpLines().
Referenced by SortedStringSet().
size()
size_t cbrc::SortedStringSet::size () const inline
Definition at line 86 of file SortedStringSet.hh.
The documentation for this class was generated from the following file:
ematch_src/utils/SortedStringSet/SortedStringSet.hh