NGSFeatures: cbrc::NeighborListGraph Class Reference
cbrc::NeighborListGraph Class Reference
#include <NeighborListGraph.hh>
Public Member Functions
void readOneEdgePerLineFormat (std::istream &)
virtual ~NeighborListGraph ()
nodeIndexT numNodes () const
bool hasEdge (const nodeIndexT &n0, const nodeIndexT &n1) const
const std::vector< nodeIndexT > & neighborList (nodeIndexT n) const
FLENumArray< nodeIndexT > shortestPathByEdgeLength (const nodeIndexT &n) const
std::string nodeIndexTLabel (nodeIndexT n) const
void checkConsistency () const
std::string label (nodeIndexT n) const
void readOneEdgePerLineFormat (std::istream &)
virtual ~NeighborListGraph ()
nodeIndexT numNodes () const
bool hasEdge (const nodeIndexT &n0, const nodeIndexT &n1) const
const std::vector< nodeIndexT > & neighborList (nodeIndexT n) const
FLENumArray< nodeIndexT > shortestPathByEdgeLength (const nodeIndexT &n) const
std::string nodeIndexTLabel (nodeIndexT n) const
void checkConsistency () const
std::string label (nodeIndexT n) const
Public Member Functions inherited from cbrc::Graph
virtual ~Graph ()
virtual ~Graph ()
Friends
std::ostream & operator<< (std::ostream &os, const NeighborListGraph &nlg)
std::ostream & operator<< (std::ostream &os, const NeighborListGraph &nlg)
Detailed Description
Definition at line 24 of file NeighborListGraph.hh.
Constructor & Destructor Documentation
~NeighborListGraph() [1/2]
virtual cbrc::NeighborListGraph::~NeighborListGraph () inline virtual
Definition at line 27 of file NeighborListGraph.hh.
~NeighborListGraph() [2/2]
virtual cbrc::NeighborListGraph::~NeighborListGraph () inline virtual
Definition at line 27 of file NeighborListGraph.hh.
Member Function Documentation
checkConsistency() [1/2]
void cbrc::NeighborListGraph::checkConsistency () const
Definition at line 55 of file NeighborListGraph.cc.
References hasEdge(), and numNodes().
checkConsistency() [2/2]
void cbrc::NeighborListGraph::checkConsistency () const
hasEdge() [1/2]
bool cbrc::NeighborListGraph::hasEdge (const nodeIndexT & n0, const nodeIndexT & n1) const virtual
Implements cbrc::Graph.
Definition at line 69 of file NeighborListGraph.cc.
Referenced by checkConsistency().
hasEdge() [2/2]
bool cbrc::NeighborListGraph::hasEdge (const nodeIndexT & n0, const nodeIndexT & n1) const virtual
Implements cbrc::Graph.
label() [1/2]
std::string cbrc::NeighborListGraph::label (nodeIndexT n) const inline
Definition at line 40 of file NeighborListGraph.hh.
label() [2/2]
std::string cbrc::NeighborListGraph::label (nodeIndexT n) const inline
Definition at line 40 of file NeighborListGraph.hh.
neighborList() [1/2]
const std::vector< nodeIndexT > & cbrc::NeighborListGraph::neighborList (nodeIndexT n) const inline
Definition at line 32 of file NeighborListGraph.hh.
neighborList() [2/2]
const std::vector< nodeIndexT > & cbrc::NeighborListGraph::neighborList (nodeIndexT n) const inline
Definition at line 32 of file NeighborListGraph.hh.
nodeIndexTLabel() [1/2]
std::string cbrc::NeighborListGraph::nodeIndexTLabel (nodeIndexT n) const inline
Definition at line 36 of file NeighborListGraph.hh.
nodeIndexTLabel() [2/2]
std::string cbrc::NeighborListGraph::nodeIndexTLabel (nodeIndexT n) const inline
Definition at line 36 of file NeighborListGraph.hh.
numNodes() [1/2]
nodeIndexT cbrc::NeighborListGraph::numNodes () const inline virtual
Implements cbrc::Graph.
Definition at line 28 of file NeighborListGraph.hh.
Referenced by checkConsistency(), and shortestPathByEdgeLength().
numNodes() [2/2]
nodeIndexT cbrc::NeighborListGraph::numNodes () const inline virtual
Implements cbrc::Graph.
Definition at line 28 of file NeighborListGraph.hh.
readOneEdgePerLineFormat() [1/2]
void cbrc::NeighborListGraph::readOneEdgePerLineFormat (std::istream & is)
Definition at line 19 of file NeighborListGraph.cc.
References GDB_ASSERTF, cbrc::SerialNumbersForStrings< serialNumT >::getSerialNumber(), cbrc::OneEdgePerLineFormat::inputDelimiter(), cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLine(), and cbrc::perlish::split().
readOneEdgePerLineFormat() [2/2]
void cbrc::NeighborListGraph::readOneEdgePerLineFormat (std::istream &)
shortestPathByEdgeLength() [1/2]
FLENumArray< nodeIndexT > cbrc::NeighborListGraph::shortestPathByEdgeLength (const nodeIndexT & n) const
Definition at line 83 of file NeighborListGraph.cc.
References numNodes(), cbrc::FLEArray< T >::size(), and cbrc::FLEArray< T >::zero().
shortestPathByEdgeLength() [2/2]
FLENumArray< nodeIndexT > cbrc::NeighborListGraph::shortestPathByEdgeLength (const nodeIndexT & n) const
Friends And Related Symbol Documentation
operator<< [1/2]
std::ostream & operator<< (std::ostream & os, const NeighborListGraph & nlg) friend
Definition at line 144 of file NeighborListGraph.cc.
operator<< [2/2]
std::ostream & operator<< (std::ostream & os, const NeighborListGraph & nlg) friend
Definition at line 144 of file NeighborListGraph.cc.
The documentation for this class was generated from the following files:
ematch_src/graph/NeighborListGraph.hh
ematch_src/utils/graph/NeighborListGraph.hh
ematch_src/graph/NeighborListGraph.cc
ematch_src/utils/graph/NeighborListGraph.cc