NGSFeatures: cbrc::KeyValuePair Class Reference
cbrc::KeyValuePair Class Reference
#include <StringHashtable.hh>
Public Member Functions
KeyValuePair (const std::string &key, const std::string &value)
KeyValuePair (const KeyValuePair &snh)
void operator= (const std::string &val)
const std::string & operator() () const
size_t hashValue () const
bool keyEquals (const KeyValuePair &snh) const
const std::string & key () const
const std::string & value () const
std::string & valueRef ()
void setValue (const std::string &newValue)
Friends
class StringHashtable
Detailed Description
Definition at line 34 of file StringHashtable.hh.
Constructor & Destructor Documentation
KeyValuePair() [1/2]
cbrc::KeyValuePair::KeyValuePair (const std::string & key, const std::string & value) inline
Definition at line 37 of file StringHashtable.hh.
References key(), and value().
KeyValuePair() [2/2]
cbrc::KeyValuePair::KeyValuePair (const KeyValuePair & snh) inline
Definition at line 42 of file StringHashtable.hh.
Member Function Documentation
hashValue()
size_t cbrc::KeyValuePair::hashValue () const inline
Definition at line 52 of file StringHashtable.hh.
References stringHashValue().
Referenced by cbrc::StringHashtable::add().
key()
const std::string & cbrc::KeyValuePair::key () const inline
Definition at line 58 of file StringHashtable.hh.
Referenced by keyEquals(), and KeyValuePair().
keyEquals()
bool cbrc::KeyValuePair::keyEquals (const KeyValuePair & snh) const inline
Definition at line 54 of file StringHashtable.hh.
References key().
Referenced by cbrc::StringHashtable::add().
operator()()
const std::string & cbrc::KeyValuePair::operator() () const inline
Definition at line 50 of file StringHashtable.hh.
operator=()
void cbrc::KeyValuePair::operator= (const std::string & val) inline
Definition at line 46 of file StringHashtable.hh.
setValue()
void cbrc::KeyValuePair::setValue (const std::string & newValue) inline
Definition at line 61 of file StringHashtable.hh.
value()
const std::string & cbrc::KeyValuePair::value () const inline
Definition at line 59 of file StringHashtable.hh.
Referenced by KeyValuePair().
valueRef()
std::string & cbrc::KeyValuePair::valueRef () inline
Definition at line 60 of file StringHashtable.hh.
Referenced by cbrc::StringHashtableLink::valueRef().
Friends And Related Symbol Documentation
StringHashtable
friend class StringHashtable friend
Definition at line 62 of file StringHashtable.hh.
The documentation for this class was generated from the following file:
ematch_src/utils/ChainHashtable/StringHashtable.hh