NGSFeatures: cbrc::TransfacTextLine Class Reference
cbrc::TransfacTextLine Class Reference
#include <TransfacTextLine.hh>
Public Member Functions
TransfacTextLine (const std::string &line)
TransfacTextLine ()
TransfacTextLine (const TransfacTextLine &transfacLine)
void set (const std::string &line)
bool empty () const
std::string label () const
std::string content () const
Detailed Description
Definition at line 17 of file TransfacTextLine.hh.
Constructor & Destructor Documentation
TransfacTextLine() [1/3]
cbrc::TransfacTextLine::TransfacTextLine (const std::string & line) inline
Definition at line 19 of file TransfacTextLine.hh.
References set().
TransfacTextLine() [2/3]
cbrc::TransfacTextLine::TransfacTextLine () inline
Definition at line 20 of file TransfacTextLine.hh.
TransfacTextLine() [3/3]
cbrc::TransfacTextLine::TransfacTextLine (const TransfacTextLine & transfacLine) inline
Definition at line 21 of file TransfacTextLine.hh.
Member Function Documentation
content()
std::string cbrc::TransfacTextLine::content () const inline
Definition at line 28 of file TransfacTextLine.hh.
Referenced by cbrc::TransfacReader::readRecord(), and cbrc::TransfacReader::TransfacReader().
empty()
bool cbrc::TransfacTextLine::empty () const inline
Definition at line 26 of file TransfacTextLine.hh.
Referenced by cbrc::TransfacReader::readRecord(), and cbrc::TransfacReader::TransfacReader().
label()
std::string cbrc::TransfacTextLine::label () const inline
Definition at line 27 of file TransfacTextLine.hh.
Referenced by cbrc::TransfacTextLabelInfo::isAccession(), cbrc::TransfacTextLabelInfo::isBindingFactor(), cbrc::TransfacTextLabelInfo::isBlankLine(), cbrc::TransfacTextLabelInfo::isDescription(), cbrc::TransfacTextLabelInfo::isFreqMatrix(), cbrc::TransfacTextLabelInfo::isFreqMatrixBody(), cbrc::TransfacTextLabelInfo::isName(), cbrc::TransfacTextLabelInfo::isRecordSeparator(), and cbrc::TransfacTextLabelInfo::isVersion().
set()
void cbrc::TransfacTextLine::set (const std::string & line)
Definition at line 19 of file TransfacTextLine.cc.
References cbrc::perlish::spaceTabString(), and cbrc::perlish::split().
Referenced by TransfacTextLine().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/readers/transfac/TransfacTextLine.hh
ematch_src/utils/sequence/readers/transfac/TransfacTextLine.cc