NGSFeatures: cbrc::RecountTagIdProbPair Class Reference
cbrc::RecountTagIdProbPair Class Reference
#include <RecountTagIdProbPair.hh>
Public Member Functions
RecountTagIdProbPair ()
const tagIdT & id () const
const probT & prob () const
void set (const tagIdT &tagId, const probT &prob)
void setTagId (const tagIdT &tagId)
void setProb (const probT &prob)
Detailed Description
Definition at line 18 of file RecountTagIdProbPair.hh.
Constructor & Destructor Documentation
RecountTagIdProbPair()
cbrc::RecountTagIdProbPair::RecountTagIdProbPair () inline
Definition at line 21 of file RecountTagIdProbPair.hh.
Member Function Documentation
id()
const tagIdT & cbrc::RecountTagIdProbPair::id () const inline
Definition at line 25 of file RecountTagIdProbPair.hh.
Referenced by cbrc::dumpNeighborList().
prob()
const probT & cbrc::RecountTagIdProbPair::prob () const inline
Definition at line 27 of file RecountTagIdProbPair.hh.
Referenced by cbrc::dumpNeighborList(), set(), and setProb().
set()
void cbrc::RecountTagIdProbPair::set (const tagIdT & tagId, const probT & prob) inline
Definition at line 30 of file RecountTagIdProbPair.hh.
References prob().
setProb()
void cbrc::RecountTagIdProbPair::setProb (const probT & prob) inline
Definition at line 36 of file RecountTagIdProbPair.hh.
References prob().
setTagId()
void cbrc::RecountTagIdProbPair::setTagId (const tagIdT & tagId) inline
Definition at line 34 of file RecountTagIdProbPair.hh.
The documentation for this class was generated from the following file:
ematch_src/RecountTagIdProbPair.hh