NGSFeatures: cbrc::TopKSorted< T, BinaryPredicate > Class Template Reference
cbrc::TopKSorted< T, BinaryPredicate > Class Template Reference
#include <TopKSorted.hh>
Public Member Functions
TopKSorted (const size_t &k, const size_t &maxStackSize)
TopKSorted (const TopKSorted< T, BinaryPredicate > &topK)
~TopKSorted ()
const size_t & k () const
const FLEArray< T > & stack () const
const T & operator() (const size_t &i) const
bool cannotBeInTopK (const T &val) const
void insertValueIfInTopK (const T &val)
void sort ()
void clear ()
TopKSorted< T, BinaryPredicate > operator= (const TopKSorted< T, BinaryPredicate > &topK)
Detailed Description
template<typename T, typename BinaryPredicate = std::greater_equal<T>>
class cbrc::TopKSorted< T, BinaryPredicate >
Definition at line 37 of file TopKSorted.hh.
Constructor & Destructor Documentation
TopKSorted() [1/2]
template<typename T , typename BinaryPredicate = std::greater_equal<T>> cbrc::TopKSorted< T, BinaryPredicate >::TopKSorted (const size_t & k, const size_t & maxStackSize) inline
Definition at line 41 of file TopKSorted.hh.
References cbrc::TopKSorted< T, BinaryPredicate >::k(), and cbrc::FLEArray< T >::setSize().
TopKSorted() [2/2]
template<typename T , typename BinaryPredicate = std::greater_equal<T>> cbrc::TopKSorted< T, BinaryPredicate >::TopKSorted (const TopKSorted< T, BinaryPredicate > & topK) inline
Definition at line 49 of file TopKSorted.hh.
References cbrc::FLEArray< T >::setSize().
~TopKSorted()
template<typename T , typename BinaryPredicate = std::greater_equal<T>> cbrc::TopKSorted< T, BinaryPredicate >::~TopKSorted () inline
Definition at line 57 of file TopKSorted.hh.
Member Function Documentation
cannotBeInTopK()
template<typename T , typename BinaryPredicate = std::greater_equal<T>> bool cbrc::TopKSorted< T, BinaryPredicate >::cannotBeInTopK (const T & val) const inline
Definition at line 73 of file TopKSorted.hh.
References cbrc::TopKSorted< T, BinaryPredicate >::k().
clear()
template<typename T , typename BinaryPredicate = std::greater_equal<T>> void cbrc::TopKSorted< T, BinaryPredicate >::clear () inline
Definition at line 118 of file TopKSorted.hh.
insertValueIfInTopK()
template<typename T , typename BinaryPredicate = std::greater_equal<T>> void cbrc::TopKSorted< T, BinaryPredicate >::insertValueIfInTopK (const T & val) inline
Definition at line 83 of file TopKSorted.hh.
References cbrc::FLEArray< T >::begin(), cbrc::TopKSorted< T, BinaryPredicate >::insertValueIfInTopK(), and cbrc::TopKSorted< T, BinaryPredicate >::k().
Referenced by cbrc::TopKSorted< T, BinaryPredicate >::insertValueIfInTopK().
k()
template<typename T , typename BinaryPredicate = std::greater_equal<T>> const size_t & cbrc::TopKSorted< T, BinaryPredicate >::k () const inline
Definition at line 61 of file TopKSorted.hh.
Referenced by cbrc::TopKSorted< T, BinaryPredicate >::cannotBeInTopK(), cbrc::TopKSorted< T, BinaryPredicate >::insertValueIfInTopK(), cbrc::TopKSorted< T, BinaryPredicate >::operator()(), cbrc::TopKSorted< T, BinaryPredicate >::sort(), and cbrc::TopKSorted< T, BinaryPredicate >::TopKSorted().
operator()()
template<typename T , typename BinaryPredicate = std::greater_equal<T>> const T & cbrc::TopKSorted< T, BinaryPredicate >::operator() (const size_t & i) const inline
Definition at line 65 of file TopKSorted.hh.
References cbrc::TopKSorted< T, BinaryPredicate >::k().
operator=()
template<typename T , typename BinaryPredicate = std::greater_equal<T>> TopKSorted< T, BinaryPredicate > cbrc::TopKSorted< T, BinaryPredicate >::operator= (const TopKSorted< T, BinaryPredicate > & topK) inline
Definition at line 120 of file TopKSorted.hh.
sort()
template<typename T , typename BinaryPredicate = std::greater_equal<T>> void cbrc::TopKSorted< T, BinaryPredicate >::sort () inline
Definition at line 112 of file TopKSorted.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and cbrc::TopKSorted< T, BinaryPredicate >::k().
stack()
template<typename T , typename BinaryPredicate = std::greater_equal<T>> const FLEArray< T > & cbrc::TopKSorted< T, BinaryPredicate >::stack () const inline
Definition at line 63 of file TopKSorted.hh.
The documentation for this class was generated from the following file:
ematch_src/utils/sorting/TopKSorted.hh