NGSFeatures: cbrc::DiscreteCumulativeProbabilityDistribution Class Reference
cbrc::DiscreteCumulativeProbabilityDistribution Class Reference
#include <DiscreteCumulativeProbabilityDistribution.hh>
Public Types
typedef FLENumArray< double > arrayT
Public Member Functions
DiscreteCumulativeProbabilityDistribution (const arrayT &distribution, long int seedval=0)
const size_t & size () const
size_t randomInt () const
const double & operator() (const size_t i) const
Detailed Description
Definition at line 19 of file DiscreteCumulativeProbabilityDistribution.hh.
Member Typedef Documentation
arrayT
typedef FLENumArray<double> cbrc::DiscreteCumulativeProbabilityDistribution::arrayT
Definition at line 21 of file DiscreteCumulativeProbabilityDistribution.hh.
Constructor & Destructor Documentation
DiscreteCumulativeProbabilityDistribution()
cbrc::DiscreteCumulativeProbabilityDistribution::DiscreteCumulativeProbabilityDistribution (const arrayT & distribution, long int seedval = 0)
Definition at line 13 of file DiscreteCumulativeProbabilityDistribution.cc.
References size().
Member Function Documentation
operator()()
const double & cbrc::DiscreteCumulativeProbabilityDistribution::operator() (const size_t i) const inline
Definition at line 32 of file DiscreteCumulativeProbabilityDistribution.hh.
randomInt()
size_t cbrc::DiscreteCumulativeProbabilityDistribution::randomInt () const
Definition at line 31 of file DiscreteCumulativeProbabilityDistribution.cc.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
size()
const size_t & cbrc::DiscreteCumulativeProbabilityDistribution::size () const inline
Definition at line 30 of file DiscreteCumulativeProbabilityDistribution.hh.
References cbrc::FLEArray< T >::size().
Referenced by DiscreteCumulativeProbabilityDistribution().
The documentation for this class was generated from the following files:
ematch_src/utils/math/probability/DiscreteCumulativeProbabilityDistribution.hh
ematch_src/utils/math/probability/DiscreteCumulativeProbabilityDistribution.cc