NGSFeatures: cbrc::FastaInputOptions Class Reference
cbrc::FastaInputOptions Class Reference
#include <FastaInputOptions.hh>
Public Types
typedef int(* seqCharFilterT) (int)
Public Member Functions
FastaInputOptions (const boost::regex &betweenLabelsDelimiterRegex=defaultBetweenLabelsDelimiterRegex(), const std::string &commentMarker=defaultCommentMarker(), const seqCharFilterT &seqCharFilter=defaultSeqCharFilter())
FastaInputOptions (const FastaInputOptions &fio)
const boost::regex & betweenLabelsDelimiterRegex () const
const std::string & commentMarker () const
const seqCharFilterT & seqCharFilter () const
void setBetweenLabelsDelimiterRegex (const boost::regex &betweenLabelsDelimiterRegex)
void setCommentMarker (const std::string &commentMarker)
void setSeqCharFilter (const seqCharFilterT &seqCharFilter)
const bool isComment (const std::string &line) const
Static Public Member Functions
static const boost::regex & defaultBetweenLabelsDelimiterRegex ()
static const std::string & defaultCommentMarker ()
static const seqCharFilterT & defaultSeqCharFilter ()
Detailed Description
Definition at line 19 of file FastaInputOptions.hh.
Member Typedef Documentation
seqCharFilterT
typedef int(* cbrc::FastaInputOptions::seqCharFilterT) (int)
Definition at line 23 of file FastaInputOptions.hh.
Constructor & Destructor Documentation
FastaInputOptions() [1/2]
cbrc::FastaInputOptions::FastaInputOptions (const boost::regex & betweenLabelsDelimiterRegex = defaultBetweenLabelsDelimiterRegex(), const std::string & commentMarker = defaultCommentMarker(), const seqCharFilterT & seqCharFilter = defaultSeqCharFilter()) inline
Definition at line 27 of file FastaInputOptions.hh.
FastaInputOptions() [2/2]
cbrc::FastaInputOptions::FastaInputOptions (const FastaInputOptions & fio) inline
Definition at line 43 of file FastaInputOptions.hh.
Member Function Documentation
betweenLabelsDelimiterRegex()
const boost::regex & cbrc::FastaInputOptions::betweenLabelsDelimiterRegex () const inline
Definition at line 53 of file FastaInputOptions.hh.
Referenced by setBetweenLabelsDelimiterRegex().
commentMarker()
const std::string & cbrc::FastaInputOptions::commentMarker () const inline
Definition at line 57 of file FastaInputOptions.hh.
Referenced by isComment(), and setCommentMarker().
defaultBetweenLabelsDelimiterRegex()
static const boost::regex & cbrc::FastaInputOptions::defaultBetweenLabelsDelimiterRegex () inline static
Definition at line 92 of file FastaInputOptions.hh.
defaultCommentMarker()
static const std::string & cbrc::FastaInputOptions::defaultCommentMarker () inline static
Definition at line 97 of file FastaInputOptions.hh.
defaultSeqCharFilter()
static const seqCharFilterT & cbrc::FastaInputOptions::defaultSeqCharFilter () inline static
Definition at line 102 of file FastaInputOptions.hh.
Referenced by cbrc::operator<<().
isComment()
const bool cbrc::FastaInputOptions::isComment (const std::string & line) const inline
Definition at line 80 of file FastaInputOptions.hh.
References commentMarker(), cbrc::FLEArray< T >::size(), and cbrc::stringUtils::startsWith().
seqCharFilter()
const seqCharFilterT & cbrc::FastaInputOptions::seqCharFilter () const inline
Definition at line 61 of file FastaInputOptions.hh.
Referenced by setSeqCharFilter().
setBetweenLabelsDelimiterRegex()
void cbrc::FastaInputOptions::setBetweenLabelsDelimiterRegex (const boost::regex & betweenLabelsDelimiterRegex) inline
Definition at line 65 of file FastaInputOptions.hh.
References betweenLabelsDelimiterRegex().
setCommentMarker()
void cbrc::FastaInputOptions::setCommentMarker (const std::string & commentMarker) inline
Definition at line 69 of file FastaInputOptions.hh.
References commentMarker().
setSeqCharFilter()
void cbrc::FastaInputOptions::setSeqCharFilter (const seqCharFilterT & seqCharFilter) inline
Definition at line 73 of file FastaInputOptions.hh.
References seqCharFilter().
The documentation for this class was generated from the following file:
ematch_src/utils/sequence/readers/fasta/FastaInputOptions.hh