NGSFeatures: cbrc::FLSorted2TypePairSet< T0, T1 > Class Template Reference
cbrc::FLSorted2TypePairSet< T0, T1 > Class Template Reference
#include <FLSorted2TypePairSet.hh>
Public Member Functions
FLSorted2TypePairSet (std::ifstream &ifs, const std::string &delimiter="\t")
FLSorted2TypePairSet ()
FLSorted2TypePairSet (const std::vector< T0 > &initialLhsList, const std::vector< std::vector< T1 > > &correspondingRightHandSideList)
void readFromTextFile (std::ifstream &ifs, const std::string &delimiter="\t")
bool operator() (const T0 &lhs, const T1 &rhs) const
Public Attributes
FLSorted< T0 > lhsToIndex
FLArray< FLSorted< T1 > > lhsIndexToRhsSorted
Friends
void testFLSorted2TypePairSet ()
Detailed Description
template<typename T0, typename T1>
class cbrc::FLSorted2TypePairSet< T0, T1 >
Definition at line 35 of file FLSorted2TypePairSet.hh.
Constructor & Destructor Documentation
FLSorted2TypePairSet() [1/3]
template<typename T0 , typename T1 > cbrc::FLSorted2TypePairSet< T0, T1 >::FLSorted2TypePairSet (std::ifstream & ifs, const std::string & delimiter = "\t") inline
Definition at line 40 of file FLSorted2TypePairSet.hh.
References cbrc::FLSorted2TypePairSet< T0, T1 >::readFromTextFile().
FLSorted2TypePairSet() [2/3]
template<typename T0 , typename T1 > cbrc::FLSorted2TypePairSet< T0, T1 >::FLSorted2TypePairSet () inline
Definition at line 44 of file FLSorted2TypePairSet.hh.
FLSorted2TypePairSet() [3/3]
template<typename T0 , typename T1 > cbrc::FLSorted2TypePairSet< T0, T1 >::FLSorted2TypePairSet (const std::vector< T0 > & initialLhsList, const std::vector< std::vector< T1 > > & correspondingRightHandSideList) inline
Definition at line 47 of file FLSorted2TypePairSet.hh.
References cbrc::FLSorted2TypePairSet< T0, T1 >::lhsToIndex, cbrc::FLEArray< T >::size(), and cbrc::FLSorted< T >::size().
Member Function Documentation
operator()()
template<typename T0 , typename T1 > bool cbrc::FLSorted2TypePairSet< T0, T1 >::operator() (const T0 & lhs, const T1 & rhs) const inline
Definition at line 89 of file FLSorted2TypePairSet.hh.
References cbrc::FLSorted< T >::has(), cbrc::FLSorted2TypePairSet< T0, T1 >::lhsIndexToRhsSorted, and cbrc::FLSorted2TypePairSet< T0, T1 >::lhsToIndex.
readFromTextFile()
template<typename T0 , typename T1 > void cbrc::FLSorted2TypePairSet< T0, T1 >::readFromTextFile (std::ifstream & ifs, const std::string & delimiter = "\t") inline
Definition at line 117 of file FLSorted2TypePairSet.hh.
References cbrc::FLEArray< T >::FLEArray(), GDB_ASSERTF, cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLine(), and cbrc::perlish::split().
Referenced by cbrc::FLSorted2TypePairSet< T0, T1 >::FLSorted2TypePairSet().
Friends And Related Symbol Documentation
testFLSorted2TypePairSet
template<typename T0 , typename T1 > void testFLSorted2TypePairSet () friend
Member Data Documentation
lhsIndexToRhsSorted
template<typename T0 , typename T1 > FLArray< FLSorted<T1> > cbrc::FLSorted2TypePairSet< T0, T1 >::lhsIndexToRhsSorted
Definition at line 98 of file FLSorted2TypePairSet.hh.
Referenced by cbrc::FLSorted2TypePairSet< T0, T1 >::operator()().
lhsToIndex
template<typename T0 , typename T1 > FLSorted<T0> cbrc::FLSorted2TypePairSet< T0, T1 >::lhsToIndex
Definition at line 97 of file FLSorted2TypePairSet.hh.
Referenced by cbrc::FLSorted2TypePairSet< T0, T1 >::FLSorted2TypePairSet(), and cbrc::FLSorted2TypePairSet< T0, T1 >::operator()().
The documentation for this class was generated from the following file:
ematch_src/utils/FLArray/FLSorted2TypePairSet.hh