NGSFeatures: cbrc::FLEArray< T > Class Template Reference
cbrc::FLEArray< T > Class Template Reference
#include <FLEArray.hh>
Public Types
typedef T * iterator
typedef const T * const_iterator
typedef unsigned char uchar
typedef T * iterator
typedef const T * const_iterator
typedef unsigned char uchar
Public Member Functions
FLEArray ()
FLEArray (const size_t &sz)
FLEArray (const std::string semanticTypeDescriptor, const std::string arrayLiteral)
FLEArray (const size_t &sz, const T &fillVal)
FLEArray (const size_t &sz, const T *const &c_array)
FLEArray (const std::vector< T > &v)
FLEArray (const FLEArray< T > &fla)
FLEArray (const FLEArray< T > &fla, const size_t &startIndex, const size_t &endIndex)
FLEArray (std::istream &is)
FLEArray (const size_t &size, std::istream &is)
virtual ~FLEArray ()
operator std::vector< T > () const
void setSize (const size_t &sz)
void resize (const size_t &sz)
FLEArray operator= (const FLEArray &fla)
FLEArray operator= (const std::vector< T > &v)
void assign (const typename FLEArray< T >::const_iterator &begin, const typename FLEArray< T >::const_iterator &end)
void assign (const typename std::vector< T >::const_iterator &begin, const typename std::vector< T >::const_iterator &end)
void setFromLiteral (const std::string semanticTypeDescriptor, const std::string arrayLiteral)
void replace (const size_t &begIdx, const FLEArray< T > &replacementArray)
void replace (const size_t &begIdx, const size_t &endIdx, const T *const &cArray)
bool operator== (const FLEArray &fla) const
bool operator!= (const FLEArray &fla) const
virtual T & operator[] (const size_t &index) const
virtual const T & operator() (const size_t &index) const
const size_t & size () const
size_t bsize () const
bool empty () const
bool indexInRange (const size_t &idx) const
iterator begin () const
iterator end () const
const_iterator constBegin () const
const_iterator constEnd () const
void zero ()
void fill (const T &fillVal, const size_t begIdx=0)
void fill (const T &fillVal, const size_t &begIdx, const size_t &endIdx)
void fillWithByte (const int &fillByte)
void read (std::istream &is)
void write (std::ostream &os) const
virtual void print (std::ostream &os=std::cout, const std::string &delimiter="\t") const
virtual void printNumbered (std::ostream &os=std::cout, const size_t startLabel=0) const
size_t find (const T &val, const size_t &begIdx, const size_t &endIdx)
size_t find (const T &val, const size_t begIdx=0)
size_t rfind (const T &val, const size_t &begIdx, const size_t &endIdx)
size_t rfind (const T &val, const size_t begIdx=0)
FLEArray ()
FLEArray (const size_t &sz)
FLEArray (const std::string semanticTypeDescriptor, const std::string arrayLiteral)
FLEArray (const size_t &sz, const T &fillVal)
FLEArray (const size_t &sz, const T *const &c_array)
FLEArray (const std::vector< T > &v)
FLEArray (const FLEArray< T > &fla)
FLEArray (const FLEArray< T > &fla, const size_t &startIndex, const size_t &endIndex)
FLEArray (std::istream &is)
FLEArray (const size_t &size, std::istream &is)
virtual ~FLEArray ()
operator std::vector< T > () const
void setSize (const size_t &sz)
void resize (const size_t &sz)
FLEArray operator= (const FLEArray &fla)
FLEArray operator= (const std::vector< T > &v)
void assign (const typename FLEArray< T >::const_iterator &begin, const typename FLEArray< T >::const_iterator &end)
void assign (const typename std::vector< T >::const_iterator &begin, const typename std::vector< T >::const_iterator &end)
void setFromLiteral (const std::string semanticTypeDescriptor, const std::string arrayLiteral)
void replace (const size_t &begIdx, const FLEArray< T > &replacementArray)
void replace (const size_t &begIdx, const size_t &endIdx, const T *const &cArray)
bool operator== (const FLEArray &fla) const
bool operator!= (const FLEArray &fla) const
virtual T & operator[] (const size_t &index) const
virtual const T & operator() (const size_t &index) const
const size_t & size () const
size_t bsize () const
bool empty () const
bool indexInRange (const size_t &idx) const
iterator begin () const
iterator end () const
const_iterator constBegin () const
const_iterator constEnd () const
void zero ()
void fill (const T &fillVal, const size_t begIdx=0)
void fill (const T &fillVal, const size_t &begIdx, const size_t &endIdx)
void fillWithByte (const int &fillByte)
void read (std::istream &is)
void write (std::ostream &os) const
virtual void print (std::ostream &os=std::cout, const std::string &delimiter="\t") const
virtual void printNumbered (std::ostream &os=std::cout, const size_t startLabel=0) const
size_t find (const T &val, const size_t &begIdx, const size_t &endIdx)
size_t find (const T &val, const size_t begIdx=0)
size_t rfind (const T &val, const size_t &begIdx, const size_t &endIdx)
size_t rfind (const T &val, const size_t begIdx=0)
Static Public Member Functions
static void skip (std::istream &is)
static void skip (std::istream &is)
Static Public Attributes
static const size_t npos = static_cast<size_t>(-1)
Protected Member Functions
bool _validIndex (const size_t &idx) const
bool _validRange (const size_t &begIdx, const size_t &endIdx)
void _assertNonzeroSize () const
void _assertSizeEqual (const FLEArray< T > &fla) const
bool _validIndex (const size_t &idx) const
bool _validRange (const size_t &begIdx, const size_t &endIdx)
void _assertNonzeroSize () const
void _assertSizeEqual (const FLEArray< T > &fla) const
Static Protected Member Functions
static size_t bsize (const size_t &numElems)
static size_t bsize (const size_t &numElems)
Protected Attributes
size_t s
T * a
Detailed Description
template<typename T>
class cbrc::FLEArray< T >
Definition at line 46 of file FLEArray.hh.
Member Typedef Documentation
const_iterator [1/2]
template<typename T > typedef const T* cbrc::FLEArray< T >::const_iterator
Definition at line 52 of file FLEArray.hh.
const_iterator [2/2]
template<typename T > typedef const T* cbrc::FLEArray< T >::const_iterator
Definition at line 52 of file FLEArray.hh.
iterator [1/2]
template<typename T > typedef T* cbrc::FLEArray< T >::iterator
Definition at line 51 of file FLEArray.hh.
iterator [2/2]
template<typename T > typedef T* cbrc::FLEArray< T >::iterator
Definition at line 51 of file FLEArray.hh.
uchar [1/2]
template<typename T > typedef unsigned char cbrc::FLEArray< T >::uchar
Definition at line 53 of file FLEArray.hh.
uchar [2/2]
template<typename T > typedef unsigned char cbrc::FLEArray< T >::uchar
Definition at line 53 of file FLEArray.hh.
Constructor & Destructor Documentation
FLEArray() [1/20]
template<typename T > cbrc::FLEArray< T >::FLEArray () inline
Definition at line 61 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::s.
Referenced by cbrc::FLEArray< T >::_assertNonzeroSize(), cbrc::FLEArray< T >::_assertSizeEqual(), cbrc::FLEArray< T >::_validRange(), cbrc::FLEArray< T >::assign(), cbrc::FLEArray< T >::assign(), cbrc::GlobalAffineIdentityAligner::bestPossibleSuffixScore(), cbrc::SeqGlobalAffineAligner::bestPossibleSuffixScore(), cbrc::HammingDistanceComputer::computeBounded(), cbrc::HammingDistanceComputer::computeBoundedGapAtBeg(), cbrc::HammingDistanceComputer::computeBoundedGapAtBeg(), cbrc::HammingDistanceComputer::computeBoundedGapAtEnd(), cbrc::FLEArray< T >::fill(), cbrc::FLEArray< T >::fillWithByte(), cbrc::FLENumArray< T >::finalMaxIndex(), cbrc::FLENumArray< T >::finalMinIndex(), cbrc::FLEArray< T >::find(), cbrc::FLENumArray< T >::firstMaxIndex(), cbrc::FLENumArray< T >::firstMinIndex(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::SerialNumbersForStrings< serialNumT >::getSerialNumber(), cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::getSerialNumber(), cbrc::Matrix< T >::Matrix(), cbrc::Matrix< T >::Matrix(), cbrc::Matrix< T >::Matrix(), cbrc::FLENumArray< T >::max(), cbrc::FLENumArray< T >::max(), cbrc::FLENumArray< T >::min(), cbrc::FLENumArray< T >::min(), cbrc::FLEArray< T >::operator!=(), cbrc::FLEArray< T >::operator()(), cbrc::SerialNumbersForStrings< serialNumT >::operator()(), cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::operator()(), cbrc::FLENumArray< T >::operator*=(), cbrc::FLENumArray< T >::operator+=(), cbrc::FLENumArray< T >::operator-=(), cbrc::FLENumArray< T >::operator/=(), cbrc::FLEArray< T >::operator=(), cbrc::Matrix< T >::operator=(), cbrc::FLEArray< T >::operator==(), cbrc::SerialNumbersForStrings< serialNumT >::operator==(), cbrc::FLEArray< T >::operator[](), cbrc::FLEArrayFast< T >::operator[](), cbrc::Matrix< T >::operator[](), cbrc::BoundedLenFifoVector< T >::popOldest(), cbrc::FLEArray< T >::print(), cbrc::TrivialHistogram< T >::printNonzeroEntries(), cbrc::FLEArray< T >::printNumbered(), cbrc::FLEArray< T >::read(), cbrc::FLSorted2TypePairSet< T0, T1 >::readFromTextFile(), cbrc::ConstantLabeledSquareDoubleFLENumMatrix::renumLabels(), cbrc::LabeledSquareFLENumMatrix< elemT >::reorderLabels(), cbrc::FLEArray< T >::replace(), cbrc::FLEArray< T >::replace(), cbrc::FLEArray< T >::resize(), cbrc::Matrix< T >::resize(), cbrc::FLEArray< T >::rfind(), cbrc::SeqGlobalAffineAligner::scoreBounded(), cbrc::GlobalAffineIdentityAligner::scoreBounded(), cbrc::FLEArray< T >::setFromLiteral(), cbrc::FLEArray< T >::setSize(), cbrc::FLEArray< T >::skip(), cbrc::FLENumArray< T >::squareElements(), cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::strings(), cbrc::FLENumArray< T >::sum(), cbrc::ResidueIndexMapTranslator::translateInPlace(), and cbrc::SimilaritySearchableSequences::wouldSkipAll().
FLEArray() [2/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const size_t & sz) inline explicit
Definition at line 63 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, and cbrc::FLEArray< T >::size().
FLEArray() [3/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const std::string semanticTypeDescriptor, const std::string arrayLiteral) inline
Definition at line 67 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::setFromLiteral().
FLEArray() [4/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const size_t & sz, const T & fillVal) inline
Definition at line 73 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::fill(), and cbrc::FLEArray< T >::size().
FLEArray() [5/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const size_t & sz, const T *const & c_array) inline
Definition at line 78 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
FLEArray() [6/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const std::vector< T > & v) inline
Definition at line 83 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::size().
FLEArray() [7/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const FLEArray< T > & fla) inline
Definition at line 89 of file FLEArray.hh.
References cbrc::FLEArray< T >::assign(), cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
FLEArray() [8/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const FLEArray< T > & fla, const size_t & startIndex, const size_t & endIndex) inline
Definition at line 93 of file FLEArray.hh.
References cbrc::FLEArray< T >::assign(), cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and cbrc::FLEArray< T >::size().
FLEArray() [9/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (std::istream & is) inline
Definition at line 100 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::size().
FLEArray() [10/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const size_t & size, std::istream & is) inline
Definition at line 106 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), cbrc::FLEArray< T >::read(), and cbrc::FLEArray< T >::size().
~FLEArray() [1/2]
template<typename T > virtual cbrc::FLEArray< T >::~FLEArray () inline virtual
Definition at line 113 of file FLEArray.hh.
References cbrc::FLEArray< T >::a.
FLEArray() [11/20]
template<typename T > cbrc::FLEArray< T >::FLEArray () inline
Definition at line 61 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::s.
FLEArray() [12/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const size_t & sz) inline explicit
Definition at line 63 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, and cbrc::FLEArray< T >::size().
FLEArray() [13/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const std::string semanticTypeDescriptor, const std::string arrayLiteral) inline
Definition at line 67 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::setFromLiteral().
FLEArray() [14/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const size_t & sz, const T & fillVal) inline
Definition at line 73 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::fill(), and cbrc::FLEArray< T >::size().
FLEArray() [15/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const size_t & sz, const T *const & c_array) inline
Definition at line 78 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
FLEArray() [16/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const std::vector< T > & v) inline
Definition at line 83 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::size().
FLEArray() [17/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const FLEArray< T > & fla) inline
Definition at line 89 of file FLEArray.hh.
References cbrc::FLEArray< T >::assign(), cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
FLEArray() [18/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const FLEArray< T > & fla, const size_t & startIndex, const size_t & endIndex) inline
Definition at line 93 of file FLEArray.hh.
References cbrc::FLEArray< T >::assign(), cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and cbrc::FLEArray< T >::size().
FLEArray() [19/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (std::istream & is) inline
Definition at line 100 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::size().
FLEArray() [20/20]
template<typename T > cbrc::FLEArray< T >::FLEArray (const size_t & size, std::istream & is) inline
Definition at line 106 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), cbrc::FLEArray< T >::read(), and cbrc::FLEArray< T >::size().
~FLEArray() [2/2]
template<typename T > virtual cbrc::FLEArray< T >::~FLEArray () inline virtual
Definition at line 113 of file FLEArray.hh.
References cbrc::FLEArray< T >::a.
Member Function Documentation
_assertNonzeroSize() [1/2]
template<typename T > void cbrc::FLEArray< T >::_assertNonzeroSize () const protected
Definition at line 751 of file FLEArray.hh.
References cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
Referenced by cbrc::FLENumArray< T >::finalMaxIndex(), cbrc::FLENumArray< T >::finalMinIndex(), cbrc::FLENumArray< T >::firstMaxIndex(), cbrc::FLENumArray< T >::firstMinIndex(), cbrc::FLENumArray< T >::max(), cbrc::FLENumArray< T >::max(), cbrc::FLENumArray< T >::min(), and cbrc::FLENumArray< T >::min().
_assertNonzeroSize() [2/2]
template<typename T > void cbrc::FLEArray< T >::_assertNonzeroSize () const protected
_assertSizeEqual() [1/2]
template<typename T > void cbrc::FLEArray< T >::_assertSizeEqual (const FLEArray< T > & fla) const protected
Definition at line 763 of file FLEArray.hh.
References cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
Referenced by cbrc::FLENumArray< T >::operator+=(), and cbrc::FLENumArray< T >::operator-=().
_assertSizeEqual() [2/2]
template<typename T > void cbrc::FLEArray< T >::_assertSizeEqual (const FLEArray< T > & fla) const protected
_validIndex() [1/2]
template<typename T > bool cbrc::FLEArray< T >::_validIndex (const size_t & idx) const protected
Definition at line 726 of file FLEArray.hh.
References cbrc::FLEArray< T >::s.
Referenced by cbrc::FLEArray< T >::_validRange(), cbrc::FLENumArray< T >::max(), cbrc::FLENumArray< T >::min(), cbrc::FLEArray< T >::operator()(), and cbrc::FLEArray< T >::operator[]().
_validIndex() [2/2]
template<typename T > bool cbrc::FLEArray< T >::_validIndex (const size_t & idx) const protected
_validRange() [1/2]
template<typename T > bool cbrc::FLEArray< T >::_validRange (const size_t & begIdx, const size_t & endIdx) protected
Definition at line 740 of file FLEArray.hh.
References cbrc::FLEArray< T >::_validIndex(), and cbrc::FLEArray< T >::FLEArray().
Referenced by cbrc::FLEArray< T >::fill(), cbrc::FLEArray< T >::find(), and cbrc::FLEArray< T >::rfind().
_validRange() [2/2]
template<typename T > bool cbrc::FLEArray< T >::_validRange (const size_t & begIdx, const size_t & endIdx) protected
assign() [1/4]
template<typename T > void cbrc::FLEArray< T >::assign (const typename FLEArray< T >::const_iterator & begin, const typename FLEArray< T >::const_iterator & end)
Definition at line 642 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::resize().
Referenced by cbrc::RecountTagCounts::assign(), cbrc::FLESorted< T >::assign(), cbrc::FLSorted< T >::assign(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::operator=(), cbrc::FLEArray< T >::operator=(), and cbrc::FLSortedFunctions::read().
assign() [2/4]
template<typename T > void cbrc::FLEArray< T >::assign (const typename FLEArray< T >::const_iterator & begin, const typename FLEArray< T >::const_iterator & end)
assign() [3/4]
template<typename T > void cbrc::FLEArray< T >::assign (const typename std::vector< T >::const_iterator & begin, const typename std::vector< T >::const_iterator & end)
Definition at line 654 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::resize().
assign() [4/4]
template<typename T > void cbrc::FLEArray< T >::assign (const typename std::vector< T >::const_iterator & begin, const typename std::vector< T >::const_iterator & end)
begin() [1/2]
template<typename T > iterator cbrc::FLEArray< T >::begin () const inline
Definition at line 202 of file FLEArray.hh.
References cbrc::FLEArray< T >::a.
Referenced by cbrc::GlobalAffineIdentityAligner::alignment(), cbrc::SeqGlobalAffineAligner::alignment(), cbrc::allPairsNearestGlobalAffineScore(), cbrc::FLEArray< T >::assign(), cbrc::FLEArray< T >::assign(), cbrc::FLESorted< T >::assign(), cbrc::FLSorted< T >::assign(), cbrc::RecountTagCounts::assignDifference(), cbrc::ResidueIndexMap::assignResidueIndices(), cbrc::RecountTagCounts::assignSum(), cbrc::FLESorted< T >::begin(), cbrc::FLSorted< T >::begin(), cbrc::ResidueIndexedSequence::begin(), cbrc::SerialNumbersForStrings< serialNumT >::begin(), cbrc::BlastEValuesByClass::bestEValuePerClass(), cbrc::SimilaritySearchableSequences::bestMatch(), cbrc::clusterByIdentity(), cbrc::HammingDistanceComputer::computeBoundedGapAtBeg(), cbrc::dumpAminoAcidContentWPformat(), cbrc::dumpBlastNNUtility(), cbrc::FLESorted< T >::elementRank(), cbrc::FLESorted< T >::elementRankAfterTies(), cbrc::FastafmtRecord::FastafmtRecord(), cbrc::FastaRecord::FastaRecord(), cbrc::FLArray< T >::FLArray(), cbrc::FLArraySortedPermutation(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArraySortedPermutation(), cbrc::FLESorted< T >::FLESorted(), cbrc::FLSorted< T >::FLSorted(), cbrc::FLSorted< T >::has(), cbrc::FLESorted< T >::has(), cbrc::TopKSorted< T, BinaryPredicate >::insertValueIfInTopK(), cbrc::ArgvParser::isMember(), cbrc::LabeledAsciiSeq::LabeledAsciiSeq(), cbrc::LabeledAsciiSeq::LabeledAsciiSeq(), cbrc::labeledBlastToOddsRatio(), cbrc::LabeledSequence::LabeledSequence(), cbrc::LabeledSequence::LabeledSequence(), cbrc::LabeledSequence::LabeledSequence(), cbrc::listConnectedComponents(), cbrc::MallocArray< T >::MallocArray(), cbrc::FLENumArray< T >::max(), cbrc::FLENumArray< T >::max(), cbrc::stlUtils::max(), cbrc::FLENumArray< T >::min(), cbrc::FLENumArray< T >::min(), cbrc::FLEArray< alignScoreT >::operator std::vector< alignScoreT >(), cbrc::FLSorted< T >::operator()(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::FLArray< T >::operator=(), cbrc::FLEArray< T >::operator=(), cbrc::FLNumArray< T >::operator=(), cbrc::LabeledAsciiSeq::operator=(), cbrc::MallocArray< T >::operator=(), cbrc::FLESorted< T >::operator=(), cbrc::FLSorted< T >::operator=(), cbrc::sigma4bitPackingUtils::pack(), cbrc::printRandomRepresentativeFromEachConnectedComponent(), cbrc::DiscreteCumulativeProbabilityDistribution::randomInt(), cbrc::LabeledSquareFLENumMatrix< elemT >::reorderLabels(), cbrc::ResidueIndexMapTranslator::ResidueIndexMapTranslator(), cbrc::runAllShortestEdgeLengthPaths(), cbrc::FastafmtRecord::setLabels(), cbrc::FastaRecord::setLabels(), cbrc::TopKSorted< T, BinaryPredicate >::sort(), cbrc::perlish::split(), cbrc::perlish::split(), cbrc::ResidueIndexMap::splitIntoProperOnlySubstrings(), cbrc::stringUtils::startsWith(), cbrc::StringSpecEnum::StringSpecEnum(), cbrc::testFLArrayByIndexSortingPredicate(), cbrc::testForEach(), cbrc::testMapSpeed(), cbrc::testStringKeyHashtableSpeed(), cbrc::ResidueIndexMap::toResidues(), cbrc::stlUtils::transformAll(), cbrc::ResidueIndexMapTransformer::transformInPlace(), cbrc::sigma4bitPackingUtils::unpack(), cbrc::FastafmtReader::upcaseSequence(), and cbrc::FastaReader::upcaseSequence().
begin() [2/2]
template<typename T > iterator cbrc::FLEArray< T >::begin () const inline
Definition at line 202 of file FLEArray.hh.
References cbrc::FLEArray< T >::a.
bsize() [1/4]
template<typename T > size_t cbrc::FLEArray< T >::bsize () const inline
Definition at line 192 of file FLEArray.hh.
References cbrc::FLEArray< T >::size().
Referenced by cbrc::FLEArray< T >::fillWithByte(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::read(), cbrc::FLEArray< T >::replace(), cbrc::FLEArray< T >::replace(), and cbrc::FLEArray< T >::write().
bsize() [2/4]
template<typename T > size_t cbrc::FLEArray< T >::bsize () const inline
Definition at line 192 of file FLEArray.hh.
References cbrc::FLEArray< T >::size().
bsize() [3/4]
template<typename T > static size_t cbrc::FLEArray< T >::bsize (const size_t & numElems) inline static protected
Definition at line 272 of file FLEArray.hh.
bsize() [4/4]
template<typename T > static size_t cbrc::FLEArray< T >::bsize (const size_t & numElems) inline static protected
Definition at line 272 of file FLEArray.hh.
constBegin() [1/2]
template<typename T > const_iterator cbrc::FLEArray< T >::constBegin () const inline
Definition at line 205 of file FLEArray.hh.
References cbrc::FLEArray< T >::a.
Referenced by cbrc::RecountTagCounts::assign(), cbrc::RecountTagCounts::assignSum(), cbrc::HammingDistanceComputer::computeBoundedGapAtBeg(), cbrc::RecountExpectationMatchingTagCorrector::computeCountCorrections(), cbrc::RecountExpectationMatchingTagCorrector::computeCountCorrections_by1stDerivative(), cbrc::RecountTagCounts::constBegin(), cbrc::RecountTagCounts::maxAbsDiff(), and cbrc::RecountExpectationMatchingTagCorrector::totalFoldChangeError().
constBegin() [2/2]
template<typename T > const_iterator cbrc::FLEArray< T >::constBegin () const inline
Definition at line 205 of file FLEArray.hh.
References cbrc::FLEArray< T >::a.
constEnd() [1/2]
template<typename T > const_iterator cbrc::FLEArray< T >::constEnd () const inline
Definition at line 206 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, and cbrc::FLEArray< T >::s.
Referenced by cbrc::RecountTagCounts::assign(), cbrc::HammingDistanceComputer::computeBoundedGapAtBeg(), cbrc::RecountTagCounts::constEnd(), cbrc::RecountTagCounts::maxAbsDiff(), and cbrc::RecountExpectationMatchingTagCorrector::totalFoldChangeError().
constEnd() [2/2]
template<typename T > const_iterator cbrc::FLEArray< T >::constEnd () const inline
Definition at line 206 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, and cbrc::FLEArray< T >::s.
empty() [1/2]
template<typename T > bool cbrc::FLEArray< T >::empty () const inline
Definition at line 194 of file FLEArray.hh.
References cbrc::FLEArray< T >::s.
Referenced by cbrc::FLSorted< T >::assign(), cbrc::fastafmtFunctions::countRecords(), cbrc::ArgvParser::dieIfUnusedArgs(), cbrc::operator<<(), and cbrc::FLSorted< T >::operator=().
empty() [2/2]
template<typename T > bool cbrc::FLEArray< T >::empty () const inline
Definition at line 194 of file FLEArray.hh.
References cbrc::FLEArray< T >::s.
end() [1/2]
template<typename T > iterator cbrc::FLEArray< T >::end () const inline
Definition at line 203 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, and cbrc::FLEArray< T >::s.
Referenced by cbrc::GlobalAffineIdentityAligner::alignment(), cbrc::SeqGlobalAffineAligner::alignment(), cbrc::allPairsNearestGlobalAffineScore(), cbrc::FLEArray< T >::assign(), cbrc::FLEArray< T >::assign(), cbrc::FLESorted< T >::assign(), cbrc::FLSorted< T >::assign(), cbrc::RecountTagCounts::assignDifference(), cbrc::ResidueIndexMap::assignResidueIndices(), cbrc::RecountTagCounts::assignSum(), cbrc::BlastEValuesByClass::bestEValuePerClass(), cbrc::SimilaritySearchableSequences::bestMatch(), cbrc::clusterByIdentity(), cbrc::HammingDistanceComputer::computeBoundedGapAtBeg(), cbrc::dumpAminoAcidContentWPformat(), cbrc::dumpBlastNNUtility(), cbrc::FLESorted< T >::elementRank(), cbrc::FLESorted< T >::elementRankAfterTies(), cbrc::FLESorted< T >::end(), cbrc::FLSorted< T >::end(), cbrc::ResidueIndexedSequence::end(), cbrc::SerialNumbersForStrings< serialNumT >::end(), cbrc::FastafmtRecord::FastafmtRecord(), cbrc::FastaRecord::FastaRecord(), cbrc::FLArray< T >::FLArray(), cbrc::FLArraySortedPermutation(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArraySortedPermutation(), cbrc::FLESorted< T >::FLESorted(), cbrc::FLSorted< T >::FLSorted(), cbrc::FLSorted< T >::has(), cbrc::FLESorted< T >::has(), cbrc::ArgvParser::isMember(), cbrc::LabeledAsciiSeq::LabeledAsciiSeq(), cbrc::LabeledAsciiSeq::LabeledAsciiSeq(), cbrc::labeledBlastToOddsRatio(), cbrc::LabeledSequence::LabeledSequence(), cbrc::LabeledSequence::LabeledSequence(), cbrc::LabeledSequence::LabeledSequence(), cbrc::listConnectedComponents(), cbrc::MallocArray< T >::MallocArray(), cbrc::FLENumArray< T >::max(), cbrc::stlUtils::max(), cbrc::FLENumArray< T >::min(), cbrc::smoothing::monotonicSmoothY(), cbrc::FLEArray< alignScoreT >::operator std::vector< alignScoreT >(), cbrc::LabeledSequencePairPredicate_logicalOr::operator()(), cbrc::FLSorted< T >::operator()(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::FLArray< T >::operator=(), cbrc::FLEArray< T >::operator=(), cbrc::FLNumArray< T >::operator=(), cbrc::LabeledAsciiSeq::operator=(), cbrc::MallocArray< T >::operator=(), cbrc::FLESorted< T >::operator=(), cbrc::FLSorted< T >::operator=(), cbrc::sigma4bitPackingUtils::pack(), cbrc::printRandomRepresentativeFromEachConnectedComponent(), cbrc::DiscreteCumulativeProbabilityDistribution::randomInt(), cbrc::LabeledSquareFLENumMatrix< elemT >::reorderLabels(), cbrc::ResidueIndexMapTranslator::ResidueIndexMapTranslator(), cbrc::runAllShortestEdgeLengthPaths(), cbrc::FastafmtRecord::setLabels(), cbrc::FastaRecord::setLabels(), cbrc::TopKSorted< T, BinaryPredicate >::sort(), cbrc::perlish::split(), cbrc::stringUtils::startsWith(), cbrc::StringSpecEnum::StringSpecEnum(), cbrc::testFLArrayByIndexSortingPredicate(), cbrc::testForEach(), cbrc::testMapSpeed(), cbrc::testStringKeyHashtableSpeed(), cbrc::stlUtils::transformAll(), cbrc::ResidueIndexMapTransformer::transformInPlace(), cbrc::sigma4bitPackingUtils::unpack(), cbrc::FastafmtReader::upcaseSequence(), and cbrc::FastaReader::upcaseSequence().
end() [2/2]
template<typename T > iterator cbrc::FLEArray< T >::end () const inline
Definition at line 203 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, and cbrc::FLEArray< T >::s.
fill() [1/4]
template<typename T > void cbrc::FLEArray< T >::fill (const T & fillVal, const size_t & begIdx, const size_t & endIdx)
Definition at line 572 of file FLEArray.hh.
References cbrc::FLEArray< T >::_validRange(), cbrc::FLEArray< T >::a, and cbrc::FLEArray< T >::FLEArray().
fill() [2/4]
template<typename T > void cbrc::FLEArray< T >::fill (const T & fillVal, const size_t & begIdx, const size_t & endIdx)
fill() [3/4]
template<typename T > void cbrc::FLEArray< T >::fill (const T & fillVal, const size_t begIdx = 0) inline
Definition at line 214 of file FLEArray.hh.
References cbrc::FLEArray< T >::fill(), and cbrc::FLEArray< T >::size().
Referenced by cbrc::ConnectedComponentOnlineComputer::ConnectedComponentOnlineComputer(), cbrc::FLEArray< T >::fill(), cbrc::FLEArray< T >::FLEArray(), cbrc::ResidueIndexMapTransformer::ResidueIndexMapTransformer(), cbrc::ResidueIndexMapTranslator::ResidueIndexMapTranslator(), and cbrc::FLEArray< T >::zero().
fill() [4/4]
template<typename T > void cbrc::FLEArray< T >::fill (const T & fillVal, const size_t begIdx = 0) inline
Definition at line 214 of file FLEArray.hh.
References cbrc::FLEArray< T >::fill(), and cbrc::FLEArray< T >::size().
fillWithByte() [1/2]
template<typename T > void cbrc::FLEArray< T >::fillWithByte (const int & fillByte) inline
Definition at line 221 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), and cbrc::FLEArray< T >::FLEArray().
fillWithByte() [2/2]
template<typename T > void cbrc::FLEArray< T >::fillWithByte (const int & fillByte) inline
Definition at line 221 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), and cbrc::FLEArray< T >::FLEArray().
find() [1/4]
template<typename T > size_t cbrc::FLEArray< T >::find (const T & val, const size_t & begIdx, const size_t & endIdx)
Definition at line 692 of file FLEArray.hh.
References cbrc::FLEArray< T >::_validRange(), cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::npos.
Referenced by cbrc::perlish::_split(), cbrc::assertStringLooksOkay(), cbrc::FLEArray< T >::find(), cbrc::Blast8ResultReader::isBlastCommentLine(), cbrc::UnsignedDoubleMap::operator()(), cbrc::TransfacBindingFactor::set(), cbrc::perlish::split(), cbrc::perlish::splitOnOneMatch(), cbrc::perlish::splitOnOneOrMoreCharsInCharSet(), cbrc::perlish::splitOnOneOrMoreCharsInCharSet(), cbrc::sprotGrepOC(), cbrc::stringUtils::stringReplaceAll(), cbrc::perlish::toSeconds(), and cbrc::meminfo::total().
find() [2/4]
template<typename T > size_t cbrc::FLEArray< T >::find (const T & val, const size_t & begIdx, const size_t & endIdx)
find() [3/4]
template<typename T > size_t cbrc::FLEArray< T >::find (const T & val, const size_t begIdx = 0) inline
Definition at line 258 of file FLEArray.hh.
References cbrc::FLEArray< T >::find(), and cbrc::FLEArray< T >::size().
find() [4/4]
template<typename T > size_t cbrc::FLEArray< T >::find (const T & val, const size_t begIdx = 0) inline
Definition at line 258 of file FLEArray.hh.
References cbrc::FLEArray< T >::find(), and cbrc::FLEArray< T >::size().
indexInRange() [1/2]
template<typename T > bool cbrc::FLEArray< T >::indexInRange (const size_t & idx) const inline
Definition at line 198 of file FLEArray.hh.
References cbrc::FLEArray< T >::size().
Referenced by cbrc::SeqGlobalAffineAligner::bestPossibleSuffixScore().
indexInRange() [2/2]
template<typename T > bool cbrc::FLEArray< T >::indexInRange (const size_t & idx) const inline
Definition at line 198 of file FLEArray.hh.
References cbrc::FLEArray< T >::size().
operator std::vector< T >() [1/2]
template<typename T > cbrc::FLEArray< T >::operator std::vector< T > () const inline
Definition at line 116 of file FLEArray.hh.
operator std::vector< T >() [2/2]
template<typename T > cbrc::FLEArray< T >::operator std::vector< T > () const inline
Definition at line 116 of file FLEArray.hh.
operator!=() [1/2]
template<typename T > bool cbrc::FLEArray< T >::operator!= (const FLEArray< T > & fla) const inline
Definition at line 170 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
operator!=() [2/2]
template<typename T > bool cbrc::FLEArray< T >::operator!= (const FLEArray< T > & fla) const inline
Definition at line 170 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
operator()() [1/2]
template<typename T > virtual const T & cbrc::FLEArray< T >::operator() (const size_t & index) const inline virtual
Definition at line 184 of file FLEArray.hh.
References cbrc::FLEArray< T >::_validIndex(), cbrc::FLEArray< T >::a, and cbrc::FLEArray< T >::FLEArray().
operator()() [2/2]
template<typename T > virtual const T & cbrc::FLEArray< T >::operator() (const size_t & index) const inline virtual
Definition at line 184 of file FLEArray.hh.
References cbrc::FLEArray< T >::_validIndex(), cbrc::FLEArray< T >::a, and cbrc::FLEArray< T >::FLEArray().
operator=() [1/4]
template<typename T > FLEArray< T > cbrc::FLEArray< T >::operator= (const FLEArray< T > & fla)
Definition at line 609 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::assign(), cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::size().
operator=() [2/4]
template<typename T > FLEArray cbrc::FLEArray< T >::operator= (const FLEArray< T > & fla)
operator=() [3/4]
template<typename T > FLEArray cbrc::FLEArray< T >::operator= (const std::vector< T > & v) inline
Definition at line 138 of file FLEArray.hh.
References cbrc::FLEArray< T >::assign().
operator=() [4/4]
template<typename T > FLEArray cbrc::FLEArray< T >::operator= (const std::vector< T > & v) inline
Definition at line 138 of file FLEArray.hh.
References cbrc::FLEArray< T >::assign().
operator==() [1/2]
template<typename T > bool cbrc::FLEArray< T >::operator== (const FLEArray< T > & fla) const inline
Definition at line 163 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
operator==() [2/2]
template<typename T > bool cbrc::FLEArray< T >::operator== (const FLEArray< T > & fla) const inline
Definition at line 163 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
operator[]() [1/2]
template<typename T > virtual T & cbrc::FLEArray< T >::operator[] (const size_t & index) const inline virtual
Reimplemented in cbrc::FLEArrayFast< T >, cbrc::FLENumArrayFast< T >, cbrc::FLEArrayFast< T >, and cbrc::FLENumArrayFast< T >.
Definition at line 179 of file FLEArray.hh.
References cbrc::FLEArray< T >::_validIndex(), cbrc::FLEArray< T >::a, and cbrc::FLEArray< T >::FLEArray().
operator[]() [2/2]
template<typename T > virtual T & cbrc::FLEArray< T >::operator[] (const size_t & index) const inline virtual
Reimplemented in cbrc::FLEArrayFast< T >, cbrc::FLENumArrayFast< T >, cbrc::FLEArrayFast< T >, and cbrc::FLENumArrayFast< T >.
Definition at line 179 of file FLEArray.hh.
References cbrc::FLEArray< T >::_validIndex(), cbrc::FLEArray< T >::a, and cbrc::FLEArray< T >::FLEArray().
print() [1/2]
template<typename T > void cbrc::FLEArray< T >::print (std::ostream & os = std::cout, const std::string & delimiter = "\t") const virtual
Definition at line 547 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
Referenced by cbrc::runRecountExpectationMatchingTagCorrector(), and cbrc::sprotToFasta().
print() [2/2]
template<typename T > virtual void cbrc::FLEArray< T >::print (std::ostream & os = std::cout, const std::string & delimiter = "\t") const virtual
printNumbered() [1/2]
template<typename T > void cbrc::FLEArray< T >::printNumbered (std::ostream & os = std::cout, const size_t startLabel = 0) const virtual
Definition at line 558 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
printNumbered() [2/2]
template<typename T > virtual void cbrc::FLEArray< T >::printNumbered (std::ostream & os = std::cout, const size_t startLabel = 0) const virtual
read() [1/2]
template<typename T > void cbrc::FLEArray< T >::read (std::istream & is)
Definition at line 780 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::read(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::size().
Referenced by cbrc::FLEArray< T >::FLEArray(), cbrc::FLESorted< T >::FLESorted(), cbrc::FLSortedFunctions::read(), cbrc::vectorMatrix::read(), cbrc::FLEArray< T >::read(), cbrc::FLESorted< T >::read(), cbrc::MallocArray< T >::read(), cbrc::ResidueIndexedSequence::read(), cbrc::RecountNeighborList::read(), cbrc::Sigma4FLArray::read(), cbrc::binaryIO::read(), cbrc::binaryIO::read(), cbrc::binaryIO::read(), cbrc::FLEArray< T >::skip(), cbrc::binaryIO::traceOrDie(), cbrc::TrivialHistogram< T >::TrivialHistogram(), and cbrc::TrivialUnsignedHistogram< T >::TrivialUnsignedHistogram().
read() [2/2]
template<typename T > void cbrc::FLEArray< T >::read (std::istream & is)
replace() [1/4]
template<typename T > void cbrc::FLEArray< T >::replace (const size_t & begIdx, const FLEArray< T > & replacementArray)
Definition at line 667 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
Referenced by cbrc::perlish::_split_surroundingSquareBracketsFoundAndRemoved(), and cbrc::stringUtils::stringReplaceAll().
replace() [2/4]
template<typename T > void cbrc::FLEArray< T >::replace (const size_t & begIdx, const FLEArray< T > & replacementArray)
replace() [3/4]
template<typename T > void cbrc::FLEArray< T >::replace (const size_t & begIdx, const size_t & endIdx, const T *const & cArray)
Definition at line 678 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().
replace() [4/4]
template<typename T > void cbrc::FLEArray< T >::replace (const size_t & begIdx, const size_t & endIdx, const T *const & cArray)
resize() [1/2]
template<typename T > void cbrc::FLEArray< T >::resize (const size_t & sz)
Definition at line 585 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::setSize().
Referenced by cbrc::FLEArray< T >::assign(), cbrc::FLEArray< T >::assign(), cbrc::FLESorted< T >::assign(), cbrc::FLSorted< T >::assign(), cbrc::perlish::chomp(), cbrc::perlish::chop(), cbrc::FLESorted< T >::FLESorted(), cbrc::FLSorted< T >::FLSorted(), cbrc::DNAArrayBit16< len >::getIndices(), cbrc::DNAArrayBit8< len >::getIndices(), cbrc::Matrix< T >::operator=(), cbrc::FLESorted< T >::operator=(), cbrc::FLSorted< T >::operator=(), cbrc::vectorMatrix::read(), cbrc::FLEArray< T >::setFromLiteral(), cbrc::perlish::splitOnOneMatch(), testMatrix(), cbrc::ResidueIndexMap::toResidues(), cbrc::ResidueIndexMap::toResidues(), cbrc::ResidueIndexMap::toResidues(), cbrc::binaryIO::traceOrDie(), cbrc::sigma4bitPackingUtils::unpack(), cbrc::ResidueIndexMap::vectorToResidues(), and cbrc::RecountNeighborProbGraphWriter::write().
resize() [2/2]
template<typename T > void cbrc::FLEArray< T >::resize (const size_t & sz)
rfind() [1/4]
template<typename T > size_t cbrc::FLEArray< T >::rfind (const T & val, const size_t & begIdx, const size_t & endIdx)
Definition at line 709 of file FLEArray.hh.
References cbrc::FLEArray< T >::_validRange(), cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::npos.
Referenced by cbrc::FLEArray< T >::rfind().
rfind() [2/4]
template<typename T > size_t cbrc::FLEArray< T >::rfind (const T & val, const size_t & begIdx, const size_t & endIdx)
rfind() [3/4]
template<typename T > size_t cbrc::FLEArray< T >::rfind (const T & val, const size_t begIdx = 0) inline
Definition at line 266 of file FLEArray.hh.
References cbrc::FLEArray< T >::rfind(), and cbrc::FLEArray< T >::size().
rfind() [4/4]
template<typename T > size_t cbrc::FLEArray< T >::rfind (const T & val, const size_t begIdx = 0) inline
Definition at line 266 of file FLEArray.hh.
References cbrc::FLEArray< T >::rfind(), and cbrc::FLEArray< T >::size().
setFromLiteral() [1/2]
template<typename T > void cbrc::FLEArray< T >::setFromLiteral (const std::string semanticTypeDescriptor, const std::string arrayLiteral) inline
Definition at line 508 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), GDB_DIEF, cbrc::FLEArray< T >::resize(), cbrc::FLEArray< T >::size(), and cbrc::perlish::split().
Referenced by cbrc::FLEArray< T >::FLEArray().
setFromLiteral() [2/2]
template<typename T > void cbrc::FLEArray< T >::setFromLiteral (const std::string semanticTypeDescriptor, const std::string arrayLiteral)
setSize() [1/2]
template<typename T > void cbrc::FLEArray< T >::setSize (const size_t & sz) inline
Definition at line 126 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::size().
Referenced by cbrc::ResidueIndexMap::assignResidueIndices(), cbrc::ConnectedComponentOnlineComputer::ConnectedComponentOnlineComputer(), cbrc::FLEArrayFunctions::cumulativeSum(), cbrc::LogChoose::LogChoose(), cbrc::LabeledSquareFLENumMatrix< elemT >::reorderLabels(), cbrc::ResidueIndexMapTransformer::ResidueIndexMapTransformer(), cbrc::ResidueIndexMapTranslator::ResidueIndexMapTranslator(), cbrc::FLEArray< T >::resize(), cbrc::RecountTagCounts::setSize(), cbrc::TopKSorted< T, BinaryPredicate >::TopKSorted(), and cbrc::TopKSorted< T, BinaryPredicate >::TopKSorted().
setSize() [2/2]
template<typename T > void cbrc::FLEArray< T >::setSize (const size_t & sz) inline
Definition at line 126 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::size().
size() [1/2]
template<typename T > const size_t & cbrc::FLEArray< T >::size () const inline
Definition at line 189 of file FLEArray.hh.
References cbrc::FLEArray< T >::s.
Referenced by cbrc::FLEArray< T >::_assertNonzeroSize(), cbrc::FLEArray< T >::_assertSizeEqual(), cbrc::perlish::_split_surroundingSquareBracketsFoundAndRemoved(), cbrc::perlish::_split_trailingPlusCharFoundAndRemoved(), cbrc::adjacentCloseHamming(), cbrc::GlobalAffineDist::alignment(), cbrc::GlobalAffineIdentityAligner::alignment(), cbrc::SeqGlobalAffineAligner::alignment(), cbrc::allPairsHammingNeighbors(), cbrc::allPairsNearestGlobalAffineScore(), cbrc::htmlStrings::anchorHrefBasic(), cbrc::RecountTagCounts::assignDifference(), cbrc::RecountTagCounts::assignSum(), cbrc::smoothing::averageYCoordinateOfPointIWithNeighborPointUntilMinSampleSizeAttained(), cbrc::smoothing::averageYCoordinatesWithNeighboringPointsUntilMinSampleSizeAttained(), cbrc::BlastEValuesByClass::bestEValuePerClass(), cbrc::SimilaritySearchableSequences::bestMatch(), cbrc::GlobalAffineDist::bestPossibleDist(), cbrc::GlobalAffineDist::bestPossibleSuffixDist(), cbrc::SeqGlobalAffineAligner::bestPossibleSuffixScore(), cbrc::GlobalAffineIdentityAligner::bestPossibleSuffixScore(), cbrc::GlobalAffineIdentityAligner::bestPossibleSuffixScore(), cbrc::SeqGlobalAffineAligner::bestPossibleSuffixScore(), cbrc::Blast8ResultReader::Blast8ResultReader(), cbrc::FLEArray< T >::bsize(), cbrc::calculatePermutationSumOfSquaredDifferencesDistribution(), cbrc::ResidueIndexMap::canonicalizeCase(), cbrc::clusterByIdentity(), cbrc::computeAllPairsIdentity(), cbrc::HammingDistanceComputer::computeBoundedGapAtBeg(), cbrc::HammingDistanceComputer::computeBoundedGapAtEnd(), cbrc::KnapsackEnumerator::computeCombinations(), cbrc::convertMultipleEdgePerLineToOneEdgePerLineFormat(), cbrc::FLEArrayFunctions::cumulativeSum(), cbrc::ArgvParser::die(), cbrc::ArgvParser::dieIfUnusedArgs(), cbrc::FLEArrayFunctions::diff(), cbrc::GlobalAffineDist::dist(), cbrc::GlobalAffineDist::distBounded(), cbrc::GlobalAffineDist::distFreeStartGap(), cbrc::FLEArrayFunctions::doubleFLENumArrayFromStrings(), cbrc::dumpAminoAcidContentWPformat(), cbrc::dumpBlastNNUtility(), cbrc::fastaHeadBytes(), cbrc::fastaPrintDuplicateSequences(), cbrc::fastaTailBytes(), cbrc::GlobalAffineDist::feasibleBound(), cbrc::GlobalAffineIdentityAligner::feasibleBound(), cbrc::SeqGlobalAffineAligner::feasibleBound(), cbrc::FLEArray< T >::fill(), cbrc::filterBlast8ResultEValueThreshold(), cbrc::filterSameClassHighBlast(), cbrc::FLENumArray< T >::finalMaxIndex(), cbrc::FLENumArray< T >::finalMinIndex(), cbrc::FLEArray< T >::find(), cbrc::FLENumArray< T >::firstMaxIndex(), cbrc::FLENumArray< T >::firstMinIndex(), cbrc::FLArray< T >::FLArray(), cbrc::FLArray< T >::FLArray(), cbrc::FLArraySortedPermutation(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArraySortedPermutation(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::FLSorted2TypePairSet< T0, T1 >::FLSorted2TypePairSet(), cbrc::ArgvParser::getArgOrDie(), cbrc::ArgvParser::getDoc(), cbrc::ConnectedComponentOnlineComputer::getNodeComponents(), cbrc::SerialNumbersForStrings< serialNumT >::getSerialNumber(), cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::getSerialNumber(), cbrc::GlobalAffineDist::GlobalAffineDist(), cbrc::GlobalAffineIdentityAligner::GlobalAffineIdentityAligner(), cbrc::hasHighIdentityToDataset(), cbrc::SimilaritySearchableSequences::identicalMatches(), cbrc::GlobalAffineIdentityAligner::identity(), cbrc::FLEArray< T >::indexInRange(), cbrc::FastaInputOptions::isComment(), cbrc::vectorMatrix::isRectangular(), cbrc::perlish::join(), cbrc::LabeledAsciiSeq::LabeledAsciiSeq(), cbrc::labeledBlastToOddsRatio(), cbrc::LabeledSequence::LabeledSequence(), cbrc::LabeledSequence::LabeledSequence(), cbrc::LabeledSequence::LabeledSequence(), cbrc::LabeledSquareFLENumMatrix< elemT >::LabeledSquareFLENumMatrix(), cbrc::LabeledSequence::length(), cbrc::GlobalAffineDist::lengthBasedUpperBound(), cbrc::GlobalAffineIdentityAligner::lengthDifferenceBasedScoreUpperBound(), cbrc::SeqGlobalAffineAligner::lengthDifferenceBasedScoreUpperBound(), cbrc::listConnectedComponents(), cbrc::perlish::looksLikeUnsignedInts(), cbrc::KnapsackObjectVector::makeFromWeightVector(), cbrc::MallocArray< T >::MallocArray(), cbrc::RecountTagCounts::maxAbsDiff(), cbrc::ResidueIndexMap::maxIndex(), cbrc::RecountComputerForGraphOnDisk::meanCountsFromTrue(), cbrc::RecountComputerForGraphOnDisk::meanCountsFromTrue(), cbrc::smoothing::mergeIdenticalAdjacentX(), cbrc::smoothing::mergeIdenticalAdjacentX(), cbrc::smoothing::monotonicSmoothY(), cbrc::TransfacReader::nextNonBlankLine(), cbrc::FastaRecordReader::nextRecordOrDie(), cbrc::FLEArrayFunctions::normalizeSum(), cbrc::LabeledSequence::notLonger(), cbrc::OneEdgePerLineFormat::numNodesInStream(), cbrc::observedMeanStdev_fromTrueCounts(), cbrc::GlobalAffineDist::oneSequenceBasedUpperBound(), cbrc::FLEArray< alignScoreT >::operator std::vector< alignScoreT >(), cbrc::FLEArray< T >::operator!=(), cbrc::Sigma4FLArray::operator!=(), cbrc::ResiduesIndexMap::operator()(), cbrc::ResiduesIndexMap::operator()(), cbrc::ResiduesIndexMap::operator()(), cbrc::SerialNumbersForStrings< serialNumT >::operator()(), cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::operator()(), cbrc::FLENumArray< T >::operator*=(), cbrc::BitArray::trueIterator::operator++(), cbrc::FLENumArray< T >::operator+=(), cbrc::MallocNumArray< T >::operator+=(), cbrc::FLENumArray< T >::operator-=(), cbrc::FLENumArray< T >::operator/=(), cbrc::Sigma4FLArray::operator<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::operator<<(), cbrc::FLEArray< T >::operator=(), cbrc::FLEMatrix< T >::operator=(), cbrc::FLMatrix< T >::operator=(), cbrc::LabeledAsciiSeq::operator=(), cbrc::MallocArray< T >::operator=(), cbrc::MallocNumArray< T >::operator=(), cbrc::Sigma4FLArray::operator=(), cbrc::FLEMatrix< T >::operator=(), cbrc::FLMatrix< T >::operator=(), cbrc::FLArray< T >::operator==(), cbrc::FLEArray< T >::operator==(), cbrc::MallocArray< T >::operator==(), cbrc::SerialNumbersForStrings< serialNumT >::operator==(), cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::operator==(), cbrc::Sigma4FLArray::operator==(), cbrc::Alignment::outputHtml(), cbrc::Alignment::outputHtmlMarkSame(), cbrc::sigma4bitPackingUtils::pack(), cbrc::BoundedLenFifoVector< T >::popOldest(), cbrc::GlobalAffineDist::prefixDistBounded(), cbrc::SeqGlobalAffineAligner::prefixScoreBounded(), cbrc::LabeledSequencePairPredicate_logicalOr::print(), cbrc::FastaWriter::print(), cbrc::FLEArray< T >::print(), cbrc::MatrixGraph::printAdjacencyLists(), cbrc::printCloseNeighbors(), cbrc::PermutationGenerator::printMask(), cbrc::TrivialHistogram< T >::printNonzeroEntries(), cbrc::TrivialUnsignedHistogram< T >::printNonzeroEntries(), cbrc::FLEArray< T >::printNumbered(), cbrc::ArgvParser::printOptionDoc(), cbrc::printRandomRepresentativeFromEachConnectedComponent(), cbrc::ResidueIndexMap::properResidue(), cbrc::ResidueIndexMap::properResidues(), cbrc::GlobalAffineIdentityAligner::purelyLengthDifferenceBasedScoreUpperBound(), cbrc::SeqGlobalAffineAligner::purelyLengthDifferenceBasedScoreUpperBound(), cbrc::BoundedLenFifoVector< T >::push(), cbrc::FLArrayFunctions::randomElement(), cbrc::FLEArrayFunctions::randomElement(), cbrc::vectorMatrix::read(), cbrc::FLEArray< T >::read(), cbrc::MatrixGraph::readContinuousIntegerNodesFormat(), cbrc::MatrixGraph::readEdgesOneEdgePerLineFormat(), cbrc::FLSorted2TypePairSet< T0, T1 >::readFromTextFile(), cbrc::TagSet::readFromTextStream(), cbrc::NeighborListGraph::readOneEdgePerLineFormat(), cbrc::KnapsackObjectVector::readText_idsFrom0(), cbrc::RecursivePermutationGenerator::RecursivePermutationGenerator(), cbrc::SerialNumbersForStrings< serialNumT >::registerNewSerialNumbers(), cbrc::perlish::removeCharFromString(), cbrc::perlish::removeLeadingWhiteSpace(), cbrc::ConstantLabeledSquareDoubleFLENumMatrix::renumLabels(), cbrc::LabeledSquareFLENumMatrix< elemT >::reorderLabels(), cbrc::FLEArray< T >::replace(), cbrc::FLEArray< T >::replace(), cbrc::ResidueIndexMapTransformer::ResidueIndexMapTransformer(), cbrc::ResidueIndexMapTranslator::ResidueIndexMapTranslator(), cbrc::FLEArray< T >::rfind(), cbrc::runAddAlignmentToHtml(), cbrc::runAddIdenticalToHtml(), cbrc::runAllShortestEdgeLengthPaths(), cbrc::runGlobalAffineSearcher(), cbrc::runSimilaritySearchableSequences(), cbrc::GlobalAffineIdentityAligner::score(), cbrc::SeqGlobalAffineAligner::score(), cbrc::SeqGlobalAffineAligner::scoreBounded(), cbrc::GlobalAffineIdentityAligner::scoreBounded(), cbrc::GlobalAffineIdentityAligner::scoreFreeStartGap(), cbrc::SeqGlobalAffineAligner::scoreFreeStartGap(), cbrc::SeqGlobalAffineAligner::scoreSuffixBounded(), cbrc::SeqGlobalAffineAligner::SeqGlobalAffineAligner(), cbrc::SerialNumbersForStrings< serialNumT >::SerialNumbersForStrings(), cbrc::SerialNumbersForStrings< serialNumT >::SerialNumbersForStrings(), cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::SerialNumbersForStrings_accessCounting(), cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::SerialNumbersForStrings_accessCounting(), cbrc::ArgvParser::set(), cbrc::TransfacBindingFactor::set(), cbrc::RecountNeighborList::set(), cbrc::DNAArrayBit16< len >::set(), cbrc::ArgvParser::set(), cbrc::ArgvParser::setCautiously(), cbrc::ArgvParser::setCautiouslyOrDie(), cbrc::FLEArray< T >::setFromLiteral(), cbrc::ArgvParser::setFromNextUnused(), cbrc::Blast8Result::setFromStream(), cbrc::ConstantLabeledSquareDoubleFLENumMatrix::setFromStream(), cbrc::FLEArrayFunctions::setNumCombinationsVector(), cbrc::ArgvParser::setOrDie(), cbrc::FLEArray< T >::setSize(), cbrc::FLMatrix< T >::shiftLeft(), cbrc::FLEMatrix< T >::shiftLeft(), cbrc::FLMatrix< T >::shiftRight(), cbrc::FLEMatrix< T >::shiftRight(), cbrc::NeighborListGraph::shortestPathByEdgeLength(), cbrc::ResidueIndexMap::sigma(), cbrc::Sigma4FLArray::Sigma4FLArray(), cbrc::SeqGlobalAffineAligner::singleSeqBasedScoreUpperBound(), cbrc::GlobalAffineIdentityAligner::singleSeqBasedScoreUpperBound(), cbrc::RecountTagCounts::size(), cbrc::FLESorted< T >::size(), cbrc::FLSorted< T >::size(), cbrc::TrivialHistogram< T >::size(), cbrc::TrivialUnsignedHistogram< T >::size(), cbrc::PermutationGenerator::size(), cbrc::DiscreteCumulativeProbabilityDistribution::size(), cbrc::SimilaritySearchableSequences::size(), cbrc::LabeledAsciiSeq::size(), cbrc::LabeledSequence::size(), cbrc::ResidueIndexedSequence::size(), cbrc::StringSpecEnum::size(), cbrc::KnapsackObjectVector::size(), cbrc::smoothMinPoints(), cbrc::smoothMinPoints(), cbrc::sortFastaByLength(), cbrc::perlish::spaceTabString(), cbrc::perlish::split(), cbrc::perlish::splitByLength(), cbrc::ResidueIndexMap::splitIntoProperOnlySubstrings(), cbrc::perlish::splitOnOneMatch(), cbrc::perlish::splitOnOneOrMoreCharsInCharSet(), cbrc::perlish::splitOnOneOrMoreCharsInCharSet(), cbrc::FLENumArray< T >::squareElements(), cbrc::stringUtils::stringReplaceAll(), cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::strings(), cbrc::StringSpecEnum::StringSpecEnum(), cbrc::FLENumArray< T >::sum(), cbrc::sumSquaredDifferences(), cbrc::htmlStrings::tagString(), cbrc::testConnectedComponentOnlineComputer(), cbrc::testFLArray(), cbrc::testFLArrayByIndexSortingPredicate(), cbrc::testMapSpeed(), cbrc::testSeqGlobalAffineAligner(), cbrc::testStringKeyHashtableSpeed(), cbrc::perlish::toInt(), cbrc::ResidueIndexMap::toResidueIndex(), cbrc::ResidueIndexMap::toResidues(), cbrc::perlish::toSeconds(), cbrc::perlish::toUnsignedInt(), cbrc::perlish::toUnsignedInts(), cbrc::binaryIO::traceOrDie(), cbrc::FLEMatrix< T >::validAsMatrix(), cbrc::FLMatrix< T >::validAsMatrix(), cbrc::ResidueIndexMap::validResidue(), cbrc::ResidueIndexMap::validResidues(), cbrc::RecountComputerForGraphOnDisk::varianceCountsFromTrue(), cbrc::RecountComputerForGraphOnDisk::varianceCountsFromTrue(), cbrc::vectorSum(), cbrc::ResidueIndexMap::vectorToResidues(), cbrc::SimilaritySearchableSequences::withinHammingDistance(), cbrc::FLSortedFunctions::write(), cbrc::stringBinaryIO::write(), cbrc::vectorMatrix::write(), cbrc::binaryIO::write(), cbrc::RecountNeighborProbGraphWriter::write(), and cbrc::RecountNeighborList::write().
size() [2/2]
template<typename T > const size_t & cbrc::FLEArray< T >::size () const inline
Definition at line 189 of file FLEArray.hh.
References cbrc::FLEArray< T >::s.
skip() [1/2]
template<typename T > static void cbrc::FLEArray< T >::skip (std::istream & is) inline static
Definition at line 233 of file FLEArray.hh.
References cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::read().
skip() [2/2]
template<typename T > static void cbrc::FLEArray< T >::skip (std::istream & is) inline static
Definition at line 233 of file FLEArray.hh.
References cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::read().
write() [1/2]
template<typename T > void cbrc::FLEArray< T >::write (std::ostream & os) const inline
Definition at line 239 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::write().
Referenced by cbrc::FLSortedFunctions::write(), cbrc::binaryIO::write(), cbrc::stringBinaryIO::write(), cbrc::stringBinaryIO::write(), cbrc::vectorMatrix::write(), cbrc::binaryIO::write(), cbrc::RecountNeighborProbGraphWriter::write(), cbrc::MallocArray< T >::write(), cbrc::TrivialHistogram< T >::write(), cbrc::TrivialUnsignedHistogram< T >::write(), cbrc::FLEArray< T >::write(), cbrc::FLESorted< T >::write(), cbrc::ResidueIndexedSequence::write(), cbrc::ResidueIndexMap::write(), cbrc::RecountNeighborList::write(), cbrc::Sigma4FLArray::write(), cbrc::BitMatrix::writeAsPbm(), cbrc::binaryIO::writeContentsOnly(), cbrc::stringBinaryIO::writeContentsOnly(), and cbrc::writeRecountNeighborProbGraph().
write() [2/2]
template<typename T > void cbrc::FLEArray< T >::write (std::ostream & os) const inline
Definition at line 239 of file FLEArray.hh.
References cbrc::FLEArray< T >::a, cbrc::FLEArray< T >::bsize(), cbrc::FLEArray< T >::s, and cbrc::FLEArray< T >::write().
zero() [1/2]
template<typename T > void cbrc::FLEArray< T >::zero () inline
Definition at line 212 of file FLEArray.hh.
References cbrc::FLEArray< T >::fill().
Referenced by cbrc::calculatePermutationSumOfSquaredDifferencesDistribution(), cbrc::RecountTagCounts::RecountTagCounts(), cbrc::RecountTagCounts::RecountTagCounts(), cbrc::runAllShortestEdgeLengthPaths(), cbrc::NeighborListGraph::shortestPathByEdgeLength(), testFLDiagonalMatrix(), cbrc::RecountComputerForGraphOnDisk::varianceCountsFromTrue(), cbrc::RecountComputerForGraphOnDisk::varianceCountsFromTrue(), and cbrc::RecountTagCounts::zero().
zero() [2/2]
template<typename T > void cbrc::FLEArray< T >::zero () inline
Definition at line 212 of file FLEArray.hh.
References cbrc::FLEArray< T >::fill().
Member Data Documentation
a
template<typename T > T * cbrc::FLEArray< T >::a protected
Definition at line 290 of file FLEArray.hh.
Referenced by cbrc::FLEArray< T >::assign(), cbrc::FLEArray< T >::assign(), cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::constBegin(), cbrc::FLEArray< T >::constEnd(), cbrc::FLEArray< T >::end(), cbrc::FLEArray< T >::fill(), cbrc::FLEArray< T >::fillWithByte(), cbrc::FLENumArray< T >::finalMaxIndex(), cbrc::FLENumArray< T >::finalMinIndex(), cbrc::FLEArray< T >::find(), cbrc::FLENumArray< T >::firstMaxIndex(), cbrc::FLENumArray< T >::firstMinIndex(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::DNAArrayBit16< len >::const_iterator::operator!=(), cbrc::FLEArray< T >::operator!=(), cbrc::Sigma4FLArray::operator!=(), cbrc::FLEArray< T >::operator()(), cbrc::FLENumArray< T >::operator*=(), cbrc::BitArray::trueIterator::operator++(), cbrc::FLENumArray< T >::operator+=(), cbrc::FLENumArray< T >::operator-=(), cbrc::FLENumArray< T >::operator/=(), cbrc::Sigma4FLArray::operator<(), cbrc::FLEArray< T >::operator=(), cbrc::MallocArray< T >::operator=(), cbrc::MallocNumArray< T >::operator=(), cbrc::Sigma4FLArray::operator=(), cbrc::FLArray< T >::operator==(), cbrc::FLEArray< T >::operator==(), cbrc::MallocArray< T >::operator==(), cbrc::Sigma4FLArray::operator==(), cbrc::FLEArray< T >::operator[](), cbrc::FLEArrayFast< T >::operator[](), cbrc::FLENumArrayFast< T >::operator[](), cbrc::FLEArray< T >::print(), cbrc::FLEArray< T >::printNumbered(), cbrc::FLEArray< T >::read(), cbrc::FLEArray< T >::replace(), cbrc::FLEArray< T >::replace(), cbrc::FLEArray< T >::resize(), cbrc::FLEArray< T >::rfind(), cbrc::FLEArray< T >::setFromLiteral(), cbrc::FLEArray< T >::setSize(), cbrc::Sigma4FLArray::Sigma4FLArray(), cbrc::FLENumArray< T >::squareElements(), cbrc::FLENumArray< T >::sum(), cbrc::FLEArray< T >::write(), and cbrc::FLEArray< T >::~FLEArray().
npos
template<typename T > static const size_t cbrc::FLEArray< T >::npos = static_cast<size_t>(-1) static
Definition at line 57 of file FLEArray.hh.
Referenced by cbrc::FLEArray< T >::find(), and cbrc::FLEArray< T >::rfind().
s
template<typename T > size_t cbrc::FLEArray< T >::s protected
Definition at line 289 of file FLEArray.hh.
Referenced by cbrc::FLEArray< T >::_validIndex(), cbrc::FLEArray< T >::constEnd(), cbrc::FLEArray< T >::empty(), cbrc::FLEArray< T >::end(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEMatrix< T >::FLEMatrix(), cbrc::FLMatrix< T >::FLMatrix(), cbrc::SerialNumbersForStrings< serialNumT >::getSerialNumber(), cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::getSerialNumber(), cbrc::SerialNumbersForStrings< serialNumT >::operator()(), cbrc::SerialNumbersForStrings_accessCounting< serialNumT >::operator()(), cbrc::FLEArray< T >::operator=(), cbrc::FLEMatrix< T >::operator=(), cbrc::FLMatrix< T >::operator=(), cbrc::FLEMatrix< T >::operator==(), cbrc::FLMatrix< T >::operator==(), cbrc::FLEArray< T >::read(), cbrc::FLEArray< T >::resize(), cbrc::FLEArray< T >::setSize(), cbrc::FLEArray< T >::size(), and cbrc::FLEArray< T >::write().
The documentation for this class was generated from the following files:
ematch_src/utils/FLArray/FLEArray.hh
knapsack_src/utils/FLArray/FLEArray.hh