NGSFeatures: cbrc::ConnectedComponentOnlineComputer Class Reference
cbrc::ConnectedComponentOnlineComputer Class Reference
#include <ConnectedComponentOnlineComputer.hh>
Public Member Functions
ConnectedComponentOnlineComputer (nodeIndexT numNodes)
void addNode (nodeIndexT n0)
void addEdge (nodeIndexT n0, nodeIndexT n1)
void addGraph (const Graph &g)
nodeIndexT getComponent (const nodeIndexT &n)
nodeIndexT getNodeComponents (FLEArray< nodeIndexT > &nodeComponents)
ConnectedComponentOnlineComputer (nodeIndexT numNodes)
void addNode (nodeIndexT n0)
void addEdge (nodeIndexT n0, nodeIndexT n1)
void addGraph (const Graph &g)
nodeIndexT getComponent (const nodeIndexT &n)
nodeIndexT getNodeComponents (FLEArray< nodeIndexT > &nodeComponents)
Detailed Description
Definition at line 37 of file ConnectedComponentOnlineComputer.hh.
Constructor & Destructor Documentation
ConnectedComponentOnlineComputer() [1/2]
cbrc::ConnectedComponentOnlineComputer::ConnectedComponentOnlineComputer (nodeIndexT numNodes) inline
Definition at line 39 of file ConnectedComponentOnlineComputer.hh.
References cbrc::FLEArray< T >::fill(), and cbrc::FLEArray< T >::setSize().
ConnectedComponentOnlineComputer() [2/2]
cbrc::ConnectedComponentOnlineComputer::ConnectedComponentOnlineComputer (nodeIndexT numNodes) inline
Definition at line 39 of file ConnectedComponentOnlineComputer.hh.
References cbrc::FLEArray< T >::fill(), and cbrc::FLEArray< T >::setSize().
Member Function Documentation
addEdge() [1/2]
void cbrc::ConnectedComponentOnlineComputer::addEdge (nodeIndexT n0, nodeIndexT n1)
Definition at line 35 of file ConnectedComponentOnlineComputer.cc.
Referenced by addGraph().
addEdge() [2/2]
void cbrc::ConnectedComponentOnlineComputer::addEdge (nodeIndexT n0, nodeIndexT n1)
addGraph() [1/2]
void cbrc::ConnectedComponentOnlineComputer::addGraph (const Graph & g)
Definition at line 128 of file ConnectedComponentOnlineComputer.cc.
References addEdge().
addGraph() [2/2]
void cbrc::ConnectedComponentOnlineComputer::addGraph (const Graph & g)
addNode() [1/2]
void cbrc::ConnectedComponentOnlineComputer::addNode (nodeIndexT n0) inline
Definition at line 46 of file ConnectedComponentOnlineComputer.hh.
addNode() [2/2]
void cbrc::ConnectedComponentOnlineComputer::addNode (nodeIndexT n0) inline
Definition at line 46 of file ConnectedComponentOnlineComputer.hh.
getComponent() [1/2]
nodeIndexT cbrc::ConnectedComponentOnlineComputer::getComponent (const nodeIndexT & n) inline
Definition at line 57 of file ConnectedComponentOnlineComputer.hh.
getComponent() [2/2]
nodeIndexT cbrc::ConnectedComponentOnlineComputer::getComponent (const nodeIndexT & n) inline
Definition at line 57 of file ConnectedComponentOnlineComputer.hh.
getNodeComponents() [1/2]
unsigned int cbrc::ConnectedComponentOnlineComputer::getNodeComponents (FLEArray< nodeIndexT > & nodeComponents)
Definition at line 58 of file ConnectedComponentOnlineComputer.cc.
References cbrc::FLEArray< T >::size().
getNodeComponents() [2/2]
nodeIndexT cbrc::ConnectedComponentOnlineComputer::getNodeComponents (FLEArray< nodeIndexT > & nodeComponents)
The documentation for this class was generated from the following files:
ematch_src/graph/ConnectedComponentOnlineComputer.hh
ematch_src/utils/graph/ConnectedComponentOnlineComputer.hh
ematch_src/graph/ConnectedComponentOnlineComputer.cc
ematch_src/utils/graph/ConnectedComponentOnlineComputer.cc