NGSFeatures: cbrc::DNAArrayBit16< len > Class Template Reference
cbrc::DNAArrayBit16< len > Class Template Reference
#include <DNAArrayBit16.hh>
Classes
class const_iterator
Public Member Functions
DNAArrayBit16 ()
DNAArrayBit16 (const DNAArrayBit16_bases8 bases) throw (std::length_error, std::invalid_argument)
DNAArrayBit16 (ResidueIndexMap::arrayT residueIndices) throw (std::length_error)
DNAArrayBit16_bases8 getMaxBases () const
DNAArrayBit16_bases8 getBases () const
void setBases (DNAArrayBit16_bases8 bs) throw (std::invalid_argument)
operator size_t () const
bool operator== (const char *const s) const
void operator++ () throw (std::invalid_argument)
DNAArrayBit16_bases8 operator() (const size_t index) const throw (std::out_of_range)
void set (ResidueIndexMap::arrayT residueIndices) throw (std::length_error)
void set (const size_t index, const byte base) throw (std::out_of_range, std::invalid_argument)
DNAArrayBit16< len > substitute (const size_t index, const byte base) const throw (std::out_of_range, std::invalid_argument)
std::string getResidues () const
std::string getIndices () const
size_t length () const
void friend testDNAArrayBit16 ()
Static Public Member Functions
static std::string toResidues (DNAArrayBit16_bases8 bases)
Friends
class DNAArrayBit16Hamming
Detailed Description
template<size_t len>
class cbrc::DNAArrayBit16< len >
Definition at line 54 of file DNAArrayBit16.hh.
Constructor & Destructor Documentation
DNAArrayBit16() [1/3]
template<size_t len> cbrc::DNAArrayBit16< len >::DNAArrayBit16 () inline
Definition at line 56 of file DNAArrayBit16.hh.
References cbrc::DNAArrayBit16< len >::DNAArrayBit16().
Referenced by cbrc::DNAArrayBit16< len >::DNAArrayBit16().
DNAArrayBit16() [2/3]
template<size_t len> cbrc::DNAArrayBit16< len >::DNAArrayBit16 (const DNAArrayBit16_bases8 bases) throw (std::length_error, std::invalid_argument) inline
Definition at line 57 of file DNAArrayBit16.hh.
DNAArrayBit16() [3/3]
template<size_t len> cbrc::DNAArrayBit16< len >::DNAArrayBit16 (ResidueIndexMap::arrayT residueIndices) throw (std::length_error) inline
Definition at line 61 of file DNAArrayBit16.hh.
References cbrc::DNAArrayBit16< len >::set().
Member Function Documentation
getBases()
template<size_t len> DNAArrayBit16_bases8 cbrc::DNAArrayBit16< len >::getBases () const inline
Definition at line 68 of file DNAArrayBit16.hh.
getIndices()
template<size_t len> std::string cbrc::DNAArrayBit16< len >::getIndices () const inline
Definition at line 162 of file DNAArrayBit16.hh.
References cbrc::FLEArray< T >::resize().
Referenced by cbrc::DNAArrayBit16< len >::getResidues().
getMaxBases()
template<size_t len> DNAArrayBit16_bases8 cbrc::DNAArrayBit16< len >::getMaxBases () const inline
Definition at line 67 of file DNAArrayBit16.hh.
References cbrc::DNAArrayBit16_maxBases.
getResidues()
template<size_t len> std::string cbrc::DNAArrayBit16< len >::getResidues () const inline
Definition at line 161 of file DNAArrayBit16.hh.
References cbrc::DNAProperResidueIndexMap, and cbrc::DNAArrayBit16< len >::getIndices().
length()
template<size_t len> size_t cbrc::DNAArrayBit16< len >::length () const inline
Definition at line 168 of file DNAArrayBit16.hh.
Referenced by cbrc::DNAArrayBit16< len >::set().
operator size_t()
template<size_t len> cbrc::DNAArrayBit16< len >::operator size_t () const inline
Definition at line 96 of file DNAArrayBit16.hh.
operator()()
template<size_t len> DNAArrayBit16_bases8 cbrc::DNAArrayBit16< len >::operator() (const size_t index) const throw (std::out_of_range) inline
Definition at line 120 of file DNAArrayBit16.hh.
References cbrc::DNAArrayBit16_setMask.
operator++()
template<size_t len> void cbrc::DNAArrayBit16< len >::operator++ () throw (std::invalid_argument) inline
Definition at line 107 of file DNAArrayBit16.hh.
References cbrc::DNAArrayBit16_maxResidueIndex, and cbrc::DNAArrayBit16_numPossible.
operator==()
template<size_t len> bool cbrc::DNAArrayBit16< len >::operator== (const char *const s) const inline
Definition at line 99 of file DNAArrayBit16.hh.
References cbrc::DNAProperResidueIndexMap.
set() [1/2]
template<size_t len> void cbrc::DNAArrayBit16< len >::set (const size_t index, const byte base) throw (std::out_of_range, std::invalid_argument) inline
Definition at line 140 of file DNAArrayBit16.hh.
References cbrc::DNAArrayBit16_clearMask.
set() [2/2]
template<size_t len> void cbrc::DNAArrayBit16< len >::set (ResidueIndexMap::arrayT residueIndices) throw (std::length_error) inline
Definition at line 126 of file DNAArrayBit16.hh.
References cbrc::DNAArrayBit16< len >::length(), cbrc::DNAArrayBit16< len >::set(), and cbrc::FLEArray< T >::size().
Referenced by cbrc::DNAArrayBit16< len >::DNAArrayBit16(), and cbrc::DNAArrayBit16< len >::set().
setBases()
template<size_t len> void cbrc::DNAArrayBit16< len >::setBases (DNAArrayBit16_bases8 bs) throw (std::invalid_argument) inline
Definition at line 69 of file DNAArrayBit16.hh.
substitute()
template<size_t len> DNAArrayBit16< len > cbrc::DNAArrayBit16< len >::substitute (const size_t index, const byte base) const throw (std::out_of_range, std::invalid_argument) inline
Definition at line 150 of file DNAArrayBit16.hh.
testDNAArrayBit16()
template<size_t len> void friend cbrc::DNAArrayBit16< len >::testDNAArrayBit16 ()
toResidues()
template<size_t len> static std::string cbrc::DNAArrayBit16< len >::toResidues (DNAArrayBit16_bases8 bases) inline static
Definition at line 158 of file DNAArrayBit16.hh.
Friends And Related Symbol Documentation
DNAArrayBit16Hamming
template<size_t len> friend class DNAArrayBit16Hamming friend
Definition at line 169 of file DNAArrayBit16.hh.
The documentation for this class was generated from the following file:
ematch_src/utils/sequence/packedDNA/DNAArrayBit16.hh