NGSFeatures: cbrc::BitArray Class Reference
cbrc::BitArray Class Reference
#include <BitArray.hh>
Classes
class trueIterator
Public Member Functions
BitArray ()
BitArray (const size_t &size)
BitArray (const BitArray &ba)
virtual ~BitArray ()
void setSize (const size_t &size)
BitArray & operator= (const BitArray &ba)
void fill (const bool &fillVal)
void zero ()
void fillWithByte (const int &fillByte)
bool validIndex (const size_t &index) const
bool operator== (const BitArray &ba) const
virtual bool operator[] (const size_t &index) const
virtual void set (const size_t &index, const bool &val) const
virtual void set (const size_t &index) const
void setFast (const size_t &index) const
virtual void clear (const size_t &index) const
void clearFast (const size_t &index) const
trueIterator trueEnd () const
trueIterator trueBegin () const
size_t size () const
size_t getSizeInBytes () const
Protected Attributes
size_t _size
size_t sizeInBytes
byte * a
Detailed Description
Definition at line 55 of file BitArray.hh.
Constructor & Destructor Documentation
BitArray() [1/3]
cbrc::BitArray::BitArray () inline
Definition at line 58 of file BitArray.hh.
References _size, a, and sizeInBytes.
BitArray() [2/3]
cbrc::BitArray::BitArray (const size_t & size)
Definition at line 14 of file BitArray.cc.
References a, BITARRAY_BITS_PER_BYTE, size(), and sizeInBytes.
BitArray() [3/3]
cbrc::BitArray::BitArray (const BitArray & ba) inline
Definition at line 62 of file BitArray.hh.
References a, and sizeInBytes.
~BitArray()
virtual cbrc::BitArray::~BitArray () inline virtual
Definition at line 68 of file BitArray.hh.
References a.
Member Function Documentation
clear()
virtual void cbrc::BitArray::clear (const size_t & index) const inline virtual
Definition at line 118 of file BitArray.hh.
References a, cbrc::BitArrayInverseMask, and validIndex().
clearFast()
void cbrc::BitArray::clearFast (const size_t & index) const inline
Definition at line 125 of file BitArray.hh.
References a, and cbrc::BitArrayInverseMask.
Referenced by set().
fill()
void cbrc::BitArray::fill (const bool & fillVal) inline
Definition at line 74 of file BitArray.hh.
References a, and sizeInBytes.
fillWithByte()
void cbrc::BitArray::fillWithByte (const int & fillByte) inline
Definition at line 81 of file BitArray.hh.
References a, and sizeInBytes.
getSizeInBytes()
size_t cbrc::BitArray::getSizeInBytes () const inline
Definition at line 157 of file BitArray.hh.
References sizeInBytes.
operator=()
BitArray & cbrc::BitArray::operator= (const BitArray & ba)
Definition at line 42 of file BitArray.cc.
References a, and sizeInBytes.
operator==()
bool cbrc::BitArray::operator== (const BitArray & ba) const inline
Definition at line 87 of file BitArray.hh.
References a, size(), and sizeInBytes.
operator[]()
virtual bool cbrc::BitArray::operator[] (const size_t & index) const inline virtual
Definition at line 92 of file BitArray.hh.
References a, cbrc::BitArrayMask, and validIndex().
set() [1/2]
virtual void cbrc::BitArray::set (const size_t & index) const inline virtual
Definition at line 105 of file BitArray.hh.
References a, cbrc::BitArrayMask, and validIndex().
set() [2/2]
virtual void cbrc::BitArray::set (const size_t & index, const bool & val) const inline virtual
Definition at line 99 of file BitArray.hh.
References clearFast(), setFast(), and validIndex().
Referenced by cbrc::BitArrayStack::push().
setFast()
void cbrc::BitArray::setFast (const size_t & index) const inline
Definition at line 112 of file BitArray.hh.
References a, and cbrc::BitArrayMask.
Referenced by set().
setSize()
void cbrc::BitArray::setSize (const size_t & size)
Definition at line 25 of file BitArray.cc.
References _size, a, BITARRAY_BITS_PER_BYTE, size(), and sizeInBytes.
size()
size_t cbrc::BitArray::size () const inline
Definition at line 156 of file BitArray.hh.
References _size.
Referenced by BitArray(), cbrc::operator<<(), operator==(), setSize(), trueBegin(), trueEnd(), and validIndex().
trueBegin()
BitArray::trueIterator cbrc::BitArray::trueBegin () const
Definition at line 101 of file BitArray.cc.
References a, BITARRAY_BITS_PER_BYTE, IMPOSSIBLE_VALUE, size(), sizeInBytes, and trueEnd().
trueEnd()
trueIterator cbrc::BitArray::trueEnd () const inline
Definition at line 147 of file BitArray.hh.
References size().
Referenced by trueBegin().
validIndex()
bool cbrc::BitArray::validIndex (const size_t & index) const
Definition at line 56 of file BitArray.cc.
References size().
Referenced by clear(), operator[](), set(), and set().
zero()
void cbrc::BitArray::zero () inline
Definition at line 79 of file BitArray.hh.
References a, and sizeInBytes.
Member Data Documentation
_size
size_t cbrc::BitArray::_size protected
Definition at line 160 of file BitArray.hh.
Referenced by BitArray(), setSize(), and size().
a
byte* cbrc::BitArray::a protected
Definition at line 162 of file BitArray.hh.
Referenced by BitArray(), BitArray(), BitArray(), clear(), clearFast(), fill(), fillWithByte(), operator=(), operator==(), operator[](), set(), setFast(), setSize(), trueBegin(), zero(), and ~BitArray().
sizeInBytes
size_t cbrc::BitArray::sizeInBytes protected
Definition at line 161 of file BitArray.hh.
Referenced by BitArray(), BitArray(), BitArray(), fill(), fillWithByte(), getSizeInBytes(), operator=(), operator==(), setSize(), trueBegin(), and zero().
The documentation for this class was generated from the following files:
ematch_src/utils/BitMatrix/BitArray.hh
ematch_src/utils/BitMatrix/BitArray.cc