NGSFeatures: cbrc::TransfacBindingFactor Class Reference
cbrc::TransfacBindingFactor Class Reference
#include <TransfacBindingFactor.hh>
Public Member Functions
TransfacBindingFactor (const std::string &transfacBFString)
TransfacBindingFactor ()
void set (const std::string &transfacBFString)
std::string id () const
std::string name () const
std::string speciesName () const
std::string genusName () const
std::string speciesCommonName () const
Detailed Description
Definition at line 19 of file TransfacBindingFactor.hh.
Constructor & Destructor Documentation
TransfacBindingFactor() [1/2]
cbrc::TransfacBindingFactor::TransfacBindingFactor (const std::string & transfacBFString) inline
Definition at line 21 of file TransfacBindingFactor.hh.
References set().
TransfacBindingFactor() [2/2]
cbrc::TransfacBindingFactor::TransfacBindingFactor () inline
Definition at line 22 of file TransfacBindingFactor.hh.
Member Function Documentation
genusName()
std::string cbrc::TransfacBindingFactor::genusName () const inline
Definition at line 27 of file TransfacBindingFactor.hh.
id()
std::string cbrc::TransfacBindingFactor::id () const inline
Definition at line 24 of file TransfacBindingFactor.hh.
name()
std::string cbrc::TransfacBindingFactor::name () const inline
Definition at line 25 of file TransfacBindingFactor.hh.
set()
void cbrc::TransfacBindingFactor::set (const std::string & transfacBFString)
Definition at line 13 of file TransfacBindingFactor.cc.
References cbrc::FLEArray< T >::find(), cbrc::perlish::removeCharFromString(), cbrc::perlish::removeLeadingWhiteSpace(), cbrc::FLEArray< T >::size(), and cbrc::perlish::split().
Referenced by cbrc::TransfacReader::readRecord(), and TransfacBindingFactor().
speciesCommonName()
std::string cbrc::TransfacBindingFactor::speciesCommonName () const inline
Definition at line 28 of file TransfacBindingFactor.hh.
speciesName()
std::string cbrc::TransfacBindingFactor::speciesName () const inline
Definition at line 26 of file TransfacBindingFactor.hh.
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/readers/transfac/TransfacBindingFactor.hh
ematch_src/utils/sequence/readers/transfac/TransfacBindingFactor.cc