NGSFeatures: cbrc::OneEdgePerLineFormat Class Reference
cbrc::OneEdgePerLineFormat Class Reference
#include <OneEdgePerLineFormat.hh>
Static Public Member Functions
static nodeIndexT numNodesInStream (std::istream &is)
static const boost::regex & inputDelimiter ()
static nodeIndexT numNodesInStream (std::istream &is)
static const boost::regex & inputDelimiter ()
Detailed Description
Definition at line 21 of file OneEdgePerLineFormat.hh.
Member Function Documentation
inputDelimiter() [1/2]
static const boost::regex & cbrc::OneEdgePerLineFormat::inputDelimiter () inline static
Definition at line 24 of file OneEdgePerLineFormat.hh.
Referenced by cbrc::listConnectedComponents(), numNodesInStream(), cbrc::printRandomRepresentativeFromEachConnectedComponent(), and cbrc::NeighborListGraph::readOneEdgePerLineFormat().
inputDelimiter() [2/2]
static const boost::regex & cbrc::OneEdgePerLineFormat::inputDelimiter () inline static
Definition at line 24 of file OneEdgePerLineFormat.hh.
numNodesInStream() [1/2]
nodeIndexT cbrc::OneEdgePerLineFormat::numNodesInStream (std::istream & is) static
Definition at line 16 of file OneEdgePerLineFormat.cc.
References inputDelimiter(), cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLine(), and cbrc::perlish::split().
Referenced by cbrc::listConnectedComponents(), and cbrc::printRandomRepresentativeFromEachConnectedComponent().
numNodesInStream() [2/2]
static nodeIndexT cbrc::OneEdgePerLineFormat::numNodesInStream (std::istream & is) static
The documentation for this class was generated from the following files:
ematch_src/graph/OneEdgePerLineFormat.hh
ematch_src/utils/graph/OneEdgePerLineFormat.hh
ematch_src/graph/OneEdgePerLineFormat.cc
ematch_src/utils/graph/OneEdgePerLineFormat.cc