NGSFeatures: cbrc::LabeledSquareFLENumMatrix< elemT > Class Template Reference
cbrc::LabeledSquareFLENumMatrix< elemT > Class Template Reference
#include <LabeledSquareFLENumMatrix.hh>
Public Member Functions
LabeledSquareFLENumMatrix (const SerialNumbersForStrings< size_t > &labels)
elemT & operator() (const size_t &index0, const size_t &index1) const
elemT & operator() (const std::string &label0, const std::string &label1) const
const std::string & label (const size_t &i) const
const size_t & size () const
void zero ()
void reorderLabels (const std::vector< std::string > &newOrderLabels, const elemT defaultValue=0)
Detailed Description
template<typename elemT>
class cbrc::LabeledSquareFLENumMatrix< elemT >
Definition at line 36 of file LabeledSquareFLENumMatrix.hh.
Constructor & Destructor Documentation
LabeledSquareFLENumMatrix()
template<typename elemT > cbrc::LabeledSquareFLENumMatrix< elemT >::LabeledSquareFLENumMatrix (const SerialNumbersForStrings< size_t > & labels) inline
Definition at line 38 of file LabeledSquareFLENumMatrix.hh.
References cbrc::FLEMatrix< T >::setSize(), and cbrc::FLEArray< T >::size().
Member Function Documentation
label()
template<typename elemT > const std::string & cbrc::LabeledSquareFLENumMatrix< elemT >::label (const size_t & i) const inline
Definition at line 55 of file LabeledSquareFLENumMatrix.hh.
operator()() [1/2]
template<typename elemT > elemT & cbrc::LabeledSquareFLENumMatrix< elemT >::operator() (const size_t & index0, const size_t & index1) const inline
Definition at line 46 of file LabeledSquareFLENumMatrix.hh.
operator()() [2/2]
template<typename elemT > elemT & cbrc::LabeledSquareFLENumMatrix< elemT >::operator() (const std::string & label0, const std::string & label1) const inline
Definition at line 50 of file LabeledSquareFLENumMatrix.hh.
reorderLabels()
template<typename elemT > void cbrc::LabeledSquareFLENumMatrix< elemT >::reorderLabels (const std::vector< std::string > & newOrderLabels, const elemT defaultValue = 0)
Definition at line 104 of file LabeledSquareFLENumMatrix.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), cbrc::FLEArray< T >::FLEArray(), cbrc::FLEArray< T >::setSize(), and cbrc::FLEArray< T >::size().
size()
template<typename elemT > const size_t & cbrc::LabeledSquareFLENumMatrix< elemT >::size () const inline
Definition at line 57 of file LabeledSquareFLENumMatrix.hh.
References cbrc::FLEMatrix< T >::size0().
zero()
template<typename elemT > void cbrc::LabeledSquareFLENumMatrix< elemT >::zero () inline
Definition at line 61 of file LabeledSquareFLENumMatrix.hh.
References cbrc::FLEMatrix< T >::zero().
The documentation for this class was generated from the following file:
ematch_src/utils/FLArray/LabeledSquareFLENumMatrix.hh