NGSFeatures: cbrc::FLESorted< T > Class Template Reference
cbrc::FLESorted< T > Class Template Reference
#include <FLESorted.hh>
Public Types
typedef const T * const_iterator
Public Member Functions
FLESorted ()
FLESorted (const std::vector< T > &v)
FLESorted (std::istream &is)
void operator= (const std::vector< T > &v)
void assign (const typename std::vector< T >::const_iterator &begin, const typename std::vector< T >::const_iterator &end)
const FLEArray< T > & asArray () const
const size_t & size () const
const T & operator() (const size_t &i) const
const_iterator begin () const
const_iterator end () const
bool has (const T &val) const
size_t elementRank (const T &val) const
size_t elementRankAfterTies (const T &val) const
void read (std::istream &is)
void write (std::ostream &os) const
Detailed Description
template<typename T>
class cbrc::FLESorted< T >
Definition at line 28 of file FLESorted.hh.
Member Typedef Documentation
const_iterator
template<typename T > typedef const T* cbrc::FLESorted< T >::const_iterator
Definition at line 32 of file FLESorted.hh.
Constructor & Destructor Documentation
FLESorted() [1/3]
template<typename T > cbrc::FLESorted< T >::FLESorted () inline
Definition at line 36 of file FLESorted.hh.
FLESorted() [2/3]
template<typename T > cbrc::FLESorted< T >::FLESorted (const std::vector< T > & v) inline
Definition at line 38 of file FLESorted.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and cbrc::FLEArray< T >::resize().
FLESorted() [3/3]
template<typename T > cbrc::FLESorted< T >::FLESorted (std::istream & is) inline
Definition at line 43 of file FLESorted.hh.
References cbrc::FLEArray< T >::read().
Member Function Documentation
asArray()
template<typename T > const FLEArray< T > & cbrc::FLESorted< T >::asArray () const inline
Definition at line 66 of file FLESorted.hh.
assign()
template<typename T > void cbrc::FLESorted< T >::assign (const typename std::vector< T >::const_iterator & begin, const typename std::vector< T >::const_iterator & end) inline
Definition at line 56 of file FLESorted.hh.
References cbrc::FLEArray< T >::assign(), cbrc::FLEArray< T >::begin(), cbrc::FLESorted< T >::begin(), cbrc::FLEArray< T >::end(), cbrc::FLESorted< T >::end(), and cbrc::FLEArray< T >::resize().
begin()
template<typename T > const_iterator cbrc::FLESorted< T >::begin () const inline
Definition at line 76 of file FLESorted.hh.
References cbrc::FLEArray< T >::begin().
Referenced by cbrc::FLESorted< T >::assign().
elementRank()
template<typename T > size_t cbrc::FLESorted< T >::elementRank (const T & val) const inline
Definition at line 86 of file FLESorted.hh.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
elementRankAfterTies()
template<typename T > size_t cbrc::FLESorted< T >::elementRankAfterTies (const T & val) const inline
Definition at line 91 of file FLESorted.hh.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
end()
template<typename T > const_iterator cbrc::FLESorted< T >::end () const inline
Definition at line 77 of file FLESorted.hh.
References cbrc::FLEArray< T >::end().
Referenced by cbrc::FLESorted< T >::assign().
has()
template<typename T > bool cbrc::FLESorted< T >::has (const T & val) const inline
Definition at line 81 of file FLESorted.hh.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
operator()()
template<typename T > const T & cbrc::FLESorted< T >::operator() (const size_t & i) const inline
Definition at line 73 of file FLESorted.hh.
operator=()
template<typename T > void cbrc::FLESorted< T >::operator= (const std::vector< T > & v) inline
Definition at line 50 of file FLESorted.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and cbrc::FLEArray< T >::resize().
read()
template<typename T > void cbrc::FLESorted< T >::read (std::istream & is) inline
Definition at line 98 of file FLESorted.hh.
References cbrc::FLEArray< T >::read().
size()
template<typename T > const size_t & cbrc::FLESorted< T >::size () const inline
Definition at line 71 of file FLESorted.hh.
References cbrc::FLEArray< T >::size().
write()
template<typename T > void cbrc::FLESorted< T >::write (std::ostream & os) const inline
Definition at line 100 of file FLESorted.hh.
References cbrc::FLEArray< T >::write().
The documentation for this class was generated from the following file:
ematch_src/utils/FLArray/FLESorted.hh