NGSFeatures: cbrc::ResidueIndexedSequence Class Reference
cbrc::ResidueIndexedSequence Class Reference
#include <ResidueIndexedSequence.hh>
Public Types
typedef ResidueIndexMap::arrayT::const_iterator const_iterator
Public Member Functions
ResidueIndexedSequence (const ResidueIndexMap &rim, const std::string &asciiSeq, const std::string name=std::string(""))
ResidueIndexedSequence (std::istream &is)
ResidueIndexedSequence ()
const ResidueIndexMap & residueIndexMap () const
ResidueIndexMap & residueIndexMapNonconst ()
const ResidueIndexMap::arrayT & sequence () const
const std::string & name () const
std::string toResidues () const
size_t size () const
ResidueIndexMap::indexT * begin () const
ResidueIndexMap::indexT * end () const
const ResidueIndexMap::indexT & operator() (const size_t &i) const
ResidueIndexMap::indexT & operator[] (const size_t &i) const
void read (std::istream &is)
void write (std::ostream &os) const
Static Public Member Functions
static const std::string & binaryStreamSignature ()
Detailed Description
Definition at line 26 of file ResidueIndexedSequence.hh.
Member Typedef Documentation
const_iterator
typedef ResidueIndexMap::arrayT::const_iterator cbrc::ResidueIndexedSequence::const_iterator
Definition at line 29 of file ResidueIndexedSequence.hh.
Constructor & Destructor Documentation
ResidueIndexedSequence() [1/3]
cbrc::ResidueIndexedSequence::ResidueIndexedSequence (const ResidueIndexMap & rim, const std::string & asciiSeq, const std::string name = std::string("")) inline
Definition at line 32 of file ResidueIndexedSequence.hh.
References cbrc::ResidueIndexMap::assignResidueIndices().
ResidueIndexedSequence() [2/3]
cbrc::ResidueIndexedSequence::ResidueIndexedSequence (std::istream & is) inline
Definition at line 40 of file ResidueIndexedSequence.hh.
References read().
ResidueIndexedSequence() [3/3]
cbrc::ResidueIndexedSequence::ResidueIndexedSequence () inline
Definition at line 45 of file ResidueIndexedSequence.hh.
Member Function Documentation
begin()
ResidueIndexMap::indexT * cbrc::ResidueIndexedSequence::begin () const inline
Definition at line 67 of file ResidueIndexedSequence.hh.
References cbrc::FLEArray< T >::begin().
binaryStreamSignature()
static const std::string & cbrc::ResidueIndexedSequence::binaryStreamSignature () inline static
Definition at line 79 of file ResidueIndexedSequence.hh.
Referenced by read(), and write().
end()
ResidueIndexMap::indexT * cbrc::ResidueIndexedSequence::end () const inline
Definition at line 68 of file ResidueIndexedSequence.hh.
References cbrc::FLEArray< T >::end().
name()
const std::string & cbrc::ResidueIndexedSequence::name () const inline
Definition at line 52 of file ResidueIndexedSequence.hh.
operator()()
const ResidueIndexMap::indexT & cbrc::ResidueIndexedSequence::operator() (const size_t & i) const inline
Definition at line 70 of file ResidueIndexedSequence.hh.
operator[]()
ResidueIndexMap::indexT & cbrc::ResidueIndexedSequence::operator[] (const size_t & i) const inline
Definition at line 73 of file ResidueIndexedSequence.hh.
read()
void cbrc::ResidueIndexedSequence::read (std::istream & is)
Definition at line 16 of file ResidueIndexedSequence.cc.
References binaryStreamSignature(), cbrc::perlish::die(), cbrc::FLEArray< T >::read(), cbrc::ResidueIndexMap::read(), cbrc::stringBinaryIO::read(), and size().
Referenced by ResidueIndexedSequence().
residueIndexMap()
const ResidueIndexMap & cbrc::ResidueIndexedSequence::residueIndexMap () const inline
Definition at line 49 of file ResidueIndexedSequence.hh.
Referenced by toResidues(), and write().
residueIndexMapNonconst()
ResidueIndexMap & cbrc::ResidueIndexedSequence::residueIndexMapNonconst () inline
Definition at line 50 of file ResidueIndexedSequence.hh.
sequence()
const ResidueIndexMap::arrayT & cbrc::ResidueIndexedSequence::sequence () const inline
Definition at line 51 of file ResidueIndexedSequence.hh.
size()
size_t cbrc::ResidueIndexedSequence::size () const inline
Definition at line 66 of file ResidueIndexedSequence.hh.
References cbrc::FLEArray< T >::size().
Referenced by read().
toResidues()
std::string cbrc::ResidueIndexedSequence::toResidues () const inline
Definition at line 58 of file ResidueIndexedSequence.hh.
References residueIndexMap(), and toResidues().
Referenced by toResidues().
write()
void cbrc::ResidueIndexedSequence::write (std::ostream & os) const
Definition at line 37 of file ResidueIndexedSequence.cc.
References binaryStreamSignature(), residueIndexMap(), cbrc::stringBinaryIO::write(), cbrc::FLEArray< T >::write(), and cbrc::stringBinaryIO::writeContentsOnly().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/ResidueIndexedSequence.hh
ematch_src/utils/sequence/ResidueIndexedSequence.cc