NGSFeatures: cbrc::TransfacReader Class Reference
cbrc::TransfacReader Class Reference
#include <TransfacReader.hh>
Public Member Functions
TransfacReader (std::istream &is)
std::string collectionHeader () const
TransfacTextLine nextNonBlankLine () const
bool readRecord ()
std::string version () const
std::string accession () const
std::string description () const
std::string name () const
TransfacBindingFactor bindingFactor () const
std::string alphabet () const
std::vector< std::vector< unsigned int > > freqMatrix () const
std::string consensusSequence () const
Detailed Description
Definition at line 20 of file TransfacReader.hh.
Constructor & Destructor Documentation
TransfacReader()
cbrc::TransfacReader::TransfacReader (std::istream & is)
Definition at line 14 of file TransfacReader.cc.
References cbrc::TransfacTextLine::content(), cbrc::TransfacTextLine::empty(), cbrc::TransfacTextLabelInfo::isRecordSeparator(), cbrc::TransfacTextLabelInfo::isVersion(), and nextNonBlankLine().
Member Function Documentation
accession()
std::string cbrc::TransfacReader::accession () const inline
Definition at line 27 of file TransfacReader.hh.
alphabet()
std::string cbrc::TransfacReader::alphabet () const inline
Definition at line 32 of file TransfacReader.hh.
bindingFactor()
TransfacBindingFactor cbrc::TransfacReader::bindingFactor () const inline
Definition at line 30 of file TransfacReader.hh.
collectionHeader()
std::string cbrc::TransfacReader::collectionHeader () const inline
Definition at line 23 of file TransfacReader.hh.
consensusSequence()
std::string cbrc::TransfacReader::consensusSequence () const inline
Definition at line 34 of file TransfacReader.hh.
description()
std::string cbrc::TransfacReader::description () const inline
Definition at line 28 of file TransfacReader.hh.
freqMatrix()
std::vector< std::vector< unsigned int > > cbrc::TransfacReader::freqMatrix () const inline
Definition at line 33 of file TransfacReader.hh.
name()
std::string cbrc::TransfacReader::name () const inline
Definition at line 29 of file TransfacReader.hh.
nextNonBlankLine()
TransfacTextLine cbrc::TransfacReader::nextNonBlankLine () const
Definition at line 95 of file TransfacReader.cc.
References cbrc::TransfacTextLabelInfo::isBlankLine(), cbrc::FLEArray< T >::size(), and cbrc::perlish::slurpLine().
Referenced by readRecord(), and TransfacReader().
readRecord()
bool cbrc::TransfacReader::readRecord ()
Definition at line 33 of file TransfacReader.cc.
References cbrc::TransfacTextLine::content(), cbrc::TransfacTextLine::empty(), cbrc::TransfacTextLabelInfo::isAccession(), cbrc::TransfacTextLabelInfo::isBindingFactor(), cbrc::TransfacTextLabelInfo::isDescription(), cbrc::TransfacTextLabelInfo::isFreqMatrix(), cbrc::TransfacTextLabelInfo::isName(), cbrc::TransfacTextLabelInfo::isRecordSeparator(), nextNonBlankLine(), and cbrc::TransfacBindingFactor::set().
version()
std::string cbrc::TransfacReader::version () const inline
Definition at line 26 of file TransfacReader.hh.
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/readers/transfac/TransfacReader.hh
ematch_src/utils/sequence/readers/transfac/TransfacReader.cc