NGSFeatures: cbrc::String2KeyHashIterator< ValT > Class Template Reference
cbrc::String2KeyHashIterator< ValT > Class Template Reference
#include <String2KeyHashtable.hh>
Public Member Functions
String2KeyHashIterator ()
String2KeyHashIterator (String2KeyHashtableLink< ValT > **head, String2KeyHashtableLink< ValT > **last)
bool valid ()
bool operator== (const String2KeyHashIterator< ValT > &ch) const
bool operator!= (const String2KeyHashIterator< ValT > &ch) const
String2KeyAndValue< ValT > * getElemPtr () const
String2KeyAndValue< ValT > & operator* () const
String2KeyHashIterator< ValT > & operator++ ()
Friends
class String2KeyHashtable< ValT >
Detailed Description
template<typename ValT>
class cbrc::String2KeyHashIterator< ValT >
Definition at line 143 of file String2KeyHashtable.hh.
Constructor & Destructor Documentation
String2KeyHashIterator() [1/2]
template<typename ValT > cbrc::String2KeyHashIterator< ValT >::String2KeyHashIterator () inline
Definition at line 137 of file String2KeyHashtable.hh.
String2KeyHashIterator() [2/2]
template<typename ValT > cbrc::String2KeyHashIterator< ValT >::String2KeyHashIterator (String2KeyHashtableLink< ValT > ** head, String2KeyHashtableLink< ValT > ** last) inline
Definition at line 137 of file String2KeyHashtable.hh.
Member Function Documentation
getElemPtr()
template<typename ValT > String2KeyAndValue< ValT > * cbrc::String2KeyHashIterator< ValT >::getElemPtr () const inline
Definition at line 157 of file String2KeyHashtable.hh.
Referenced by cbrc::String2KeyHashIterator< ValT >::operator*().
operator!=()
template<typename ValT > bool cbrc::String2KeyHashIterator< ValT >::operator!= (const String2KeyHashIterator< ValT > & ch) const inline
Definition at line 156 of file String2KeyHashtable.hh.
operator*()
template<typename ValT > String2KeyAndValue< ValT > & cbrc::String2KeyHashIterator< ValT >::operator* () const inline
Definition at line 158 of file String2KeyHashtable.hh.
References cbrc::String2KeyHashIterator< ValT >::getElemPtr().
operator++()
template<typename ValT > String2KeyHashIterator< ValT > & cbrc::String2KeyHashIterator< ValT >::operator++ () inline
Definition at line 160 of file String2KeyHashtable.hh.
References cbrc::String2KeyHashIterator< ValT >::valid().
operator==()
template<typename ValT > bool cbrc::String2KeyHashIterator< ValT >::operator== (const String2KeyHashIterator< ValT > & ch) const inline
Definition at line 152 of file String2KeyHashtable.hh.
valid()
template<typename ValT > bool cbrc::String2KeyHashIterator< ValT >::valid () inline
Definition at line 151 of file String2KeyHashtable.hh.
Referenced by cbrc::String2KeyHashIterator< ValT >::operator++().
Friends And Related Symbol Documentation
String2KeyHashtable< ValT >
template<typename ValT > friend class String2KeyHashtable< ValT > friend
Definition at line 137 of file String2KeyHashtable.hh.
The documentation for this class was generated from the following file:
ematch_src/utils/ChainHashtable/String2KeyHashtable.hh