NGSFeatures: cbrc::FastafmtReader Class Reference
cbrc::FastafmtReader Class Reference
#include <FastafmtReader.hh>
Public Member Functions
FastafmtReader (FastafmtInputOptions options=defaultFastaInputOptions)
bool readRecord (std::istream &is)
std::vector< FastafmtRecord > slurpSeqs (std::istream &is)
void resetToReadFreshStream ()
const std::string & curHead () const
FastafmtRecord curRecord () const
const std::string & seq () const
const FastafmtInputOptions & fastafmtInputOptions () const
FastafmtInputOptions & fastafmtInputOptionsRef ()
const size_t & lineLengthForPrintingSequence () const
const std::string & commentMarker () const
void upcaseSequence ()
Detailed Description
Definition at line 31 of file FastafmtReader.hh.
Constructor & Destructor Documentation
FastafmtReader()
cbrc::FastafmtReader::FastafmtReader (FastafmtInputOptions options = defaultFastaInputOptions) inline
Definition at line 34 of file FastafmtReader.hh.
Member Function Documentation
commentMarker()
const std::string & cbrc::FastafmtReader::commentMarker () const inline
Definition at line 81 of file FastafmtReader.hh.
curHead()
const std::string & cbrc::FastafmtReader::curHead () const inline
Definition at line 57 of file FastafmtReader.hh.
curRecord()
FastafmtRecord cbrc::FastafmtReader::curRecord () const inline
Definition at line 61 of file FastafmtReader.hh.
Referenced by seq().
fastafmtInputOptions()
const FastafmtInputOptions & cbrc::FastafmtReader::fastafmtInputOptions () const inline
Definition at line 70 of file FastafmtReader.hh.
fastafmtInputOptionsRef()
FastafmtInputOptions & cbrc::FastafmtReader::fastafmtInputOptionsRef () inline
Definition at line 74 of file FastafmtReader.hh.
lineLengthForPrintingSequence()
const size_t & cbrc::FastafmtReader::lineLengthForPrintingSequence () const inline
Definition at line 78 of file FastafmtReader.hh.
readRecord()
bool cbrc::FastafmtReader::readRecord (std::istream & is)
Definition at line 18 of file FastafmtReader.cc.
References seq(), cbrc::FastafmtRecord::seqRef(), and cbrc::FastafmtConstants::seqTerminationMarker().
resetToReadFreshStream()
void cbrc::FastafmtReader::resetToReadFreshStream () inline
Definition at line 49 of file FastafmtReader.hh.
seq()
const std::string & cbrc::FastafmtReader::seq () const inline
Definition at line 65 of file FastafmtReader.hh.
References curRecord(), and cbrc::FastafmtRecord::seq().
Referenced by readRecord().
slurpSeqs()
std::vector< FastafmtRecord > cbrc::FastafmtReader::slurpSeqs (std::istream & is)
upcaseSequence()
void cbrc::FastafmtReader::upcaseSequence ()
Definition at line 140 of file FastafmtReader.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and cbrc::FastafmtRecord::seqRef().
The documentation for this class was generated from the following files:
ematch_src/utils/sequence/fastafmt/FastafmtReader.hh
ematch_src/utils/sequence/fastafmt/FastafmtReader.cc