NGSFeatures: cbrc::RecountExpectationMatchingTagCorrector Class Reference
cbrc::RecountExpectationMatchingTagCorrector Class Reference
#include <RecountExpectationMatchingTagCorrector.hh>
Public Member Functions
RecountExpectationMatchingTagCorrector (const RecountComputerForGraphOnDisk &expectationComputer, const RecountTagCounts &observedCounts, const size_t numRoundsToWaitForBetter=10)
const size_t & numRoundsToWaitForBetter () const
const RecountTagCounts & estimatedTrueCounts () const
const tagCountT & bestEstError () const
const RecountTagCounts & bestEstCounts () const
const size_t & bestEstCountsIteration () const
const int & curIdx () const
int prevIdx () const
void incrementIdx ()
void inferTrueTagCounts ()
void computeCountCorrections ()
RecountExpectationMatchingTagCorrector (const RecountComputerForGraphOnDisk &expectationComputer, const RecountTagCounts &observedCounts, const tagCountT maxCountDiff_convergenceCriterion=0.4, const double momentum=0.1, const tagCountT initialLearningRate=1.0, const size_t numIterationsToWaitForImprovement=100, const tagCountT learningRateDeaccelarationFactor=0.9)
const RecountTagCounts & estimatedTrueCounts () const
const tagCountT & learningRate () const
const RecountTagCounts & bestEstCounts () const
const tagCountT & bestEstCountsTotalFoldChange () const
const size_t & bestEstCountsIteration () const
const int & curIdx () const
int prevIdx () const
void incrementIdx ()
void inferTrueTagCounts ()
void computeCountCorrections_by1stDerivative ()
tagCountT totalFoldChangeError () const
Detailed Description
Definition at line 23 of file RecountExpectationMatchingTagCorrector.hh.
Constructor & Destructor Documentation
RecountExpectationMatchingTagCorrector() [1/2]
cbrc::RecountExpectationMatchingTagCorrector::RecountExpectationMatchingTagCorrector (const RecountComputerForGraphOnDisk & expectationComputer, const RecountTagCounts & observedCounts, const size_t numRoundsToWaitForBetter = 10)
Definition at line 17 of file RecountExpectationMatchingTagCorrector.cc.
References cbrc::RecountTagCounts::assign(), curIdx(), prevIdx(), cbrc::RecountTagCounts::setSize(), cbrc::RecountTagCounts::size(), and cbrc::RecountTagCounts::zero().
RecountExpectationMatchingTagCorrector() [2/2]
cbrc::RecountExpectationMatchingTagCorrector::RecountExpectationMatchingTagCorrector (const RecountComputerForGraphOnDisk & expectationComputer, const RecountTagCounts & observedCounts, const tagCountT maxCountDiff_convergenceCriterion = 0.4, const double momentum = 0.1, const tagCountT initialLearningRate = 1.0, const size_t numIterationsToWaitForImprovement = 100, const tagCountT learningRateDeaccelarationFactor = 0.9)
Definition at line 17 of file RecountGradientSearchTagCorrector.cc.
References cbrc::RecountTagCounts::assign(), curIdx(), prevIdx(), cbrc::RecountTagCounts::setSize(), cbrc::RecountTagCounts::size(), and cbrc::RecountTagCounts::zero().
Member Function Documentation
bestEstCounts() [1/2]
const RecountTagCounts & cbrc::RecountExpectationMatchingTagCorrector::bestEstCounts () const inline
Definition at line 49 of file RecountExpectationMatchingTagCorrector.hh.
bestEstCounts() [2/2]
const RecountTagCounts & cbrc::RecountExpectationMatchingTagCorrector::bestEstCounts () const inline
Definition at line 51 of file RecountGradientSearchTagCorrector.hh.
bestEstCountsIteration() [1/2]
const size_t & cbrc::RecountExpectationMatchingTagCorrector::bestEstCountsIteration () const inline
Definition at line 53 of file RecountExpectationMatchingTagCorrector.hh.
Referenced by inferTrueTagCounts().
bestEstCountsIteration() [2/2]
const size_t & cbrc::RecountExpectationMatchingTagCorrector::bestEstCountsIteration () const inline
Definition at line 59 of file RecountGradientSearchTagCorrector.hh.
bestEstCountsTotalFoldChange()
const tagCountT & cbrc::RecountExpectationMatchingTagCorrector::bestEstCountsTotalFoldChange () const inline
Definition at line 55 of file RecountGradientSearchTagCorrector.hh.
bestEstError()
const tagCountT & cbrc::RecountExpectationMatchingTagCorrector::bestEstError () const inline
Definition at line 45 of file RecountExpectationMatchingTagCorrector.hh.
Referenced by inferTrueTagCounts().
computeCountCorrections()
void cbrc::RecountExpectationMatchingTagCorrector::computeCountCorrections ()
Definition at line 74 of file RecountExpectationMatchingTagCorrector.cc.
References cbrc::RecountTagCounts::constBegin(), cbrc::FLEArray< T >::constBegin(), curIdx(), cbrc::RecountTagCounts::end(), and prevIdx().
Referenced by inferTrueTagCounts().
computeCountCorrections_by1stDerivative()
void cbrc::RecountExpectationMatchingTagCorrector::computeCountCorrections_by1stDerivative ()
Definition at line 126 of file RecountGradientSearchTagCorrector.cc.
References cbrc::RecountTagCounts::constBegin(), cbrc::FLEArray< T >::constBegin(), curIdx(), cbrc::RecountTagCounts::end(), learningRate(), and prevIdx().
curIdx() [1/2]
const int & cbrc::RecountExpectationMatchingTagCorrector::curIdx () const inline
Definition at line 60 of file RecountExpectationMatchingTagCorrector.hh.
Referenced by computeCountCorrections(), computeCountCorrections_by1stDerivative(), estimatedTrueCounts(), inferTrueTagCounts(), prevIdx(), RecountExpectationMatchingTagCorrector(), and RecountExpectationMatchingTagCorrector().
curIdx() [2/2]
const int & cbrc::RecountExpectationMatchingTagCorrector::curIdx () const inline
Definition at line 66 of file RecountGradientSearchTagCorrector.hh.
estimatedTrueCounts() [1/2]
const RecountTagCounts & cbrc::RecountExpectationMatchingTagCorrector::estimatedTrueCounts () const inline
Definition at line 41 of file RecountExpectationMatchingTagCorrector.hh.
References curIdx().
estimatedTrueCounts() [2/2]
const RecountTagCounts & cbrc::RecountExpectationMatchingTagCorrector::estimatedTrueCounts () const inline
Definition at line 43 of file RecountGradientSearchTagCorrector.hh.
References curIdx().
incrementIdx() [1/2]
void cbrc::RecountExpectationMatchingTagCorrector::incrementIdx () inline
Definition at line 68 of file RecountExpectationMatchingTagCorrector.hh.
References prevIdx().
Referenced by inferTrueTagCounts().
incrementIdx() [2/2]
void cbrc::RecountExpectationMatchingTagCorrector::incrementIdx () inline
Definition at line 74 of file RecountGradientSearchTagCorrector.hh.
References prevIdx().
inferTrueTagCounts() [1/2]
void cbrc::RecountExpectationMatchingTagCorrector::inferTrueTagCounts ()
Definition at line 43 of file RecountExpectationMatchingTagCorrector.cc.
References cbrc::RecountTagCounts::assign(), bestEstCountsIteration(), bestEstError(), computeCountCorrections(), curIdx(), incrementIdx(), cbrc::RecountTagCounts::maxAbsDiff(), numRoundsToWaitForBetter(), and prevIdx().
inferTrueTagCounts() [2/2]
void cbrc::RecountExpectationMatchingTagCorrector::inferTrueTagCounts ()
learningRate()
const tagCountT & cbrc::RecountExpectationMatchingTagCorrector::learningRate () const inline
Definition at line 47 of file RecountGradientSearchTagCorrector.hh.
Referenced by computeCountCorrections_by1stDerivative().
numRoundsToWaitForBetter()
const size_t & cbrc::RecountExpectationMatchingTagCorrector::numRoundsToWaitForBetter () const inline
Definition at line 37 of file RecountExpectationMatchingTagCorrector.hh.
Referenced by inferTrueTagCounts().
prevIdx() [1/2]
int cbrc::RecountExpectationMatchingTagCorrector::prevIdx () const inline
Definition at line 64 of file RecountExpectationMatchingTagCorrector.hh.
References curIdx().
Referenced by computeCountCorrections(), computeCountCorrections_by1stDerivative(), incrementIdx(), inferTrueTagCounts(), RecountExpectationMatchingTagCorrector(), and RecountExpectationMatchingTagCorrector().
prevIdx() [2/2]
int cbrc::RecountExpectationMatchingTagCorrector::prevIdx () const inline
Definition at line 70 of file RecountGradientSearchTagCorrector.hh.
References curIdx().
totalFoldChangeError()
tagCountT cbrc::RecountExpectationMatchingTagCorrector::totalFoldChangeError () const
Definition at line 146 of file RecountGradientSearchTagCorrector.cc.
References cbrc::RecountTagCounts::constBegin(), cbrc::FLEArray< T >::constBegin(), and cbrc::FLEArray< T >::constEnd().
The documentation for this class was generated from the following files:
ematch_src/RecountExpectationMatchingTagCorrector.hh
ematch_src/RecountGradientSearchTagCorrector.hh
ematch_src/RecountExpectationMatchingTagCorrector.cc
ematch_src/RecountGradientSearchTagCorrector.cc