NGSFeatures: cbrc::UnsignedDoubleMap Class Reference
cbrc::UnsignedDoubleMap Class Reference
#include <UnsignedDoubleMap.hh>
Public Types
typedef std::map< unsigned, double > mapT
Public Member Functions
UnsignedDoubleMap ()
bool has (const unsigned &key) const
double operator() (const unsigned &key) const
void operator() (const unsigned &key, const double &val)
const mapT & map () const
Detailed Description
Definition at line 26 of file UnsignedDoubleMap.hh.
Member Typedef Documentation
mapT
typedef std::map<unsigned, double> cbrc::UnsignedDoubleMap::mapT
Definition at line 29 of file UnsignedDoubleMap.hh.
Constructor & Destructor Documentation
UnsignedDoubleMap()
cbrc::UnsignedDoubleMap::UnsignedDoubleMap () inline
Definition at line 32 of file UnsignedDoubleMap.hh.
Member Function Documentation
has()
bool cbrc::UnsignedDoubleMap::has (const unsigned & key) const inline
Definition at line 35 of file UnsignedDoubleMap.hh.
References map().
map()
const mapT & cbrc::UnsignedDoubleMap::map () const inline
Definition at line 58 of file UnsignedDoubleMap.hh.
Referenced by has(), operator()(), and operator()().
operator()() [1/2]
double cbrc::UnsignedDoubleMap::operator() (const unsigned & key) const inline
Definition at line 39 of file UnsignedDoubleMap.hh.
References cbrc::FLEArray< T >::find(), GDB_DIEF, and map().
operator()() [2/2]
void cbrc::UnsignedDoubleMap::operator() (const unsigned & key, const double & val) inline
Definition at line 47 of file UnsignedDoubleMap.hh.
References map().
The documentation for this class was generated from the following file:
ematch_src/utils/stl/UnsignedDoubleMap.hh