NGSFeatures: cbrc::FLArray< T > Class Template Reference
cbrc::FLArray< T > Class Template Reference
#include <FLArray.hh>
Public Types
typedef T * iterator
typedef const T * const_iterator
Public Member Functions
FLArray ()
FLArray (const size_t &sz)
FLArray (const size_t &sz, const T &fillVal)
FLArray (const size_t &sz, const T *&b)
FLArray (const std::vector< T > &v)
FLArray (const std::string &v)
FLArray (const FLArray< T > &fla)
virtual ~FLArray ()
operator std::vector< T > () const
void setSize (size_t sz)
void resize (size_t sz)
FLArray operator= (const FLArray &fla)
FLArray operator= (std::vector< T > v)
void assign (const typename FLArray< T >::const_iterator &begin, const typename FLArray< T >::const_iterator &end)
void assign (const typename std::vector< T >::const_iterator &begin, const typename std::vector< T >::const_iterator &end)
void zero ()
void fill (const T &fillVal)
void fillWithByte (const int &fillByte)
bool validIndex (const size_t &index) const
bool operator== (const FLArray &fla) const
virtual const T & operator() (const size_t &index) const
virtual T & operator[] (const size_t &index) const
void copyTo (const T &elem, size_t index)
virtual void printNumbered (std::ostream &os=std::cout, unsigned startLabel=0) const
const size_t & size () const
bool empty () const
iterator begin () const
iterator end () const
Protected Attributes
size_t s
T * a
Detailed Description
template<typename T>
class cbrc::FLArray< T >
Definition at line 39 of file FLArray.hh.
Member Typedef Documentation
const_iterator
template<typename T > typedef const T* cbrc::FLArray< T >::const_iterator
Definition at line 42 of file FLArray.hh.
iterator
template<typename T > typedef T* cbrc::FLArray< T >::iterator
Definition at line 41 of file FLArray.hh.
Constructor & Destructor Documentation
FLArray() [1/7]
template<typename T > cbrc::FLArray< T >::FLArray () inline
Definition at line 45 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::s.
FLArray() [2/7]
template<typename T > cbrc::FLArray< T >::FLArray (const size_t & sz) inline explicit
Definition at line 47 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::size().
FLArray() [3/7]
template<typename T > cbrc::FLArray< T >::FLArray (const size_t & sz, const T & fillVal) inline
Definition at line 51 of file FLArray.hh.
References cbrc::FLArray< T >::a, cbrc::FLArray< T >::fill(), and cbrc::FLArray< T >::size().
FLArray() [4/7]
template<typename T > cbrc::FLArray< T >::FLArray (const size_t & sz, const T *& b) inline
Definition at line 56 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::size().
FLArray() [5/7]
template<typename T > cbrc::FLArray< T >::FLArray (const std::vector< T > & v) inline
Definition at line 61 of file FLArray.hh.
References cbrc::FLArray< T >::a, cbrc::FLArray< T >::s, cbrc::FLArray< T >::size(), and cbrc::FLEArray< T >::size().
FLArray() [6/7]
template<typename T > cbrc::FLArray< T >::FLArray (const std::string & v) inline
Definition at line 67 of file FLArray.hh.
References cbrc::FLArray< T >::a, cbrc::FLArray< T >::s, cbrc::FLArray< T >::size(), and cbrc::FLEArray< T >::size().
FLArray() [7/7]
template<typename T > cbrc::FLArray< T >::FLArray (const FLArray< T > & fla) inline
Definition at line 73 of file FLArray.hh.
References cbrc::FLArray< T >::assign(), cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
~FLArray()
template<typename T > virtual cbrc::FLArray< T >::~FLArray () inline virtual
Definition at line 77 of file FLArray.hh.
References cbrc::FLArray< T >::a.
Member Function Documentation
assign() [1/2]
template<typename T > void cbrc::FLArray< T >::assign (const typename FLArray< T >::const_iterator & begin, const typename FLArray< T >::const_iterator & end) inline
Definition at line 110 of file FLArray.hh.
References cbrc::FLArray< T >::a, cbrc::FLArray< T >::begin(), cbrc::FLArray< T >::end(), and cbrc::FLArray< T >::resize().
Referenced by cbrc::FLArray< T >::FLArray(), cbrc::FLArray< T >::operator=(), cbrc::FLNumArray< T >::operator=(), and cbrc::FLArray< T >::operator=().
assign() [2/2]
template<typename T > void cbrc::FLArray< T >::assign (const typename std::vector< T >::const_iterator & begin, const typename std::vector< T >::const_iterator & end) inline
Definition at line 119 of file FLArray.hh.
References cbrc::FLArray< T >::a, cbrc::FLArray< T >::begin(), cbrc::FLArray< T >::end(), and cbrc::FLArray< T >::resize().
begin()
template<typename T > iterator cbrc::FLArray< T >::begin () const inline
Definition at line 177 of file FLArray.hh.
References cbrc::FLArray< T >::a.
Referenced by cbrc::FLArray< T >::assign(), cbrc::FLArray< T >::assign(), cbrc::FLStack< elemType >::begin(), cbrc::FLStack< elemType >::end(), and cbrc::FLArray< cbrc::FLSorted< T1 > >::operator std::vector< cbrc::FLSorted< T1 > >().
copyTo()
template<typename T > void cbrc::FLArray< T >::copyTo (const T & elem, size_t index) inline
Definition at line 162 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::validIndex().
empty()
template<typename T > bool cbrc::FLArray< T >::empty () const inline
Definition at line 176 of file FLArray.hh.
References cbrc::FLArray< T >::s.
end()
template<typename T > iterator cbrc::FLArray< T >::end () const inline
Definition at line 178 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::s.
Referenced by cbrc::FLArray< T >::assign(), cbrc::FLArray< T >::assign(), and cbrc::FLArray< cbrc::FLSorted< T1 > >::operator std::vector< cbrc::FLSorted< T1 > >().
fill()
template<typename T > void cbrc::FLArray< T >::fill (const T & fillVal) inline
Definition at line 129 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::s.
Referenced by cbrc::FLArray< T >::FLArray(), and cbrc::FLArray< T >::zero().
fillWithByte()
template<typename T > void cbrc::FLArray< T >::fillWithByte (const int & fillByte) inline
Definition at line 132 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::s.
operator std::vector< T >()
template<typename T > cbrc::FLArray< T >::operator std::vector< T > () const inline
Definition at line 79 of file FLArray.hh.
operator()()
template<typename T > virtual const T & cbrc::FLArray< T >::operator() (const size_t & index) const inline virtual
Definition at line 152 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::validIndex().
operator=() [1/2]
template<typename T > FLArray cbrc::FLArray< T >::operator= (const FLArray< T > & fla) inline
Definition at line 102 of file FLArray.hh.
References cbrc::FLArray< T >::assign(), cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
operator=() [2/2]
template<typename T > FLArray cbrc::FLArray< T >::operator= (std::vector< T > v) inline
Definition at line 106 of file FLArray.hh.
References cbrc::FLArray< T >::assign().
operator==()
template<typename T > bool cbrc::FLArray< T >::operator== (const FLArray< T > & fla) const inline
Definition at line 147 of file FLArray.hh.
References cbrc::FLArray< T >::a, cbrc::FLEArray< T >::a, cbrc::FLArray< T >::size(), and cbrc::FLEArray< T >::size().
operator[]()
template<typename T > virtual T & cbrc::FLArray< T >::operator[] (const size_t & index) const inline virtual
Definition at line 157 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::validIndex().
printNumbered()
template<typename T > virtual void cbrc::FLArray< T >::printNumbered (std::ostream & os = std::cout, unsigned startLabel = 0) const inline virtual
Definition at line 167 of file FLArray.hh.
References cbrc::FLArray< T >::a, and cbrc::FLArray< T >::size().
resize()
template<typename T > void cbrc::FLArray< T >::resize (size_t sz) inline
Definition at line 89 of file FLArray.hh.
References cbrc::FLArray< T >::a, cbrc::FLArray< T >::s, and cbrc::FLArray< T >::setSize().
Referenced by cbrc::FLArray< T >::assign(), and cbrc::FLArray< T >::assign().
setSize()
template<typename T > void cbrc::FLArray< T >::setSize (size_t sz) inline
Definition at line 84 of file FLArray.hh.
References cbrc::FLArray< T >::a, cbrc::FLArray< T >::s, and cbrc::FLArray< T >::size().
Referenced by cbrc::FLStack< elemType >::FLStack(), cbrc::LogFactorial::LogFactorial(), cbrc::FLArray< T >::resize(), and cbrc::FLStack< elemType >::setCapacity().
size()
template<typename T > const size_t & cbrc::FLArray< T >::size () const inline
Definition at line 175 of file FLArray.hh.
References cbrc::FLArray< T >::s.
Referenced by cbrc::FLStack< elemType >::capacity(), cbrc::FLArray< T >::FLArray(), cbrc::FLArray< T >::FLArray(), cbrc::FLArray< T >::FLArray(), cbrc::FLArray< T >::FLArray(), cbrc::FLArray< T >::FLArray(), cbrc::FLNumArray< T >::max(), cbrc::FLNumArray< T >::maxIndex(), cbrc::FLArray< cbrc::FLSorted< T1 > >::operator std::vector< cbrc::FLSorted< T1 > >(), cbrc::FLNumArray< T >::operator*=(), cbrc::FLNumArray< T >::operator/=(), cbrc::FLArray< T >::operator==(), cbrc::FLArray< T >::printNumbered(), cbrc::FLArray< T >::setSize(), cbrc::LogFactorial::size(), cbrc::FLNumArray< T >::squareElements(), and cbrc::FLNumArray< T >::sum().
validIndex()
template<typename T > bool cbrc::FLArray< T >::validIndex (const size_t & index) const inline
Definition at line 135 of file FLArray.hh.
References cbrc::FLArray< T >::s.
Referenced by cbrc::FLArray< T >::copyTo(), cbrc::FLArray< T >::operator()(), and cbrc::FLArray< T >::operator[]().
zero()
template<typename T > void cbrc::FLArray< T >::zero () inline
Definition at line 128 of file FLArray.hh.
References cbrc::FLArray< T >::fill().
Member Data Documentation
a
template<typename T > T* cbrc::FLArray< T >::a protected
Definition at line 183 of file FLArray.hh.
Referenced by cbrc::FLArray< T >::assign(), cbrc::FLArray< T >::assign(), cbrc::FLArray< T >::begin(), cbrc::FLArray< T >::copyTo(), cbrc::FLArray< T >::end(), cbrc::FLArray< T >::fill(), cbrc::FLArray< T >::fillWithByte(), cbrc::FLArray< T >::FLArray(), cbrc::FLArray< T >::FLArray(), cbrc::FLArray< T >::FLArray(), cbrc::FLArray< T >::FLArray(), cbrc::FLArray< T >::FLArray(), cbrc::FLArray< T >::FLArray(), cbrc::FLNumArray< T >::max(), cbrc::FLNumArray< T >::maxIndex(), cbrc::FLArray< T >::operator()(), cbrc::FLNumArray< T >::operator*=(), cbrc::FLNumArray< T >::operator/=(), cbrc::FLArray< T >::operator==(), cbrc::FLArray< T >::operator[](), cbrc::FLArrayFast< T >::operator[](), cbrc::FLNumArrayFast< T >::operator[](), cbrc::FLArray< T >::printNumbered(), cbrc::FLArray< T >::resize(), cbrc::FLArray< T >::setSize(), cbrc::FLNumArray< T >::squareElements(), cbrc::FLNumArray< T >::sum(), and cbrc::FLArray< T >::~FLArray().
s
template<typename T > size_t cbrc::FLArray< T >::s protected
Definition at line 182 of file FLArray.hh.
Referenced by cbrc::FLArray< T >::empty(), cbrc::FLArray< T >::end(), cbrc::FLArray< T >::fill(), cbrc::FLArray< T >::fillWithByte(), cbrc::FLArray< T >::FLArray(), cbrc::FLArray< T >::FLArray(), cbrc::FLArray< T >::FLArray(), cbrc::FLArray< T >::resize(), cbrc::FLArray< T >::setSize(), cbrc::FLArray< T >::size(), and cbrc::FLArray< T >::validIndex().
The documentation for this class was generated from the following file:
ematch_src/utils/FLArray/FLArray.hh