NGSFeatures: ematch_src/utils/sequence/align/run/clusterByIdentity.cc File Reference
clusterByIdentity.cc File Reference
#include <iostream>
#include "boost/foreach.hpp"
#include "utils/argvParsing/ArgvParser.hh"
#include "utils/sequence/readers/fasta/FastaSeqSlurper.hh"
#include "utils/graph/ConnectedComponentOnlineComputer.hh"
#include "utils/FLArray/FLEArrayByIndexSortingPredicate.hh"
#include "../SeqGlobalAffineAligner.hh"
#include "../AminoScoreIdentity.hh"
Classes
struct argsT
Namespaces
namespace cbrc
Macros
#define IDENTITY_FLAGS -i|--identity
#define ADJUSTMENT_FLAGS -a|--adjustment-factor
Functions
void cbrc::clusterByIdentity ()
int main (int argc, const char *argv[])
Variables
static struct argsT args
Macro Definition Documentation
ADJUSTMENT_FLAGS
#define ADJUSTMENT_FLAGS -a|--adjustment-factor
Definition at line 22 of file clusterByIdentity.cc.
IDENTITY_FLAGS
#define IDENTITY_FLAGS -i|--identity
Definition at line 21 of file clusterByIdentity.cc.
Function Documentation
main()
int main (int argc, const char * argv[])
Definition at line 157 of file clusterByIdentity.cc.
References ADJUSTMENT_FLAGS, args, cbrc::clusterByIdentity(), cbrc::ArgvParser::die(), cbrc::ArgvParser::dieIfUnusedArgs(), argsT::fastaIstreamPtr, cbrc::ArgvParser::getIstreamPtr(), IDENTITY_FLAGS, argsT::identityThreshold, argsT::lengthAdjustmentFactor, cbrc::ArgvParser::printDoc(), Q, cbrc::ArgvParser::set(), cbrc::ArgvParser::setDoc(), and cbrc::ArgvParser::setOrDie().
Variable Documentation
args
struct argsT args static
Referenced by cbrc::clusterByIdentity(), cbrc::computeAllPairsIdentity(), cbrc::fastaGrepName(), cbrc::fastaHeadBytes(), cbrc::fastaHeadRecords(), cbrc::fastaPrintDuplicateSeqs2Streams(), cbrc::fastaTailBytes(), main(), main(), cbrc::sortFastaByLength(), cbrc::sprotGrepOC(), and cbrc::sprotToFasta().