NGSFeatures: ematch_src/dumpRecountNeighborProbGraphOnDisk_ConnectedComponentSize.cc File Reference
dumpRecountNeighborProbGraphOnDisk_ConnectedComponentSize.cc File Reference
#include <iostream>
#include "utils/argvParsing/ArgvParser.hh"
#include "./RecountNeighborProbGraphOnDisk.hh"
#include "./graph/ConnectedComponentOnlineComputer.hh"
Namespaces
namespace cbrc
Functions
void cbrc::dumpNeighborList (const TagSet &tagID_to_seq, const RecountNeighborList neighborList)
void cbrc::dumpRecountNeighborProbGraphOnDisk ()
int main (int argc, const char *argv[])
Variables
static std::ifstream arg_tagSeqs_ifstream
static std::ifstream arg_neighborsProbGraphOnDisk_ifstream
Function Documentation
main()
int main (int argc, const char * argv[])
Definition at line 102 of file dumpRecountNeighborProbGraphOnDisk_ConnectedComponentSize.cc.
References arg_neighborsProbGraphOnDisk_ifstream, arg_tagSeqs_ifstream, cbrc::ArgvParser::dieIfUnusedArgs(), cbrc::dumpRecountNeighborProbGraphOnDisk(), and cbrc::ArgvParser::setOrDie().
Variable Documentation
arg_neighborsProbGraphOnDisk_ifstream
std::ifstream arg_neighborsProbGraphOnDisk_ifstream static
Definition at line 17 of file dumpRecountNeighborProbGraphOnDisk_ConnectedComponentSize.cc.
Referenced by main().
arg_tagSeqs_ifstream
std::ifstream arg_tagSeqs_ifstream static
Definition at line 16 of file dumpRecountNeighborProbGraphOnDisk_ConnectedComponentSize.cc.
Referenced by main().