NGSFeatures: ematch_src/utils/perlish/getline.hh File Reference
getline.hh File Reference
#include <sys/types.h>
#include <utime.h>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
Macros
#define EXPAND_CHUNK 16
Functions
ssize_t getline (char **lineptr, size_t *n, FILE *stream)
Macro Definition Documentation
EXPAND_CHUNK
#define EXPAND_CHUNK 16
Function Documentation
getline()
ssize_t getline (char ** lineptr, size_t * n, FILE * stream) inline
Definition at line 17 of file getline.hh.
Referenced by main(), number_of_lines(), and cbrc::perlish::slurpLine().