NGSFeatures: src/EstimateTrueCount_EntropyFast.cc File Reference
EstimateTrueCount_EntropyFast.cc File Reference
#include "Utilities.hh"
#include <iostream>
#include <vector>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <map>
#include <algorithm>
#include <cmath>
#include <ctime>
#include <numeric>
#include <iomanip>
#include <stdio.h>
Classes
struct sort_pred
struct sort_pred_double
struct strCmp
Functions
double h (double x)
vector< double > h_alloc (std::vector< double > &x_vect)
double der_h (double x)
double compute_sum (std::vector< double > &x_vect)
double compute_sum_hx_vect (std::vector< double > &x_vect)
double compute_dot (std::vector< double > &x_vect, std::vector< double > &y_vect)
int make_proba (std::vector< double > &x_vect, std::vector< double > &res_vect)
vector< double > make_proba_alloc (std::vector< double > &x_vect)
int copy_vect (std::vector< double > &x_vect, std::vector< double > &res_vect)
vector< double > alloc_vect (int nx)
double f (std::vector< double > &x_vect, std::vector< double > &m_vect)
double ent (std::vector< double > &x_vect)
double der_f_k (std::vector< double > &x_vect, std::vector< double > &m_vect, int kk)
double der_ent_k (std::vector< double > &x_vect, int kk)
double final_f (std::vector< double > &x_vect, std::vector< double > &m_vect, double gamma)
int final_der (std::vector< double > &x_vect, std::vector< double > &m_vect, double gamma, std::vector< double > &res_vect)
double backtrackingLineSearch (std::vector< double > &x_vect, std::vector< double > &m_vect, std::vector< double > &der_vect, double new_fx, double gamma)
vector< double > gradient_descent (std::vector< double > &m_vect, double gamma)
vector< double > wrap_gradient_descent (std::vector< double > &m_vect, double gamma)
string ConvertInt2String (int IntVal)
string ConvertDouble2String (double DblVal)
double computeLogLik (std::vector< double > &m, std::vector< double > &p, double &lmbd)
vector< double > multiplyVecWithVecCorsp (std::vector< double > &Vec1, std::vector< double > &Vec2)
vector< double > divideVecWithVecCorsp (std::vector< double > &Vec1, std::vector< double > &Vec2)
vector< double > divideVecWithScalar (std::vector< double > &Vec, double &theC)
vector< double > sparseM_vec_prod (vector< double > &p, std::vector< int > &rowId, std::vector< int > &colId, std::vector< double > &realVal)
double getMainTagPropInit (std::vector< double > &arg)
double getMainTagPropMeanScaled (std::vector< double > &arg)
vector< pair< int, int > > getIndexFromVector (std::vector< string > &nbNt, std::vector< string > &arg)
vector< pair< int, int > > getIndexFromMap (std::vector< string > &nbNt, std::map< string, int > &m)
vector< double > getPropSum (std::vector< string > &neigb, map< string, double > &m)
vector< double > getNumTagProp (std::vector< string > &neigb, map< string, double > &m)
int main (int arg_count, char *arg_vec[])
Function Documentation
alloc_vect()
vector< double > alloc_vect (int nx)
Definition at line 167 of file EstimateTrueCount_EntropyFast.cc.
Referenced by backtrackingLineSearch(), and gradient_descent().
backtrackingLineSearch()
double backtrackingLineSearch (std::vector< double > & x_vect, std::vector< double > & m_vect, std::vector< double > & der_vect, double new_fx, double gamma)
Definition at line 337 of file EstimateTrueCount_EntropyFast.cc.
References alloc_vect(), compute_dot(), and final_f().
Referenced by gradient_descent().
compute_dot()
double compute_dot (std::vector< double > & x_vect, std::vector< double > & y_vect)
Definition at line 98 of file EstimateTrueCount_EntropyFast.cc.
Referenced by backtrackingLineSearch().
compute_sum()
double compute_sum (std::vector< double > & x_vect)
Definition at line 63 of file EstimateTrueCount_EntropyFast.cc.
Referenced by make_proba(), and make_proba_alloc().
compute_sum_hx_vect()
double compute_sum_hx_vect (std::vector< double > & x_vect)
Definition at line 80 of file EstimateTrueCount_EntropyFast.cc.
References h().
Referenced by der_ent_k(), der_f_k(), ent(), and f().
computeLogLik()
double computeLogLik (std::vector< double > & m, std::vector< double > & p, double & lmbd)
Definition at line 522 of file EstimateTrueCount_EntropyFast.cc.
Referenced by main().
ConvertDouble2String()
string ConvertDouble2String (double DblVal)
Definition at line 511 of file EstimateTrueCount_EntropyFast.cc.
ConvertInt2String()
string ConvertInt2String (int IntVal)
Definition at line 500 of file EstimateTrueCount_EntropyFast.cc.
copy_vect()
int copy_vect (std::vector< double > & x_vect, std::vector< double > & res_vect)
Definition at line 152 of file EstimateTrueCount_EntropyFast.cc.
Referenced by gradient_descent().
der_ent_k()
double der_ent_k (std::vector< double > & x_vect, int kk)
Definition at line 275 of file EstimateTrueCount_EntropyFast.cc.
References compute_sum_hx_vect(), der_h(), and h().
Referenced by final_der().
der_f_k()
double der_f_k (std::vector< double > & x_vect, std::vector< double > & m_vect, int kk)
Definition at line 249 of file EstimateTrueCount_EntropyFast.cc.
References compute_sum_hx_vect(), der_h(), and h().
Referenced by final_der().
der_h()
double der_h (double x)
Definition at line 47 of file EstimateTrueCount_EntropyFast.cc.
Referenced by der_ent_k(), and der_f_k().
divideVecWithScalar()
vector< double > divideVecWithScalar (std::vector< double > & Vec, double & theC)
Definition at line 559 of file EstimateTrueCount_EntropyFast.cc.
Referenced by main().
divideVecWithVecCorsp()
vector< double > divideVecWithVecCorsp (std::vector< double > & Vec1, std::vector< double > & Vec2)
Definition at line 547 of file EstimateTrueCount_EntropyFast.cc.
Referenced by main().
ent()
double ent (std::vector< double > & x_vect)
Definition at line 217 of file EstimateTrueCount_EntropyFast.cc.
References compute_sum_hx_vect(), and h().
Referenced by final_f().
f()
double f (std::vector< double > & x_vect, std::vector< double > & m_vect)
Definition at line 192 of file EstimateTrueCount_EntropyFast.cc.
References compute_sum_hx_vect(), and h().
Referenced by final_f(), cbrc::Blast8Result::setFields(), and testLogFactorial().
final_der()
int final_der (std::vector< double > & x_vect, std::vector< double > & m_vect, double gamma, std::vector< double > & res_vect)
Definition at line 314 of file EstimateTrueCount_EntropyFast.cc.
References der_ent_k(), and der_f_k().
Referenced by gradient_descent().
final_f()
double final_f (std::vector< double > & x_vect, std::vector< double > & m_vect, double gamma)
Definition at line 307 of file EstimateTrueCount_EntropyFast.cc.
References ent(), and f().
Referenced by backtrackingLineSearch(), gradient_descent(), and wrap_gradient_descent().
getIndexFromMap()
vector< pair< int, int > > getIndexFromMap (std::vector< string > & nbNt, std::map< string, int > & m)
Definition at line 637 of file EstimateTrueCount_EntropyFast.cc.
Referenced by main().
getIndexFromVector()
vector< pair< int, int > > getIndexFromVector (std::vector< string > & nbNt, std::vector< string > & arg)
Definition at line 612 of file EstimateTrueCount_EntropyFast.cc.
getMainTagPropInit()
double getMainTagPropInit (std::vector< double > & arg)
Definition at line 589 of file EstimateTrueCount_EntropyFast.cc.
Referenced by main().
getMainTagPropMeanScaled()
double getMainTagPropMeanScaled (std::vector< double > & arg)
Definition at line 600 of file EstimateTrueCount_EntropyFast.cc.
Referenced by main().
getNumTagProp()
vector< double > getNumTagProp (std::vector< string > & neigb, map< string, double > & m)
Definition at line 691 of file EstimateTrueCount_EntropyFast.cc.
Referenced by main().
getPropSum()
vector< double > getPropSum (std::vector< string > & neigb, map< string, double > & m)
Definition at line 656 of file EstimateTrueCount_EntropyFast.cc.
Referenced by main().
gradient_descent()
vector< double > gradient_descent (std::vector< double > & m_vect, double gamma)
Definition at line 388 of file EstimateTrueCount_EntropyFast.cc.
References alloc_vect(), backtrackingLineSearch(), copy_vect(), final_der(), and final_f().
Referenced by wrap_gradient_descent().
h()
double h (double x)
Definition at line 28 of file EstimateTrueCount_EntropyFast.cc.
Referenced by cbrc::betacf(), cbrc::betacf(), cbrc::betacf(), compute_sum_hx_vect(), der_ent_k(), der_f_k(), ent(), f(), and h_alloc().
h_alloc()
vector< double > h_alloc (std::vector< double > & x_vect)
Definition at line 33 of file EstimateTrueCount_EntropyFast.cc.
References h().
Referenced by wrap_gradient_descent().
main()
int main (int arg_count, char * arg_vec[])
Definition at line 755 of file EstimateTrueCount_EntropyFast.cc.
References computeLogLik(), divideVecWithScalar(), divideVecWithVecCorsp(), GetBaseNameFromFilename(), getIndexFromMap(), getline(), getMainTagPropInit(), getMainTagPropMeanScaled(), getNumTagProp(), GetPathNameFromFilename(), getPropSum(), isnan(), multiplyVecWithVecCorsp(), sparseM_vec_prod(), and wrap_gradient_descent().
make_proba()
int make_proba (std::vector< double > & x_vect, std::vector< double > & res_vect)
Definition at line 116 of file EstimateTrueCount_EntropyFast.cc.
References compute_sum().
make_proba_alloc()
vector< double > make_proba_alloc (std::vector< double > & x_vect)
Definition at line 133 of file EstimateTrueCount_EntropyFast.cc.
References compute_sum().
Referenced by wrap_gradient_descent().
multiplyVecWithVecCorsp()
vector< double > multiplyVecWithVecCorsp (std::vector< double > & Vec1, std::vector< double > & Vec2)
Definition at line 536 of file EstimateTrueCount_EntropyFast.cc.
Referenced by main().
sparseM_vec_prod()
vector< double > sparseM_vec_prod (vector< double > & p, std::vector< int > & rowId, std::vector< int > & colId, std::vector< double > & realVal)
Definition at line 571 of file EstimateTrueCount_EntropyFast.cc.
Referenced by main().
wrap_gradient_descent()
vector< double > wrap_gradient_descent (std::vector< double > & m_vect, double gamma)
Definition at line 462 of file EstimateTrueCount_EntropyFast.cc.
References final_f(), gradient_descent(), h_alloc(), and make_proba_alloc().
Referenced by main().