NGSFeatures: src/EstimateTrueCount.cc File Reference
EstimateTrueCount.cc File Reference
#include "Utilities.hh"
#include <algorithm>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <numeric>
#include <sstream>
#include <string>
#include <vector>
#include <cmath>
#include <cstdlib>
#include <cstring>
Classes
struct sort_pred
struct sort_pred_double
struct strCmp
Functions
double computeLogLik (const std::vector< double > &m, const std::vector< double > &p, const double &lmbd)
vector< double > multiplyVecWithVecCorsp (const std::vector< double > &Vec1, const std::vector< double > &Vec2)
vector< double > divideVecWithVecCorsp (const std::vector< double > &Vec1, const std::vector< double > &Vec2)
vector< double > divideVecWithScalar (const std::vector< double > &Vec, const double &theC)
vector< double > sparseM_vec_prod (const vector< double > &p, const std::vector< int > &rowId, const std::vector< int > &colId, const std::vector< double > &realVal)
double getMainTagPropInit (const std::vector< double > &arg)
double getMainTagPropMeanScaled (const std::vector< double > &arg)
vector< pair< int, int > > getIndexFromVector (std::vector< string > &nbNt, std::vector< string > &arg)
vector< pair< int, int > > getIndexFromMap (const std::vector< string > &nbNt, const std::map< string, int > &m)
vector< double > getPropSum (const std::vector< string > &neigb, const map< string, double > &m)
vector< double > getNumTagProp (const std::vector< string > &neigb, const map< string, double > &m)
int main (int arg_count, char *arg_vec[])
Function Documentation
computeLogLik()
double computeLogLik (const std::vector< double > & m, const std::vector< double > & p, const double & lmbd)
Definition at line 26 of file EstimateTrueCount.cc.
Referenced by main().
divideVecWithScalar()
vector< double > divideVecWithScalar (const std::vector< double > & Vec, const double & theC)
Definition at line 63 of file EstimateTrueCount.cc.
Referenced by main().
divideVecWithVecCorsp()
vector< double > divideVecWithVecCorsp (const std::vector< double > & Vec1, const std::vector< double > & Vec2)
Definition at line 50 of file EstimateTrueCount.cc.
Referenced by main().
getIndexFromMap()
vector< pair< int, int > > getIndexFromMap (const std::vector< string > & nbNt, const std::map< string, int > & m)
Definition at line 132 of file EstimateTrueCount.cc.
Referenced by main().
getIndexFromVector()
vector< pair< int, int > > getIndexFromVector (std::vector< string > & nbNt, std::vector< string > & arg)
Definition at line 111 of file EstimateTrueCount.cc.
getMainTagPropInit()
double getMainTagPropInit (const std::vector< double > & arg)
Definition at line 89 of file EstimateTrueCount.cc.
Referenced by main().
getMainTagPropMeanScaled()
double getMainTagPropMeanScaled (const std::vector< double > & arg)
Definition at line 100 of file EstimateTrueCount.cc.
Referenced by main().
getNumTagProp()
vector< double > getNumTagProp (const std::vector< string > & neigb, const map< string, double > & m)
Definition at line 180 of file EstimateTrueCount.cc.
Referenced by main().
getPropSum()
vector< double > getPropSum (const std::vector< string > & neigb, const map< string, double > & m)
Definition at line 151 of file EstimateTrueCount.cc.
Referenced by main().
main()
int main (int arg_count, char * arg_vec[])
Definition at line 228 of file EstimateTrueCount.cc.
References computeLogLik(), divideVecWithScalar(), divideVecWithVecCorsp(), GetBaseNameFromFilename(), getIndexFromMap(), getline(), getMainTagPropInit(), getMainTagPropMeanScaled(), getNumTagProp(), GetPathNameFromFilename(), getPropSum(), isnan(), multiplyVecWithVecCorsp(), and sparseM_vec_prod().
multiplyVecWithVecCorsp()
vector< double > multiplyVecWithVecCorsp (const std::vector< double > & Vec1, const std::vector< double > & Vec2)
Definition at line 37 of file EstimateTrueCount.cc.
Referenced by main().
sparseM_vec_prod()
vector< double > sparseM_vec_prod (const vector< double > & p, const std::vector< int > & rowId, const std::vector< int > & colId, const std::vector< double > & realVal)
Definition at line 76 of file EstimateTrueCount.cc.
Referenced by main().