NGSFeatures: src/EstimateTrueCount_Capacity.cc File Reference
EstimateTrueCount_Capacity.cc File Reference
#include "Utilities.hh"
#include <iostream>
#include <vector>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <map>
#include <algorithm>
#include <cmath>
#include <ctime>
#include <numeric>
#include <iomanip>
Classes
struct sort_pred
struct sort_pred_double
struct strCmp
Functions
double computeLogLik (std::vector< double > &m, std::vector< double > &p, double &lmbd)
vector< double > multiplyVecWithVecCorsp (std::vector< double > &Vec1, std::vector< double > &Vec2)
vector< double > divideVecWithVecCorsp (std::vector< double > &Vec1, std::vector< double > &Vec2)
vector< double > divideVecWithScalar (std::vector< double > &Vec, double &theC)
vector< double > sparseM_vec_prod (vector< double > &p, std::vector< int > &rowId, std::vector< int > &colId, std::vector< double > &realVal)
double getMainTagPropInit (std::vector< double > &arg)
double getMainTagPropMeanScaled (std::vector< double > &arg)
vector< pair< int, int > > getIndexFromVector (std::vector< string > &nbNt, std::vector< string > &arg)
vector< pair< int, int > > getIndexFromMap (std::vector< string > &nbNt, std::map< string, int > &m)
vector< double > getPropSum (std::vector< string > &neigb, map< string, double > &m)
vector< double > getNumTagProp (std::vector< string > &neigb, map< string, double > &m)
int main (int arg_count, char *arg_vec[])
Function Documentation
computeLogLik()
double computeLogLik (std::vector< double > & m, std::vector< double > & p, double & lmbd)
Definition at line 26 of file EstimateTrueCount_Capacity.cc.
Referenced by main().
divideVecWithScalar()
vector< double > divideVecWithScalar (std::vector< double > & Vec, double & theC)
Definition at line 60 of file EstimateTrueCount_Capacity.cc.
Referenced by main().
divideVecWithVecCorsp()
vector< double > divideVecWithVecCorsp (std::vector< double > & Vec1, std::vector< double > & Vec2)
Definition at line 48 of file EstimateTrueCount_Capacity.cc.
Referenced by main().
getIndexFromMap()
vector< pair< int, int > > getIndexFromMap (std::vector< string > & nbNt, std::map< string, int > & m)
Definition at line 138 of file EstimateTrueCount_Capacity.cc.
Referenced by main().
getIndexFromVector()
vector< pair< int, int > > getIndexFromVector (std::vector< string > & nbNt, std::vector< string > & arg)
Definition at line 113 of file EstimateTrueCount_Capacity.cc.
getMainTagPropInit()
double getMainTagPropInit (std::vector< double > & arg)
Definition at line 90 of file EstimateTrueCount_Capacity.cc.
Referenced by main().
getMainTagPropMeanScaled()
double getMainTagPropMeanScaled (std::vector< double > & arg)
Definition at line 101 of file EstimateTrueCount_Capacity.cc.
Referenced by main().
getNumTagProp()
vector< double > getNumTagProp (std::vector< string > & neigb, map< string, double > & m)
Definition at line 192 of file EstimateTrueCount_Capacity.cc.
Referenced by main().
getPropSum()
vector< double > getPropSum (std::vector< string > & neigb, map< string, double > & m)
Definition at line 157 of file EstimateTrueCount_Capacity.cc.
Referenced by main().
main()
int main (int arg_count, char * arg_vec[])
Definition at line 256 of file EstimateTrueCount_Capacity.cc.
References computeLogLik(), divideVecWithScalar(), divideVecWithVecCorsp(), GetBaseNameFromFilename(), getIndexFromMap(), getline(), getMainTagPropInit(), getMainTagPropMeanScaled(), getNumTagProp(), GetPathNameFromFilename(), getPropSum(), isnan(), multiplyVecWithVecCorsp(), and sparseM_vec_prod().
multiplyVecWithVecCorsp()
vector< double > multiplyVecWithVecCorsp (std::vector< double > & Vec1, std::vector< double > & Vec2)
Definition at line 37 of file EstimateTrueCount_Capacity.cc.
Referenced by main().
sparseM_vec_prod()
vector< double > sparseM_vec_prod (vector< double > & p, std::vector< int > & rowId, std::vector< int > & colId, std::vector< double > & realVal)
Definition at line 72 of file EstimateTrueCount_Capacity.cc.
Referenced by main().