NGSFeatures: ematch_src/utils/sequence/fastafmt/run/fastafmtCountRecordsAndBases.cc File Reference
fastafmtCountRecordsAndBases.cc File Reference
#include <iostream>
#include <utility>
#include "utils/perlish/perlish.hh"
#include "utils/argvParsing/ArgvParser.hh"
#include "../fastafmtConst.hh"
Typedefs
typedef std::pair< unsigned int, unsigned int > baseAndRecordCountPairT
Functions
baseAndRecordCountPairT fastafmtCountRecordsAndBases (std::istream &fastaInputStream, const char commentChar)
int main (int argc, const char *argv[])
Typedef Documentation
baseAndRecordCountPairT
typedef std::pair<unsigned int, unsigned int> baseAndRecordCountPairT
Definition at line 21 of file fastafmtCountRecordsAndBases.cc.
Function Documentation
fastafmtCountRecordsAndBases()
baseAndRecordCountPairT fastafmtCountRecordsAndBases (std::istream & fastaInputStream, const char commentChar)
Definition at line 24 of file fastafmtCountRecordsAndBases.cc.
References FASTAFMT_RECORD_MARKER_CHAR.
Referenced by main().
main()
int main (int argc, const char * argv[])
Definition at line 53 of file fastafmtCountRecordsAndBases.cc.
References args, FASTAFMT_RECORD_MARKER_CSTRING, fastafmtCountRecordsAndBases(), and cbrc::perlish::isDirectory().