NGSFeatures: ematch_src/FindNeighboursWithQualJuxt.cc File Reference
FindNeighboursWithQualJuxt.cc File Reference
#include <iostream>
#include <vector>
#include <fstream>
#include <sstream>
#include <map>
#include <cmath>
#include <cstdlib>
Functions
template<typename T >
void prn_vec_binos (const std::vector< T > &arg, ostream &fn, string sep="")
template<typename T >
void prn_vec_oneval (const std::vector< T > &arg, string sep="", unsigned lim=0)
template<typename T >
void prn_vec (const std::vector< T > &arg, string sep="")
std::string GetBaseNameFromFilename (const std::string &fileName)
Extract base filename from a full file path.
std::string GetPathNameFromFilename (const std::string &filename)
Extract directory path from a full file path.
double Solexa2Phred (double sQ)
string ConvertInt2String (int IntVal)
vector< int > MismatchPos (std::vector< int >STag, string Nb)
double MultiplyError (std::vector< double > &Qual, std::vector< int > &Pos)
vector< int > MismatchPosByVec (std::vector< int >STag, vector< int > Nb)
double normalizeQualByMismatches1Tag (std::vector< int > &SeedTag, std::vector< int > NbTags, std::vector< double > &qual)
vector< int > neighbors (vector< int > &arg, int posNo, int baseNo)
string Vec2Str (vector< int > NTg)
int main (int arg_count, char *arg_vec[])
Function Documentation
ConvertInt2String()
string ConvertInt2String (int IntVal)
Definition at line 70 of file FindNeighboursWithQualJuxt.cc.
Referenced by MismatchPos(), and Vec2Str().
GetBaseNameFromFilename()
std::string GetBaseNameFromFilename (const std::string & fileName)
Extract base filename from a full file path.
Removes the directory path and file extension, returning only the base name.
Parameters
fileName Full file path (e.g., "/path/to/file.txt")
Returns
Base filename without path or extension (e.g., "file")
Example:
std::string path = "/home/user/data/sequences.fastq";
std::string base = GetBaseNameFromFilename(path);
// base == "sequences"
Definition at line 43 of file FindNeighboursWithQualJuxt.cc.
Referenced by main().
GetPathNameFromFilename()
std::string GetPathNameFromFilename (const std::string & filename)
Extract directory path from a full file path.
Returns the directory portion of a file path, excluding the filename.
Parameters
filename Full file path (e.g., "/path/to/file.txt")
Returns
Directory path with trailing slash (e.g., "/path/to/")
Example:
std::string path = "/home/user/data/sequences.fastq";
std::string dir = GetPathNameFromFilename(path);
// dir == "/home/user/data/"
Definition at line 54 of file FindNeighboursWithQualJuxt.cc.
Referenced by main().
main()
int main (int arg_count, char * arg_vec[])
Definition at line 156 of file FindNeighboursWithQualJuxt.cc.
References GetBaseNameFromFilename(), getline(), GetPathNameFromFilename(), neighbors(), and normalizeQualByMismatches1Tag().
MismatchPos()
vector< int > MismatchPos (std::vector< int > STag, string Nb)
Definition at line 79 of file FindNeighboursWithQualJuxt.cc.
References ConvertInt2String().
MismatchPosByVec()
vector< int > MismatchPosByVec (std::vector< int > STag, vector< int > Nb)
Definition at line 109 of file FindNeighboursWithQualJuxt.cc.
Referenced by normalizeQualByMismatches1Tag().
MultiplyError()
double MultiplyError (std::vector< double > & Qual, std::vector< int > & Pos)
Definition at line 96 of file FindNeighboursWithQualJuxt.cc.
References Solexa2Phred().
Referenced by normalizeQualByMismatches1Tag().
neighbors()
vector< int > neighbors (vector< int > & arg, int posNo, int baseNo)
Definition at line 133 of file FindNeighboursWithQualJuxt.cc.
Referenced by main().
normalizeQualByMismatches1Tag()
double normalizeQualByMismatches1Tag (std::vector< int > & SeedTag, std::vector< int > NbTags, std::vector< double > & qual)
Definition at line 126 of file FindNeighboursWithQualJuxt.cc.
References MismatchPosByVec(), and MultiplyError().
Referenced by main().
prn_vec()
template<typename T > void prn_vec (const std::vector< T > & arg, string sep = "")
Definition at line 35 of file FindNeighboursWithQualJuxt.cc.
prn_vec_binos()
template<typename T > void prn_vec_binos (const std::vector< T > & arg, ostream & fn, string sep = "")
Definition at line 15 of file FindNeighboursWithQualJuxt.cc.
prn_vec_oneval()
template<typename T > void prn_vec_oneval (const std::vector< T > & arg, string sep = "", unsigned lim = 0)
Definition at line 25 of file FindNeighboursWithQualJuxt.cc.
Solexa2Phred()
double Solexa2Phred (double sQ)
Definition at line 64 of file FindNeighboursWithQualJuxt.cc.
Referenced by MultiplyError().
Vec2Str()
string Vec2Str (vector< int > NTg)
Definition at line 145 of file FindNeighboursWithQualJuxt.cc.
References ConvertInt2String().