NGSFeatures: src/FindNeighboursWithQual.cc File Reference
FindNeighboursWithQual.cc File Reference
#include "Utilities.hh"
#include <iostream>
#include <vector>
#include <fstream>
#include <sstream>
#include <map>
#include <cmath>
#include <cstdlib>
Functions
double Solexa2Phred (double sQ)
string ConvertInt2String (int IntVal)
vector< int > MismatchPos (const std::vector< int > &STag, const string &Nb)
double MultiplyError (const std::vector< double > &Qual, const std::vector< int > &Pos)
vector< int > MismatchPosByVec (const std::vector< int > &STag, const vector< int > &Nb)
double normalizeQualByMismatches1Tag (const std::vector< int > &SeedTag, const std::vector< int > &NbTags, const std::vector< double > &qual)
vector< int > neighbors (const vector< int > &arg, int posNo, int baseNo)
string Vec2Str (const vector< int > &NTg)
int main (int arg_count, char *arg_vec[])
Function Documentation
ConvertInt2String()
string ConvertInt2String (int IntVal) inline
Definition at line 25 of file FindNeighboursWithQual.cc.
main()
int main (int arg_count, char * arg_vec[])
Definition at line 107 of file FindNeighboursWithQual.cc.
References GetBaseNameFromFilename(), getline(), GetPathNameFromFilename(), neighbors(), normalizeQualByMismatches1Tag(), and Vec2Str().
MismatchPos()
vector< int > MismatchPos (const std::vector< int > & STag, const string & Nb)
Definition at line 30 of file FindNeighboursWithQual.cc.
MismatchPosByVec()
vector< int > MismatchPosByVec (const std::vector< int > & STag, const vector< int > & Nb)
Definition at line 63 of file FindNeighboursWithQual.cc.
Referenced by normalizeQualByMismatches1Tag().
MultiplyError()
double MultiplyError (const std::vector< double > & Qual, const std::vector< int > & Pos)
Definition at line 48 of file FindNeighboursWithQual.cc.
References Solexa2Phred().
Referenced by normalizeQualByMismatches1Tag().
neighbors()
vector< int > neighbors (const vector< int > & arg, int posNo, int baseNo)
Definition at line 85 of file FindNeighboursWithQual.cc.
Referenced by main(), cbrc::MatrixGraph::printAdjacencyLists(), and cbrc::printCloseNeighbors().
normalizeQualByMismatches1Tag()
double normalizeQualByMismatches1Tag (const std::vector< int > & SeedTag, const std::vector< int > & NbTags, const std::vector< double > & qual)
Definition at line 77 of file FindNeighboursWithQual.cc.
References MismatchPosByVec(), and MultiplyError().
Referenced by main().
Solexa2Phred()
double Solexa2Phred (double sQ) inline
Definition at line 17 of file FindNeighboursWithQual.cc.
Referenced by MultiplyError().
Vec2Str()
string Vec2Str (const vector< int > & NTg)
Definition at line 94 of file FindNeighboursWithQual.cc.
Referenced by main().