NGSFeatures: src/GenerateProportion.cc File Reference
GenerateProportion.cc File Reference
#include "Utilities.hh"
#include <iostream>
#include <vector>
#include <fstream>
#include <sstream>
#include <cmath>
Functions
std::pair< int, int > number_of_lines (char *myfn)
int main (int arg_count, char *arg_vec[])
Function Documentation
main()
int main (int arg_count, char * arg_vec[])
Definition at line 44 of file GenerateProportion.cc.
References getline(), id2tagnum(), and number_of_lines().
number_of_lines()
std::pair< int, int > number_of_lines (char * myfn)
Definition at line 9 of file GenerateProportion.cc.
References getline().
Referenced by main().