NGSFeatures: ematch_src/utils/sequence/align/run/hasHighIdentityToDataset.cc File Reference
hasHighIdentityToDataset.cc File Reference
#include <iostream>
#include "utils/argvParsing/ArgvParser.hh"
#include "utils/FLArray/FLEArray.hh"
#include "utils/sequence/readers/fasta/FastaSeqSlurper.hh"
#include "../SeqGlobalAffineAligner.hh"
#include "../AminoScoreIdentity.hh"
Namespaces
namespace cbrc
Macros
#define ADJUSTMENT_FLAG -a|--adjustment-factor
#define IDENTITY_FLAG -i|--identity
#define OUTPUT_ALL_PAIRS_FLAG -o|--output-all-pairs
#define PROGRESS_TO_STDERR -p|--progress-to-stderr
#define USAGE "[-o] [-p] -i identityThreshold [-a lengthAdjustmentFactor] datasetFastafile queryFastaFile"
Functions
void cbrc::hasHighIdentityToDataset ()
int main (int argc, const char *argv[])
Variables
bool arg_outputAllPairs
bool arg_progressToStderr
double arg_identityThreshold
double arg_lengthAdjustmentFactor
std::istream * arg_fastaIstreamPtr1
std::istream * arg_fastaIstreamPtr2
Macro Definition Documentation
ADJUSTMENT_FLAG
#define ADJUSTMENT_FLAG -a|--adjustment-factor
Definition at line 19 of file hasHighIdentityToDataset.cc.
IDENTITY_FLAG
#define IDENTITY_FLAG -i|--identity
Definition at line 20 of file hasHighIdentityToDataset.cc.
OUTPUT_ALL_PAIRS_FLAG
#define OUTPUT_ALL_PAIRS_FLAG -o|--output-all-pairs
Definition at line 21 of file hasHighIdentityToDataset.cc.
PROGRESS_TO_STDERR
#define PROGRESS_TO_STDERR -p|--progress-to-stderr
Definition at line 22 of file hasHighIdentityToDataset.cc.
USAGE
#define USAGE "[-o] [-p] -i identityThreshold [-a lengthAdjustmentFactor] datasetFastafile queryFastaFile"
Definition at line 23 of file hasHighIdentityToDataset.cc.
Function Documentation
main()
int main (int argc, const char * argv[])
Definition at line 128 of file hasHighIdentityToDataset.cc.
References ADJUSTMENT_FLAG, arg_fastaIstreamPtr1, arg_fastaIstreamPtr2, arg_identityThreshold, arg_lengthAdjustmentFactor, arg_outputAllPairs, arg_progressToStderr, cbrc::ArgvParser::die(), cbrc::ArgvParser::dieIfUnusedArgs(), cbrc::ArgvParser::getIstreamPtr(), cbrc::ArgvParser::hasFlag(), cbrc::hasHighIdentityToDataset(), IDENTITY_FLAG, OUTPUT_ALL_PAIRS_FLAG, PROGRESS_TO_STDERR, Q, cbrc::ArgvParser::set(), cbrc::ArgvParser::setOrDie(), and USAGE.
Variable Documentation
arg_fastaIstreamPtr1
std::istream* arg_fastaIstreamPtr1
Definition at line 30 of file hasHighIdentityToDataset.cc.
Referenced by cbrc::hasHighIdentityToDataset(), and main().
arg_fastaIstreamPtr2
std::istream* arg_fastaIstreamPtr2
Definition at line 31 of file hasHighIdentityToDataset.cc.
Referenced by cbrc::hasHighIdentityToDataset(), and main().
arg_identityThreshold
double arg_identityThreshold
Definition at line 28 of file hasHighIdentityToDataset.cc.
Referenced by cbrc::hasHighIdentityToDataset(), and main().
arg_lengthAdjustmentFactor
double arg_lengthAdjustmentFactor
Definition at line 29 of file hasHighIdentityToDataset.cc.
Referenced by cbrc::hasHighIdentityToDataset(), and main().
arg_outputAllPairs
bool arg_outputAllPairs
Definition at line 26 of file hasHighIdentityToDataset.cc.
Referenced by cbrc::hasHighIdentityToDataset(), and main().
arg_progressToStderr
bool arg_progressToStderr
Definition at line 27 of file hasHighIdentityToDataset.cc.
Referenced by cbrc::hasHighIdentityToDataset(), and main().