NGSFeatures: cbrc::HammingDistanceComputer Namespace Reference
cbrc::HammingDistanceComputer Namespace Reference
Functions
size_t computeBounded (const LabeledSequence &seq0, const LabeledSequence &seq1, const double &threshold)
size_t computeBoundedGapAtEnd (const std::string &seq0, const std::string &seq1, const double &threshold)
size_t computeBoundedGapAtBeg (const LabeledSequence &seq0, const LabeledSequence &seq1, const double &threshold)
size_t computeBoundedGapAtBeg (const std::string &seq0, const std::string &seq1, const double &threshold)
Function Documentation
computeBounded()
size_t cbrc::HammingDistanceComputer::computeBounded (const LabeledSequence & seq0, const LabeledSequence & seq1, const double & threshold)
Definition at line 13 of file HammingDistanceComputer.cc.
References cbrc::FLEArray< T >::FLEArray().
Referenced by cbrc::allPairsHammingNeighbors(), and cbrc::SimilaritySearchableSequences::withinHammingDistance().
computeBoundedGapAtBeg() [1/2]
size_t cbrc::HammingDistanceComputer::computeBoundedGapAtBeg (const LabeledSequence & seq0, const LabeledSequence & seq1, const double & threshold)
Definition at line 80 of file HammingDistanceComputer.cc.
References cbrc::FLEArray< T >::constBegin(), cbrc::FLEArray< T >::constEnd(), cbrc::FLEArray< T >::FLEArray(), and GDB_ASSERTF.
computeBoundedGapAtBeg() [2/2]
size_t cbrc::HammingDistanceComputer::computeBoundedGapAtBeg (const std::string & seq0, const std::string & seq1, const double & threshold)
Definition at line 129 of file HammingDistanceComputer.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), cbrc::FLEArray< T >::FLEArray(), GDB_ASSERTF, and cbrc::FLEArray< T >::size().
computeBoundedGapAtEnd()
size_t cbrc::HammingDistanceComputer::computeBoundedGapAtEnd (const std::string & seq0, const std::string & seq1, const double & threshold)
Definition at line 47 of file HammingDistanceComputer.cc.
References cbrc::FLEArray< T >::FLEArray(), and cbrc::FLEArray< T >::size().