NGSFeatures: cbrc::htmlStrings Namespace Reference
cbrc::htmlStrings Namespace Reference
Functions
std::string equalWidthFontStyle (const unsigned int fontSize)
std::string tagString (const std::string &tagName, const std::string &contents, const std::string &tagExtraText)
std::string anchorHrefBasic (const std::string &nameBase, const std::string &contents, const std::string &nameExtension)
std::string header (const std::string &title)
std::string end ()
const std::string endQuote ("\"")
std::string anchorName (const std::string &name, const std::string &contents, const std::string &extraText="")
Function Documentation
anchorHrefBasic()
std::string cbrc::htmlStrings::anchorHrefBasic (const std::string & nameBase, const std::string & contents, const std::string & nameExtension)
Definition at line 54 of file htmlStrings.cc.
References anchorName(), endQuote(), cbrc::FLEArray< T >::size(), and tagString().
Referenced by cbrc::runAddAlignmentToHtml().
anchorName()
std::string cbrc::htmlStrings::anchorName (const std::string & name, const std::string & contents, const std::string & extraText = "") inline
Definition at line 29 of file htmlStrings.hh.
References endQuote(), and tagString().
Referenced by anchorHrefBasic(), and cbrc::runAddAlignmentToHtml().
end()
std::string cbrc::htmlStrings::end ()
Definition at line 66 of file htmlStrings.cc.
Referenced by cbrc::runAddAlignmentToHtml(), and cbrc::runAddIdenticalToHtml().
endQuote()
const std::string cbrc::htmlStrings::endQuote ("\"")
Referenced by anchorHrefBasic(), and anchorName().
equalWidthFontStyle()
std::string cbrc::htmlStrings::equalWidthFontStyle (const unsigned int fontSize)
Definition at line 23 of file htmlStrings.cc.
References cbrc::perlish::toString().
header()
std::string cbrc::htmlStrings::header (const std::string & title)
Definition at line 60 of file htmlStrings.cc.
References tagString().
Referenced by cbrc::runAddAlignmentToHtml(), and cbrc::runAddIdenticalToHtml().
tagString()
std::string cbrc::htmlStrings::tagString (const std::string & tagName, const std::string & contents, const std::string & tagExtraText)
Definition at line 43 of file htmlStrings.cc.
References cbrc::FLEArray< T >::size().
Referenced by anchorHrefBasic(), anchorName(), and header().