NGSFeatures: cbrc::stringBinaryIO Namespace Reference
cbrc::stringBinaryIO Namespace Reference
Functions
void read (std::string &s, std::istream &is)
void read (std::string &s, std::istream &is, const size_t &size)
void read (std::vector< std::string > &stringVector, std::istream &is)
void write (const std::string &s, std::ostream &os)
void writeContentsOnly (const std::string &s, std::ostream &os)
void write (const std::vector< std::string > &stringVector, std::ostream &os)
Function Documentation
read() [1/3]
void cbrc::stringBinaryIO::read (std::string & s, std::istream & is) inline
Definition at line 82 of file stringBinaryIO.hh.
References cbrc::perlish::die(), and read().
Referenced by cbrc::ResidueIndexedSequence::read(), cbrc::ResidueIndexMap::read(), cbrc::SerialNumbersForStrings< serialNumT >::read(), read(), and read().
read() [2/3]
void cbrc::stringBinaryIO::read (std::string & s, std::istream & is, const size_t & size) inline
Definition at line 103 of file stringBinaryIO.hh.
References cbrc::perlish::die().
read() [3/3]
void cbrc::stringBinaryIO::read (std::vector< std::string > & stringVector, std::istream & is) inline
Definition at line 61 of file stringBinaryIO.hh.
References cbrc::perlish::die(), and read().
write() [1/2]
void cbrc::stringBinaryIO::write (const std::string & s, std::ostream & os) inline
Definition at line 137 of file stringBinaryIO.hh.
References cbrc::FLEArray< T >::write(), and writeContentsOnly().
Referenced by write(), cbrc::ResidueIndexedSequence::write(), cbrc::ResidueIndexMap::write(), and cbrc::SerialNumbersForStrings< serialNumT >::write().
write() [2/2]
void cbrc::stringBinaryIO::write (const std::vector< std::string > & stringVector, std::ostream & os) inline
Definition at line 123 of file stringBinaryIO.hh.
References cbrc::FLEArray< T >::size(), write(), and cbrc::FLEArray< T >::write().
writeContentsOnly()
void cbrc::stringBinaryIO::writeContentsOnly (const std::string & s, std::ostream & os) inline
Definition at line 147 of file stringBinaryIO.hh.
References cbrc::perlish::die(), and cbrc::FLEArray< T >::write().
Referenced by write(), cbrc::ResidueIndexedSequence::write(), and cbrc::ResidueIndexMap::write().