NGSFeatures: cbrc::sigma4bitPackingUtils Namespace Reference
cbrc::sigma4bitPackingUtils Namespace Reference
Typedefs
typedef std::pair< size_t, byte > idxT
typedef std::vector< byte > unpackedVecT
Functions
void pack (byte *const &dest, const unpackedVecT &source)
void unpack (unpackedVecT &dest, const byte *const &source, const size_t &size)
unpackedVecT toUnpacked (const byte *const &source, const size_t &size)
void assignNthUnpacked (byte &destByte, const byte *const &source, const Sigma4bitPackedIdx &packedIdx)
void assignNthUnpacked (byte &destByte, const byte *const &source, const size_t &n)
static size_t numBytesNeededToStore (const size_t &numElems)
Typedef Documentation
idxT
typedef std::pair<size_t, byte> cbrc::sigma4bitPackingUtils::idxT
Definition at line 32 of file sigma4bitPackingUtils.hh.
unpackedVecT
typedef std::vector<byte> cbrc::sigma4bitPackingUtils::unpackedVecT
Definition at line 33 of file sigma4bitPackingUtils.hh.
Function Documentation
assignNthUnpacked() [1/2]
void cbrc::sigma4bitPackingUtils::assignNthUnpacked (byte & destByte, const byte *const & source, const Sigma4bitPackedIdx & packedIdx)
Definition at line 81 of file sigma4bitPackingUtils.cc.
References cbrc::mask.
Referenced by assignNthUnpacked(), cbrc::TagSet::operator()(), and unpack().
assignNthUnpacked() [2/2]
void cbrc::sigma4bitPackingUtils::assignNthUnpacked (byte & destByte, const byte *const & source, const size_t & n) inline
Definition at line 63 of file sigma4bitPackingUtils.hh.
References assignNthUnpacked().
numBytesNeededToStore()
static size_t cbrc::sigma4bitPackingUtils::numBytesNeededToStore (const size_t & numElems) inline static
Definition at line 72 of file sigma4bitPackingUtils.hh.
References SIGMA.
Referenced by cbrc::TagSet::sizeInBytes().
pack()
void cbrc::sigma4bitPackingUtils::pack (byte *const & dest, const unpackedVecT & source)
Definition at line 27 of file sigma4bitPackingUtils.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), GDB_ASSERTF, SIGMA, and cbrc::FLEArray< T >::size().
Referenced by cbrc::TagSet::readFromTextStream().
toUnpacked()
unpackedVecT cbrc::sigma4bitPackingUtils::toUnpacked (const byte *const & source, const size_t & size) inline
Definition at line 49 of file sigma4bitPackingUtils.hh.
References unpack().
Referenced by cbrc::TagSet::toString().
unpack()
void cbrc::sigma4bitPackingUtils::unpack (unpackedVecT & dest, const byte *const & source, const size_t & size)
Definition at line 65 of file sigma4bitPackingUtils.cc.
References assignNthUnpacked(), cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and cbrc::FLEArray< T >::resize().
Referenced by toUnpacked().