NGSFeatures: cbrc::perlish Namespace Reference
cbrc::perlish Namespace Reference
Functions
static void _fatalError (const int lineNo)
bool isSharpCommentOrEmpty (const std::string &s)
bool alwaysFalse (const std::string &s)
bool slurpLine (std::string &line, std::istream &iStream, bool ignoreLine(const std::string &))
std::string slurpLine (std::istream &is, bool ignoreLine(const std::string &))
std::string slurpLine (FILE *ifp, bool ignoreLine(const std::string &))
void slurpLines (stringVecT &lines, std::istream &is, bool ignoreLine(const std::string &))
stringVecT slurpLines (std::istream &is, bool ignoreLine(const std::string &))
std::vector< stringVecT > slurpAndSplit (std::istream &is, const std::string &pattern, bool ignoreLine(const std::string &))
std::vector< std::string > slurpNLines (std::istream &is, bool ignoreLine(const std::string &), int n)
std::string join (const std::string &delimiter, const std::vector< std::string > &sVec)
std::vector< std::string > split (const boost::regex &pattern, const std::string &s)
std::vector< std::string > split (const boost::regex &pattern, const std::string::const_iterator &textBeg, const std::string::const_iterator &textEnd)
std::vector< std::string > split (const boost::regex &pattern, const std::string &s, const size_t &limit)
std::vector< std::string > split (const std::string pattern, const std::string s)
std::vector< std::string > _split (std::string pattern, const std::string s)
std::vector< std::string > split (std::string pattern, const std::string s, const size_t limit)
bool _split_trailingPlusCharFoundAndRemoved (std::string &pattern)
bool _split_surroundingSquareBracketsFoundAndRemoved (std::string &pattern)
void _split_diePatternTypeNotImplemented (const std::string pattern)
std::vector< std::string > splitByLength (const std::string toBeSplit, const size_t segmentLength)
std::vector< std::string > splitOnOneOrMoreCharsInCharSet (const std::string s, const std::string splitChars)
std::vector< std::string > splitOnOneMatch (const std::string s, const std::string delimiterString, int limit)
std::vector< std::string > splitOnOneOrMoreCharsInCharSet (const std::string s, const std::string splitChars, const int limit)
void chop (std::string &s)
void chomp (std::string &s)
bool canStatFile (const std::string s)
bool isDirectory (const std::string &s)
std::ifstream::pos_type size (std::ifstream &ifs)
size_t numLines (std::ifstream &ifs)
void openOrDie (std::ifstream &ifs, const std::string &pathname)
bool looksLikeRealCstring (const char *const s)
bool looksLikeReal (const std::string &s)
double toDouble (const char *const s)
double toDouble (const std::string s)
std::string toString (const double val, const char *format)
std::string toString (const double val, const std::string &format)
std::string toString (const int val, const char *const format)
std::string toString (const int val, const std::string &format)
std::string toString (const unsigned int val, const char *const format)
std::string toString (const long unsigned int val, const char *const format)
std::string toString (const long unsigned int val, const std::string &format)
std::string toString (const unsigned int val, const std::string &format)
void fromString (unsigned int &lhs, const char *valueCString)
void fromString (unsigned int &lhs, const std::string &valueString)
void fromString (long unsigned int &lhs, const char *valueCString)
void fromString (long unsigned int &lhs, const std::string &valueString)
void fromString (double &lhs, const char *valueCString)
void fromString (double &lhs, const std::string &valueString)
bool looksLikeUnsignedIntCstring (const char *const s)
bool looksLikeUnsignedInt (const std::string &s, const size_t startIndex)
bool looksLikeUnsignedInts (const std::vector< std::string > &sVec)
bool looksLikeIntCstring (const char *const s)
bool looksLikeInt (const std::string &s, const size_t startIndex)
unsigned int toUnsignedInt (const char *const s)
unsigned int toUnsignedInt (const std::string s, const size_t startIndex)
std::vector< unsigned int > toUnsignedInts (const std::vector< std::string > &sVec)
int toInt (const char *const s)
int toInt (const std::string s, const size_t startIndex)
void removeCharFromString (std::string &s, const char c)
void removeLeadingWhiteSpace (std::string &s)
double toSeconds (const std::string &timeString)
const std::string & spaceTabString ()
std::vector< std::string > emptyVectorOfStringTypes ()
const std::string nullString ("")
std::string join (const std::string &delimiter, const stringVecT &sVec)
bool exists (const std::string filename)
void openCautiously (std::ofstream &ofs, const std::string &pathname)
void die (const std::string &filename, const int &line, const std::string &errorMessage)
void die (const std::string &filename, const int &line, const std::ostringstream &errorMessageStringStream)
bool isNumeric (const char &c)
bool looksLikeUnsignedInts (const stringVecT &sVec)
std::vector< unsigned int > toUnsignedInts (const stringVecT &sVec)
size_t toSizeT (const char *const s)
size_t toSizeT (const std::string s, size_t startIndex=0)
std::vector< size_t > toSizeTs (const stringVecT &sVec)
std::string substituteString (std::string &s, const std::string &stringToReplace, const std::string modifiers="")
template<typename T >
T min (const T &a, const T &b)
template<typename T >
T min (const T &a, const T &b, const T &c)
template<typename T >
T min (const T &a, const T &b, const T &c, const T &d)
static void _fatalError (const int lineNo)
static void _fatalError (const int lineNo)
Variables
static std::ostringstream _errorStream
static std::ostringstream _errorStream
static std::ostringstream _errorStream
Function Documentation
_fatalError() [1/3]
static void cbrc::perlish::_fatalError (const int lineNo) static
Definition at line 878 of file perlish.cc.
References _errorStream, and cbrc::gdbExit().
_fatalError() [2/3]
static void cbrc::perlish::_fatalError (const int lineNo) static
Definition at line 878 of file perlish.cc.
References _errorStream, and cbrc::gdbExit().
_fatalError() [3/3]
static void cbrc::perlish::_fatalError (const int lineNo) static
Definition at line 878 of file perlish.cc.
References _errorStream, and cbrc::gdbExit().
_split()
stringVecT cbrc::perlish::_split (std::string pattern, const std::string s)
Definition at line 232 of file perlish.cc.
References _errorStream, _split_diePatternTypeNotImplemented(), _split_surroundingSquareBracketsFoundAndRemoved(), _split_trailingPlusCharFoundAndRemoved(), cbrc::FLEArray< T >::find(), splitOnOneMatch(), and splitOnOneOrMoreCharsInCharSet().
Referenced by split().
_split_diePatternTypeNotImplemented()
void cbrc::perlish::_split_diePatternTypeNotImplemented (const std::string pattern)
Definition at line 327 of file perlish.cc.
References _errorStream, and PERLISH_FATAL_ERROR.
Referenced by _split(), and split().
_split_surroundingSquareBracketsFoundAndRemoved()
bool cbrc::perlish::_split_surroundingSquareBracketsFoundAndRemoved (std::string & pattern)
Definition at line 317 of file perlish.cc.
References cbrc::FLEArray< T >::replace(), and cbrc::FLEArray< T >::size().
Referenced by _split(), and split().
_split_trailingPlusCharFoundAndRemoved()
bool cbrc::perlish::_split_trailingPlusCharFoundAndRemoved (std::string & pattern)
Definition at line 307 of file perlish.cc.
References chop(), and cbrc::FLEArray< T >::size().
Referenced by _split(), and split().
alwaysFalse()
bool cbrc::perlish::alwaysFalse (const std::string & s)
Definition at line 32 of file perlish.cc.
Referenced by cbrc::runAddAlignmentToHtml().
canStatFile()
bool cbrc::perlish::canStatFile (const std::string s)
Definition at line 520 of file perlish.cc.
Referenced by main(), and cbrc::testCanStatFile().
chomp()
void cbrc::perlish::chomp (std::string & s)
Definition at line 515 of file perlish.cc.
References cbrc::FLEArray< T >::resize().
chop()
void cbrc::perlish::chop (std::string & s)
Definition at line 510 of file perlish.cc.
References cbrc::FLEArray< T >::resize().
Referenced by _split_trailingPlusCharFoundAndRemoved(), and cbrc::SprotReader::readRecord().
die() [1/2]
void cbrc::perlish::die (const std::string & filename, const int & line, const std::ostringstream & errorMessageStringStream) inline
Definition at line 134 of file perlish.hh.
References die().
die() [2/2]
void cbrc::perlish::die (const std::string & filename, const int & line, const std::string & errorMessage) inline
Definition at line 248 of file perlish.hh.
References cbrc::gdbExit().
Referenced by die(), cbrc::ResidueIndexedSequence::read(), cbrc::ResidueIndexMap::read(), cbrc::stringBinaryIO::read(), cbrc::stringBinaryIO::read(), cbrc::binaryIO::read(), cbrc::binaryIO::read(), cbrc::stringBinaryIO::read(), cbrc::binaryIO::read(), cbrc::ResidueIndexMap::write(), cbrc::binaryIO::writeContentsOnly(), and cbrc::stringBinaryIO::writeContentsOnly().
emptyVectorOfStringTypes()
stringVecT cbrc::perlish::emptyVectorOfStringTypes ()
Definition at line 862 of file perlish.cc.
exists()
bool cbrc::perlish::exists (const std::string filename) inline
Definition at line 230 of file perlish.hh.
Referenced by openCautiously().
fromString() [1/6]
void cbrc::perlish::fromString (double & lhs, const char * valueCString)
Definition at line 679 of file perlish.cc.
fromString() [2/6]
void cbrc::perlish::fromString (double & lhs, const std::string & valueString)
Definition at line 682 of file perlish.cc.
References fromString().
fromString() [3/6]
void cbrc::perlish::fromString (long unsigned int & lhs, const char * valueCString)
Definition at line 673 of file perlish.cc.
fromString() [4/6]
void cbrc::perlish::fromString (long unsigned int & lhs, const std::string & valueString)
Definition at line 676 of file perlish.cc.
References fromString().
fromString() [5/6]
void cbrc::perlish::fromString (unsigned int & lhs, const char * valueCString)
Definition at line 667 of file perlish.cc.
Referenced by fromString(), fromString(), fromString(), cbrc::SortedTagSet::readFromTextStream(), and cbrc::TagSet::readFromTextStream().
fromString() [6/6]
void cbrc::perlish::fromString (unsigned int & lhs, const std::string & valueString)
Definition at line 670 of file perlish.cc.
References fromString().
isDirectory()
bool cbrc::perlish::isDirectory (const std::string & s)
Definition at line 525 of file perlish.cc.
Referenced by main().
isNumeric()
bool cbrc::perlish::isNumeric (const char & c) inline
Definition at line 142 of file perlish.hh.
isSharpCommentOrEmpty()
bool cbrc::perlish::isSharpCommentOrEmpty (const std::string & s)
Definition at line 26 of file perlish.cc.
Referenced by cbrc::ConstantLabeledSquareDoubleFLENumMatrix::setFromStream().
join() [1/2]
std::string cbrc::perlish::join (const std::string & delimiter, const std::vector< std::string > & sVec)
Definition at line 125 of file perlish.cc.
References cbrc::FLEArray< T >::size().
join() [2/2]
std::string cbrc::perlish::join (const std::string & delimiter, const stringVecT & sVec)
Definition at line 125 of file perlish.cc.
References cbrc::FLEArray< T >::size().
looksLikeInt()
bool cbrc::perlish::looksLikeInt (const std::string & s, const size_t startIndex)
Definition at line 718 of file perlish.cc.
References looksLikeIntCstring().
looksLikeIntCstring()
bool cbrc::perlish::looksLikeIntCstring (const char *const s)
Definition at line 709 of file perlish.cc.
Referenced by looksLikeInt(), and toInt().
looksLikeReal()
bool cbrc::perlish::looksLikeReal (const std::string & s)
Definition at line 611 of file perlish.cc.
References looksLikeRealCstring().
Referenced by cbrc::testNumberStringFunctions(), and toSeconds().
looksLikeRealCstring()
bool cbrc::perlish::looksLikeRealCstring (const char *const s)
Definition at line 571 of file perlish.cc.
Referenced by looksLikeReal(), and toDouble().
looksLikeUnsignedInt()
bool cbrc::perlish::looksLikeUnsignedInt (const std::string & s, const size_t startIndex)
Definition at line 697 of file perlish.cc.
References looksLikeUnsignedIntCstring().
Referenced by cbrc::TransfacTextLabelInfo::isFreqMatrixBody(), looksLikeUnsignedInts(), cbrc::testNumberStringFunctions(), and cbrc::meminfo::total().
looksLikeUnsignedIntCstring()
bool cbrc::perlish::looksLikeUnsignedIntCstring (const char *const s)
Definition at line 689 of file perlish.cc.
Referenced by looksLikeUnsignedInt(), and toUnsignedInt().
looksLikeUnsignedInts() [1/2]
bool cbrc::perlish::looksLikeUnsignedInts (const std::vector< std::string > & sVec)
Definition at line 702 of file perlish.cc.
References looksLikeUnsignedInt(), and cbrc::FLEArray< T >::size().
Referenced by toUnsignedInts().
looksLikeUnsignedInts() [2/2]
bool cbrc::perlish::looksLikeUnsignedInts (const stringVecT & sVec)
Definition at line 702 of file perlish.cc.
References looksLikeUnsignedInt(), and cbrc::FLEArray< T >::size().
Referenced by toUnsignedInts().
min() [1/3]
template<typename T > T cbrc::perlish::min (const T & a, const T & b)
Definition at line 215 of file perlish.hh.
min() [2/3]
template<typename T > T cbrc::perlish::min (const T & a, const T & b, const T & c)
Definition at line 220 of file perlish.hh.
min() [3/3]
template<typename T > T cbrc::perlish::min (const T & a, const T & b, const T & c, const T & d)
Definition at line 225 of file perlish.hh.
nullString()
const std::string cbrc::perlish::nullString ("")
numLines()
size_t cbrc::perlish::numLines (std::ifstream & ifs)
Definition at line 550 of file perlish.cc.
References numLines().
Referenced by numLines().
openCautiously()
void cbrc::perlish::openCautiously (std::ofstream & ofs, const std::string & pathname) inline
Definition at line 239 of file perlish.hh.
References exists(), and GDB_ASSERTF.
openOrDie()
void cbrc::perlish::openOrDie (std::ifstream & ifs, const std::string & pathname)
Definition at line 563 of file perlish.cc.
References GDB_ASSERTF.
Referenced by cbrc::allPairsGlobalAffineScore(), cbrc::runGlobalAffineNearestClass(), and cbrc::runGlobalAffineSearcher().
removeCharFromString()
void cbrc::perlish::removeCharFromString (std::string & s, const char c)
Definition at line 775 of file perlish.cc.
References cbrc::FLEArray< T >::size().
Referenced by cbrc::TransfacBindingFactor::set().
removeLeadingWhiteSpace()
void cbrc::perlish::removeLeadingWhiteSpace (std::string & s)
Definition at line 786 of file perlish.cc.
References cbrc::FLEArray< T >::size().
Referenced by cbrc::TransfacBindingFactor::set().
size()
std::ifstream::pos_type cbrc::perlish::size (std::ifstream & ifs)
Definition at line 532 of file perlish.cc.
slurpAndSplit()
std::vector< stringVecT > cbrc::perlish::slurpAndSplit (std::istream & is, const std::string & pattern, bool ignoreLineconst std::string &)
Definition at line 96 of file perlish.cc.
References slurpLine(), and split().
slurpLine() [1/3]
std::string cbrc::perlish::slurpLine (FILE * ifp, bool ignoreLineconst std::string &)
Definition at line 57 of file perlish.cc.
References getline().
slurpLine() [2/3]
std::string cbrc::perlish::slurpLine (std::istream & is, bool ignoreLineconst std::string &)
Definition at line 47 of file perlish.cc.
slurpLine() [3/3]
bool cbrc::perlish::slurpLine (std::string & line, std::istream & iStream, bool ignoreLineconst std::string &)
Definition at line 35 of file perlish.cc.
Referenced by cbrc::convertMultipleEdgePerLineToOneEdgePerLineFormat(), cbrc::filterBlast8ResultEValueThreshold(), cbrc::listConnectedComponents(), cbrc::TransfacReader::nextNonBlankLine(), cbrc::OneEdgePerLineFormat::numNodesInStream(), cbrc::printRandomRepresentativeFromEachConnectedComponent(), cbrc::MatrixGraph::readContinuousIntegerNodesFormat(), cbrc::MatrixGraph::readEdgesOneEdgePerLineFormat(), cbrc::FLSorted2TypePairSet< T0, T1 >::readFromTextFile(), cbrc::SortedTagSet::readFromTextStream(), cbrc::TagSet::readFromTextStream(), cbrc::NeighborListGraph::readOneEdgePerLineFormat(), cbrc::KnapsackObjectVector::readText_idsFrom0(), cbrc::RecountTagCounts::RecountTagCounts(), cbrc::RecountTagCounts::RecountTagCounts(), cbrc::Blast8Result::setFromStream(), cbrc::ConstantLabeledSquareDoubleFLENumMatrix::setFromStream(), slurpAndSplit(), cbrc::meminfo::total(), and cbrc::RecountNeighborProbGraphWriter::write().
slurpLines() [1/2]
stringVecT cbrc::perlish::slurpLines (std::istream & is, bool ignoreLineconst std::string &)
Definition at line 89 of file perlish.cc.
References slurpLines().
slurpLines() [2/2]
void cbrc::perlish::slurpLines (stringVecT & lines, std::istream & is, bool ignoreLineconst std::string &)
Definition at line 73 of file perlish.cc.
Referenced by cbrc::Blast8ResultReader::Blast8ResultReader(), cbrc::SortedStringSet::readFromTextStream(), cbrc::runAddAlignmentToHtml(), cbrc::runAddIdenticalToHtml(), slurpLines(), cbrc::smoothMinPoints(), cbrc::smoothMinPoints(), cbrc::testMapSpeed(), and cbrc::testStringKeyHashtableSpeed().
slurpNLines()
stringVecT cbrc::perlish::slurpNLines (std::istream & is, bool ignoreLineconst std::string &, int n)
Definition at line 109 of file perlish.cc.
spaceTabString()
const std::string & cbrc::perlish::spaceTabString ()
Definition at line 853 of file perlish.cc.
References cbrc::FLEArray< T >::size(), and spaceTabString().
Referenced by cbrc::TransfacTextLine::set(), and spaceTabString().
split() [1/5]
stringVecT cbrc::perlish::split (const boost::regex & pattern, const std::string & s)
Definition at line 139 of file perlish.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and split().
Referenced by cbrc::Blast8ResultReader::Blast8ResultReader(), cbrc::convertMultipleEdgePerLineToOneEdgePerLineFormat(), cbrc::filterBlast8ResultEValueThreshold(), cbrc::listConnectedComponents(), cbrc::OneEdgePerLineFormat::numNodesInStream(), cbrc::printRandomRepresentativeFromEachConnectedComponent(), cbrc::MatrixGraph::readContinuousIntegerNodesFormat(), cbrc::MatrixGraph::readEdgesOneEdgePerLineFormat(), cbrc::FLSorted2TypePairSet< T0, T1 >::readFromTextFile(), cbrc::TagSet::readFromTextStream(), cbrc::NeighborListGraph::readOneEdgePerLineFormat(), cbrc::SprotReader::readRecord(), cbrc::KnapsackObjectVector::readText_idsFrom0(), cbrc::RecountTagCounts::RecountTagCounts(), cbrc::RecountTagCounts::RecountTagCounts(), cbrc::ResidueIndexMapTranslator::ResidueIndexMapTranslator(), cbrc::runAddAlignmentToHtml(), cbrc::runAddIdenticalToHtml(), cbrc::TransfacTextLine::set(), cbrc::TransfacBindingFactor::set(), cbrc::FLEArray< T >::setFromLiteral(), cbrc::Blast8Result::setFromStream(), cbrc::ConstantLabeledSquareDoubleFLENumMatrix::setFromStream(), slurpAndSplit(), cbrc::smoothMinPoints(), cbrc::smoothMinPoints(), split(), and cbrc::RecountNeighborProbGraphWriter::write().
split() [2/5]
stringVecT cbrc::perlish::split (const boost::regex & pattern, const std::string & s, const size_t & limit)
Definition at line 189 of file perlish.cc.
References cbrc::FLEArray< T >::begin(), and GDB_ASSERTF.
split() [3/5]
stringVecT cbrc::perlish::split (const boost::regex & pattern, const std::string::const_iterator & textBeg, const std::string::const_iterator & textEnd)
Definition at line 149 of file perlish.cc.
References cbrc::matchesPrefixOf(), and cbrc::FLEArray< T >::size().
split() [4/5]
stringVecT cbrc::perlish::split (const std::string pattern, const std::string s)
Definition at line 227 of file perlish.cc.
References _split().
split() [5/5]
stringVecT cbrc::perlish::split (std::string pattern, const std::string s, const size_t limit)
Definition at line 267 of file perlish.cc.
References _errorStream, _split_diePatternTypeNotImplemented(), _split_surroundingSquareBracketsFoundAndRemoved(), _split_trailingPlusCharFoundAndRemoved(), cbrc::FLEArray< T >::find(), splitOnOneMatch(), and splitOnOneOrMoreCharsInCharSet().
splitByLength()
stringVecT cbrc::perlish::splitByLength (const std::string toBeSplit, const size_t segmentLength)
Definition at line 343 of file perlish.cc.
References cbrc::FLEArray< T >::size().
Referenced by cbrc::operator<<().
splitOnOneMatch()
stringVecT cbrc::perlish::splitOnOneMatch (const std::string s, const std::string delimiterString, int limit)
Definition at line 396 of file perlish.cc.
References cbrc::FLEArray< T >::find(), cbrc::FLEArray< T >::resize(), and cbrc::FLEArray< T >::size().
Referenced by _split(), and split().
splitOnOneOrMoreCharsInCharSet() [1/2]
stringVecT cbrc::perlish::splitOnOneOrMoreCharsInCharSet (const std::string s, const std::string splitChars)
Definition at line 353 of file perlish.cc.
References cbrc::FLEArray< T >::find(), and cbrc::FLEArray< T >::size().
Referenced by _split(), and split().
splitOnOneOrMoreCharsInCharSet() [2/2]
stringVecT cbrc::perlish::splitOnOneOrMoreCharsInCharSet (const std::string s, const std::string splitChars, const int limit)
Definition at line 459 of file perlish.cc.
References cbrc::FLEArray< T >::find(), and cbrc::FLEArray< T >::size().
substituteString()
std::string cbrc::perlish::substituteString (std::string & s, const std::string & stringToReplace, const std::string modifiers = "")
toDouble() [1/2]
double cbrc::perlish::toDouble (const char *const s)
Definition at line 613 of file perlish.cc.
References _errorStream, looksLikeRealCstring(), and PERLISH_FATAL_ERROR.
Referenced by cbrc::Blast8Result::eValue(), main(), main(), cbrc::smoothMinPoints(), cbrc::smoothMinPoints(), cbrc::testNumberStringFunctions(), toDouble(), and toSeconds().
toDouble() [2/2]
double cbrc::perlish::toDouble (const std::string s)
Definition at line 621 of file perlish.cc.
References toDouble().
toInt() [1/2]
int cbrc::perlish::toInt (const char *const s)
Definition at line 754 of file perlish.cc.
References _errorStream, looksLikeIntCstring(), and PERLISH_FATAL_ERROR.
Referenced by toInt().
toInt() [2/2]
int cbrc::perlish::toInt (const std::string s, const size_t startIndex)
Definition at line 762 of file perlish.cc.
References _errorStream, PERLISH_FATAL_ERROR, cbrc::FLEArray< T >::size(), and toInt().
toSeconds()
double cbrc::perlish::toSeconds (const std::string & timeString)
Definition at line 798 of file perlish.cc.
References _errorStream, cbrc::FLEArray< T >::find(), looksLikeReal(), PERLISH_FATAL_ERROR, cbrc::FLEArray< T >::size(), and toDouble().
toSizeT() [1/2]
size_t cbrc::perlish::toSizeT (const char *const s)
toSizeT() [2/2]
size_t cbrc::perlish::toSizeT (const std::string s, size_t startIndex = 0)
toSizeTs()
std::vector< size_t > cbrc::perlish::toSizeTs (const stringVecT & sVec)
toString() [1/8]
std::string cbrc::perlish::toString (const double val, const char * format)
Definition at line 623 of file perlish.cc.
Referenced by cbrc::htmlStrings::equalWidthFontStyle(), cbrc::Alignment::outputHtml(), cbrc::Alignment::outputHtmlMarkSame(), cbrc::Alignment::outputTextMarkSame(), toString(), toString(), toString(), and toString().
toString() [2/8]
std::string cbrc::perlish::toString (const double val, const std::string & format)
Definition at line 630 of file perlish.cc.
References toString().
toString() [3/8]
std::string cbrc::perlish::toString (const int val, const char *const format)
Definition at line 633 of file perlish.cc.
toString() [4/8]
std::string cbrc::perlish::toString (const int val, const std::string & format)
Definition at line 640 of file perlish.cc.
References toString().
toString() [5/8]
std::string cbrc::perlish::toString (const long unsigned int val, const char *const format)
Definition at line 651 of file perlish.cc.
toString() [6/8]
std::string cbrc::perlish::toString (const long unsigned int val, const std::string & format)
Definition at line 658 of file perlish.cc.
References toString().
toString() [7/8]
std::string cbrc::perlish::toString (const unsigned int val, const char *const format)
Definition at line 643 of file perlish.cc.
toString() [8/8]
std::string cbrc::perlish::toString (const unsigned int val, const std::string & format)
Definition at line 662 of file perlish.cc.
References toString().
toUnsignedInt() [1/2]
unsigned int cbrc::perlish::toUnsignedInt (const char *const s)
Definition at line 724 of file perlish.cc.
References GDB_ASSERTF, and looksLikeUnsignedIntCstring().
Referenced by main(), cbrc::smoothMinPoints(), cbrc::smoothMinPoints(), cbrc::testNumberStringFunctions(), cbrc::meminfo::total(), toUnsignedInt(), and toUnsignedInts().
toUnsignedInt() [2/2]
unsigned int cbrc::perlish::toUnsignedInt (const std::string s, const size_t startIndex)
Definition at line 731 of file perlish.cc.
References _errorStream, PERLISH_FATAL_ERROR, cbrc::FLEArray< T >::size(), and toUnsignedInt().
toUnsignedInts() [1/2]
std::vector< unsigned int > cbrc::perlish::toUnsignedInts (const std::vector< std::string > & sVec)
Definition at line 743 of file perlish.cc.
References looksLikeUnsignedInts(), cbrc::FLEArray< T >::size(), and toUnsignedInt().
toUnsignedInts() [2/2]
std::vector< unsigned int > cbrc::perlish::toUnsignedInts (const stringVecT & sVec)
Definition at line 743 of file perlish.cc.
References looksLikeUnsignedInts(), cbrc::FLEArray< T >::size(), and toUnsignedInt().
Variable Documentation
_errorStream [1/3]
std::ostringstream cbrc::perlish::_errorStream static
Definition at line 23 of file perlish.cc.
Referenced by _fatalError(), _split(), _split_diePatternTypeNotImplemented(), split(), toDouble(), toInt(), toInt(), toSeconds(), and toUnsignedInt().
_errorStream [2/3]
std::ostringstream cbrc::perlish::_errorStream static
Definition at line 23 of file perlish.cc.
_errorStream [3/3]
std::ostringstream cbrc::perlish::_errorStream static
Definition at line 23 of file perlish.cc.