NGSFeatures: cbrc::stringUtils Namespace Reference
cbrc::stringUtils Namespace Reference
Functions
static const std::string null ("")
bool startsWith (const std::string &t, const std::string &q)
bool endsWith (const std::string &t, const std::string &q)
std::string::size_type stringReplaceAll (std::string &s, const std::string &oldSubstring, const std::string &newSubstring)
Function Documentation
endsWith()
bool cbrc::stringUtils::endsWith (const std::string & t, const std::string & q) inline
Definition at line 51 of file stringUtils.hh.
null()
static const std::string cbrc::stringUtils::null ("") static
startsWith()
bool cbrc::stringUtils::startsWith (const std::string & t, const std::string & q) inline
Definition at line 33 of file stringUtils.hh.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
Referenced by cbrc::FastaInputOptions::isComment().
stringReplaceAll()
std::string::size_type cbrc::stringUtils::stringReplaceAll (std::string & s, const std::string & oldSubstring, const std::string & newSubstring) inline
Definition at line 77 of file stringUtils.hh.
References cbrc::FLEArray< T >::find(), cbrc::FLEArray< T >::replace(), and cbrc::FLEArray< T >::size().