NGSFeatures: cbrc::fastafmtFunctions Namespace Reference
cbrc::fastafmtFunctions Namespace Reference
Functions
size_t countRecords (std::istream &iStream)
size_t skipRecords (std::istream &iStream, const size_t &numToSkip)
size_t printRecords (std::istream &iStream, std::ostream &oStream=std::cout)
size_t printRecords (std::istream &iStream, const size_t &numToPrint, std::ostream &oStream=std::cout)
Function Documentation
countRecords()
size_t cbrc::fastafmtFunctions::countRecords (std::istream & iStream)
Definition at line 22 of file fastafmtFunctions.cc.
References cbrc::FLEArray< T >::empty(), and FASTAFMT_RECORD_MARKER_CHAR.
Referenced by main().
printRecords() [1/2]
size_t cbrc::fastafmtFunctions::printRecords (std::istream & iStream, const size_t & numToPrint, std::ostream & oStream = std::cout)
Definition at line 89 of file fastafmtFunctions.cc.
References FASTAFMT_RECORD_MARKER_CHAR.
printRecords() [2/2]
size_t cbrc::fastafmtFunctions::printRecords (std::istream & iStream, std::ostream & oStream = std::cout)
Definition at line 65 of file fastafmtFunctions.cc.
References FASTAFMT_RECORD_MARKER_CHAR.
Referenced by cbrc::fastaHeadRecords().
skipRecords()
size_t cbrc::fastafmtFunctions::skipRecords (std::istream & iStream, const size_t & numToSkip)
Definition at line 37 of file fastafmtFunctions.cc.
References FASTAFMT_RECORD_MARKER_CHAR.
Referenced by cbrc::fastaHeadRecords().