NGSFeatures: cbrc::FLEArrayFunctions Namespace Reference
cbrc::FLEArrayFunctions Namespace Reference
Functions
template<typename T >
const T & randomElement (const FLEArray< T > a, long int callerGivenSeed=0)
template<typename elemType >
void setNumCombinationsVector (FLENumArray< elemType > &numCombinationsVector)
FLENumArray< double > doubleFLENumArrayFromStrings (std::vector< std::string > asStrings, size_t start, size_t end)
template<typename elemType >
void diff (FLENumArray< elemType > &a, const FLENumArray< elemType > &b, const FLENumArray< elemType >c)
template<typename T >
void cumulativeSum (FLENumArray< T > &a, const FLENumArray< T > &b)
template<typename T >
void normalizeSum (FLENumArray< T > &a, double sumAfterNormalization=1.0)
Function Documentation
cumulativeSum()
template<typename T > void cbrc::FLEArrayFunctions::cumulativeSum (FLENumArray< T > & a, const FLENumArray< T > & b)
Definition at line 81 of file FLEArrayFunctions.hh.
References GDB_ASSERT, cbrc::FLEArray< T >::setSize(), and cbrc::FLEArray< T >::size().
diff()
template<typename elemType > void cbrc::FLEArrayFunctions::diff (FLENumArray< elemType > & a, const FLENumArray< elemType > & b, const FLENumArray< elemType > c)
Definition at line 72 of file FLEArrayFunctions.hh.
References cbrc::FLEArray< T >::size().
doubleFLENumArrayFromStrings()
FLENumArray< double > cbrc::FLEArrayFunctions::doubleFLENumArrayFromStrings (std::vector< std::string > asStrings, size_t start, size_t end)
Definition at line 60 of file FLEArrayFunctions.hh.
References cbrc::FLEArray< T >::size().
normalizeSum()
template<typename T > void cbrc::FLEArrayFunctions::normalizeSum (FLENumArray< T > & a, double sumAfterNormalization = 1.0)
Definition at line 91 of file FLEArrayFunctions.hh.
References cbrc::FLEArray< T >::size().
randomElement()
template<typename T > const T & cbrc::FLEArrayFunctions::randomElement (const FLEArray< T > a, long int callerGivenSeed = 0)
Definition at line 28 of file FLEArrayFunctions.hh.
References cbrc::FLEArray< T >::size().
Referenced by cbrc::printRandomRepresentativeFromEachConnectedComponent().
setNumCombinationsVector()
template<typename elemType > void cbrc::FLEArrayFunctions::setNumCombinationsVector (FLENumArray< elemType > & numCombinationsVector)
Definition at line 49 of file FLEArrayFunctions.hh.
References cbrc::FLEArray< T >::size().