NGSFeatures: cbrc::stlUtils Namespace Reference
cbrc::stlUtils Namespace Reference
Typedefs
typedef unsigned char uchar
Functions
uchar max (const std::vector< uchar > &vec)
template<typename T , typename F >
void transformAll (T &container, F op)
template<typename T1 , typename T2 >
bool pairSecondLess (const std::pair< T1, T2 > &p1, const std::pair< T1, T2 > &p2)
Typedef Documentation
uchar
typedef unsigned char cbrc::stlUtils::uchar
Definition at line 23 of file stlUtils.hh.
Function Documentation
max()
uchar cbrc::stlUtils::max (const std::vector< uchar > & vec) inline
Definition at line 25 of file stlUtils.hh.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
Referenced by cbrc::Sigma4FLArray::Sigma4FLArray().
pairSecondLess()
template<typename T1 , typename T2 > bool cbrc::stlUtils::pairSecondLess (const std::pair< T1, T2 > & p1, const std::pair< T1, T2 > & p2)
Definition at line 38 of file stlUtils.hh.
transformAll()
template<typename T , typename F > void cbrc::stlUtils::transformAll (T & container, F op)
Definition at line 32 of file stlUtils.hh.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().