NGSFeatures: cbrc Namespace Reference
cbrc Namespace Reference
Namespaces
namespace binaryIO
namespace ChainHashtableUtils
namespace fastafmt
namespace fastafmtFunctions
namespace FLArrayFunctions
namespace FLEArrayFunctions
namespace FLSortedFunctions
namespace HammingDistanceComputer
namespace html
namespace htmlStrings
namespace mathUtils
namespace meminfo
namespace moreNumericLimits
namespace pairPredicate
namespace perlish
namespace ptrUtils
namespace rankCorrelationFunctions
namespace RecountNeighborProbGraphFormat
namespace ResidueIndexMapPredefined
namespace ResidueIndexMapPredefinedAlphabets
namespace sigma4bitPackingUtils
namespace smoothing
namespace sortingUtils
namespace stlConstants
namespace stlUtils
namespace stringBinaryIO
namespace stringUtils
namespace uintMath
namespace vectorMatrix
Classes
class Alignment
class AminoScore
class AminoScoreIdentity
class AminoScorePam120
class ArgvParser
class BitArray
class BitArrayFast
class BitArrayStack
class BitMatrix
class BitMatrixFast
class Blast8Result
class Blast8ResultReader
class BlastEValuesByClass
class BoundedLenFifoVector
class ChainHashIterator
class ChainHashtable
class ChainHashtableLink
class ComplementDNA
class ConnectedComponentOnlineComputer
class ConstantLabeledSquareDoubleFLENumMatrix
class ConstantLabeledSquareDoubleInterface
class ConstResidueIndexSequenceBoundaries
class DeltaCompressedInt
class DiscreteCumulativeProbabilityDistribution
class DNAArrayBit16
class DNAArrayBit8
class DNAExtendedResidueIndexMap
class FastaConstants
class FastafmtConstants
class FastafmtInputOptions
class FastafmtReader
class FastafmtRecord
class FastaInputOptions
class FastaReader
class FastaRecord
class FastaRecordReader
class FastaSeqSlurper
class FastaWriter
class FLArray
class FLArrayByIndexSortingPredicate
class FLArrayFast
class FLDiagonalMatrix
class FLEArray
class FLEArrayByIndexSortingPredicate
class FLEArrayFast
class FLEMatrix
class FLEMatrixFast
class FLENumArray
class FLENumArrayFast
class FLENumMatrix
class FLENumMatrixFast
class FLESorted
class FLMatrix
class FLMatrixFast
class FLNumArray
class FLNumArrayFast
class FLNumMatrix
class FLNumMatrixFast
class FLSorted
class FLSorted2TypePairSet
class FLStack
class GlobalAffineDist
class GlobalAffineIdentityAligner
class Graph
class HashableSizeTKey
class KeyValuePair
class KmerCount
class KmerIndexer
class KnapsackEnumerator
class KnapsackObject
class KnapsackObjectVector
class LabeledAsciiSeq
class LabeledIdentityDoubleMatrix
class LabeledSequence
class LabeledSequencePairPredicate
class LabeledSequencePairPredicate_1stSeqClassFilter
class LabeledSequencePairPredicate_alwaysFalse
class LabeledSequencePairPredicate_logicalOr
class LabeledSequencePairPredicate_namesEqual
class LabeledSequences
class LabeledSquareFLENumMatrix
class LogChoose
class LogFactorial
class MallocArray
class MallocArrayFast
class MallocNumArray
class MallocNumArrayFast
class Matrix
class MatrixGraph
class NeighborListGraph
class OneEdgePerLineFormat
class PermutationGenerator
class Point2D
class RecountComputerForGraphOnDisk
class RecountExpectationMatchingTagCorrector
class RecountNeighborList
class RecountNeighborProbGraphOnDisk
class RecountNeighborProbGraphWriter
class RecountTagCounts
class RecountTagIdProbPair
class RecursivePermutationGenerator
class ResidueColor
class ResidueColorGenebee
class ResidueIndexedSequence
class ResidueIndexMap
class ResidueIndexMapTransformer
class ResidueIndexMapTranslator
class ResidueIndexWindow
class ResidueIndexWindowFactory
class ResidueSimilarityAffineEdit
class ResiduesIndexMap
class SeqGlobalAffineAligner
class SerialNumbersForStrings
class SerialNumbersForStrings_accessCounting
class SetWrapper
class Sigma4bitPackedIdx
class Sigma4FLArray
class SimilaritySearchableSequences
class SortedStringSet
class SortedTagSet
class SprotReader
class StayFiniteLog
class String2KeyAndValue
class String2KeyHashIterator
class String2KeyHashtable
class String2KeyHashtableLink
class StringHashtable
class StringHashtableIterator
class StringHashtableLink
class StringKeyAndValue
class StringKeyHashIterator
class StringKeyHashtable
class StringKeyHashtableLink
class StringSpecEnum
class StringStringDoubleMap
class StringUnaryPredicate
class StringUnaryPredicateAlwaysFalse
class StringUnaryPredicateAlwaysTrue
class StringUnaryPredicateContainsNotSimpleMatch
class StringUnaryPredicateContainsSimpleMatch
class SymmetricBitMatrix
class TagSet
class TextWindow
class TopKSorted
class TopKUnique
class TransfacBindingFactor
class TransfacReader
class TransfacTextLabelInfo
class TransfacTextLine
class TrivialHistogram
class TrivialUnsignedHistogram
class UInt31
class UInt332
class UnsignedDoubleMap
class VectorMap
class WeightedGraph
class WeightedPoint2D
Typedefs
typedef unsigned int nodeIndexT
typedef short unsigned int neighborhoodSizeT
typedef double probT
typedef double tagCountT
typedef unsigned int tagIdT
typedef std::vector< probT > probVecT
typedef std::vector< tagIdT > tagIdVecT
typedef unsigned char byte
typedef boost::match_results< std::string::const_iterator > match_resultT
typedef int alignScoreT
typedef unsigned short int DNAArrayBit16_bases8
typedef long double _LD
typedef std::vector< std::string > stringVecT
typedef std::map< std::pair< std::string, std::string >, double > StringStringDoubleMapT
typedef unsigned int uint
Functions
void dumpNeighborList (const TagSet &tagID_to_seq, const RecountNeighborList neighborList)
void dumpRecountNeighborProbGraphOnDisk ()
void dumpNeighborList (const SortedTagSet &tagId_to_seq, const RecountNeighborList neighborList)
std::ostream & operator<< (std::ostream &os, const MatrixGraph &mg)
std::ostream & operator<< (std::ostream &os, const NeighborListGraph &nlg)
void convertMultipleEdgePerLineToOneEdgePerLineFormat (std::istream &inStream)
void listConnectedComponents (std::string filename)
void printRandomRepresentativeFromEachConnectedComponent (std::string filename)
void runAllShortestEdgeLengthPaths (bool summarizeOnly)
void testConnectedComponentOnlineComputer (const bool &verify)
void observedMeanStdev_fromTrueCounts ()
std::ostream & operator<< (std::ostream &oStream, const RecountNeighborList &tagNode)
std::ostream & operator<< (std::ostream &oStream, const RecountTagCounts &tagCounts)
std::ostream & operator<< (std::ostream &oStream, const RecountTagIdProbPair &pair)
void runRecountExpectationMatchingTagCorrector ()
std::ostream & operator<< (std::ostream &os, const SortedTagSet &tagSet)
std::ostream & operator<< (std::ostream &os, const TagSet &tagSet)
static const std::string _argvParserNullString ("")
std::ostream & operator<< (std::ostream &os, const BitArray &ba)
std::ostream & operator<< (std::ostream &os, const BitMatrix &bm)
std::ostream & operator<< (std::ostream &os, const SymmetricBitMatrix &sbm)
bool matchesPrefixOf (const std::string::const_iterator &textBeg, const std::string::const_iterator &textEnd, const boost::regex &pattern)
bool matchesPrefixOf (const std::string &text, const boost::regex &pattern)
bool advancePastMatchAtPoint (std::string::const_iterator &point, const std::string::const_iterator &textEnd, const boost::regex &regex)
static int nextPrime (size_t num)
size_t nextPrime (const size_t &num)
std::string size_tToBinaryRepresentationString (size_t a)
static int nextPrime (size_t num)
static size_t bytesHashVal (const size_t numBytes, size_t *a)
static size_t string2HashVal (const std::string &s0, const std::string &s1)
template<typename ValT >
std::ostream & operator<< (std::ostream &os, const String2KeyHashtable< ValT > &skh)
std::ostream & operator<< (std::ostream &os, const StringHashtableIterator &skh)
std::ostream & operator<< (std::ostream &os, const StringHashtable &skh)
template<typename ValT >
std::ostream & operator<< (std::ostream &os, const StringKeyHashIterator< ValT > &skh)
template<typename ValT >
std::ostream & operator<< (std::ostream &os, const StringKeyHashtable< ValT > &skh)
void testMapSpeed ()
void testPlatformMacro ()
void testString2KeyHashtable ()
void testStringKeyHashtableSpeed ()
template<typename intType >
std::ostream & operator<< (std::ostream &os, const DeltaCompressedInt< intType > &dc)
std::ostream & operator<< (std::ostream &os, const ConstantLabeledSquareDoubleFLENumMatrix &mat)
std::ostream & operator<< (std::ostream &os, const FLNumArray< unsigned char > &fla)
template<typename T >
std::ostream & operator<< (std::ostream &os, const FLArray< T > &fla)
FLEArray< size_t > FLArrayIdentityPermutation (size_t s)
template<typename T >
FLEArray< size_t > FLArraySortedPermutation (FLArray< T > a)
template<typename T , typename op >
FLEArray< size_t > FLArraySortedPermutation (FLArray< T > a)
template<typename elemType >
std::ostream & operator<< (std::ostream &os, const FLDiagonalMatrix< elemType > &fldm)
template<typename T >
std::ostream & operator<< (std::ostream &os, const FLEArray< T > &fla)
std::ostream & operator<< (std::ostream &os, const FLENumArray< unsigned char > &fla)
FLEArray< size_t > FLEArrayIdentityPermutation (size_t s)
template<typename T >
FLEArray< size_t > FLEArraySortedPermutation (FLEArray< T > a)
template<typename T , typename op >
FLEArray< size_t > FLEArraySortedPermutation (FLEArray< T > a)
template<typename T >
std::ostream & operator<< (std::ostream &os, const FLEMatrix< T > &flm)
template<typename T >
std::ostream & operator<< (std::ostream &os, const FLESorted< T > &sl)
template<typename T >
std::ostream & operator<< (std::ostream &os, const FLMatrix< T > &flm)
template<typename T >
std::ostream & operator<< (std::ostream &os, const FLSorted< T > &sl)
template<typename T0 , typename T1 >
std::ostream & operator<< (std::ostream &os, const FLSorted2TypePairSet< T0, T1 > &pairSet)
template<typename elemType >
std::ostream & operator<< (std::ostream &os, const FLStack< elemType > &fls)
template<typename elemT >
std::ostream & operator<< (std::ostream &os, const LabeledSquareFLENumMatrix< elemT > &mat)
std::ostream & operator<< (std::ostream &os, const MallocNumArray< unsigned char > &fla)
template<typename T >
std::ostream & operator<< (std::ostream &os, const MallocArray< T > &fla)
void isConstantLabeledSquareDoubleFLENumMatrixSymmetric ()
void testFLArrayByIndexSortingPredicate ()
double vectorSum (std::vector< double > a)
void testFLArray ()
void print (int elem)
void testForEach ()
void gdbExit (const int status=-1)
template<typename XT , typename YT >
std::ostream & operator<< (std::ostream &os, const Point2D< XT, YT > &point)
void smoothMinPoints (size_t minSampleSize)
void smoothMinPoints (size_t minSampleSize, const bool positiveCorrelation)
template<typename XT , typename YT , typename WT >
std::ostream & operator<< (std::ostream &os, const WeightedPoint2D< XT, YT, WT > &point)
template<typename T >
std::ostream & operator<< (std::ostream &os, const TrivialHistogram< T > &histo)
template<typename T >
std::ostream & operator<< (std::ostream &os, const TrivialUnsignedHistogram< T > &histo)
std::ostream & operator<< (std::ostream &os, const PermutationGenerator &pg)
size_t maxSumSquaredDifferences (const size_t permSize)
size_t sumSquaredDifferences (const FLENumArray< size_t > &a)
void calculatePermutationSumOfSquaredDifferencesDistribution (const size_t permSize)
double lg (const double x)
std::ostream & operator<< (std::ostream &os, const DiscreteCumulativeProbabilityDistribution &cmldist)
void testStayFiniteLog ()
template<typename ValType >
void log_transform (Matrix< ValType > &M)
template<typename ValType , typename ResultPrecision >
ResultPrecision pearson_corr (Matrix< ValType > &M, const size_t pos1, const size_t pos2, size_t *valid_data, bool ColumnCompare=0)
std::ostream & operator<< (std::ostream &os, const UInt31 &ui31)
std::ostream & operator<< (std::ostream &os, const UInt332 &ui332)
void testCanStatFile (std::string filename)
void testNumberStringFunctions ()
std::ostream & operator<< (std::ostream &os, const Alignment &al)
std::ostream & operator<< (std::ostream &os, const AminoScore &aScore)
const ResidueSimilarityAffineEdit residueSimilarityAffineEdit_DNA (DNAExtendedResidueIndexMap)
void printCloseNeighbors (const BoundedLenFifoVector< LabeledAsciiSeq > &neighbors)
void adjacentCloseHamming ()
void allPairsHammingNeighbors (const bool &byPercent, const double &threshold, std::istream &fastaInputStream)
void allPairsNearestGlobalAffineScore ()
void clusterByIdentity ()
void computeAllPairsIdentity ()
void computeGlobalAffineIdentity (const bool &doAlignment, std::istream &multifastaIstream)
void hasHighIdentityToDataset ()
void runAddAlignmentToHtml (std::istream &dataSequencesStream, std::istream &queryHtmlStream, std::istream &querySequencesStream, const std::string &outputPathnameForLinking, std::ostream &outputStream)
void runAddIdenticalToHtml (std::istream &dataSequencesStream, std::istream &queryHtmlStream, std::istream &querySequencesStream, const std::string &outputPathnameForLinking, std::ostream &outputStream)
void printIfHtml (const std::string &message)
void runGlobalAffineAlignment ()
void runGlobalAffineNearestClass ()
void runGlobalAffineSearcher (const std::string &filename0, const std::string &filename1, const bool &ignoreSelf)
void runSimilaritySearchableSequences (std::istream &sequencesStream, std::istream &queryStream, const alignScoreT &loosenessFactor, std::string &outputFormat, bool &markDifferent)
void allPairsGlobalAffineScore ()
void testSeqGlobalAffineAligner ()
std::ostream & operator<< (std::ostream &os, const FastafmtReader &fr)
std::ostream & operator<< (std::ostream &os, const FastafmtRecord &fastafmtRecord)
std::ostream & operator<< (std::ostream &os, const LabeledAsciiSeq &namedSeq)
std::ostream & operator<< (std::ostream &os, const LabeledSequence &ls)
const std::string LabeledSequenceUndefinedLabel ("undefined")
template<size_t len>
std::ostream & operator<< (std::ostream &os, const DNAArrayBit16< len > &dnaArray)
template<size_t len>
std::ostream & operator<< (std::ostream &os, const DNAArrayBit8< len > &dnaArray)
std::ostream & operator<< (std::ostream &oStream, const Sigma4bitPackedIdx &packedIdx)
std::ostream & operator<< (std::ostream &oStream, const Sigma4FLArray &array)
std::ostream & operator<< (std::ostream &os, const Blast8ResultReader &brr)
std::ostream & operator<< (std::ostream &os, const Blast8Result &br)
std::ostream & operator<< (std::ostream &oStream, const FastaInputOptions &fio)
std::ostream & operator<< (std::ostream &os, const FastaReader &fr)
std::ostream & operator<< (std::ostream &os, const FastaRecord &fastaRecord)
const FastaRecord * nextRecordOrDie (std::istream &iStream, const char *const errorMessage)
void dumpAminoAcidContentWPformat ()
void fastafmtAppendToRecordHeads ()
void fastaGrepName ()
void fastaHeadBytes ()
void fastaHeadRecords ()
void fastaPrintDuplicateSequences (std::istream &fastaIstream)
void fastaPrintDuplicateSeqs2Streams ()
void fastaTailBytes ()
void sortFastaByLength ()
void filterBlast8ResultEValueThreshold (double eValueThreshold)
void filterSameClassHighBlast (std::istream &trainStream, std::istream &blastResultsStream, const double &eValueThreshold)
void labeledBlastToOddsRatio (std::istream &trainStream, std::istream &blastResultsStream)
void printBlast8ResultNegLgEValues ()
void printNormalizedBlastSimilarity ()
void dumpBlastNNUtility (std::istream &trainStream, std::istream &utilityMatrixStream, std::istream &blastResultsStream)
void sprotGrepOC ()
void sprotToFasta ()
std::ostream & operator<< (std::ostream &os, const SprotReader &sprotReader)
std::ostream & operator<< (std::ostream &os, const TransfacBindingFactor &tbf)
std::ostream & operator<< (std::ostream &os, const TransfacTextLine &ttl)
std::ostream & operator<< (std::ostream &os, const ResidueIndexMap &rim)
bool operator== (const ResidueIndexMap &rim1, const ResidueIndexMap &rim2)
const std::string ResidueIndexMapAminoAlphabetProper ("ARNDCQEGHILKMFPSTWYV")
const ResidueIndexMap & residueIndexMapGuessedFromResidues (const std::string &residues)
const ResidueIndexMap & residueIndexMapFromName (const std::string &seqTypeName)
const ResidueIndexMap & residueIndexMapFromSeqType (const ResidueIndexMapPredefined::seqTypeT &seqType)
const ResidueIndexMap & residueIndexMapFromSeqType (const ResidueIndexMapPredefinedAlphabets::seqTypeT &seqType)
std::ostream & operator<< (std::ostream &os, const ResidueIndexWindow &riw)
const ResiduesIndexMap & residuesIndexMapFromName (const std::string &seqTypeName)
void writeResidueIndexMap (std::ostream &os, const std::string &alphabetProper, const std::string &alphabet, const bool &caseSensitive)
std::ostream & operator<< (std::ostream &os, const SerialNumbersForStrings &sns)
template<typename serialNumT >
std::ostream & operator<< (std::ostream &os, const SerialNumbersForStrings< serialNumT > &sns)
template<typename serialNumT >
std::ostream & operator<< (std::ostream &os, const SerialNumbersForStrings_accessCounting< serialNumT > &sns)
std::ostream & operator<< (std::ostream &os, const SortedStringSet &strSet)
void betacf (const double &a, const double &b, const double &x, mpfr_t &f_bcf)
void betai (const double &a, const double &b, const double &x)
void TtoP (const double &t_val, const double &dfree)
long double betacf (const long double &a, const long double &b, const long double &x)
long double betai (const long double &a, const long double &b, const long double &x)
long double TtoP (const long double &t_val, const long double &dfree)
double betacf (const double &a, const double &b, const double &x)
static void assertStringLooksOkay (const std::string &valuesString)
void pushbackLiteral (std::vector< double > &vec, const std::string &valuesString)
void pushbackLiteral (std::vector< int > &vec, const std::string &valuesString)
void pushbackLiteral (std::vector< unsigned > &vec, const std::string &valuesString)
void _pushbackLiteral (std::vector< double > &vec, const double &elem0,...)
void _pushbackLiteral (std::vector< int > &vec, const int &elem0,...)
void _pushbackLiteral (std::vector< unsigned > &vec, const unsigned &elem0,...)
std::ostream & operator<< (std::ostream &os, const StringStringDoubleMap &ssdm)
void testStringStringDoubleMap ()
std::vector< std::string > _toVector (const char *cString, const void *dummySentinel)
std::vector< std::string > _toVector (const char *cString0,...)
std::ostream & operator<< (std::ostream &oStream, const UnsignedDoubleMap &unsignedDoubleMap)
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::vector< std::vector< T > > &m)
std::ostream & operator<< (std::ostream &os, const StringSpecEnum &stringSpecEnum)
void writeRecountNeighborProbGraph ()
std::ostream & operator<< (std::ostream &oStream, const KnapsackObject &object)
std::ostream & operator<< (std::ostream &oStream, const KnapsackObjectVector &objectVector)
static const std::string _argvParserNullString ("")
Variables
const byte BitArrayMask [] = {0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80}
const byte BitArrayInverseMask [] = {0xfe, 0xfd, 0xfb, 0xf7, 0xef, 0xdf, 0xbf, 0x7f}
const byte BitArrayCumInverseMask [] = {0xfe, 0xfc, 0xf8, 0xf0, 0xe0, 0xc0, 0x80}
const byte BitMatrixMask [] = {128, 64, 32, 16, 8, 4, 2, 1}
const byte BitMatrixInverseMask [] = {127, 191, 223, 239, 247, 251, 253, 254}
const byte SymmetricBitMatrixMask [] = {1, 2, 4, 8, 16, 32, 64, 128}
const byte SymmetricBitMatrixInverseMask [] = {254, 253, 251, 247, 239, 223, 191, 127}
const LabeledIdentityDoubleMatrix labeledIdentityDoubleMatrix
const alignScoreT alignScoreTMin = INT_MIN
const AminoScoreIdentity aminoScoreIdentity
static const alignScoreT PAM120 [24][24]
static const alignScoreT PAM120MaxScore [24]
const AminoScorePam120 aminoScorePam120
const ResidueSimilarityAffineEdit residueSimilarityAffineEdit_amino (aminoResidueIndexMap)
static const char toComplement []
const ComplementDNA complementDNA
static FastafmtInputOptions defaultFastaInputOptions
const LabeledSequencePairPredicate_alwaysFalse labeledSequencePairPredicate_alwaysFalse
const LabeledSequencePairPredicate_namesEqual labeledSequencePairPredicate_namesEqual
const DNAArrayBit16_bases8 DNAArrayBit16_setMask [] = {0x0003, 0x000c, 0x0030, 0x00c0, 0x0300, 0x0c00, 0x3000, 0xc000}
const DNAArrayBit16_bases8 DNAArrayBit16_clearMask [] = {0xfffc, 0xfff3, 0xffcf, 0xff3f, 0xfcff, 0xf3ff, 0xcfff, 0x3fff}
const DNAArrayBit16_bases8 DNAArrayBit16_maxBases [] = {0x0000, 0x0003, 0x000f, 0x003f, 0x00ff, 0x03ff, 0x0fff, 0x3fff, 0xffff}
const unsigned DNAArrayBit16_numPossible []
const DNAArrayBit16_bases8 DNAArrayBit16_maxPossible []
const byte DNAArrayBit16_maxResidueIndex = 3
const byte DNAArrayBit16_maxLength = 8
static const byte setMask [] = {0x03, 0x0c, 0x30, 0xc0}
static const byte clearMask [] = {0xfc, 0xf3, 0xcf, 0x3f}
static const byte maxResidueIndex = 3
static const byte mask [] = {0xc0, 0x30, 0x0c, 0x03}
static const Sigma4FLArray::byte mask [] = {0xc0, 0x30, 0x0c, 0x03}
static FastaInputOptions defaultFastaInputOptions
static const ResidueColorGenebee residueColorGenebee
const ResidueIndexMap DNAProperResidueIndexMap ("acgt")
const ResidueIndexMap DNAWithNResidueIndexMap ("acgt", "acgtn")
const ResidueIndexMap DNAExtendedResidueIndexMap ("acgt", "acgtbdhkmnrsvwy")
const ResidueIndexMap RNAProperResidueIndexMap ("acgu")
const ResidueIndexMap aminoResidueIndexMap ("ARNDBCQEZGHILKMFPSTWYVUX")
const ResidueIndexMap A_to_Z_residueIndexMap ("abcdefghijklmnopqrstuvwxyz")
const ResidueIndexMap RNAResidueIndexMap ("acgu")
ResidueIndexMapTranslator standardRNACodonTranslator (RNAProperResidueIndexMap, aminoResidueIndexMap, "\ gca:A gcc:A gcg:A gcu:A aga:R agg:R cga:R cgc:R \ cgg:R cgu:R gac:D gau:D aac:N aau:N ugc:C ugu:C \ gaa:E gag:E caa:Q cag:Q gga:G ggc:G ggg:G ggu:G \ cau:H aua:I auc:I auu:I uua:L uug:L cua:L cuc:L \ cug:L cuu:L aaa:K aag:K aug:M uuc:F uuu:F cca:P \ ccc:P ccg:P ccu:P agc:S agu:S uca:S ucc:S ucg:S \ ucu:S aca:T acc:T acg:T acu:T ugg:W uac:Y uau:Y \ gua:V guc:V gug:V guu:V uaa:stop uag:stop uga:stop\ ")
const ResiduesIndexMap DNAProperResiduesIndexMap (DNAProperResidueIndexMap)
const ResiduesIndexMap RNAProperResiduesIndexMap (RNAProperResidueIndexMap)
const ResiduesIndexMap aminoResiduesIndexMap (aminoResidueIndexMap)
const StringUnaryPredicateAlwaysTrue stringUnaryPredicateAlwaysTrue
const StringUnaryPredicateAlwaysFalse stringUnaryPredicateAlwaysFalse
Typedef Documentation
_LD
typedef long double cbrc::_LD
Definition at line 36 of file Ttable-new.hh.
alignScoreT
typedef int cbrc::alignScoreT
Definition at line 22 of file AminoScore.hh.
byte
typedef unsigned char cbrc::byte
Definition at line 48 of file BitArray.hh.
DNAArrayBit16_bases8
typedef unsigned short int cbrc::DNAArrayBit16_bases8
Definition at line 37 of file DNAArrayBit16.hh.
match_resultT
typedef boost::match_results<std::string::const_iterator> cbrc::match_resultT
Definition at line 25 of file boostUtils.hh.
neighborhoodSizeT
typedef short unsigned int cbrc::neighborhoodSizeT
Definition at line 20 of file recountTypes.hh.
nodeIndexT
typedef unsigned int cbrc::nodeIndexT
Definition at line 18 of file graphTypes.hh.
probT
typedef double cbrc::probT
Definition at line 21 of file recountTypes.hh.
probVecT
typedef std::vector<probT> cbrc::probVecT
Definition at line 25 of file recountTypes.hh.
StringStringDoubleMapT
typedef std::map< std::pair<std::string, std::string>, double> cbrc::StringStringDoubleMapT
Definition at line 26 of file StringStringDoubleMap.hh.
stringVecT
typedef std::vector< std::string > cbrc::stringVecT
Definition at line 18 of file stlTypes.hh.
tagCountT
typedef double cbrc::tagCountT
Definition at line 22 of file recountTypes.hh.
tagIdT
typedef unsigned int cbrc::tagIdT
Definition at line 23 of file recountTypes.hh.
tagIdVecT
typedef std::vector<tagIdT> cbrc::tagIdVecT
Definition at line 26 of file recountTypes.hh.
uint
typedef unsigned int cbrc::uint
Definition at line 18 of file universalTypedefs.hh.
Function Documentation
_argvParserNullString() [1/2]
static const std::string cbrc::_argvParserNullString ("") static
Referenced by cbrc::ArgvParser::getArg(), cbrc::ArgvParser::getArgOrDie(), cbrc::ArgvParser::getEnumOrDie(), cbrc::ArgvParser::getFlag(), cbrc::ArgvParser::getOptOrDie(), cbrc::ArgvParser::isNullString(), cbrc::ArgvParser::set(), cbrc::ArgvParser::set(), cbrc::ArgvParser::setCautiously(), cbrc::ArgvParser::setCautiously(), cbrc::ArgvParser::setCautiouslyOrDie(), cbrc::ArgvParser::setCautiouslyOrDie(), cbrc::ArgvParser::setOrDie(), cbrc::ArgvParser::setOrDie(), and cbrc::ArgvParser::shift().
_argvParserNullString() [2/2]
static const std::string cbrc::_argvParserNullString ("") static
_pushbackLiteral() [1/3]
void cbrc::_pushbackLiteral (std::vector< double > & vec, const double & elem0, ...) inline
Definition at line 69 of file pushbackLiteralVariadic.hh.
_pushbackLiteral() [2/3]
void cbrc::_pushbackLiteral (std::vector< int > & vec, const int & elem0, ...) inline
Definition at line 71 of file pushbackLiteralVariadic.hh.
_pushbackLiteral() [3/3]
void cbrc::_pushbackLiteral (std::vector< unsigned > & vec, const unsigned & elem0, ...) inline
Definition at line 73 of file pushbackLiteralVariadic.hh.
_toVector() [1/2]
std::vector< std::string > cbrc::_toVector (const char * cString, const void * dummySentinel)
Definition at line 31 of file toVector.hh.
_toVector() [2/2]
std::vector< std::string > cbrc::_toVector (const char * cString0, ...)
Definition at line 38 of file toVector.hh.
adjacentCloseHamming()
void cbrc::adjacentCloseHamming ()
Definition at line 73 of file adjacentCloseHamming.cc.
References argFastaInputStreamPtr, argNumNeighbors, printCloseNeighbors(), and cbrc::FLEArray< T >::size().
Referenced by main().
advancePastMatchAtPoint()
bool cbrc::advancePastMatchAtPoint (std::string::const_iterator & point, const std::string::const_iterator & textEnd, const boost::regex & regex) inline
Definition at line 76 of file boostUtils.hh.
allPairsGlobalAffineScore()
void cbrc::allPairsGlobalAffineScore ()
Definition at line 29 of file allPairsGlobalAffineScore.cc.
References aminoResidueIndexMap, arg_bound, arg_filename0, arg_filename1, arg_useBound, cbrc::perlish::openOrDie(), seqs0, and seqs1.
Referenced by main().
allPairsHammingNeighbors()
void cbrc::allPairsHammingNeighbors (const bool & byPercent, const double & threshold, std::istream & fastaInputStream)
Definition at line 23 of file allPairsHammingNeighbors.cc.
References cbrc::HammingDistanceComputer::computeBounded(), and cbrc::FLEArray< T >::size().
Referenced by main().
allPairsNearestGlobalAffineScore()
void cbrc::allPairsNearestGlobalAffineScore ()
Definition at line 39 of file allPairsNearestGlobalAffineScore.cc.
References alignScoreTMin, cbrc::FLEArray< T >::begin(), cbrc::SeqGlobalAffineAligner::bestPossibleSuffixScore(), cbrc::FLEArray< T >::end(), FLEArrayIdentityPermutation(), ignoreSelf, seqs0, seqs1, and cbrc::FLEArray< T >::size().
Referenced by main().
assertStringLooksOkay()
static void cbrc::assertStringLooksOkay (const std::string & valuesString) static
Definition at line 36 of file pushbackLiteral.hh.
References cbrc::FLEArray< T >::find(), and GDB_ASSERTF.
betacf() [1/3]
double cbrc::betacf (const double & a, const double & b, const double & x)
Definition at line 36 of file Ttable.hh.
References h().
betacf() [2/3]
void cbrc::betacf (const double & a, const double & b, const double & x, mpfr_t & f_bcf)
Definition at line 37 of file Ttable-gmp.hh.
References h().
Referenced by betai(), and betai().
betacf() [3/3]
long double cbrc::betacf (const long double & a, const long double & b, const long double & x)
Definition at line 36 of file Ttable-long.hh.
References fabsl(), and h().
betai() [1/2]
double cbrc::betai (const double & a, const double & b, const double & x)
Definition at line 192 of file Ttable-gmp.hh.
References betacf().
Referenced by TtoP(), and TtoP().
betai() [2/2]
long double cbrc::betai (const long double & a, const long double & b, const long double & x)
Definition at line 90 of file Ttable-long.hh.
References betacf(), and lgammal().
bytesHashVal()
static size_t cbrc::bytesHashVal (const size_t numBytes, size_t * a) static
Definition at line 43 of file String2KeyHashtable.hh.
References BIT_ROTATE_LEFT.
Referenced by string2HashVal().
calculatePermutationSumOfSquaredDifferencesDistribution()
void cbrc::calculatePermutationSumOfSquaredDifferencesDistribution (const size_t permSize)
Definition at line 35 of file calculateRankCorrelationSignificance.cc.
References maxSumSquaredDifferences(), cbrc::FLEArray< T >::size(), sumSquaredDifferences(), and cbrc::FLEArray< T >::zero().
Referenced by main().
clusterByIdentity()
void cbrc::clusterByIdentity ()
Definition at line 36 of file clusterByIdentity.cc.
References aminoResidueIndexMap, aminoScoreIdentity, args, cbrc::FLEArray< T >::begin(), cbrc::SeqGlobalAffineAligner::bestPossibleSuffixScore(), cbrc::FLEArray< T >::end(), FLEArrayIdentityPermutation(), GDB_ASSERTF, and cbrc::FLEArray< T >::size().
Referenced by main().
computeAllPairsIdentity()
void cbrc::computeAllPairsIdentity ()
Definition at line 30 of file computeAllPairsIdentity.cc.
References A_to_Z_residueIndexMap, args, and cbrc::FLEArray< T >::size().
Referenced by main().
computeGlobalAffineIdentity()
void cbrc::computeGlobalAffineIdentity (const bool & doAlignment, std::istream & multifastaIstream)
Definition at line 19 of file computeGlobalAffineIdentity.cc.
References A_to_Z_residueIndexMap.
Referenced by main().
convertMultipleEdgePerLineToOneEdgePerLineFormat()
void cbrc::convertMultipleEdgePerLineToOneEdgePerLineFormat (std::istream & inStream)
Definition at line 19 of file convertMultipleEdgePerLineToOneEdgePerLineFormat.cc.
References cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLine(), and cbrc::perlish::split().
Referenced by main().
dumpAminoAcidContentWPformat()
void cbrc::dumpAminoAcidContentWPformat ()
Definition at line 26 of file fasta_dumpAminoAcidContentWPformat.cc.
References cbrc::ResidueIndexMap::alphabetProper(), aminoResidueIndexMap, arg_fastaIstreamPtr, cbrc::FLEArray< T >::begin(), cbrc::ResidueIndexMap::canonicalizeCase(), cbrc::FLEArray< T >::end(), and cbrc::FLEArray< T >::size().
Referenced by main().
dumpBlastNNUtility()
void cbrc::dumpBlastNNUtility (std::istream & trainStream, std::istream & utilityMatrixStream, std::istream & blastResultsStream)
Definition at line 28 of file runDumpBlastNNUtility.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), cbrc::Blast8ResultReader::has(), and cbrc::FLEArray< T >::size().
Referenced by main().
dumpNeighborList() [1/2]
void cbrc::dumpNeighborList (const SortedTagSet & tagId_to_seq, const RecountNeighborList neighborList)
Definition at line 23 of file dumpRecountNeighborProbGraphOnDisk_SortedTagSet.cc.
References cbrc::RecountNeighborList::id(), and cbrc::SortedTagSet::toString().
dumpNeighborList() [2/2]
void cbrc::dumpNeighborList (const TagSet & tagID_to_seq, const RecountNeighborList neighborList)
Definition at line 23 of file dumpRecountNeighborProbGraphOnDisk.cc.
References cbrc::RecountNeighborList::id(), cbrc::RecountTagIdProbPair::id(), cbrc::RecountTagIdProbPair::prob(), and cbrc::TagSet::toString().
Referenced by dumpRecountNeighborProbGraphOnDisk().
dumpRecountNeighborProbGraphOnDisk()
void cbrc::dumpRecountNeighborProbGraphOnDisk ()
Definition at line 36 of file dumpRecountNeighborProbGraphOnDisk.cc.
References arg_neighborsProbGraphOnDisk_ifstream, arg_tagSeqs_ifstream, cbrc::RecountNeighborProbGraphOnDisk::curNeighborList(), dumpNeighborList(), cbrc::RecountNeighborProbGraphOnDisk::readFirstNode(), and cbrc::RecountNeighborProbGraphOnDisk::readNextNode().
Referenced by main().
fastafmtAppendToRecordHeads()
void cbrc::fastafmtAppendToRecordHeads ()
Definition at line 22 of file fastaAppendToRecordHeads.cc.
References arg_fastaIstreamPtr, and arg_messageToAppend.
Referenced by main().
fastaGrepName()
void cbrc::fastaGrepName ()
Definition at line 24 of file fastaGrepName.cc.
References args.
Referenced by main().
fastaHeadBytes()
void cbrc::fastaHeadBytes ()
Definition at line 31 of file fastaHead.cc.
References args, and cbrc::FLEArray< T >::size().
Referenced by main().
fastaHeadRecords()
void cbrc::fastaHeadRecords ()
Definition at line 57 of file fastaHead.cc.
References args, cbrc::fastafmtFunctions::printRecords(), and cbrc::fastafmtFunctions::skipRecords().
Referenced by main().
fastaPrintDuplicateSeqs2Streams()
void cbrc::fastaPrintDuplicateSeqs2Streams ()
Definition at line 23 of file fastaPrintDuplicateSeqs2Streams.cc.
References args.
Referenced by main().
fastaPrintDuplicateSequences()
void cbrc::fastaPrintDuplicateSequences (std::istream & fastaIstream)
Definition at line 15 of file fastaPrintDuplicateSeqs.cc.
References cbrc::FLEArray< T >::size().
Referenced by main().
fastaTailBytes()
void cbrc::fastaTailBytes ()
Definition at line 31 of file fastaTail.cc.
References args, and cbrc::FLEArray< T >::size().
Referenced by main().
filterBlast8ResultEValueThreshold()
void cbrc::filterBlast8ResultEValueThreshold (double eValueThreshold)
Definition at line 24 of file filterBlast8ResultEValueThreshold.cc.
References cbrc::Blast8ResultReader::isBlastCommentLine(), cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLine(), and cbrc::perlish::split().
Referenced by main().
filterSameClassHighBlast()
void cbrc::filterSameClassHighBlast (std::istream & trainStream, std::istream & blastResultsStream, const double & eValueThreshold)
Definition at line 23 of file filterSameClassHighBlast.cc.
References cbrc::Blast8ResultReader::has(), and cbrc::FLEArray< T >::size().
Referenced by main().
FLArrayIdentityPermutation()
FLEArray< size_t > cbrc::FLArrayIdentityPermutation (size_t s) inline
Definition at line 30 of file FLArrayByIndexSortingPredicate.hh.
Referenced by FLArraySortedPermutation(), and testFLArrayByIndexSortingPredicate().
FLArraySortedPermutation() [1/2]
template<typename T > FLEArray< size_t > cbrc::FLArraySortedPermutation (FLArray< T > a)
Definition at line 48 of file FLArrayByIndexSortingPredicate.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), FLArrayIdentityPermutation(), and cbrc::FLEArray< T >::size().
FLArraySortedPermutation() [2/2]
template<typename T , typename op > FLEArray< size_t > cbrc::FLArraySortedPermutation (FLArray< T > a)
Definition at line 55 of file FLArrayByIndexSortingPredicate.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), FLArrayIdentityPermutation(), and cbrc::FLEArray< T >::size().
FLEArrayIdentityPermutation()
FLEArray< size_t > cbrc::FLEArrayIdentityPermutation (size_t s) inline
Definition at line 29 of file FLEArrayByIndexSortingPredicate.hh.
Referenced by allPairsNearestGlobalAffineScore(), cbrc::SimilaritySearchableSequences::bestMatch(), clusterByIdentity(), FLEArraySortedPermutation(), labeledBlastToOddsRatio(), listConnectedComponents(), printRandomRepresentativeFromEachConnectedComponent(), and runAllShortestEdgeLengthPaths().
FLEArraySortedPermutation() [1/2]
template<typename T > FLEArray< size_t > cbrc::FLEArraySortedPermutation (FLEArray< T > a)
Definition at line 47 of file FLEArrayByIndexSortingPredicate.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), FLEArrayIdentityPermutation(), and cbrc::FLEArray< T >::size().
FLEArraySortedPermutation() [2/2]
template<typename T , typename op > FLEArray< size_t > cbrc::FLEArraySortedPermutation (FLEArray< T > a)
Definition at line 54 of file FLEArrayByIndexSortingPredicate.hh.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), FLEArrayIdentityPermutation(), and cbrc::FLEArray< T >::size().
gdbExit()
void cbrc::gdbExit (const int status = -1) inline
Definition at line 196 of file gdbUtils.hh.
Referenced by cbrc::perlish::_fatalError(), and cbrc::perlish::die().
hasHighIdentityToDataset()
void cbrc::hasHighIdentityToDataset ()
Definition at line 38 of file hasHighIdentityToDataset.cc.
References aminoResidueIndexMap, aminoScoreIdentity, arg_fastaIstreamPtr1, arg_fastaIstreamPtr2, arg_identityThreshold, arg_lengthAdjustmentFactor, arg_outputAllPairs, arg_progressToStderr, cbrc::SeqGlobalAffineAligner::bestPossibleSuffixScore(), GDB_ASSERTF, and cbrc::FLEArray< T >::size().
Referenced by main().
isConstantLabeledSquareDoubleFLENumMatrixSymmetric()
void cbrc::isConstantLabeledSquareDoubleFLENumMatrixSymmetric ()
Definition at line 17 of file isConstantLabeledSquareDoubleFLENumMatrixSymmetric.cc.
Referenced by main().
labeledBlastToOddsRatio()
void cbrc::labeledBlastToOddsRatio (std::istream & trainStream, std::istream & blastResultsStream)
Definition at line 28 of file labeledBlastToOddsRatio.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), FLEArrayIdentityPermutation(), cbrc::Blast8ResultReader::has(), cbrc::smoothing::mergeIdenticalAdjacentX(), cbrc::smoothing::monotonicSmoothY(), and cbrc::FLEArray< T >::size().
Referenced by main().
LabeledSequenceUndefinedLabel()
const std::string cbrc::LabeledSequenceUndefinedLabel ("undefined")
Referenced by cbrc::LabeledSequence::label().
lg()
double cbrc::lg (const double x) inline
Definition at line 21 of file lg.hh.
listConnectedComponents()
void cbrc::listConnectedComponents (std::string filename)
Definition at line 21 of file listConnectedComponents.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), FLEArrayIdentityPermutation(), cbrc::OneEdgePerLineFormat::inputDelimiter(), cbrc::OneEdgePerLineFormat::numNodesInStream(), cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLine(), and cbrc::perlish::split().
Referenced by main().
log_transform()
template<typename ValType > void cbrc::log_transform (Matrix< ValType > & M) inline
Definition at line 30 of file MatrixAlgorithm.hh.
matchesPrefixOf() [1/2]
bool cbrc::matchesPrefixOf (const std::string & text, const boost::regex & pattern) inline
Definition at line 51 of file boostUtils.hh.
References matchesPrefixOf().
matchesPrefixOf() [2/2]
bool cbrc::matchesPrefixOf (const std::string::const_iterator & textBeg, const std::string::const_iterator & textEnd, const boost::regex & pattern) inline
Definition at line 59 of file boostUtils.hh.
Referenced by matchesPrefixOf(), and cbrc::perlish::split().
maxSumSquaredDifferences()
size_t cbrc::maxSumSquaredDifferences (const size_t permSize)
Definition at line 17 of file calculateRankCorrelationSignificance.cc.
Referenced by calculatePermutationSumOfSquaredDifferencesDistribution().
nextPrime() [1/3]
size_t cbrc::nextPrime (const size_t & num) inline
Definition at line 21 of file nextPrime.hh.
nextPrime() [2/3]
static int cbrc::nextPrime (size_t num) static
Definition at line 101 of file ChainHashtable.hh.
Referenced by cbrc::StringHashtable::StringHashtable().
nextPrime() [3/3]
static int cbrc::nextPrime (size_t num) static
Definition at line 29 of file String2KeyHashtable.hh.
nextRecordOrDie()
const FastaRecord * cbrc::nextRecordOrDie (std::istream & iStream, const char *const errorMessage)
observedMeanStdev_fromTrueCounts()
void cbrc::observedMeanStdev_fromTrueCounts ()
Definition at line 32 of file observedMeanStdev_fromTrueCounts.cc.
References arg_tagCountsFile, arg_tagNeighborProbGraphFile, arg_tagSeqsFile, cbrc::FLEArray< T >::size(), cbrc::RecountTagCounts::sum(), and cbrc::TagSet::toString().
Referenced by main().
operator<<() [1/69]
std::ostream & cbrc::operator<< (std::ostream & os, const Alignment & al)
Definition at line 266 of file Alignment.cc.
operator<<() [2/69]
std::ostream & cbrc::operator<< (std::ostream & os, const AminoScore & aScore)
Definition at line 30 of file AminoScore.cc.
operator<<() [3/69]
std::ostream & cbrc::operator<< (std::ostream & os, const BitArray & ba) inline
Definition at line 204 of file BitArray.hh.
References cbrc::BitArray::size().
operator<<() [4/69]
std::ostream & cbrc::operator<< (std::ostream & os, const BitMatrix & bm) inline
Definition at line 218 of file BitMatrix.hh.
operator<<() [5/69]
std::ostream & cbrc::operator<< (std::ostream & os, const Blast8Result & br) inline
Definition at line 53 of file Blast8ResultReader.hh.
operator<<() [6/69]
std::ostream & cbrc::operator<< (std::ostream & os, const Blast8ResultReader & brr)
Definition at line 108 of file Blast8ResultReader.cc.
operator<<() [7/69]
std::ostream & cbrc::operator<< (std::ostream & os, const ConstantLabeledSquareDoubleFLENumMatrix & mat)
Definition at line 147 of file ConstantLabeledSquareDoubleFLENumMatrix.cc.
operator<<() [8/69]
template<typename intType > std::ostream & cbrc::operator<< (std::ostream & os, const DeltaCompressedInt< intType > & dc)
Definition at line 131 of file DeltaCompressedInt.hh.
operator<<() [9/69]
std::ostream & cbrc::operator<< (std::ostream & os, const DiscreteCumulativeProbabilityDistribution & cmldist)
Definition at line 39 of file DiscreteCumulativeProbabilityDistribution.cc.
References cbrc::FLEArray< T >::size().
operator<<() [10/69]
template<size_t len> std::ostream & cbrc::operator<< (std::ostream & os, const DNAArrayBit16< len > & dnaArray)
Definition at line 223 of file DNAArrayBit16.hh.
References DNAProperResidueIndexMap.
operator<<() [11/69]
template<size_t len> std::ostream & cbrc::operator<< (std::ostream & os, const DNAArrayBit8< len > & dnaArray)
Definition at line 108 of file DNAArrayBit8.hh.
References DNAProperResidueIndexMap.
operator<<() [12/69]
std::ostream & cbrc::operator<< (std::ostream & os, const FastafmtReader & fr)
Definition at line 149 of file FastafmtReader.cc.
References cbrc::FLEArray< T >::size().
operator<<() [13/69]
std::ostream & cbrc::operator<< (std::ostream & os, const FastafmtRecord & fastafmtRecord) inline
Definition at line 87 of file FastafmtRecord.hh.
operator<<() [14/69]
std::ostream & cbrc::operator<< (std::ostream & os, const FastaReader & fr)
Definition at line 133 of file FastaReader.cc.
References cbrc::FLEArray< T >::size().
operator<<() [15/69]
std::ostream & cbrc::operator<< (std::ostream & os, const FastaRecord & fastaRecord)
Definition at line 28 of file FastaRecord.cc.
operator<<() [16/69]
template<typename T > std::ostream & cbrc::operator<< (std::ostream & os, const FLArray< T > & fla)
Definition at line 306 of file FLArray.hh.
References cbrc::FLEArray< T >::size().
operator<<() [17/69]
template<typename elemType > std::ostream & cbrc::operator<< (std::ostream & os, const FLDiagonalMatrix< elemType > & fldm)
Definition at line 63 of file FLDiagonalMatrix.hh.
operator<<() [18/69]
template<typename T > std::ostream & cbrc::operator<< (std::ostream & os, const FLEArray< T > & fla)
Definition at line 477 of file FLEArray.hh.
References cbrc::FLEArray< T >::size().
operator<<() [19/69]
template<typename T > std::ostream & cbrc::operator<< (std::ostream & os, const FLEMatrix< T > & flm)
Definition at line 417 of file FLEMatrix.hh.
References cbrc::FLEArray< T >::size().
operator<<() [20/69]
std::ostream & cbrc::operator<< (std::ostream & os, const FLENumArray< unsigned char > & fla) inline
Definition at line 488 of file FLEArray.hh.
References cbrc::FLEArray< T >::size().
operator<<() [21/69]
template<typename T > std::ostream & cbrc::operator<< (std::ostream & os, const FLESorted< T > & sl)
Definition at line 108 of file FLESorted.hh.
operator<<() [22/69]
template<typename T > std::ostream & cbrc::operator<< (std::ostream & os, const FLMatrix< T > & flm)
Definition at line 397 of file FLMatrix.hh.
References cbrc::FLEArray< T >::size().
operator<<() [23/69]
std::ostream & cbrc::operator<< (std::ostream & os, const FLNumArray< unsigned char > & fla) inline
Definition at line 296 of file FLArray.hh.
References cbrc::FLEArray< T >::size().
operator<<() [24/69]
template<typename T0 , typename T1 > std::ostream & cbrc::operator<< (std::ostream & os, const FLSorted2TypePairSet< T0, T1 > & pairSet) inline
Definition at line 155 of file FLSorted2TypePairSet.hh.
References cbrc::FLEArray< T >::size().
operator<<() [25/69]
template<typename T > std::ostream & cbrc::operator<< (std::ostream & os, const FLSorted< T > & sl)
Definition at line 89 of file FLSorted.hh.
operator<<() [26/69]
template<typename elemType > std::ostream & cbrc::operator<< (std::ostream & os, const FLStack< elemType > & fls)
Definition at line 75 of file FLStack.hh.
References cbrc::FLEArray< T >::size().
operator<<() [27/69]
std::ostream & cbrc::operator<< (std::ostream & os, const LabeledAsciiSeq & namedSeq) inline
Definition at line 100 of file LabeledAsciiSeq.hh.
operator<<() [28/69]
std::ostream & cbrc::operator<< (std::ostream & os, const LabeledSequence & ls)
Definition at line 66 of file LabeledSequence.cc.
References cbrc::FLEArray< T >::size(), and cbrc::perlish::splitByLength().
operator<<() [29/69]
template<typename elemT > std::ostream & cbrc::operator<< (std::ostream & os, const LabeledSquareFLENumMatrix< elemT > & mat)
Definition at line 140 of file LabeledSquareFLENumMatrix.hh.
References cbrc::FLEArray< T >::size().
operator<<() [30/69]
template<typename T > std::ostream & cbrc::operator<< (std::ostream & os, const MallocArray< T > & fla)
Definition at line 372 of file MallocArray.hh.
References cbrc::FLEArray< T >::size().
operator<<() [31/69]
std::ostream & cbrc::operator<< (std::ostream & os, const MallocNumArray< unsigned char > & fla) inline
Definition at line 362 of file MallocArray.hh.
References cbrc::FLEArray< T >::size().
operator<<() [32/69]
std::ostream & cbrc::operator<< (std::ostream & os, const MatrixGraph & mg)
Definition at line 111 of file MatrixGraph.cc.
operator<<() [33/69]
std::ostream & cbrc::operator<< (std::ostream & os, const NeighborListGraph & nlg)
Definition at line 144 of file NeighborListGraph.cc.
operator<<() [34/69]
std::ostream & cbrc::operator<< (std::ostream & os, const PermutationGenerator & pg)
Definition at line 51 of file PermutationGenerator.hh.
References cbrc::FLEArray< T >::size().
operator<<() [35/69]
template<typename XT , typename YT > std::ostream & cbrc::operator<< (std::ostream & os, const Point2D< XT, YT > & point)
Definition at line 95 of file Point2D.hh.
operator<<() [36/69]
std::ostream & cbrc::operator<< (std::ostream & os, const ResidueIndexMap & rim)
Definition at line 438 of file ResidueIndexMap.cc.
References cbrc::ResidueIndexMap::alphabet(), cbrc::ResidueIndexMap::alphabetProper(), and cbrc::ResidueIndexMap::caseSensitive().
operator<<() [37/69]
std::ostream & cbrc::operator<< (std::ostream & os, const ResidueIndexWindow & riw) inline
Definition at line 95 of file ResidueIndexWindow.hh.
operator<<() [38/69]
std::ostream & cbrc::operator<< (std::ostream & os, const SerialNumbersForStrings & sns)
Definition at line 21 of file SerialNumbersForStrings.cc.
References cbrc::FLEArray< T >::size().
operator<<() [39/69]
template<typename serialNumT > std::ostream & cbrc::operator<< (std::ostream & os, const SerialNumbersForStrings< serialNumT > & sns) inline
Definition at line 175 of file SerialNumbersForStrings.hh.
References cbrc::FLEArray< T >::size().
operator<<() [40/69]
template<typename serialNumT > std::ostream & cbrc::operator<< (std::ostream & os, const SerialNumbersForStrings_accessCounting< serialNumT > & sns) inline
Definition at line 179 of file SerialNumbersForStrings_accessCounting.hh.
References cbrc::FLEArray< T >::size().
operator<<() [41/69]
std::ostream & cbrc::operator<< (std::ostream & os, const SortedStringSet & strSet) inline
Definition at line 122 of file SortedStringSet.hh.
operator<<() [42/69]
std::ostream & cbrc::operator<< (std::ostream & os, const SortedTagSet & tagSet) inline
Definition at line 121 of file SortedTagSet.hh.
operator<<() [43/69]
std::ostream & cbrc::operator<< (std::ostream & os, const SprotReader & sprotReader)
Definition at line 154 of file SprotReader.cc.
operator<<() [44/69]
template<typename T > std::ostream & cbrc::operator<< (std::ostream & os, const std::vector< std::vector< T > > & m)
Definition at line 82 of file vectorMatrix.hh.
References cbrc::FLEArray< T >::size().
operator<<() [45/69]
template<typename ValT > std::ostream & cbrc::operator<< (std::ostream & os, const String2KeyHashtable< ValT > & skh)
Definition at line 451 of file String2KeyHashtable.hh.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
operator<<() [46/69]
std::ostream & cbrc::operator<< (std::ostream & os, const StringHashtable & skh) inline
Definition at line 461 of file StringHashtable.hh.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
operator<<() [47/69]
std::ostream & cbrc::operator<< (std::ostream & os, const StringHashtableIterator & skh) inline
Definition at line 454 of file StringHashtable.hh.
operator<<() [48/69]
template<typename ValT > std::ostream & cbrc::operator<< (std::ostream & os, const StringKeyHashIterator< ValT > & skh)
Definition at line 398 of file StringKeyHashtable.hh.
operator<<() [49/69]
template<typename ValT > std::ostream & cbrc::operator<< (std::ostream & os, const StringKeyHashtable< ValT > & skh)
Definition at line 405 of file StringKeyHashtable.hh.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
operator<<() [50/69]
std::ostream & cbrc::operator<< (std::ostream & os, const StringSpecEnum & stringSpecEnum) inline
Definition at line 83 of file StringSpecEnum.hh.
operator<<() [51/69]
std::ostream & cbrc::operator<< (std::ostream & os, const StringStringDoubleMap & ssdm)
Definition at line 57 of file StringStringDoubleMap.hh.
operator<<() [52/69]
std::ostream & cbrc::operator<< (std::ostream & os, const SymmetricBitMatrix & sbm) inline
Definition at line 145 of file SymmetricBitMatrix.hh.
operator<<() [53/69]
std::ostream & cbrc::operator<< (std::ostream & os, const TagSet & tagSet) inline
Definition at line 184 of file TagSet.hh.
operator<<() [54/69]
std::ostream & cbrc::operator<< (std::ostream & os, const TransfacBindingFactor & tbf)
Definition at line 57 of file TransfacBindingFactor.cc.
operator<<() [55/69]
std::ostream & cbrc::operator<< (std::ostream & os, const TransfacTextLine & ttl)
Definition at line 37 of file TransfacTextLine.cc.
References cbrc::FLEArray< T >::empty().
operator<<() [56/69]
template<typename T > std::ostream & cbrc::operator<< (std::ostream & os, const TrivialHistogram< T > & histo) inline
Definition at line 70 of file TrivialHistogram.hh.
References cbrc::FLEArray< T >::size().
operator<<() [57/69]
template<typename T > std::ostream & cbrc::operator<< (std::ostream & os, const TrivialUnsignedHistogram< T > & histo) inline
Definition at line 67 of file TrivialUnsignedHistogram.hh.
References cbrc::FLEArray< T >::size().
operator<<() [58/69]
std::ostream & cbrc::operator<< (std::ostream & os, const UInt31 & ui31)
Definition at line 71 of file UInt31.hh.
operator<<() [59/69]
std::ostream & cbrc::operator<< (std::ostream & os, const UInt332 & ui332)
Definition at line 90 of file UInt332.hh.
operator<<() [60/69]
template<typename XT , typename YT , typename WT > std::ostream & cbrc::operator<< (std::ostream & os, const WeightedPoint2D< XT, YT, WT > & point)
Definition at line 98 of file WeightedPoint2D.hh.
operator<<() [61/69]
std::ostream & cbrc::operator<< (std::ostream & oStream, const FastaInputOptions & fio) inline
Definition at line 118 of file FastaInputOptions.hh.
References cbrc::FastaInputOptions::defaultSeqCharFilter().
operator<<() [62/69]
std::ostream & cbrc::operator<< (std::ostream & oStream, const KnapsackObject & object) inline
Definition at line 54 of file KnapsackObject.hh.
operator<<() [63/69]
std::ostream & cbrc::operator<< (std::ostream & oStream, const KnapsackObjectVector & objectVector) inline
Definition at line 83 of file KnapsackObjectVector.hh.
References cbrc::FLEArray< T >::size().
operator<<() [64/69]
std::ostream & cbrc::operator<< (std::ostream & oStream, const RecountNeighborList & tagNode) inline
Definition at line 82 of file RecountNeighborList.hh.
operator<<() [65/69]
std::ostream & cbrc::operator<< (std::ostream & oStream, const RecountTagCounts & tagCounts) inline
Definition at line 137 of file RecountTagCounts.hh.
operator<<() [66/69]
std::ostream & cbrc::operator<< (std::ostream & oStream, const RecountTagIdProbPair & pair) inline
Definition at line 45 of file RecountTagIdProbPair.hh.
operator<<() [67/69]
std::ostream & cbrc::operator<< (std::ostream & oStream, const Sigma4bitPackedIdx & packedIdx) inline
Definition at line 50 of file Sigma4bitPackedIdx.hh.
operator<<() [68/69]
std::ostream & cbrc::operator<< (std::ostream & oStream, const Sigma4FLArray & array) inline
Definition at line 166 of file Sigma4FLArray.hh.
References cbrc::Sigma4FLArray::size().
operator<<() [69/69]
std::ostream & cbrc::operator<< (std::ostream & oStream, const UnsignedDoubleMap & unsignedDoubleMap) inline
Definition at line 68 of file UnsignedDoubleMap.hh.
References cbrc::FLEArray< T >::begin(), and cbrc::FLEArray< T >::end().
operator==()
bool cbrc::operator== (const ResidueIndexMap & rim1, const ResidueIndexMap & rim2) inline
Definition at line 196 of file ResidueIndexMap.hh.
pearson_corr()
template<typename ValType , typename ResultPrecision > ResultPrecision cbrc::pearson_corr (Matrix< ValType > & M, const size_t pos1, const size_t pos2, size_t * valid_data, bool ColumnCompare = 0) inline
Definition at line 47 of file MatrixAlgorithm.hh.
print()
void cbrc::print (int elem)
Definition at line 21 of file testForEach.cc.
Referenced by testForEach().
printBlast8ResultNegLgEValues()
void cbrc::printBlast8ResultNegLgEValues ()
Definition at line 21 of file printBlast8ResultNegLgEValues.cc.
References cbrc::Blast8ResultReader::printNegLgEValues().
Referenced by main().
printCloseNeighbors()
void cbrc::printCloseNeighbors (const BoundedLenFifoVector< LabeledAsciiSeq > & neighbors)
Definition at line 36 of file adjacentCloseHamming.cc.
References argByPercent, argFlushLeft, argThreshold, neighbors(), and cbrc::FLEArray< T >::size().
Referenced by adjacentCloseHamming().
printIfHtml()
void cbrc::printIfHtml (const std::string & message)
Definition at line 35 of file runGlobalAffineAlignment.cc.
References outputHtml.
Referenced by runGlobalAffineAlignment().
printNormalizedBlastSimilarity()
void cbrc::printNormalizedBlastSimilarity ()
Definition at line 21 of file printNormalizedBlastSimilarity.cc.
References cbrc::Blast8ResultReader::printNormalizedSimilarity().
Referenced by main().
printRandomRepresentativeFromEachConnectedComponent()
void cbrc::printRandomRepresentativeFromEachConnectedComponent (std::string filename)
Definition at line 25 of file printRandomRepresentativeFromEachConnectedComponent.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), FLEArrayIdentityPermutation(), cbrc::OneEdgePerLineFormat::inputDelimiter(), cbrc::OneEdgePerLineFormat::numNodesInStream(), cbrc::FLEArrayFunctions::randomElement(), cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLine(), and cbrc::perlish::split().
Referenced by main().
pushbackLiteral() [1/3]
void cbrc::pushbackLiteral (std::vector< double > & vec, const std::string & valuesString) inline
Definition at line 65 of file pushbackLiteral.hh.
pushbackLiteral() [2/3]
void cbrc::pushbackLiteral (std::vector< int > & vec, const std::string & valuesString) inline
Definition at line 66 of file pushbackLiteral.hh.
pushbackLiteral() [3/3]
void cbrc::pushbackLiteral (std::vector< unsigned > & vec, const std::string & valuesString) inline
Definition at line 67 of file pushbackLiteral.hh.
ResidueIndexMapAminoAlphabetProper()
const std::string cbrc::ResidueIndexMapAminoAlphabetProper ("ARNDCQEGHILKMFPSTWYV")
residueIndexMapFromName()
const ResidueIndexMap & cbrc::residueIndexMapFromName (const std::string & seqTypeName) inline
Definition at line 73 of file ResidueIndexMapPredefined.hh.
References aminoResidueIndexMap, DNAProperResidueIndexMap, and RNAProperResidueIndexMap.
residueIndexMapFromSeqType() [1/2]
const ResidueIndexMap & cbrc::residueIndexMapFromSeqType (const ResidueIndexMapPredefined::seqTypeT & seqType) inline
Definition at line 86 of file ResidueIndexMapPredefined.hh.
References cbrc::ResidueIndexMapPredefined::amino, aminoResidueIndexMap, cbrc::ResidueIndexMapPredefined::DNA, DNAProperResidueIndexMap, cbrc::ResidueIndexMapPredefined::RNA, and RNAProperResidueIndexMap.
residueIndexMapFromSeqType() [2/2]
const ResidueIndexMap & cbrc::residueIndexMapFromSeqType (const ResidueIndexMapPredefinedAlphabets::seqTypeT & seqType) inline
Definition at line 80 of file ResidueIndexMapPredefinedAlphabets.hh.
References cbrc::ResidueIndexMapPredefinedAlphabets::amino, aminoResidueIndexMap, cbrc::ResidueIndexMapPredefinedAlphabets::DNA, DNAProperResidueIndexMap, cbrc::ResidueIndexMapPredefinedAlphabets::RNA, and RNAResidueIndexMap.
residueIndexMapGuessedFromResidues()
const ResidueIndexMap & cbrc::residueIndexMapGuessedFromResidues (const std::string & residues) inline
Definition at line 63 of file ResidueIndexMapPredefined.hh.
References aminoResidueIndexMap, DNAProperResidueIndexMap, DNAWithNResidueIndexMap, and RNAProperResidueIndexMap.
Referenced by cbrc::LabeledSequence::LabeledSequence().
residueSimilarityAffineEdit_DNA()
const ResidueSimilarityAffineEdit cbrc::residueSimilarityAffineEdit_DNA (DNAExtendedResidueIndexMap)
residuesIndexMapFromName()
const ResiduesIndexMap & cbrc::residuesIndexMapFromName (const std::string & seqTypeName) inline
Definition at line 97 of file ResiduesIndexMap.hh.
References aminoResiduesIndexMap, DNAProperResiduesIndexMap, and RNAProperResiduesIndexMap.
runAddAlignmentToHtml()
void cbrc::runAddAlignmentToHtml (std::istream & dataSequencesStream, std::istream & queryHtmlStream, std::istream & querySequencesStream, const std::string & outputPathnameForLinking, std::ostream & outputStream)
Definition at line 38 of file runAddAlignmentToHtml.cc.
References cbrc::perlish::alwaysFalse(), aminoResidueIndexMap, aminoScorePam120, cbrc::htmlStrings::anchorHrefBasic(), cbrc::htmlStrings::anchorName(), cbrc::htmlStrings::end(), cbrc::htmlStrings::header(), opts, cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLines(), and cbrc::perlish::split().
Referenced by main().
runAddIdenticalToHtml()
void cbrc::runAddIdenticalToHtml (std::istream & dataSequencesStream, std::istream & queryHtmlStream, std::istream & querySequencesStream, const std::string & outputPathnameForLinking, std::ostream & outputStream)
Definition at line 44 of file runAddIdenticalToHtml.cc.
References aminoResidueIndexMap, aminoScoreIdentity, cbrc::htmlStrings::end(), cbrc::htmlStrings::header(), opts, cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLines(), and cbrc::perlish::split().
Referenced by main().
runAllShortestEdgeLengthPaths()
void cbrc::runAllShortestEdgeLengthPaths (bool summarizeOnly)
Definition at line 15 of file runAllShortestEdgeLengthPaths.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), FLEArrayIdentityPermutation(), cbrc::FLEArray< T >::size(), and cbrc::FLEArray< T >::zero().
Referenced by main().
runGlobalAffineAlignment()
void cbrc::runGlobalAffineAlignment ()
Definition at line 39 of file runGlobalAffineAlignment.cc.
References aminoResidueIndexMap, fastaIstreamPtr, markColumns, markDifferent, outputHtml, and printIfHtml().
Referenced by main().
runGlobalAffineNearestClass()
void cbrc::runGlobalAffineNearestClass ()
Definition at line 29 of file runGlobalAffineNearestClass.cc.
References arg_filename0, arg_filename1, arg_ignoreNotSelf, labeledSequencePairPredicate_namesEqual, cbrc::perlish::openOrDie(), seqs0, and seqs1.
Referenced by main().
runGlobalAffineSearcher()
void cbrc::runGlobalAffineSearcher (const std::string & filename0, const std::string & filename1, const bool & ignoreSelf)
Definition at line 18 of file runGlobalAffineNearestClassDiff.cc.
References ignoreSelf, labeledSequencePairPredicate_namesEqual, cbrc::perlish::openOrDie(), seqs0, seqs1, and cbrc::FLEArray< T >::size().
Referenced by main().
runRecountExpectationMatchingTagCorrector()
void cbrc::runRecountExpectationMatchingTagCorrector ()
Definition at line 26 of file runRecountExpectationMatchingTagCorrector.cc.
References arg_roundsToWait, arg_tagCountsFile, arg_tagNeighborProbGraphFile, arg_tagSeqsFile, cbrc::RecountTagCounts::min(), and cbrc::FLEArray< T >::print().
Referenced by main().
runSimilaritySearchableSequences()
void cbrc::runSimilaritySearchableSequences (std::istream & sequencesStream, std::istream & queryStream, const alignScoreT & loosenessFactor, std::string & outputFormat, bool & markDifferent)
Definition at line 29 of file runSimilaritySearchableSequences.cc.
References aminoResidueIndexMap, aminoScorePam120, markDifferent, and cbrc::FLEArray< T >::size().
Referenced by main().
size_tToBinaryRepresentationString()
std::string cbrc::size_tToBinaryRepresentationString (size_t a)
Definition at line 22 of file size_tToBinaryRepresentationString.hh.
smoothMinPoints() [1/2]
void cbrc::smoothMinPoints (size_t minSampleSize)
Definition at line 23 of file smoothMinSampleSize.cc.
References cbrc::smoothing::averageYCoordinatesWithNeighboringPointsUntilMinSampleSizeAttained(), cbrc::smoothing::mergeIdenticalAdjacentX(), cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLines(), cbrc::smoothing::sortInPlaceAscendingValue(), cbrc::perlish::split(), cbrc::perlish::toDouble(), and cbrc::perlish::toUnsignedInt().
Referenced by main().
smoothMinPoints() [2/2]
void cbrc::smoothMinPoints (size_t minSampleSize, const bool positiveCorrelation)
Definition at line 27 of file smoothMonotonically.cc.
References cbrc::smoothing::monotonicSmoothY(), cbrc::FLEArray< T >::size(), cbrc::perlish::slurpLines(), cbrc::smoothing::sortInPlaceAscendingValue(), cbrc::perlish::split(), cbrc::perlish::toDouble(), and cbrc::perlish::toUnsignedInt().
sortFastaByLength()
void cbrc::sortFastaByLength ()
Definition at line 24 of file sortFastaByLength.cc.
References args, and cbrc::FLEArray< T >::size().
Referenced by main().
sprotGrepOC()
void cbrc::sprotGrepOC ()
Definition at line 24 of file sprotGrepOC.cc.
References args, and cbrc::FLEArray< T >::find().
Referenced by main().
sprotToFasta()
void cbrc::sprotToFasta ()
Definition at line 23 of file sprotToFasta.cc.
References args, and cbrc::FLEArray< T >::print().
Referenced by main().
string2HashVal()
static size_t cbrc::string2HashVal (const std::string & s0, const std::string & s1) static
Definition at line 62 of file String2KeyHashtable.hh.
References BIT_ROTATE_LEFT, and bytesHashVal().
Referenced by cbrc::String2KeyHashtable< ValT >::add2(), cbrc::String2KeyHashtable< ValT >::has(), cbrc::String2KeyAndValue< ValT >::hashVal(), cbrc::String2KeyHashtable< ValT >::operator()(), and cbrc::String2KeyHashtable< ValT >::ref().
sumSquaredDifferences()
size_t cbrc::sumSquaredDifferences (const FLENumArray< size_t > & a)
Definition at line 26 of file calculateRankCorrelationSignificance.cc.
References cbrc::FLEArray< T >::size().
Referenced by calculatePermutationSumOfSquaredDifferencesDistribution().
testCanStatFile()
void cbrc::testCanStatFile (std::string filename)
Definition at line 18 of file testCanStatFile.cc.
References cbrc::perlish::canStatFile().
Referenced by main().
testConnectedComponentOnlineComputer()
void cbrc::testConnectedComponentOnlineComputer (const bool & verify)
Definition at line 18 of file testConnectedComponentOnlineComputer.cc.
References cbrc::FLEArray< T >::size().
Referenced by main().
testFLArray()
void cbrc::testFLArray ()
Definition at line 30 of file testFLArrayCast.cc.
References cbrc::FLEArray< T >::size(), and vectorSum().
Referenced by main().
testFLArrayByIndexSortingPredicate()
void cbrc::testFLArrayByIndexSortingPredicate ()
Definition at line 18 of file testFLArrayByIndexSortingPredicate.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), FLArrayIdentityPermutation(), and cbrc::FLEArray< T >::size().
Referenced by main().
testForEach()
void cbrc::testForEach ()
Definition at line 25 of file testForEach.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), and print().
Referenced by main().
testMapSpeed()
void cbrc::testMapSpeed ()
Definition at line 18 of file testMapSpeed.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), cbrc::FLEArray< T >::size(), and cbrc::perlish::slurpLines().
Referenced by main().
testNumberStringFunctions()
void cbrc::testNumberStringFunctions ()
Definition at line 18 of file testNumberStringFunctions.cc.
References cbrc::perlish::looksLikeReal(), cbrc::perlish::looksLikeUnsignedInt(), cbrc::perlish::toDouble(), and cbrc::perlish::toUnsignedInt().
Referenced by main().
testPlatformMacro()
void cbrc::testPlatformMacro ()
Definition at line 17 of file testPlatformMacro.cc.
Referenced by main().
testSeqGlobalAffineAligner()
void cbrc::testSeqGlobalAffineAligner ()
Definition at line 28 of file testSeqGlobalAffineAligner.cc.
References aminoResidueIndexMap, aminoScorePam120, arg_fastaIstreamPtr, cbrc::SeqGlobalAffineAligner::bestPossibleSuffixScore(), and cbrc::FLEArray< T >::size().
Referenced by main().
testStayFiniteLog()
void cbrc::testStayFiniteLog ()
Definition at line 18 of file testStayFiniteLog.cc.
Referenced by main().
testString2KeyHashtable()
void cbrc::testString2KeyHashtable ()
Definition at line 18 of file testString2KeyHashtable.cc.
Referenced by main().
testStringKeyHashtableSpeed()
void cbrc::testStringKeyHashtableSpeed ()
Definition at line 19 of file testStringKeyHashtableSpeed.cc.
References cbrc::FLEArray< T >::begin(), cbrc::FLEArray< T >::end(), cbrc::FLEArray< T >::size(), and cbrc::perlish::slurpLines().
Referenced by main().
testStringStringDoubleMap()
void cbrc::testStringStringDoubleMap ()
Definition at line 18 of file testStringStringDoubleMap.cc.
Referenced by main().
TtoP() [1/2]
double cbrc::TtoP (const double & t_val, const double & dfree)
Definition at line 300 of file Ttable-gmp.hh.
References betai(), and isnan().
Referenced by main().
TtoP() [2/2]
long double cbrc::TtoP (const long double & t_val, const long double & dfree)
Definition at line 108 of file Ttable-long.hh.
References betai(), and isnan().
vectorSum()
double cbrc::vectorSum (std::vector< double > a)
Definition at line 21 of file testFLArrayCast.cc.
References cbrc::FLEArray< T >::size().
Referenced by testFLArray().
writeRecountNeighborProbGraph()
void cbrc::writeRecountNeighborProbGraph ()
Definition at line 28 of file writeRecountNeighborProbGraph.cc.
References arg_outfile, arg_tagNeighborsIstreamPtr, arg_tagSeqsIstreamPtr, and cbrc::FLEArray< T >::write().
Referenced by main().
writeResidueIndexMap()
void cbrc::writeResidueIndexMap (std::ostream & os, const std::string & alphabetProper, const std::string & alphabet, const bool & caseSensitive)
Definition at line 20 of file writeResidueIndexMap.cc.
References cbrc::ResidueIndexMap::write().
Referenced by main().
Variable Documentation
A_to_Z_residueIndexMap
const ResidueIndexMap cbrc::A_to_Z_residueIndexMap("abcdefghijklmnopqrstuvwxyz") ("abcdefghijklmnopqrstuvwxyz")
Referenced by computeAllPairsIdentity(), and computeGlobalAffineIdentity().
alignScoreTMin
const alignScoreT cbrc::alignScoreTMin = INT_MIN
Definition at line 23 of file AminoScore.hh.
Referenced by cbrc::GlobalAffineIdentityAligner::alignment(), cbrc::SeqGlobalAffineAligner::alignment(), allPairsNearestGlobalAffineScore(), cbrc::SeqGlobalAffineAligner::prefixScoreBounded(), cbrc::GlobalAffineIdentityAligner::score(), cbrc::SeqGlobalAffineAligner::score(), cbrc::SeqGlobalAffineAligner::scoreBounded(), and cbrc::GlobalAffineIdentityAligner::scoreBounded().
aminoResidueIndexMap
const ResidueIndexMap cbrc::aminoResidueIndexMap ("ARNDBCQEZGHILKMFPSTWYVUX")
Referenced by allPairsGlobalAffineScore(), clusterByIdentity(), dumpAminoAcidContentWPformat(), cbrc::ResidueIndexMapPredefined::guessSeqType(), cbrc::ResidueIndexMapPredefinedAlphabets::guessSeqType(), hasHighIdentityToDataset(), cbrc::AminoScorePam120::residueIndexMap(), residueIndexMapFromName(), residueIndexMapFromSeqType(), residueIndexMapFromSeqType(), residueIndexMapGuessedFromResidues(), cbrc::ResidueIndexMapTranslator::ResidueIndexMapTranslator(), runAddAlignmentToHtml(), runAddIdenticalToHtml(), runGlobalAffineAlignment(), runSimilaritySearchableSequences(), and testSeqGlobalAffineAligner().
aminoResiduesIndexMap
const ResiduesIndexMap cbrc::aminoResiduesIndexMap(aminoResidueIndexMap) (aminoResidueIndexMap)
Referenced by residuesIndexMapFromName().
aminoScoreIdentity
const AminoScoreIdentity cbrc::aminoScoreIdentity
Definition at line 70 of file AminoScoreIdentity.hh.
Referenced by clusterByIdentity(), hasHighIdentityToDataset(), and runAddIdenticalToHtml().
aminoScorePam120
const AminoScorePam120 cbrc::aminoScorePam120
Definition at line 80 of file AminoScorePam120.hh.
Referenced by main(), runAddAlignmentToHtml(), runSimilaritySearchableSequences(), and testSeqGlobalAffineAligner().
BitArrayCumInverseMask
const byte cbrc::BitArrayCumInverseMask[] = {0xfe, 0xfc, 0xf8, 0xf0, 0xe0, 0xc0, 0x80}
Definition at line 52 of file BitArray.hh.
Referenced by cbrc::BitArray::trueIterator::operator++().
BitArrayInverseMask
const byte cbrc::BitArrayInverseMask[] = {0xfe, 0xfd, 0xfb, 0xf7, 0xef, 0xdf, 0xbf, 0x7f}
Definition at line 51 of file BitArray.hh.
Referenced by cbrc::BitArray::clear(), and cbrc::BitArray::clearFast().
BitArrayMask
const byte cbrc::BitArrayMask[] = {0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80}
Definition at line 50 of file BitArray.hh.
Referenced by cbrc::BitArray::operator[](), cbrc::BitArray::set(), and cbrc::BitArray::setFast().
BitMatrixInverseMask
const byte cbrc::BitMatrixInverseMask[] = {127, 191, 223, 239, 247, 251, 253, 254}
Definition at line 41 of file BitMatrix.hh.
Referenced by cbrc::BitMatrix::clear(), cbrc::BitMatrixFast::clear(), and cbrc::BitMatrix::clearFast().
BitMatrixMask
const byte cbrc::BitMatrixMask[] = {128, 64, 32, 16, 8, 4, 2, 1}
Definition at line 40 of file BitMatrix.hh.
Referenced by cbrc::BitMatrix::operator()(), cbrc::BitMatrixFast::operator()(), cbrc::BitMatrix::operator()(), cbrc::BitMatrixFast::operator()(), cbrc::BitMatrixFast::set(), and cbrc::BitMatrix::setFast().
clearMask
const byte cbrc::clearMask[] = {0xfc, 0xf3, 0xcf, 0x3f} static
Definition at line 29 of file DNAArrayBit8.hh.
Referenced by cbrc::DNAArrayBit8< len >::set().
complementDNA
const ComplementDNA cbrc::complementDNA
Definition at line 64 of file ComplementDNA.hh.
defaultFastaInputOptions [1/2]
FastafmtInputOptions cbrc::defaultFastaInputOptions static
Definition at line 65 of file FastafmtInputOptions.hh.
defaultFastaInputOptions [2/2]
FastaInputOptions cbrc::defaultFastaInputOptions static
Definition at line 115 of file FastaInputOptions.hh.
DNAArrayBit16_clearMask
const DNAArrayBit16_bases8 cbrc::DNAArrayBit16_clearMask[] = {0xfffc, 0xfff3, 0xffcf, 0xff3f, 0xfcff, 0xf3ff, 0xcfff, 0x3fff}
Definition at line 40 of file DNAArrayBit16.hh.
Referenced by cbrc::DNAArrayBit16< len >::set().
DNAArrayBit16_maxBases
const DNAArrayBit16_bases8 cbrc::DNAArrayBit16_maxBases[] = {0x0000, 0x0003, 0x000f, 0x003f, 0x00ff, 0x03ff, 0x0fff, 0x3fff, 0xffff}
Definition at line 41 of file DNAArrayBit16.hh.
Referenced by cbrc::DNAArrayBit16< len >::getMaxBases().
DNAArrayBit16_maxLength
const byte cbrc::DNAArrayBit16_maxLength = 8
Definition at line 50 of file DNAArrayBit16.hh.
DNAArrayBit16_maxPossible
const DNAArrayBit16_bases8 cbrc::DNAArrayBit16_maxPossible[]
Initial value:
=
  { 0, 3, 15, 63, 255, 1023, 4095, 16383, 65535 }
Definition at line 46 of file DNAArrayBit16.hh.
Referenced by cbrc::DNAArrayBit16< len >::const_iterator::operator++().
DNAArrayBit16_maxResidueIndex
const byte cbrc::DNAArrayBit16_maxResidueIndex = 3
Definition at line 49 of file DNAArrayBit16.hh.
Referenced by cbrc::DNAArrayBit16< len >::operator++().
DNAArrayBit16_numPossible
const unsigned cbrc::DNAArrayBit16_numPossible[]
Initial value:
=
  { 0, 4, 16, 64, 256, 1024, 4096, 16384, 65536 }
Definition at line 43 of file DNAArrayBit16.hh.
Referenced by cbrc::DNAArrayBit16< len >::operator++().
DNAArrayBit16_setMask
const DNAArrayBit16_bases8 cbrc::DNAArrayBit16_setMask[] = {0x0003, 0x000c, 0x0030, 0x00c0, 0x0300, 0x0c00, 0x3000, 0xc000}
Definition at line 39 of file DNAArrayBit16.hh.
Referenced by cbrc::DNAArrayBit16< len >::operator()().
DNAExtendedResidueIndexMap
const ResidueIndexMap cbrc::DNAExtendedResidueIndexMap ("acgt" , "acgtbdhkmnrsvwy")
DNAProperResidueIndexMap
const ResidueIndexMap cbrc::DNAProperResidueIndexMap ("acgt")
Referenced by cbrc::DNAArrayBit16< len >::getResidues(), cbrc::ResidueIndexMapPredefined::guessSeqType(), cbrc::ResidueIndexMapPredefinedAlphabets::guessSeqType(), operator<<(), operator<<(), cbrc::DNAArrayBit16< len >::operator==(), cbrc::DNAArrayBit8< len >::operator==(), residueIndexMapFromName(), residueIndexMapFromSeqType(), residueIndexMapFromSeqType(), residueIndexMapGuessedFromResidues(), testDNAArrayBit16(), and testDNAArrayBit8().
DNAProperResiduesIndexMap
const ResiduesIndexMap cbrc::DNAProperResiduesIndexMap(DNAProperResidueIndexMap) (DNAProperResidueIndexMap)
Referenced by residuesIndexMapFromName().
DNAWithNResidueIndexMap
const ResidueIndexMap cbrc::DNAWithNResidueIndexMap ("acgt" , "acgtn")
Referenced by residueIndexMapGuessedFromResidues().
labeledIdentityDoubleMatrix
const LabeledIdentityDoubleMatrix cbrc::labeledIdentityDoubleMatrix
Definition at line 105 of file ConstantLabeledSquareDoubleFLENumMatrix.hh.
labeledSequencePairPredicate_alwaysFalse
const LabeledSequencePairPredicate_alwaysFalse cbrc::labeledSequencePairPredicate_alwaysFalse
Definition at line 79 of file LabeledSequencePairPredicate.hh.
labeledSequencePairPredicate_namesEqual
const LabeledSequencePairPredicate_namesEqual cbrc::labeledSequencePairPredicate_namesEqual
Definition at line 80 of file LabeledSequencePairPredicate.hh.
Referenced by runGlobalAffineNearestClass(), and runGlobalAffineSearcher().
mask [1/2]
const byte cbrc::mask[] = {0xc0, 0x30, 0x0c, 0x03} static
Definition at line 21 of file sigma4bitPackingUtils.cc.
Referenced by cbrc::sigma4bitPackingUtils::assignNthUnpacked(), and cbrc::Sigma4FLArray::operator()().
mask [2/2]
const Sigma4FLArray::byte cbrc::mask[] = {0xc0, 0x30, 0x0c, 0x03} static
Definition at line 21 of file Sigma4FLArray.cc.
maxResidueIndex
const byte cbrc::maxResidueIndex = 3 static
Definition at line 30 of file DNAArrayBit8.hh.
Referenced by cbrc::DNAArrayBit8< len >::set().
PAM120
const alignScoreT cbrc::PAM120[24][24] static
Initial value:
=
    {   { 3,-3,-1, 0,-0,-3,-1, 0,-0, 1,-3,-1,-3,-2,-2,-4, 1, 1, 1,-7,-4, 0, 1,-7},
    {-3, 6,-1,-3,-3,-4, 1,-3,-3,-4, 1,-2,-4, 2,-1,-5,-1,-1,-2, 1,-5,-3,-1,-5},
    {-1,-1, 4, 2, 2,-5, 0, 1,-0, 0, 2,-2,-4, 1,-3,-4,-2, 1, 0,-4,-2,-3, 1,-4},
    { 0,-3, 2, 5, 2,-7, 1, 3, 1, 0, 0,-3,-5,-1,-4,-7,-3, 0,-1,-8,-5,-3, 0,-8},
    {-0,-3, 2, 2, 2,-7,-0, 1,-0,-0,-0,-3,-5,-1,-4,-7,-3,-0,-1,-8,-5,-3,-0,-8},
    {-3,-4,-5,-7,-7, 9,-7,-7,-7,-4,-4,-3,-7,-7,-6,-6,-4, 0,-3,-8,-1,-3, 0,-8},
    {-1, 1, 0, 1,-0,-7, 6, 2, 2,-3, 3,-3,-2, 0,-1,-6, 0,-2,-2,-6,-5,-3,-2,-7},
    { 0,-3, 1, 3, 1,-7, 2, 5, 2,-1,-1,-3,-4,-1,-3,-7,-2,-1,-2,-8,-5,-3,-1,-8},
 {-0,-3,-0, 1,-0,-7, 2, 2, 2,-3,-1,-3,-4,-1,-3,-7,-2,-2,-2,-8,-5,-3,-2,-8},
    { 1,-4, 0, 0,-0,-4,-3,-1,-3, 5,-4,-4,-5,-3,-4,-5,-2, 1,-1,-8,-6,-2, 1,-7},
    {-3, 1, 2, 0,-0,-4, 3,-1,-1,-4, 7,-4,-3,-2,-4,-3,-1,-2,-3,-3,-1,-3,-2,-4},
    {-1,-2,-2,-3,-3,-3,-3,-3,-3,-4,-4, 6, 1,-3, 1, 0,-3,-2, 0,-6,-2, 3,-2,-6},
    {-3,-4,-4,-5,-5,-7,-2,-4,-4,-5,-3, 1, 5,-4, 3, 0,-3,-4,-3,-3,-2, 1,-4,-7},
    {-2, 2, 1,-1,-1,-7, 0,-1,-1,-3,-2,-3,-4, 5, 0,-7,-2,-1,-1,-5,-5,-4,-1,-7},
    {-2,-1,-3,-4,-4,-6,-1,-3,-3,-4,-4, 1, 3, 0, 8,-1,-3,-2,-1,-6,-4, 1,-2,-6},
    {-4,-5,-4,-7,-7,-6,-6,-7,-7,-5,-3, 0, 0,-7,-1, 8,-5,-3,-4,-1, 4,-3,-3,-7},
    { 1,-1,-2,-3,-3,-4, 0,-2,-2,-2,-1,-3,-3,-2,-3,-5, 6, 1,-1,-7,-6,-2, 1,-7},
    { 1,-1, 1, 0,-0,-0,-2,-1,-2, 1,-2,-2,-4,-1,-2,-3, 1, 3, 2,-2,-3,-2, 2,-4},
    { 1,-2, 0,-1,-1,-3,-2,-2,-2,-1,-3, 0,-3,-1,-1,-4,-1, 2, 4,-6,-3, 0, 2,-6},
    {-7, 1,-4,-8,-8,-8,-6,-8,-8,-8,-3,-6,-3,-5,-6,-1,-7,-2,-6, 12,2,-8,-2,-8},
    {-4,-5,-2,-5,-5,-1,-5,-5,-5,-6,-1,-2,-2,-5,-4, 4,-6,-3,-3,-2, 8,-3,-3,-6},
    { 0,-3,-3,-3,-3,-3,-3,-3,-3,-2,-3, 3, 1,-4, 1,-3,-2,-2, 0,-8,-3, 5,-2,-8},
    { 1,-1, 1, 0,-0,-0,-2,-1,-2, 1,-2,-2,-4,-1,-2,-3, 1, 2, 2,-2,-3,-2,12,-4},
 {-7,-5,-4,-8,-8,-8,-7,-8,-8,-7,-4,-6,-7,-7,-6,-7,-7,-4,-6,-8,-6,-8,-4,-8} }
Definition at line 22 of file AminoScorePam120.hh.
Referenced by cbrc::AminoScorePam120::score().
PAM120MaxScore
const alignScoreT cbrc::PAM120MaxScore[24] static
Initial value:
=
{   3,  6,  4,  5,  2,  9,  6,  5,  2,  5,  7,  6,  5,  5,  8,  8,  6,  3,  4, 12,  8,  5, 12, -4 }
Definition at line 50 of file AminoScorePam120.hh.
Referenced by cbrc::AminoScorePam120::maxScore().
residueColorGenebee
const ResidueColorGenebee cbrc::residueColorGenebee static
Definition at line 45 of file ResidueColorGenebee.hh.
residueSimilarityAffineEdit_amino
const ResidueSimilarityAffineEdit cbrc::residueSimilarityAffineEdit_amino(aminoResidueIndexMap) (aminoResidueIndexMap)
RNAProperResidueIndexMap
const ResidueIndexMap cbrc::RNAProperResidueIndexMap("acgu") ("acgu")
Referenced by cbrc::ResidueIndexMapPredefined::guessSeqType(), residueIndexMapFromName(), residueIndexMapFromSeqType(), and residueIndexMapGuessedFromResidues().
RNAProperResiduesIndexMap
const ResiduesIndexMap cbrc::RNAProperResiduesIndexMap(RNAProperResidueIndexMap) (RNAProperResidueIndexMap)
Referenced by residuesIndexMapFromName().
RNAResidueIndexMap
const ResidueIndexMap cbrc::RNAResidueIndexMap("acgu") ("acgu")
Referenced by cbrc::ResidueIndexMapPredefinedAlphabets::guessSeqType(), and residueIndexMapFromSeqType().
setMask
const byte cbrc::setMask[] = {0x03, 0x0c, 0x30, 0xc0} static
Definition at line 28 of file DNAArrayBit8.hh.
Referenced by cbrc::DNAArrayBit8< len >::operator()().
standardRNACodonTranslator
ResidueIndexMapTranslator cbrc::standardRNACodonTranslator(RNAProperResidueIndexMap, aminoResidueIndexMap, "\ gca:A gcc:A gcg:A gcu:A aga:R agg:R cga:R cgc:R \ cgg:R cgu:R gac:D gau:D aac:N aau:N ugc:C ugu:C \ gaa:E gag:E caa:Q cag:Q gga:G ggc:G ggg:G ggu:G \ cau:H aua:I auc:I auu:I uua:L uug:L cua:L cuc:L \ cug:L cuu:L aaa:K aag:K aug:M uuc:F uuu:F cca:P \ ccc:P ccg:P ccu:P agc:S agu:S uca:S ucc:S ucg:S \ ucu:S aca:T acc:T acg:T acu:T ugg:W uac:Y uau:Y \ gua:V guc:V gug:V guu:V uaa:stop uag:stop uga:stop\ ") (RNAProperResidueIndexMap , aminoResidueIndexMap , "\gca:A gcc:A gcg:A gcu:A aga:R agg:R cga:R cgc:R \cgg:R cgu:R gac:D gau:D aac:N aau:N ugc:C ugu:C \gaa:E gag:E caa:Q cag:Q gga:G ggc:G ggg:G ggu:G \cau:H aua:I auc:I auu:I uua:L uug:L cua:L cuc:L \cug:L cuu:L aaa:K aag:K aug:M uuc:F uuu:F cca:P \ccc:P ccg:P ccu:P agc:S agu:S uca:S ucc:S ucg:S \ucu:S aca:T acc:T acg:T acu:T ugg:W uac:Y uau:Y \gua:V guc:V gug:V guu:V uaa:stop uag:stop uga:stop\")
stringUnaryPredicateAlwaysFalse
const StringUnaryPredicateAlwaysFalse cbrc::stringUnaryPredicateAlwaysFalse
Definition at line 41 of file StringUnaryPredicate.hh.
stringUnaryPredicateAlwaysTrue
const StringUnaryPredicateAlwaysTrue cbrc::stringUnaryPredicateAlwaysTrue
Definition at line 34 of file StringUnaryPredicate.hh.
SymmetricBitMatrixInverseMask
const byte cbrc::SymmetricBitMatrixInverseMask[] = {254, 253, 251, 247, 239, 223, 191, 127}
Definition at line 38 of file SymmetricBitMatrix.hh.
Referenced by cbrc::SymmetricBitMatrix::clear(), and cbrc::SymmetricBitMatrix::clearFast().
SymmetricBitMatrixMask
const byte cbrc::SymmetricBitMatrixMask[] = {1, 2, 4, 8, 16, 32, 64, 128}
Definition at line 37 of file SymmetricBitMatrix.hh.
Referenced by cbrc::SymmetricBitMatrix::operator()(), and cbrc::SymmetricBitMatrix::setFast().
toComplement
const char cbrc::toComplement[] static
Initial value:
=
  {3,
   2,
   1,
   0,
   255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
   84,
   255,
   71,
   255,255,255,
   67,
   255,255,255,255,255,255,255,255,255,255,255,255,
   65,
   255,255,255,255,255,255,255,255,255,255,255,255,
   116,
   255,
   103,
   255,255,255,
   99,
   255,255,255,255,255,255,255,255,255,255,255,255,
   97,
   255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255
  }
Definition at line 21 of file ComplementDNA.hh.
Referenced by cbrc::ComplementDNA::operator()().