NGSFeatures: cbrc::smoothing Namespace Reference
cbrc::smoothing Namespace Reference
Typedefs
typedef Point2D< double, double > POINT
typedef WeightedPoint2D< double, double, size_t > NPOINT
typedef WeightedPoint2D< double, double, double > WPOINT
Functions
std::vector< NPOINT > mergeIdenticalAdjacentX (const std::vector< NPOINT > &u)
std::vector< WPOINT > mergeIdenticalAdjacentX (const std::vector< WPOINT > &u)
std::vector< POINT > monotonicSmoothY (std::vector< NPOINT > &u, const bool ensureYIncreasing, size_t minSampleSize)
void averageYCoordinatesWithNeighboringPointsUntilMinSampleSizeAttained (const std::vector< NPOINT > &u, std::vector< POINT > &v, const size_t minSampleSize)
void averageYCoordinateOfPointIWithNeighborPointUntilMinSampleSizeAttained (const std::vector< NPOINT > &u, std::vector< POINT > &v, const size_t minSampleSize, const size_t i)
template<typename XT , typename YT , typename WT >
void sortInPlaceAscendingValue (std::vector< WeightedPoint2D< XT, YT, WT > > &u)
Typedef Documentation
NPOINT
typedef WeightedPoint2D<double, double, size_t> cbrc::smoothing::NPOINT
Definition at line 28 of file smoothing.hh.
POINT
typedef Point2D<double, double> cbrc::smoothing::POINT
Definition at line 27 of file smoothing.hh.
WPOINT
typedef WeightedPoint2D<double, double, double> cbrc::smoothing::WPOINT
Definition at line 29 of file smoothing.hh.
Function Documentation
averageYCoordinateOfPointIWithNeighborPointUntilMinSampleSizeAttained()
void cbrc::smoothing::averageYCoordinateOfPointIWithNeighborPointUntilMinSampleSizeAttained (const std::vector< NPOINT > & u, std::vector< POINT > & v, const size_t minSampleSize, const size_t i)
Definition at line 148 of file smoothing.cc.
References cbrc::FLEArray< T >::size().
Referenced by averageYCoordinatesWithNeighboringPointsUntilMinSampleSizeAttained(), and monotonicSmoothY().
averageYCoordinatesWithNeighboringPointsUntilMinSampleSizeAttained()
void cbrc::smoothing::averageYCoordinatesWithNeighboringPointsUntilMinSampleSizeAttained (const std::vector< NPOINT > & u, std::vector< POINT > & v, const size_t minSampleSize)
Definition at line 141 of file smoothing.cc.
References averageYCoordinateOfPointIWithNeighborPointUntilMinSampleSizeAttained(), and cbrc::FLEArray< T >::size().
Referenced by monotonicSmoothY(), and cbrc::smoothMinPoints().
mergeIdenticalAdjacentX() [1/2]
std::vector< NPOINT > cbrc::smoothing::mergeIdenticalAdjacentX (const std::vector< NPOINT > & u)
Definition at line 18 of file smoothing.cc.
References cbrc::FLEArray< T >::size().
Referenced by cbrc::labeledBlastToOddsRatio(), and cbrc::smoothMinPoints().
mergeIdenticalAdjacentX() [2/2]
std::vector< WPOINT > cbrc::smoothing::mergeIdenticalAdjacentX (const std::vector< WPOINT > & u)
Definition at line 40 of file smoothing.cc.
References cbrc::FLEArray< T >::size().
monotonicSmoothY()
std::vector< POINT > cbrc::smoothing::monotonicSmoothY (std::vector< NPOINT > & u, const bool ensureYIncreasing, size_t minSampleSize)
Definition at line 64 of file smoothing.cc.
References averageYCoordinateOfPointIWithNeighborPointUntilMinSampleSizeAttained(), averageYCoordinatesWithNeighboringPointsUntilMinSampleSizeAttained(), cbrc::FLEArray< T >::end(), cbrc::WeightedPoint2D< XT, YT, WT >::nonFinite(), cbrc::FLEArray< T >::size(), and cbrc::WeightedPoint2D< XT, YT, WT >::xLess().
Referenced by cbrc::labeledBlastToOddsRatio(), and cbrc::smoothMinPoints().
sortInPlaceAscendingValue()
template<typename XT , typename YT , typename WT > void cbrc::smoothing::sortInPlaceAscendingValue (std::vector< WeightedPoint2D< XT, YT, WT > > & u) inline
Definition at line 32 of file smoothing.hh.
Referenced by cbrc::smoothMinPoints(), and cbrc::smoothMinPoints().