NGSFeatures: cbrc::binaryIO Namespace Reference
cbrc::binaryIO Namespace Reference
Functions
void read (std::string &s, std::istream &iStream)
void read (std::string &s, std::istream &iStream, const size_t &size)
void traceOrDie (const std::string &s, std::istream &iStream)
void read (stringVecT &stringVector, std::istream &iStream)
void write (const std::string &s, std::ostream &os)
void writeContentsOnly (const std::string &s, std::ostream &os)
void write (const stringVecT &stringVector, std::ostream &os)
Function Documentation
read() [1/3]
void cbrc::binaryIO::read (std::string & s, std::istream & iStream) inline
Definition at line 87 of file binaryIO.hh.
References cbrc::perlish::die(), cbrc::FLEArray< T >::read(), and read().
Referenced by read(), and read().
read() [2/3]
void cbrc::binaryIO::read (std::string & s, std::istream & iStream, const size_t & size) inline
Definition at line 108 of file binaryIO.hh.
References cbrc::perlish::die(), and cbrc::FLEArray< T >::read().
read() [3/3]
void cbrc::binaryIO::read (stringVecT & stringVector, std::istream & iStream) inline
Definition at line 66 of file binaryIO.hh.
References cbrc::perlish::die(), cbrc::FLEArray< T >::read(), and read().
traceOrDie()
void cbrc::binaryIO::traceOrDie (const std::string & s, std::istream & iStream) inline
Definition at line 128 of file binaryIO.hh.
References GDB_ASSERTF, cbrc::FLEArray< T >::read(), cbrc::FLEArray< T >::resize(), and cbrc::FLEArray< T >::size().
write() [1/2]
void cbrc::binaryIO::write (const std::string & s, std::ostream & os) inline
Definition at line 162 of file binaryIO.hh.
References cbrc::FLEArray< T >::write(), and writeContentsOnly().
Referenced by write().
write() [2/2]
void cbrc::binaryIO::write (const stringVecT & stringVector, std::ostream & os) inline
Definition at line 148 of file binaryIO.hh.
References cbrc::FLEArray< T >::size(), write(), and cbrc::FLEArray< T >::write().
writeContentsOnly()
void cbrc::binaryIO::writeContentsOnly (const std::string & s, std::ostream & os) inline
Definition at line 172 of file binaryIO.hh.
References cbrc::perlish::die(), and cbrc::FLEArray< T >::write().
Referenced by write(), and cbrc::RecountNeighborProbGraphWriter::write().