NGSFeatures: cbrc::vectorMatrix Namespace Reference
cbrc::vectorMatrix Namespace Reference
Functions
template<typename T , size_t numCols>
std::vector< std::vector< T > > fromCMatrix (T cmatrix[][numCols], const size_t numRows)
template<typename T >
void write (const std::vector< std::vector< T > > &m, std::ostream &os)
template<typename T >
std::vector< std::vector< T > > read (std::ifstream &is)
template<typename T >
bool isRectangular (const std::vector< std::vector< T > > &m)
Function Documentation
fromCMatrix()
template<typename T , size_t numCols> std::vector< std::vector< T > > cbrc::vectorMatrix::fromCMatrix (T cmatrix[][numCols], const size_t numRows)
Definition at line 24 of file vectorMatrix.hh.
isRectangular()
template<typename T > bool cbrc::vectorMatrix::isRectangular (const std::vector< std::vector< T > > & m)
Definition at line 70 of file vectorMatrix.hh.
References cbrc::FLEArray< T >::size().
read()
template<typename T > std::vector< std::vector< T > > cbrc::vectorMatrix::read (std::ifstream & is)
Definition at line 54 of file vectorMatrix.hh.
References cbrc::FLEArray< T >::read(), cbrc::FLEArray< T >::resize(), and cbrc::FLEArray< T >::size().
write()
template<typename T > void cbrc::vectorMatrix::write (const std::vector< std::vector< T > > & m, std::ostream & os)
Definition at line 39 of file vectorMatrix.hh.
References cbrc::FLEArray< T >::size(), and cbrc::FLEArray< T >::write().