NGSFeatures: ematch_src/utils/Stats/Ttable.hh File Reference
Ttable.hh File Reference
#include <cmath>
#include <limits>
#include <string>
Namespaces
namespace cbrc
Functions
double lgamma (double)
int isnan (double)
double cbrc::betacf (const double &a, const double &b, const double &x)
void cbrc::betai (const double &a, const double &b, const double &x)
void cbrc::TtoP (const double &t_val, const double &dfree)
Function Documentation
isnan()
int isnan (double)
Referenced by main(), cbrc::TtoP(), and cbrc::TtoP().
lgamma()
double lgamma (double)