NGSFeatures: src/Utilities.cc File Reference
Utilities.cc File Reference
#include "Utilities.hh"
#include <iostream>
#include <cmath>
#include <map>
#include <vector>
#include <string>
#include <cstdlib>
Functions
std::string GetBaseNameFromFilename (const std::string &fileName)
Extract base filename from a full file path.
std::string GetPathNameFromFilename (const std::string &filename)
Extract directory path from a full file path.
vector< char > tagnum2acgt (vector< int >arg)
vector< int > acgt2tagnum (string arg)
vector< int > id2tagnum (int id, int tgl)
Convert numeric ID to DNA tag representation.
Function Documentation
acgt2tagnum()
vector< int > acgt2tagnum (string arg)
Definition at line 58 of file Utilities.cc.
GetBaseNameFromFilename()
std::string GetBaseNameFromFilename (const std::string & fileName)
Extract base filename from a full file path.
Removes the directory path and file extension, returning only the base name.
Parameters
fileName Full file path (e.g., "/path/to/file.txt")
Returns
Base filename without path or extension (e.g., "file")
Example:
std::string path = "/home/user/data/sequences.fastq";
std::string base = GetBaseNameFromFilename(path);
// base == "sequences"
Definition at line 12 of file Utilities.cc.
Referenced by main().
GetPathNameFromFilename()
std::string GetPathNameFromFilename (const std::string & filename)
Extract directory path from a full file path.
Returns the directory portion of a file path, excluding the filename.
Parameters
filename Full file path (e.g., "/path/to/file.txt")
Returns
Directory path with trailing slash (e.g., "/path/to/")
Example:
std::string path = "/home/user/data/sequences.fastq";
std::string dir = GetPathNameFromFilename(path);
// dir == "/home/user/data/"
Definition at line 23 of file Utilities.cc.
Referenced by main().
id2tagnum()
vector< int > id2tagnum (int id, int tgl)
Convert numeric ID to DNA tag representation.
Converts a numeric identifier to its corresponding DNA sequence representation as a vector of integers (A=0, C=1, G=2, T=3).
Parameters
id Numeric identifier to convert
tgl Tag length (sequence length)
Returns
Vector of integers representing DNA bases
Example:
std::vector<int> tag = id2tagnum(5, 3);
// Returns numeric representation of DNA sequence
Definition at line 79 of file Utilities.cc.
Referenced by main().
tagnum2acgt()
vector< char > tagnum2acgt (vector< int > arg)
Definition at line 42 of file Utilities.cc.