NGSFeatures: src/Utilities.hh File Reference
Utilities.hh File Reference
Utility functions for NGS sequence processing and DNA manipulation.
#include <iostream>
#include <map>
#include <string>
#include <vector>
#include <cstdlib>
Functions
std::string GetBaseNameFromFilename (const std::string &fileName)
Extract base filename from a full file path.
std::string GetPathNameFromFilename (const std::string &filename)
Extract directory path from a full file path.
std::vector< int > id2tagnum (int id, int tgl)
Convert numeric ID to DNA tag representation.
std::vector< int > acgt2tagnum (const std::string &arg)
Convert ACGT string to numeric representation.
std::vector< char > tagnum2acgt (const std::vector< int > &arg)
Convert numeric representation back to ACGT characters.
template<typename T >
void prn_vec_oneval (const std::vector< T > &arg, const std::string &sep="", unsigned lim=0)
Print single value from vector at specified index.
template<typename T >
void prn_vec (const std::vector< T > &arg, const std::string &sep="")
Print all elements of a vector to stdout.
template<typename T >
void prn_vec_binos (const std::vector< T > &arg, std::ostream &fn, const std::string &sep="")
Print vector elements to a specified output stream.
template<typename T >
void prn_vec_err (const std::vector< T > &arg, const std::string &sep="")
Print vector elements to stderr.
template<typename T1 , typename T2 >
void prn_map (const std::map< T1, T2 > &arg, const std::string &sep="")
Print all key-value pairs from a map.
template<typename T >
void prnf_vec (const std::vector< T > &arg)
Print vector of floating-point numbers with fixed precision.
Detailed Description
Utility functions for NGS sequence processing and DNA manipulation.
This header provides core utility functions for:
File path operations
DNA sequence conversions (ACGT <-> numeric)
Vector and map printing utilities
Template-based generic printing functions
Note
IMPORTANT: This is a header file. Never use 'using namespace std;' in headers! It pollutes the namespace of all files that include this header. All standard library types use explicit std:: prefix.
Author
Edward Wijaya
Date
2009-2025
Copyright
Copyright 2009-2025, NGSFeatures Project
Definition in file Utilities.hh.
Function Documentation
acgt2tagnum()
std::vector< int > acgt2tagnum (const std::string & arg)
Convert ACGT string to numeric representation.
Converts DNA sequence string (ACGT) to vector of integers. Mapping: A=0, C=1, G=2, T=3
Parameters
arg DNA sequence string (e.g., "ACGT")
Returns
Vector of integers representing each base
Example:
std::string seq = "ACGT";
std::vector<int> nums = acgt2tagnum(seq);
// nums == {0, 1, 2, 3}
GetBaseNameFromFilename()
std::string GetBaseNameFromFilename (const std::string & fileName)
Extract base filename from a full file path.
Removes the directory path and file extension, returning only the base name.
Parameters
fileName Full file path (e.g., "/path/to/file.txt")
Returns
Base filename without path or extension (e.g., "file")
Example:
std::string path = "/home/user/data/sequences.fastq";
std::string base = GetBaseNameFromFilename(path);
// base == "sequences"
Definition at line 15 of file Utilities.cc.
Referenced by main().
GetPathNameFromFilename()
std::string GetPathNameFromFilename (const std::string & filename)
Extract directory path from a full file path.
Returns the directory portion of a file path, excluding the filename.
Parameters
filename Full file path (e.g., "/path/to/file.txt")
Returns
Directory path with trailing slash (e.g., "/path/to/")
Example:
std::string path = "/home/user/data/sequences.fastq";
std::string dir = GetPathNameFromFilename(path);
// dir == "/home/user/data/"
Definition at line 24 of file Utilities.cc.
Referenced by main().
id2tagnum()
std::vector< int > id2tagnum (int id, int tgl)
Convert numeric ID to DNA tag representation.
Converts a numeric identifier to its corresponding DNA sequence representation as a vector of integers (A=0, C=1, G=2, T=3).
Parameters
id Numeric identifier to convert
tgl Tag length (sequence length)
Returns
Vector of integers representing DNA bases
Example:
std::vector<int> tag = id2tagnum(5, 3);
// Returns numeric representation of DNA sequence
Definition at line 85 of file Utilities.cc.
Referenced by main().
prn_map()
template<typename T1 , typename T2 > void prn_map (const std::map< T1, T2 > & arg, const std::string & sep = "")
Print all key-value pairs from a map.
Prints map contents in "key->value" format with optional separator.
Template Parameters
T1 Key type (must support operator<<)
T2 Value type (must support operator<<)
Parameters
arg Map to print
sep Separator string between pairs (default: "")
Example:
std::map<std::string, int> m = {{"A", 1}, {"C", 2}};
prn_map(m, " ");  // Prints: A->1 C->2
Definition at line 228 of file Utilities.hh.
prn_vec()
template<typename T > void prn_vec (const std::vector< T > & arg, const std::string & sep = "")
Print all elements of a vector to stdout.
Generic template function to print vector elements with optional separator.
Template Parameters
T Element type (must support operator<<)
Parameters
arg Vector to print
sep Separator string between elements (default: "")
Example:
std::vector<int> vec = {1, 2, 3, 4, 5};
prn_vec(vec, ", ");  // Prints: 1, 2, 3, 4, 5,
Definition at line 159 of file Utilities.hh.
prn_vec_binos()
template<typename T > void prn_vec_binos (const std::vector< T > & arg, std::ostream & fn, const std::string & sep = "")
Print vector elements to a specified output stream.
Generic template function to print vector to any output stream (file, cout, etc.).
Template Parameters
T Element type (must support operator<<)
Parameters
arg Vector to print
fn Output stream to write to
sep Separator string between elements (default: "")
Example:
std::ofstream file("output.txt");
std::vector<double> vec = {1.5, 2.5, 3.5};
prn_vec_binos(vec, file, "\n");  // Write to file with newlines
Definition at line 183 of file Utilities.hh.
prn_vec_err()
template<typename T > void prn_vec_err (const std::vector< T > & arg, const std::string & sep = "")
Print vector elements to stderr.
Prints vector elements to standard error stream, useful for debugging and logging.
Template Parameters
T Element type (must support operator<<)
Parameters
arg Vector to print
sep Separator string between elements (default: "")
Example:
std::vector<std::string> errors = {"Error1", "Error2"};
prn_vec_err(errors, "\n");  // Print errors to stderr
Definition at line 205 of file Utilities.hh.
prn_vec_oneval()
template<typename T > void prn_vec_oneval (const std::vector< T > & arg, const std::string & sep = "", unsigned lim = 0)
Print single value from vector at specified index.
Prints one or two elements from a vector at the specified limit index.
Template Parameters
T Element type (must support operator<<)
Parameters
arg Vector to print from
sep Separator string (default: "")
lim Index to print (prints elements at lim and lim+1)
Example:
std::vector<int> vec = {1, 2, 3, 4, 5};
prn_vec_oneval(vec, " ", 2);  // Prints: 3 4
Definition at line 135 of file Utilities.hh.
prnf_vec()
template<typename T > void prnf_vec (const std::vector< T > & arg)
Print vector of floating-point numbers with fixed precision.
Prints floating-point vector elements using printf with 7 decimal places.
Template Parameters
T Numeric type (typically double or float)
Parameters
arg Vector of numeric values to print
Example:
std::vector<double> values = {1.234567, 2.345678, 3.456789};
prnf_vec(values);  // Prints: 1.2345670 2.3456780 3.4567890
Definition at line 249 of file Utilities.hh.
tagnum2acgt()
std::vector< char > tagnum2acgt (const std::vector< int > & arg)
Convert numeric representation back to ACGT characters.
Converts vector of integers back to DNA sequence characters. Mapping: 0=A, 1=C, 2=G, 3=T
Parameters
arg Vector of integers representing DNA bases
Returns
Vector of characters (ACGT)
Example:
std::vector<int> nums = {0, 1, 2, 3};
std::vector<char> seq = tagnum2acgt(nums);
// seq == {'A', 'C', 'G', 'T'}