# Last cvs check in: $Date: 2009/04/30 21:07:35 $
#CBRC_CPP_HOME = /home/paulh/cbrcRepos/C++ <-- set this to the appropriate place.
SRCS =  $(CBRC_CPP_HOME)/utils/perlish/perlish.cc
FASTA_SRC = $(CBRC_CPP_HOME)/utils/sequence/readers/FastaReader.cc
BLAST_RESULT_CC = $(CBRC_CPP_HOME)/utils/sequence/readers/Blast8ResultReader.cc
BLAST_RESULT_HH = $(CBRC_CPP_HOME)/utils/sequence/readers/Blast8ResultReader.hh
LABELED_INSTANCES_CC = $(CBRC_CPP_HOME)/classifiers/LabeledInstance.cc $(CBRC_CPP_HOME)/classifiers/LabeledInstances.cc

HEADERS = $(CBRC_CPP_HOME)/utils/sequence/readers/FastaReader.hh $(CBRC_CPP_HOME)/utils/perlish/perlish.hh $(CBRC_CPP_HOME)/utils/ChainHashtable/StringKeyHashtable.hh

CPP_OPT = -O3
DEBUG = -g
WARN = -Wall

list :
	@echo "currently no targets exist"

#xxx : $(SRCS) $(HEADERS) xxx.cc
#	g++ $(WARN) $(DEBUG) $(CPP_OPT) -o $@ xxx.cc $(SRCS) -I$(CBRC_CPP_HOM)
